(ns entities.max_planck
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Person "Max Planck")

(name-as-in "Max Planck" "Max Planck" "de")
(name-as-in "Max Planck" "" "zh-hk")
(name-as-in "Max Planck" "" "zh-tw")
(name-as-in "Max Planck" "Планк, Макс" "ru")
(name-as-in "Max Planck" "Max Planck" "pt")
(name-as-in "Max Planck" "Max Planck" "en")
(name-as-in "Max Planck" "" "zh-cn")
(name-as-in "Max Planck" "Max Planck" "fr")
(name-as-in "Max Planck" "Max Planck" "es")
(name-as-in "Max Planck" "" "zh-sg")
(name-as-in "Max Planck" "マックス・プランク" "ja")
(name-as-in "Max Planck" "" "zh-hans")
(name-as-in "Max Planck" "" "zh-hant")

(descr-as-in "Max Planck" "deutscher Physiker" "de")
(descr-as-in "Max Planck" "" "zh-hk")
(descr-as-in "Max Planck" "" "zh-tw")
(descr-as-in "Max Planck" "немецкий физик-теоретик, основоположник квантовой физики" "ru")
(descr-as-in "Max Planck" "" "pt")
(descr-as-in "Max Planck" "German theoretical physicist" "en")
(descr-as-in "Max Planck" "" "zh-cn")
(descr-as-in "Max Planck" "physicien allemand" "fr")
(descr-as-in "Max Planck" "físico alemán" "es")
(descr-as-in "Max Planck" "" "zh-sg")
(descr-as-in "Max Planck" "" "ja")
(descr-as-in "Max Planck" "" "zh-hans")
(descr-as-in "Max Planck" "" "zh-hant")


(refer-to ["properties.award_received"])
(refer-to ["clazzes.nobel_prize_in_physics"])
(fact claim "Max Planck" "award-received" "Nobel Prize in Physics")
(refer-to ["clazzes.adlerschild_des_deutschen_reiches"])
(fact claim "Max Planck" "award-received" "Adlerschild des Deutschen Reiches")
(refer-to ["clazzes.max_planck_medal"])
(fact claim "Max Planck" "award-received" "Max Planck Medal")
(refer-to ["clazzes.goethe_prize"])
(fact claim "Max Planck" "award-received" "Goethe Prize")
(refer-to ["clazzes.pour_le_mérite"])
(fact claim "Max Planck" "award-received" "Pour le Mérite")
(refer-to ["clazzes.copley_medal"])
(fact claim "Max Planck" "award-received" "Copley Medal")

(refer-to ["properties.residence"])
(refer-to ["entities.kiel"])
(fact claim "Max Planck" "residence" "Kiel")
(refer-to ["entities.munich"])
(fact claim "Max Planck" "residence" "Munich")

(refer-to ["properties.member_of"])
(fact claim "Max Planck" "member-of" "Q292692")
(refer-to ["clazzes.deutsche_physikalische_gesellschaft"])
(fact claim "Max Planck" "member-of" "Deutsche Physikalische Gesellschaft")
(refer-to ["clazzes.prussian_academy_of_sciences"])
(fact claim "Max Planck" "member-of" "Prussian Academy of Sciences")
(refer-to ["clazzes.kaiser_wilhelm_society"])
(fact claim "Max Planck" "member-of" "Kaiser Wilhelm Society")
(refer-to ["clazzes.notgemeinschaft_der_deutschen_wissenschaft"])
(fact claim "Max Planck" "member-of" "Notgemeinschaft der Deutschen Wissenschaft")
(refer-to ["clazzes.accademia_dei_lincei"])
(fact claim "Max Planck" "member-of" "Accademia dei Lincei")
(refer-to ["entities.royal_society"])
(fact claim "Max Planck" "member-of" "Royal Society")
(refer-to ["clazzes.bavarian_academy_of_sciences_and_humanities"])
(fact claim "Max Planck" "member-of" "Bavarian Academy of Sciences and Humanities")
(refer-to ["clazzes.saxonian_academy_of_sciences"])
(fact claim "Max Planck" "member-of" "Saxonian Academy of Sciences")
(refer-to ["entities.royal_netherlands_academy_of_arts_and_sciences"])
(fact claim "Max Planck" "member-of" "Royal Netherlands Academy of Arts and Sciences")
(refer-to ["clazzes.hungarian_academy_of_sciences"])
(fact claim "Max Planck" "member-of" "Hungarian Academy of Sciences")
(refer-to ["clazzes.pontifical_academy_of_sciences"])
(fact claim "Max Planck" "member-of" "Pontifical Academy of Sciences")
(fact claim "Max Planck" "member-of" "Q2301163")

(refer-to ["properties.lccn_identifier"])
(fact claim "Max Planck" "lccn-identifier" "n80038130")

(refer-to ["properties.member_of_political_party"])
(refer-to ["entities.german_people's_party"])
(fact claim "Max Planck" "member-of-political-party" "German People's Party")

(refer-to ["properties.bnf_identifier"])
(fact claim "Max Planck" "bnf-identifier" "12108412n")

(refer-to ["properties.isni_iso_27729"])
(fact claim "Max Planck" "isni-iso-27729" "0000 0001 1024 5894")

(refer-to ["properties.sudoc_identifier"])
(fact claim "Max Planck" "sudoc-identifier" "02888566X")

(refer-to ["properties.viaf_identifier"])
(fact claim "Max Planck" "viaf-identifier" "34487615")

(refer-to ["properties.brother"])
(fact claim "Max Planck" "brother" "Q1287829")

(refer-to ["properties.occupation_person"])
(refer-to ["clazzes.physicist"])
(fact claim "Max Planck" "occupation-person" "physicist")
(refer-to ["clazzes.university_teacher"])
(fact claim "Max Planck" "occupation-person" "university teacher")
(refer-to ["clazzes.geheimrat"])
(fact claim "Max Planck" "occupation-person" "Geheimrat")

(refer-to ["properties.gnd_identifier"])
(fact claim "Max Planck" "gnd-identifier" "118594818")

(refer-to ["properties.date_of_birth"])
(fact claim "Max Planck" "date-of-birth" "+00000001858-04-23T00:00:00Z")

(refer-to ["properties.main_type_gnd"])
(refer-to ["clazzes.person"])
(fact claim "Max Planck" "main-type-gnd" "person")

(refer-to ["properties.ndl_identifier"])
(fact claim "Max Planck" "ndl-identifier" "00452924")

(refer-to ["properties.employer"])
(refer-to ["entities.ludwig_maximilian_university_of_munich"])
(fact claim "Max Planck" "employer" "Ludwig Maximilian University of Munich")
(refer-to ["entities.university_of_kiel"])
(fact claim "Max Planck" "employer" "University of Kiel")
(refer-to ["entities.karlsruhe_institute_of_technology"])
(fact claim "Max Planck" "employer" "Karlsruhe Institute of Technology")
(refer-to ["entities.humboldt_university_of_berlin"])
(fact claim "Max Planck" "employer" "Humboldt University of Berlin")

(refer-to ["properties.place_of_burial"])
(refer-to ["entities.stadtfriedhof_göttingen"])
(fact claim "Max Planck" "place-of-burial" "Stadtfriedhof Göttingen")

(refer-to ["properties.mathematics_genealogy_project_identifier"])
(fact claim "Max Planck" "mathematics-genealogy-project-identifier" "20750")

(refer-to ["properties.signature"])
(fact claim "Max Planck" "signature" "Max.Planck.Signature.png")

(refer-to ["properties.child"])
(refer-to ["entities.erwin_planck"])
(fact claim "Max Planck" "child" "Erwin Planck")

(refer-to ["properties.place_of_death"])
(refer-to ["entities.göttingen"])
(fact claim "Max Planck" "place-of-death" "Göttingen")

(refer-to ["properties.sex"])
(refer-to ["clazzes.male"])
(fact claim "Max Planck" "sex" "male")

(refer-to ["properties.father"])
(fact claim "Max Planck" "father" "Q106490")

(refer-to ["properties.grandparent"])
(refer-to ["entities.gottlieb_jakob_planck"])
(fact claim "Max Planck" "grandparent" "Gottlieb Jakob Planck")

(refer-to ["properties.alma_mater"])
(refer-to ["entities.ludwig_maximilian_university_of_munich"])
(fact claim "Max Planck" "alma-mater" "Ludwig Maximilian University of Munich")
(refer-to ["entities.humboldt_university_of_berlin"])
(fact claim "Max Planck" "alma-mater" "Humboldt University of Berlin")

(refer-to ["properties.country_of_citizenship"])
(refer-to ["entities.germany"])
(fact claim "Max Planck" "country-of-citizenship" "Germany")

(refer-to ["properties.image"])
(fact claim "Max Planck" "image" "Max Planck (1858-1947).jpg")

(refer-to ["properties.place_of_birth"])
(refer-to ["entities.kiel"])
(fact claim "Max Planck" "place-of-birth" "Kiel")

(refer-to ["properties.doctoral_advisor"])
(refer-to ["entities.alexander_von_brill"])
(fact claim "Max Planck" "doctoral-advisor" "Alexander von Brill")

(refer-to ["properties.religion"])
(refer-to ["clazzes.lutheranism"])
(fact claim "Max Planck" "religion" "Lutheranism")

(refer-to ["properties.doctoral_student"])
(refer-to ["entities.richard_becker"])
(fact claim "Max Planck" "doctoral-student" "Richard Becker")
(refer-to ["entities.max_von_laue"])
(fact claim "Max Planck" "doctoral-student" "Max von Laue")
(refer-to ["entities.moritz_schlick"])
(fact claim "Max Planck" "doctoral-student" "Moritz Schlick")
(refer-to ["entities.max_abraham"])
(fact claim "Max Planck" "doctoral-student" "Max Abraham")
(refer-to ["entities.walther_bothe"])
(fact claim "Max Planck" "doctoral-student" "Walther Bothe")
(refer-to ["entities.walter_gordon"])
(fact claim "Max Planck" "doctoral-student" "Walter Gordon")
(refer-to ["clazzes.hilde_heinicke"])
(fact claim "Max Planck" "doctoral-student" "Hilde Heinicke")
(refer-to ["entities.gustav_ludwig_hertz"])
(fact claim "Max Planck" "doctoral-student" "Gustav Ludwig Hertz")
(refer-to ["clazzes.heinrich_karstens"])
(fact claim "Max Planck" "doctoral-student" "Heinrich Karstens")
(refer-to ["clazzes.karl_körner"])
(fact claim "Max Planck" "doctoral-student" "Karl Körner")
(refer-to ["entities.erich_kretschmann"])
(fact claim "Max Planck" "doctoral-student" "Erich Kretschmann")
(refer-to ["clazzes.isidor_israel_malkin"])
(fact claim "Max Planck" "doctoral-student" "Isidor Israel Malkin")
(refer-to ["entities.walther_meissner"])
(fact claim "Max Planck" "doctoral-student" "Walther Meissner")
(refer-to ["entities.walter_h__schottky"])
(fact claim "Max Planck" "doctoral-student" "Walter H. Schottky")
(refer-to ["entities.erich_schumann"])
(fact claim "Max Planck" "doctoral-student" "Erich Schumann")
(refer-to ["clazzes.wilhelm_wenzel"])
(fact claim "Max Planck" "doctoral-student" "Wilhelm Wenzel")

(refer-to ["properties.date_of_death"])
(fact claim "Max Planck" "date-of-death" "+00000001947-10-04T00:00:00Z")

(refer-to ["properties.aut_nkc"])
(fact claim "Max Planck" "aut-nkc" "jn20000604452")

(refer-to ["properties.commons_category"])
(refer-to ["entities.max_planck"])
(fact claim "Max Planck" "commons-category" "Max Planck")
