(ns entities.switzerland
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Geographical-feature "Switzerland")

(name-as-in "Switzerland" "Schweiz" "de")
(name-as-in "Switzerland" "瑞士" "zh-hk")
(name-as-in "Switzerland" "瑞士" "zh-tw")
(name-as-in "Switzerland" "Швейцария" "ru")
(name-as-in "Switzerland" "Suíça" "pt")
(name-as-in "Switzerland" "Switzerland" "en")
(name-as-in "Switzerland" "瑞士" "zh-cn")
(name-as-in "Switzerland" "Suisse" "fr")
(name-as-in "Switzerland" "Suiza" "es")
(name-as-in "Switzerland" "瑞士" "zh-sg")
(name-as-in "Switzerland" "スイス" "ja")
(name-as-in "Switzerland" "瑞士" "zh-hans")
(name-as-in "Switzerland" "瑞士" "zh-hant")

(descr-as-in "Switzerland" "Staat in Mitteleuropa" "de")
(descr-as-in "Switzerland" "西歐國家" "zh-hk")
(descr-as-in "Switzerland" "西歐國家" "zh-tw")
(descr-as-in "Switzerland" "страна в Европе" "ru")
(descr-as-in "Switzerland" "" "pt")
(descr-as-in "Switzerland" "federal republic in Western Europe" "en")
(descr-as-in "Switzerland" "西欧国家" "zh-cn")
(descr-as-in "Switzerland" "pays d'Europe" "fr")
(descr-as-in "Switzerland" "país de Europa" "es")
(descr-as-in "Switzerland" "西欧国家" "zh-sg")
(descr-as-in "Switzerland" "" "ja")
(descr-as-in "Switzerland" "西欧国家" "zh-hans")
(descr-as-in "Switzerland" "西歐國家" "zh-hant")


(refer-to ["properties.iso_3166_1_alpha_2"])
(fact claim "Switzerland" "iso-3166-1-alpha-2" "CH")

(refer-to ["properties.locator_map_image"])
(fact claim "Switzerland" "locator-map-image" "Europe-Switzerland.svg")

(refer-to ["properties.iso_3166_1_alpha_3"])
(fact claim "Switzerland" "iso-3166-1-alpha-3" "CHE")

(refer-to ["properties.country_calling_code"])
(fact claim "Switzerland" "country-calling-code" "+41")

(refer-to ["properties.iso_3166_1_numeric"])
(fact claim "Switzerland" "iso-3166-1-numeric" "756")

(refer-to ["properties.bnf_identifier"])
(fact claim "Switzerland" "bnf-identifier" "11868612h")

(refer-to ["properties.fips"])
(fact claim "Switzerland" "fips" "SZ")

(refer-to ["properties.isni_iso_27729"])
(fact claim "Switzerland" "isni-iso-27729" "0000 0001 2299 4614")

(refer-to ["properties.sudoc_identifier"])
(fact claim "Switzerland" "sudoc-identifier" "026438658")

(refer-to ["properties.highest_point"])
(refer-to ["entities.dufourspitze"])
(fact claim "Switzerland" "highest-point" "Dufourspitze")

(refer-to ["properties.viaf_identifier"])
(fact claim "Switzerland" "viaf-identifier" "159363991")

(refer-to ["properties.head_of_government"])
(refer-to ["entities.federal_council"])
(fact claim "Switzerland" "head-of-government" "Federal Council")

(refer-to ["properties.openstreetmap_relation_id"])
(fact claim "Switzerland" "openstreetmap-relation-id" "51701")

(refer-to ["properties.foundational_text"])
(refer-to ["clazzes.federal_charter_of_1291"])
(fact claim "Switzerland" "foundational-text" "Federal Charter of 1291")
(refer-to ["clazzes.swiss_federal_constitution"])
(fact claim "Switzerland" "foundational-text" "Swiss Federal Constitution")

(refer-to ["properties.main_type_gnd"])
(refer-to ["clazzes.geographical_feature"])
(fact claim "Switzerland" "main-type-gnd" "geographical feature")

(refer-to ["properties.coordinate_location"])
(fact claim "Switzerland" "coordinate-location" "lng 8.3333333333333 lat 46.833333333333 alt ")

(refer-to ["properties.nuts_code"])
(fact claim "Switzerland" "nuts-code" "CH")
(fact claim "Switzerland" "nuts-code" "CH0")

(refer-to ["properties.continent"])
(refer-to ["entities.europe"])
(fact claim "Switzerland" "continent" "Europe")

(refer-to ["properties.flag_image"])
(fact claim "Switzerland" "flag-image" "Flag of Switzerland.svg")

(refer-to ["properties.anthem"])
(refer-to ["clazzes.swiss_psalm"])
(fact claim "Switzerland" "anthem" "Swiss Psalm")

(refer-to ["properties.instance_of"])
(refer-to ["clazzes.sovereign_state"])
(fact claim "Switzerland" "instance-of" "sovereign state")
(refer-to ["clazzes.federal_republic"])
(fact claim "Switzerland" "instance-of" "federal republic")
(refer-to ["clazzes.country"])
(fact claim "Switzerland" "instance-of" "country")

(refer-to ["properties.top_level_domain"])
(refer-to ["clazzes._ch"])
(fact claim "Switzerland" "top-level-domain" ".ch")

(refer-to ["properties.head_of_state"])
(refer-to ["entities.federal_council"])
(fact claim "Switzerland" "head-of-state" "Federal Council")

(refer-to ["properties.capital"])
(refer-to ["entities.bern"])
(fact claim "Switzerland" "capital" "Bern")

(refer-to ["properties.shares_border_with"])
(refer-to ["entities.italy"])
(fact claim "Switzerland" "shares-border-with" "Italy")
(refer-to ["entities.austria"])
(fact claim "Switzerland" "shares-border-with" "Austria")
(refer-to ["entities.liechtenstein"])
(fact claim "Switzerland" "shares-border-with" "Liechtenstein")
(refer-to ["entities.germany"])
(fact claim "Switzerland" "shares-border-with" "Germany")
(refer-to ["entities.france"])
(fact claim "Switzerland" "shares-border-with" "France")

(refer-to ["properties.official_language"])
(refer-to ["clazzes.german"])
(fact claim "Switzerland" "official-language" "German")
(refer-to ["clazzes.italian"])
(fact claim "Switzerland" "official-language" "Italian")
(refer-to ["clazzes.french"])
(fact claim "Switzerland" "official-language" "French")
(refer-to ["clazzes.romansh_language"])
(fact claim "Switzerland" "official-language" "Romansh language")

(refer-to ["properties.currency"])
(refer-to ["clazzes.swiss_franc"])
(fact claim "Switzerland" "currency" "Swiss franc")

(refer-to ["properties.country"])
(refer-to ["entities.switzerland"])
(fact claim "Switzerland" "country" "Switzerland")

(refer-to ["properties.contains_administrative_division"])
(refer-to ["entities.appenzell_ausserrhoden"])
(fact claim "Switzerland" "contains-administrative-division" "Appenzell Ausserrhoden")
(refer-to ["entities.appenzell_innerrhoden"])
(fact claim "Switzerland" "contains-administrative-division" "Appenzell Innerrhoden")
(refer-to ["entities.aargau"])
(fact claim "Switzerland" "contains-administrative-division" "Aargau")
(refer-to ["entities.basel_land"])
(fact claim "Switzerland" "contains-administrative-division" "Basel-Land")
(refer-to ["entities.basel_stadt"])
(fact claim "Switzerland" "contains-administrative-division" "Basel-Stadt")
(refer-to ["entities.canton_of_bern"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Bern")
(refer-to ["entities.canton_of_fribourg"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Fribourg")
(refer-to ["entities.canton_of_geneva"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Geneva")
(refer-to ["entities.canton_of_glarus"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Glarus")
(refer-to ["entities.graubünden"])
(fact claim "Switzerland" "contains-administrative-division" "Graubünden")
(refer-to ["entities.canton_of_jura"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Jura")
(refer-to ["entities.canton_of_lucerne"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Lucerne")
(refer-to ["entities.canton_of_neuchâtel"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Neuchâtel")
(refer-to ["entities.nidwalden"])
(fact claim "Switzerland" "contains-administrative-division" "Nidwalden")
(refer-to ["entities.obwalden"])
(fact claim "Switzerland" "contains-administrative-division" "Obwalden")
(refer-to ["entities.canton_of_st__gallen"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of St. Gallen")
(refer-to ["entities.canton_of_schaffhausen"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Schaffhausen")
(refer-to ["entities.canton_of_schwyz"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Schwyz")
(refer-to ["entities.canton_of_solothurn"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Solothurn")
(refer-to ["entities.ticino"])
(fact claim "Switzerland" "contains-administrative-division" "Ticino")
(refer-to ["entities.thurgau"])
(fact claim "Switzerland" "contains-administrative-division" "Thurgau")
(refer-to ["entities.uri"])
(fact claim "Switzerland" "contains-administrative-division" "Uri")
(refer-to ["entities.canton_of_valais"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Valais")
(refer-to ["entities.canton_of_vaud"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Vaud")
(refer-to ["entities.canton_of_zug"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Zug")
(refer-to ["entities.canton_of_zurich"])
(fact claim "Switzerland" "contains-administrative-division" "Canton of Zurich")

(refer-to ["properties.legislative_body"])
(refer-to ["clazzes.federal_assembly"])
(fact claim "Switzerland" "legislative-body" "Federal Assembly")

(refer-to ["properties.flag"])
(refer-to ["clazzes.flag_of_switzerland"])
(fact claim "Switzerland" "flag" "Flag of Switzerland")

(refer-to ["properties.aut_nkc"])
(fact claim "Switzerland" "aut-nkc" "ge131576")

(refer-to ["properties.licence_plate_code"])
(fact claim "Switzerland" "licence-plate-code" "CH")

(refer-to ["properties.commons_category"])
(refer-to ["entities.switzerland"])
(fact claim "Switzerland" "commons-category" "Switzerland")
