(ns clazzes.franklin_medal
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Term "Franklin Medal")

(name-as-in "Franklin Medal" "Franklin-Medaille" "de")
(name-as-in "Franklin Medal" "" "zh-hk")
(name-as-in "Franklin Medal" "" "zh-tw")
(name-as-in "Franklin Medal" "Медаль Франклина" "ru")
(name-as-in "Franklin Medal" "Medalha Franklin" "pt")
(name-as-in "Franklin Medal" "Franklin Medal" "en")
(name-as-in "Franklin Medal" "" "zh-cn")
(name-as-in "Franklin Medal" "Médaille Franklin" "fr")
(name-as-in "Franklin Medal" "" "es")
(name-as-in "Franklin Medal" "" "zh-sg")
(name-as-in "Franklin Medal" "フランクリン・メダル" "ja")
(name-as-in "Franklin Medal" "" "zh-hans")
(name-as-in "Franklin Medal" "" "zh-hant")

(descr-as-in "Franklin Medal" "Wissenschaftspreis des Franklin Instituts in Philadelphia, USA" "de")
(descr-as-in "Franklin Medal" "" "zh-hk")
(descr-as-in "Franklin Medal" "" "zh-tw")
(descr-as-in "Franklin Medal" "" "ru")
(descr-as-in "Franklin Medal" "" "pt")
(descr-as-in "Franklin Medal" "science award by the Franklin Institute, Philadelphia" "en")
(descr-as-in "Franklin Medal" "" "zh-cn")
(descr-as-in "Franklin Medal" "" "fr")
(descr-as-in "Franklin Medal" "" "es")
(descr-as-in "Franklin Medal" "" "zh-sg")
(descr-as-in "Franklin Medal" "" "ja")
(descr-as-in "Franklin Medal" "" "zh-hans")
(descr-as-in "Franklin Medal" "" "zh-hant")


(refer-to ["properties.subclass_of"])
(refer-to ["clazzes.award"])
(fact claim "Franklin Medal" "subclass-of" "award")

(refer-to ["properties.named_after"])
(refer-to ["entities.benjamin_franklin"])
(fact claim "Franklin Medal" "named-after" "Benjamin Franklin")
