(ns clazzes.germans
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Term "Germans")

(name-as-in "Germans" "" "zh-hk")
(name-as-in "Germans" "alemães" "pt")
(name-as-in "Germans" "Germans" "en")
(name-as-in "Germans" "allemand" "fr")
(name-as-in "Germans" "" "zh-tw")
(name-as-in "Germans" "Deutsche" "de")
(name-as-in "Germans" "немцы" "ru")
(name-as-in "Germans" "alemanes" "es")
(name-as-in "Germans" "ドイツ人" "ja")
(name-as-in "Germans" "" "zh-cn")
(name-as-in "Germans" "" "zh-sg")

(descr-as-in "Germans" "" "zh-hk")
(descr-as-in "Germans" "" "pt")
(descr-as-in "Germans" "citizens or native-born people of Germany; or people of descent to the ethnic and ethnolinguistic group associated with the German language" "en")
(descr-as-in "Germans" "nationalité" "fr")
(descr-as-in "Germans" "" "zh-tw")
(descr-as-in "Germans" "Ethnie" "de")
(descr-as-in "Germans" "германский народ, основное население Германии, Австрии, Лихтенштейна и немецкоязычной части Швейцарии" "ru")
(descr-as-in "Germans" "grupo étnico" "es")
(descr-as-in "Germans" "" "ja")
(descr-as-in "Germans" "" "zh-cn")
(descr-as-in "Germans" "" "zh-sg")


(refer-to ["properties.country"])
(fact claim "Germans" "country" "Q183")
(fact claim "Germans" "country" "Q30")
(fact claim "Germans" "country" "Q16")
(fact claim "Germans" "country" "Q155")
(fact claim "Germans" "country" "Q408")
(fact claim "Germans" "country" "Q414")
(fact claim "Germans" "country" "Q159")
(fact claim "Germans" "country" "Q232")
(fact claim "Germans" "country" "Q36")
(fact claim "Germans" "country" "Q298")
(fact claim "Germans" "country" "Q218")
(fact claim "Germans" "country" "Q34")
(fact claim "Germans" "country" "Q212")
(fact claim "Germans" "country" "Q213")
(fact claim "Germans" "country" "Q184")
(fact claim "Germans" "country" "Q227")
(fact claim "Germans" "country" "Q863")

(refer-to ["properties.commons_category"])
(refer-to ["clazzes.germans"])
(fact claim "Germans" "commons-category" "Germans")

(refer-to ["properties.topics_main_category"])
(fact claim "Germans" "topic's-main-category" "Q3919754")
(fact claim "Germans" "topic's-main-category" "Q15636801")

(refer-to ["properties.native_language"])
(fact claim "Germans" "native-language" "Q188")

(refer-to ["properties.freebase_id"])
(fact claim "Germans" "freebase-id" "/m/013xrm")

(refer-to ["properties.ndl_auth_id"])
(fact claim "Germans" "ndl-auth-id" "00561625")

(refer-to ["properties.gnd_id"])
(fact claim "Germans" "gnd-id" "4070334-4")

(refer-to ["properties.has_part"])
(fact claim "Germans" "has-part" "Q13048507")
(fact claim "Germans" "has-part" "Q1970302")
(fact claim "Germans" "has-part" "Q702193")
(fact claim "Germans" "has-part" "Q21652104")
(fact claim "Germans" "has-part" "Q101985")
(fact claim "Germans" "has-part" "Q141817")
(fact claim "Germans" "has-part" "Q237534")
(fact claim "Germans" "has-part" "Q4531496")

(refer-to ["properties.described_by_source"])
(fact claim "Germans" "described-by-source" "Q2657718")
(fact claim "Germans" "described-by-source" "Q19538713")

(refer-to ["properties.instance_of"])
(fact claim "Germans" "instance-of" "Q41710")
(fact claim "Germans" "instance-of" "Q231002")

(refer-to ["properties.demonym"])
(fact claim "Germans" "demonym" "monolingualtext")
(fact claim "Germans" "demonym" "monolingualtext")
(fact claim "Germans" "demonym" "monolingualtext")
(fact claim "Germans" "demonym" "monolingualtext")

(refer-to ["properties.native_label"])
(fact claim "Germans" "native-label" "monolingualtext")

(refer-to ["properties.religion"])
(fact claim "Germans" "religion" "Q23540")
(fact claim "Germans" "religion" "Q1841")

(refer-to ["properties.quora_topic_id"])
(fact claim "Germans" "quora-topic-id" "German-Ethnicity-and-People")
