(ns clazzes.nazi_book_burnings
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Term "Nazi book burnings")

(name-as-in "Nazi book burnings" "" "zh-hk")
(name-as-in "Nazi book burnings" "Queima de livros" "pt")
(name-as-in "Nazi book burnings" "Nazi book burnings" "en")
(name-as-in "Nazi book burnings" "autodafés de 1933 en Allemagne" "fr")
(name-as-in "Nazi book burnings" "" "zh-tw")
(name-as-in "Nazi book burnings" "Bücherverbrennung 1933 in Deutschland" "de")
(name-as-in "Nazi book burnings" "Сожжение книг в нацистской Германии" "ru")
(name-as-in "Nazi book burnings" "quema de libros por los nazis" "es")
(name-as-in "Nazi book burnings" "ナチス・ドイツの焚書" "ja")
(name-as-in "Nazi book burnings" "纳粹焚书" "zh-cn")
(name-as-in "Nazi book burnings" "" "zh-sg")

(descr-as-in "Nazi book burnings" "" "zh-hk")
(descr-as-in "Nazi book burnings" "" "pt")
(descr-as-in "Nazi book burnings" "campaign to burn books in Nazi Germany and Austria" "en")
(descr-as-in "Nazi book burnings" "" "fr")
(descr-as-in "Nazi book burnings" "" "zh-tw")
(descr-as-in "Nazi book burnings" "Aktion wider den undeutschen Geist durch die Nationalsozialisten" "de")
(descr-as-in "Nazi book burnings" "" "ru")
(descr-as-in "Nazi book burnings" "" "es")
(descr-as-in "Nazi book burnings" "" "ja")
(descr-as-in "Nazi book burnings" "" "zh-cn")
(descr-as-in "Nazi book burnings" "" "zh-sg")


(refer-to ["properties.subclass_of"])
(fact claim "Nazi book burnings" "subclass-of" "Q5058925")

(refer-to ["properties.country"])
(fact claim "Nazi book burnings" "country" "Q7318")
(fact claim "Nazi book burnings" "country" "Q40")

(refer-to ["properties.commons_category"])
(fact claim "Nazi book burnings" "commons-category" "Book burning in Nazi Germany")

(refer-to ["properties.target"])
(fact claim "Nazi book burnings" "target" "Q571")

(refer-to ["properties.time_period"])
(fact claim "Nazi book burnings" "time-period" "Q7318")

(refer-to ["properties.babelnet_id"])
(fact claim "Nazi book burnings" "babelnet-id" "00459801n")

(refer-to ["properties.organizer"])
(fact claim "Nazi book burnings" "organizer" "Q879313")

(refer-to ["properties.end_time"])
(fact claim "Nazi book burnings" "end-time" "+1933-10-00T00:00:00Z")

(refer-to ["properties.freebase_id"])
(fact claim "Nazi book burnings" "freebase-id" "/m/02x5zmq")

(refer-to ["properties.location"])
(fact claim "Nazi book burnings" "location" "Q699504")
(fact claim "Nazi book burnings" "location" "Q892745")
(fact claim "Nazi book burnings" "location" "Q866464")
(fact claim "Nazi book burnings" "location" "Q1169041")
(fact claim "Nazi book burnings" "location" "Q195141")
(fact claim "Nazi book burnings" "location" "Q2244782")
(fact claim "Nazi book burnings" "location" "Q2066")
(fact claim "Nazi book burnings" "location" "Q2773")
(fact claim "Nazi book burnings" "location" "Q1611")
(fact claim "Nazi book burnings" "location" "Q2384")
(fact claim "Nazi book burnings" "location" "Q1588886")
(fact claim "Nazi book burnings" "location" "Q1110315")
(fact claim "Nazi book burnings" "location" "Q14546598")
(fact claim "Nazi book burnings" "location" "Q139206")
(fact claim "Nazi book burnings" "location" "Q15853128")
(fact claim "Nazi book burnings" "location" "Q1422820")
(fact claim "Nazi book burnings" "location" "Q17321567")
(fact claim "Nazi book burnings" "location" "Q2496418")
(fact claim "Nazi book burnings" "location" "Q19308768")
(fact claim "Nazi book burnings" "location" "Q1430309")
(fact claim "Nazi book burnings" "location" "Q2576193")
(fact claim "Nazi book burnings" "location" "Q561084")
(fact claim "Nazi book burnings" "location" "Q1589543")
(fact claim "Nazi book burnings" "location" "Q1981124")
(fact claim "Nazi book burnings" "location" "Q875360")
(fact claim "Nazi book burnings" "location" "Q17326832")
(fact claim "Nazi book burnings" "location" "Q30003514")
(fact claim "Nazi book burnings" "location" "Q866854")
(fact claim "Nazi book burnings" "location" "Q1583311")
(fact claim "Nazi book burnings" "location" "Q1697122")
(fact claim "Nazi book burnings" "location" "Q902341")
(fact claim "Nazi book burnings" "location" "Q866512")
(fact claim "Nazi book burnings" "location" "Q1358486")
(fact claim "Nazi book burnings" "location" "Q19965437")
(fact claim "Nazi book burnings" "location" "Q1454379")
(fact claim "Nazi book burnings" "location" "Q19588687")
(fact claim "Nazi book burnings" "location" "Q1009493")
(fact claim "Nazi book burnings" "location" "Q2103")
(fact claim "Nazi book burnings" "location" "Q1731")
(fact claim "Nazi book burnings" "location" "Q2966")
(fact claim "Nazi book burnings" "location" "Q3758")
(fact claim "Nazi book burnings" "location" "Q2079")
(fact claim "Nazi book burnings" "location" "Q1726")
(fact claim "Nazi book burnings" "location" "Q2742")
(fact claim "Nazi book burnings" "location" "Q4007")
(fact claim "Nazi book burnings" "location" "Q2999")
(fact claim "Nazi book burnings" "location" "Q3936")
(fact claim "Nazi book burnings" "location" "Q14835")
(fact claim "Nazi book burnings" "location" "Q2973")
(fact claim "Nazi book burnings" "location" "Q1719369")
(fact claim "Nazi book burnings" "location" "Q2833")
(fact claim "Nazi book burnings" "location" "Q505495")
(fact claim "Nazi book burnings" "location" "Q3874")
(fact claim "Nazi book burnings" "location" "Q3033")
(fact claim "Nazi book burnings" "location" "Q4098")
(fact claim "Nazi book burnings" "location" "Q4120832")
(fact claim "Nazi book burnings" "location" "Q3869")
(fact claim "Nazi book burnings" "location" "Q2861")
(fact claim "Nazi book burnings" "location" "Q1404")
(fact claim "Nazi book burnings" "location" "Q3852")
(fact claim "Nazi book burnings" "location" "Q2880")
(fact claim "Nazi book burnings" "location" "Q519729")
(fact claim "Nazi book burnings" "location" "Q506856")
(fact claim "Nazi book burnings" "location" "Q1720")
(fact claim "Nazi book burnings" "location" "Q2119")
(fact claim "Nazi book burnings" "location" "Q3958")
(fact claim "Nazi book burnings" "location" "Q4149")
(fact claim "Nazi book burnings" "location" "Q3042")
(fact claim "Nazi book burnings" "location" "Q3046")
(fact claim "Nazi book burnings" "location" "Q3050")
(fact claim "Nazi book burnings" "location" "Q83039")
(fact claim "Nazi book burnings" "location" "Q3955")
(fact claim "Nazi book burnings" "location" "Q8248")
(fact claim "Nazi book burnings" "location" "Q506780")
(fact claim "Nazi book burnings" "location" "Q187544")
(fact claim "Nazi book burnings" "location" "Q4044")

(refer-to ["properties.instance_of"])
(fact claim "Nazi book burnings" "instance-of" "Q1190554")
(fact claim "Nazi book burnings" "instance-of" "Q22702")

(refer-to ["properties.part_of"])
(fact claim "Nazi book burnings" "part-of" "Q122131")

(refer-to ["properties.image"])
(fact claim "Nazi book burnings" "image" "Bundesarchiv Bild 102-14597, Berlin, Opernplatz, Bücherverbrennung.jpg")

(refer-to ["properties.destroyed"])
(fact claim "Nazi book burnings" "destroyed" "Q571")
(fact claim "Nazi book burnings" "destroyed" "Q73974")

(refer-to ["properties.has_contributing_factor"])
(fact claim "Nazi book burnings" "has-contributing-factor" "Q7857654")
(fact claim "Nazi book burnings" "has-contributing-factor" "Q1861719")

(refer-to ["properties.start_time"])
(fact claim "Nazi book burnings" "start-time" "+1933-03-00T00:00:00Z")

(refer-to ["properties.ushmm_holocaust_encyclopedia_id"])
(fact claim "Nazi book burnings" "ushmm-holocaust-encyclopedia-id" "10005852")
