(ns clazzes.prague
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Term "Prague")

(name-as-in "Prague" "布拉格" "zh-hk")
(name-as-in "Prague" "Praga" "pt")
(name-as-in "Prague" "Prague" "en")
(name-as-in "Prague" "Prague" "fr")
(name-as-in "Prague" "布拉格" "zh-tw")
(name-as-in "Prague" "Prag" "de")
(name-as-in "Prague" "Прага" "ru")
(name-as-in "Prague" "Praga" "es")
(name-as-in "Prague" "プラハ" "ja")
(name-as-in "Prague" "" "zh-cn")
(name-as-in "Prague" "" "zh-sg")

(descr-as-in "Prague" "" "zh-hk")
(descr-as-in "Prague" "capital da República Checa" "pt")
(descr-as-in "Prague" "capital city of the Czech Republic" "en")
(descr-as-in "Prague" "capitale de la République tchèque" "fr")
(descr-as-in "Prague" "" "zh-tw")
(descr-as-in "Prague" "Hauptstadt Tschechiens" "de")
(descr-as-in "Prague" "столица Чехии" "ru")
(descr-as-in "Prague" "Capital de la República Checa" "es")
(descr-as-in "Prague" "チェコの首都" "ja")
(descr-as-in "Prague" "" "zh-cn")
(descr-as-in "Prague" "" "zh-sg")


(refer-to ["properties.country"])
(fact claim "Prague" "country" "Q213")
(fact claim "Prague" "country" "Q33946")
(refer-to ["clazzes.austria_hungary"])
(fact claim "Prague" "country" "Austria-Hungary")
(fact claim "Prague" "country" "Q131964")
(fact claim "Prague" "country" "Q42585")
(fact claim "Prague" "country" "Q2162698")
(fact claim "Prague" "country" "Q33946")
(fact claim "Prague" "country" "Q152750")

(refer-to ["properties.head_of_government"])
(fact claim "Prague" "head-of-government" "Q18104657")
(fact claim "Prague" "head-of-government" "Q10547432")
(fact claim "Prague" "head-of-government" "Q890970")
(fact claim "Prague" "head-of-government" "Q712430")
(fact claim "Prague" "head-of-government" "Q12021474")
(fact claim "Prague" "head-of-government" "Q630367")
(fact claim "Prague" "head-of-government" "Q509047")
(fact claim "Prague" "head-of-government" "Q12037238")
(fact claim "Prague" "head-of-government" "Q12023878")
(fact claim "Prague" "head-of-government" "Q15621392")
(fact claim "Prague" "head-of-government" "Q10857536")
(fact claim "Prague" "head-of-government" "Q12017714")
(fact claim "Prague" "head-of-government" "Q10857763")
(fact claim "Prague" "head-of-government" "Q11023716")
(fact claim "Prague" "head-of-government" "Q10710292")
(fact claim "Prague" "head-of-government" "Q11985895")
(fact claim "Prague" "head-of-government" "Q3490563")
(fact claim "Prague" "head-of-government" "Q11985895")
(fact claim "Prague" "head-of-government" "Q10781275")
(fact claim "Prague" "head-of-government" "Q12043184")
(fact claim "Prague" "head-of-government" "Q3490563")
(fact claim "Prague" "head-of-government" "Q343248")
(fact claim "Prague" "head-of-government" "Q12048031")
(fact claim "Prague" "head-of-government" "Q12028220")
(fact claim "Prague" "head-of-government" "Q4682983")
(fact claim "Prague" "head-of-government" "Q12022993")
(fact claim "Prague" "head-of-government" "Q11171177")
(fact claim "Prague" "head-of-government" "Q12024879")
(fact claim "Prague" "head-of-government" "Q12003229")
(fact claim "Prague" "head-of-government" "Q7940786")
(fact claim "Prague" "head-of-government" "Q11878707")
(fact claim "Prague" "head-of-government" "Q12026110")
(fact claim "Prague" "head-of-government" "Q12016975")
(fact claim "Prague" "head-of-government" "Q1541821")
(fact claim "Prague" "head-of-government" "Q7940553")
(fact claim "Prague" "head-of-government" "Q12017602")
(fact claim "Prague" "head-of-government" "Q14790923")
(fact claim "Prague" "head-of-government" "Q31314889")
(fact claim "Prague" "head-of-government" "Q10854115")
(fact claim "Prague" "head-of-government" "Q25478870")
(fact claim "Prague" "head-of-government" "Q33143741")
(fact claim "Prague" "head-of-government" "Q41757000")
(fact claim "Prague" "head-of-government" "Q42305043")

(refer-to ["properties.locator_map_image"])
(fact claim "Prague" "locator-map-image" "2004 Praha.png")

(refer-to ["properties.commons_gallery"])
(fact claim "Prague" "commons-gallery" "Praha")

(refer-to ["properties.catholic_encyclopedia_id"])
(fact claim "Prague" "catholic-encyclopedia-id" "12338a")

(refer-to ["properties.contains_settlement"])
(fact claim "Prague" "contains-settlement" "Q577602")
(fact claim "Prague" "contains-settlement" "Q973974")
(fact claim "Prague" "contains-settlement" "Q1490045")
(fact claim "Prague" "contains-settlement" "Q2071681")
(fact claim "Prague" "contains-settlement" "Q2157550")
(fact claim "Prague" "contains-settlement" "Q2444636")
(fact claim "Prague" "contains-settlement" "Q2444921")
(fact claim "Prague" "contains-settlement" "Q2598899")
(fact claim "Prague" "contains-settlement" "Q2667290")
(fact claim "Prague" "contains-settlement" "Q2686587")
(fact claim "Prague" "contains-settlement" "Q2743565")
(fact claim "Prague" "contains-settlement" "Q2750534")
(fact claim "Prague" "contains-settlement" "Q3490557")
(fact claim "Prague" "contains-settlement" "Q3490834")
(fact claim "Prague" "contains-settlement" "Q3490843")
(fact claim "Prague" "contains-settlement" "Q3490864")
(fact claim "Prague" "contains-settlement" "Q3498074")
(fact claim "Prague" "contains-settlement" "Q13361279")
(fact claim "Prague" "contains-settlement" "Q26807279")
(fact claim "Prague" "contains-settlement" "Q12028979")
(fact claim "Prague" "contains-settlement" "Q10565884")
(fact claim "Prague" "contains-settlement" "Q11081269")

(refer-to ["properties.great_russian_encyclopedia_online_id"])
(fact claim "Prague" "great-russian-encyclopedia-online-id" "3165617")

(refer-to ["properties.history_of_topic"])
(fact claim "Prague" "history-of-topic" "Q476797")

(refer-to ["properties.world_heritage_criteria"])
(fact claim "Prague" "world-heritage-criteria" "Q23038976")
(fact claim "Prague" "world-heritage-criteria" "Q23038978")
(fact claim "Prague" "world-heritage-criteria" "Q23038980")

(refer-to ["properties.commons_category"])
(refer-to ["clazzes.prague"])
(fact claim "Prague" "commons-category" "Prague")

(refer-to ["properties.page_banner"])
(fact claim "Prague" "page-banner" "Prague WV banner.jpg")

(refer-to ["properties.encyclopædia_britannica_online_id"])
(fact claim "Prague" "encyclopædia-britannica-online-id" "place/Prague")

(refer-to ["properties.shares_border_with"])
(fact claim "Prague" "shares-border-with" "Q188399")
(fact claim "Prague" "shares-border-with" "Q302778")
(fact claim "Prague" "shares-border-with" "Q645376")
(fact claim "Prague" "shares-border-with" "Q164457")
(fact claim "Prague" "shares-border-with" "Q169129")
(fact claim "Prague" "shares-border-with" "Q330653")
(fact claim "Prague" "shares-border-with" "Q339112")
(fact claim "Prague" "shares-border-with" "Q373414")
(fact claim "Prague" "shares-border-with" "Q386988")
(fact claim "Prague" "shares-border-with" "Q775949")
(fact claim "Prague" "shares-border-with" "Q896274")
(fact claim "Prague" "shares-border-with" "Q936675")
(fact claim "Prague" "shares-border-with" "Q1322371")
(fact claim "Prague" "shares-border-with" "Q1421441")
(fact claim "Prague" "shares-border-with" "Q1630623")
(fact claim "Prague" "shares-border-with" "Q1756968")
(fact claim "Prague" "shares-border-with" "Q1857646")
(fact claim "Prague" "shares-border-with" "Q2030200")
(fact claim "Prague" "shares-border-with" "Q2038198")
(fact claim "Prague" "shares-border-with" "Q2053522")
(fact claim "Prague" "shares-border-with" "Q2077582")
(fact claim "Prague" "shares-border-with" "Q2081396")
(fact claim "Prague" "shares-border-with" "Q2183926")
(fact claim "Prague" "shares-border-with" "Q2192982")
(fact claim "Prague" "shares-border-with" "Q2219017")
(fact claim "Prague" "shares-border-with" "Q2249194")
(fact claim "Prague" "shares-border-with" "Q2251197")
(fact claim "Prague" "shares-border-with" "Q2301557")
(fact claim "Prague" "shares-border-with" "Q2325178")
(fact claim "Prague" "shares-border-with" "Q2377065")
(fact claim "Prague" "shares-border-with" "Q2380033")
(fact claim "Prague" "shares-border-with" "Q2562449")
(fact claim "Prague" "shares-border-with" "Q2579171")
(fact claim "Prague" "shares-border-with" "Q2625864")
(fact claim "Prague" "shares-border-with" "Q2659639")
(fact claim "Prague" "shares-border-with" "Q2659658")
(fact claim "Prague" "shares-border-with" "Q2659866")
(fact claim "Prague" "shares-border-with" "Q2661922")
(fact claim "Prague" "shares-border-with" "Q2661964")
(fact claim "Prague" "shares-border-with" "Q2697750")
(fact claim "Prague" "shares-border-with" "Q2703980")

(refer-to ["properties.dewey_decimal_classification"])
(fact claim "Prague" "dewey-decimal-classification" "2--43712")

(refer-to ["properties.licence_plate_code"])
(fact claim "Prague" "licence-plate-code" "A")

(refer-to ["properties.google_doodle"])
(fact claim "Prague" "google-doodle" "230th-anniversary-of-pragues-existence-as-a-single-capital-city")

(refer-to ["properties.coordinate_of_southernmost_point"])
(fact claim "Prague" "coordinate-of-southernmost-point" "lng 14.39556 lat 49.9419 alt ")

(refer-to ["properties.subreddit"])
(refer-to ["clazzes.prague"])
(fact claim "Prague" "subreddit" "Prague")

(refer-to ["properties.viaf_id"])
(fact claim "Prague" "viaf-id" "153543031")

(refer-to ["properties.people_australia_id"])
(fact claim "Prague" "people-australia-id" "1440321")

(refer-to ["properties.coordinate_of_westernmost_point"])
(fact claim "Prague" "coordinate-of-westernmost-point" "lng 14.22444 lat 50.10299 alt ")

(refer-to ["properties.world_heritage_site_id"])
(fact claim "Prague" "world-heritage-site-id" "616")

(refer-to ["properties.list_of_monuments"])
(fact claim "Prague" "list-of-monuments" "Q12052213")

(refer-to ["properties.geoshape"])
(fact claim "Prague" "geoshape" "Data:Czech Republic/Hlavní město Praha.map")

(refer-to ["properties.iso_3166_2_code"])
(fact claim "Prague" "iso-3166-2-code" "CZ-PR")
(fact claim "Prague" "iso-3166-2-code" "CZ-10")

(refer-to ["properties.musicbrainz_area_id"])
(fact claim "Prague" "musicbrainz-area-id" "0a65a727-7465-4e6c-8b15-ed4d09e021ee")

(refer-to ["properties.coat_of_arms"])
(fact claim "Prague" "coat-of-arms" "Q630095")

(refer-to ["properties.located_in_the_administrative_territorial_entity"])
(fact claim "Prague" "located-in-the-administrative-territorial-entity" "Q2162698")
(fact claim "Prague" "located-in-the-administrative-territorial-entity" "Q42585")
(fact claim "Prague" "located-in-the-administrative-territorial-entity" "Q213")
(fact claim "Prague" "located-in-the-administrative-territorial-entity" "Q33946")
(fact claim "Prague" "located-in-the-administrative-territorial-entity" "Q152750")
(fact claim "Prague" "located-in-the-administrative-territorial-entity" "Q33946")
(fact claim "Prague" "located-in-the-administrative-territorial-entity" "Q1991965")
(fact claim "Prague" "located-in-the-administrative-territorial-entity" "Q3496079")

(refer-to ["properties.czech_neighbourhood_id_code"])
(fact claim "Prague" "czech-neighbourhood-id-code" "")

(refer-to ["properties.heritage_designation"])
(fact claim "Prague" "heritage-designation" "Q9259")

(refer-to ["properties.us_national_archives_identifier"])
(fact claim "Prague" "us-national-archives-identifier" "10045199")

(refer-to ["properties.babelnet_id"])
(fact claim "Prague" "babelnet-id" "00024930n")

(refer-to ["properties.topics_main_category"])
(fact claim "Prague" "topic's-main-category" "Q8967576")

(refer-to ["properties.encyclopædia_universalis_online_id"])
(fact claim "Prague" "encyclopædia-universalis-online-id" "prague")

(refer-to ["properties.postal_code"])
(fact claim "Prague" "postal-code" "10000–19900")

(refer-to ["properties.geonames_id"])
(fact claim "Prague" "geonames-id" "3067695")
(fact claim "Prague" "geonames-id" "3067696")

(refer-to ["properties.yso_id"])
(fact claim "Prague" "yso-id" "105069")

(refer-to ["properties.pronunciation_audio"])
(fact claim "Prague" "pronunciation-audio" "Cs-Praha.ogg")

(refer-to ["properties.openstreetmap_relation_identifier"])
(fact claim "Prague" "openstreetmap-relation-identifier" "435514")

(refer-to ["properties.permanent_duplicated_item"])
(fact claim "Prague" "permanent-duplicated-item" "Q21287474")

(refer-to ["properties.time_of_earliest_written_record"])
(fact claim "Prague" "time-of-earliest-written-record" "+0965-01-17T00:00:00Z")

(refer-to ["properties.category_of_associated_people"])
(fact claim "Prague" "category-of-associated-people" "Q7115510")

(refer-to ["properties.nkcr_aut_id"])
(fact claim "Prague" "nkcr-aut-id" "ge118011")

(refer-to ["properties.lau"])
(fact claim "Prague" "lau" "554782")

(refer-to ["properties.coordinate_of_easternmost_point"])
(fact claim "Prague" "coordinate-of-easternmost-point" "lng 14.70676 lat 50.08702 alt ")

(refer-to ["properties.sister_city"])
(fact claim "Prague" "sister-city" "Q64")
(fact claim "Prague" "sister-city" "Q1748")
(fact claim "Prague" "sister-city" "Q468557")
(fact claim "Prague" "sister-city" "Q2090")
(fact claim "Prague" "sister-city" "Q1842")
(fact claim "Prague" "sister-city" "Q16572")
(fact claim "Prague" "sister-city" "Q1055")
(fact claim "Prague" "sister-city" "Q1757")
(fact claim "Prague" "sister-city" "Q42807")
(fact claim "Prague" "sister-city" "Q26119")
(fact claim "Prague" "sister-city" "Q168202")
(fact claim "Prague" "sister-city" "Q13137")
(fact claim "Prague" "sister-city" "Q3936")
(fact claim "Prague" "sister-city" "Q239")
(fact claim "Prague" "sister-city" "Q1794")
(fact claim "Prague" "sister-city" "Q1218")
(fact claim "Prague" "sister-city" "Q649")
(fact claim "Prague" "sister-city" "Q656")
(fact claim "Prague" "sister-city" "Q1297")
(fact claim "Prague" "sister-city" "Q1867")
(fact claim "Prague" "sister-city" "Q8621")
(fact claim "Prague" "sister-city" "Q13362")
(fact claim "Prague" "sister-city" "Q3376")
(fact claim "Prague" "sister-city" "Q6252")
(fact claim "Prague" "sister-city" "Q13386")
(fact claim "Prague" "sister-city" "Q2634")
(fact claim "Prague" "sister-city" "Q216")
(fact claim "Prague" "sister-city" "Q406")
(fact claim "Prague" "sister-city" "Q472")
(fact claim "Prague" "sister-city" "Q1486")
(fact claim "Prague" "sister-city" "Q1524")
(fact claim "Prague" "sister-city" "Q1780")
(fact claim "Prague" "sister-city" "Q2807")
(fact claim "Prague" "sister-city" "Q3572")
(fact claim "Prague" "sister-city" "Q9005")
(fact claim "Prague" "sister-city" "Q9899")
(fact claim "Prague" "sister-city" "Q16556")
(fact claim "Prague" "sister-city" "Q19689")
(fact claim "Prague" "sister-city" "Q34600")
(fact claim "Prague" "sister-city" "Q51103")
(fact claim "Prague" "sister-city" "Q185632")
(fact claim "Prague" "sister-city" "Q201348")

(refer-to ["properties.facebook_places_id"])
(fact claim "Prague" "facebook-places-id" "110589025635590")

(refer-to ["properties.sudoc_authorities"])
(fact claim "Prague" "sudoc-authorities" "026398702")

(refer-to ["properties.instagram_username"])
(fact claim "Prague" "instagram-username" "prahaeu")

(refer-to ["properties.elevation_above_sea_level"])
(fact claim "Prague" "elevation-above-sea-level" "quantity")

(refer-to ["properties.fips_10_4_countries_and_regions"])
(fact claim "Prague" "fips-10-4-countries-and-regions" "EZ52")

(refer-to ["properties.population"])
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")
(fact claim "Prague" "population" "quantity")

(refer-to ["properties.bnf_id"])
(fact claim "Prague" "bnf-id" "15239961p")

(refer-to ["properties.national_library_of_israel_id"])
(fact claim "Prague" "national-library-of-israel-id" "000975420")

(refer-to ["properties.freebase_id"])
(fact claim "Prague" "freebase-id" "/m/05ywg")

(refer-to ["properties.contains_administrative_territorial_entity"])
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1987157")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3489935")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2467285")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2661930")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2785180")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2383655")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3490548")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2317527")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1810336")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2643835")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1822800")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2717469")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3499350")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3563232")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3563133")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509048")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3489926")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2067699")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3489932")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3490214")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3563100")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3490530")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2061921")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2122492")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2456160")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q168279")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3490395")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3489907")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3563089")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509354")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2501433")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q600063")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q693350")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509457")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509772")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3506327")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2709316")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2442419")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2499127")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2446033")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2786011")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q628212")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2440414")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2580968")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3563146")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3564567")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2320562")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1811143")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2834321")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1624461")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2460331")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509815")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509373")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3563211")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q744598")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2533951")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3499395")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509446")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1013032")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q753292")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3566606")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1734030")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q174248")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3566327")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2403918")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q868618")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509657")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2048241")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3497283")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2693443")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2003486")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2216373")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509834")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1821473")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q753289")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3490702")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2623877")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509023")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3490542")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2041885")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q753219")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1969345")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509780")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3509425")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2638290")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2078708")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1996280")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2331979")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3499402")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2612318")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q942842")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2795720")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q748211")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2219104")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2297365")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3176913")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3499380")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3490254")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3490377")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3489924")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q840751")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1013035")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q662985")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q1963689")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q580728")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q21891843")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q3499406")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2689681")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2189635")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q378120")
(fact claim "Prague" "contains-administrative-territorial-entity" "Q2782104")

(refer-to ["properties.coat_of_arms_image"])
(fact claim "Prague" "coat-of-arms-image" "Prague CoA CZ.svg")

(refer-to ["properties.coordinate_of_northernmost_point"])
(fact claim "Prague" "coordinate-of-northernmost-point" "lng 14.52686 lat 50.17743 alt ")

(refer-to ["properties.coordinate_location"])
(fact claim "Prague" "coordinate-location" "lng 14.421388888889 lat 50.088611111111 alt ")

(refer-to ["properties.facebook_profile_id"])
(fact claim "Prague" "facebook-profile-id" "Prahaeu")

(refer-to ["properties.nla_australia_id"])
(fact claim "Prague" "nla-australia-id" "36750052")

(refer-to ["properties.capital_of"])
(fact claim "Prague" "capital-of" "Q213")
(fact claim "Prague" "capital-of" "Q33946")
(fact claim "Prague" "capital-of" "Q39193")
(fact claim "Prague" "capital-of" "Q42585")
(fact claim "Prague" "capital-of" "Q188399")
(fact claim "Prague" "capital-of" "Q1991965")
(fact claim "Prague" "capital-of" "Q1998866")
(fact claim "Prague" "capital-of" "Q2162698")

(refer-to ["properties.inception"])
(fact claim "Prague" "inception" "+0800-00-00T00:00:00Z")

(refer-to ["properties.flag"])
(fact claim "Prague" "flag" "Q3504511")

(refer-to ["properties.category_for_films_shot_at_this_location"])
(fact claim "Prague" "category-for-films-shot-at-this-location" "Q10219619")

(refer-to ["properties.nuts_code"])
(fact claim "Prague" "nuts-code" "CZ010")
(fact claim "Prague" "nuts-code" "CZ01")

(refer-to ["properties.significant_event"])
(fact claim "Prague" "significant-event" "Q29778318")

(refer-to ["properties.isni"])
(fact claim "Prague" "isni" "0000 0004 0610 2462")

(refer-to ["properties.enclave_within"])
(fact claim "Prague" "enclave-within" "Q188399")

(refer-to ["properties.official_website"])
(fact claim "Prague" "official-website" "http://www.praha.eu/")

(refer-to ["properties.ndl_auth_id"])
(fact claim "Prague" "ndl-auth-id" "00629158")

(refer-to ["properties.gnd_id"])
(fact claim "Prague" "gnd-id" "4076310-9")

(refer-to ["properties.described_by_source"])
(fact claim "Prague" "described-by-source" "Q2041543")
(fact claim "Prague" "described-by-source" "Q4173137")
(fact claim "Prague" "described-by-source" "Q19180675")
(fact claim "Prague" "described-by-source" "Q602358")

(refer-to ["properties.lac_id"])
(fact claim "Prague" "lac-id" "0061F4569")

(refer-to ["properties.instance_of"])
(fact claim "Prague" "instance-of" "Q5119")
(fact claim "Prague" "instance-of" "Q15978299")
(fact claim "Prague" "instance-of" "Q38911")
(fact claim "Prague" "instance-of" "Q548611")
(fact claim "Prague" "instance-of" "Q5153359")
(fact claim "Prague" "instance-of" "Q192611")

(refer-to ["properties.legislative_body"])
(fact claim "Prague" "legislative-body" "Q10857287")

(refer-to ["properties.deepest_point"])
(fact claim "Prague" "deepest-point" "Q131574")

(refer-to ["properties.demonym"])
(fact claim "Prague" "demonym" "monolingualtext")
(fact claim "Prague" "demonym" "monolingualtext")
(fact claim "Prague" "demonym" "monolingualtext")
(fact claim "Prague" "demonym" "monolingualtext")

(refer-to ["properties.dmoz_id"])
(fact claim "Prague" "dmoz-id" "Regional/Europe/Czech_Republic/Regions/Prague/")

(refer-to ["properties.office_held_by_head_of_government"])
(fact claim "Prague" "office-held-by-head-of-government" "Q17149373")

(refer-to ["properties.local_dialing_code"])
(fact claim "Prague" "local-dialing-code" "2")

(refer-to ["properties.image"])
(fact claim "Prague" "image" "PragueCzechRepublicMalaStranaMostecka.jpg")
(fact claim "Prague" "image" "CharlesBridgeMalaStranaPragueCzechRepublic.jpg")

(refer-to ["properties.located_in_or_next_to_body_of_water"])
(fact claim "Prague" "located-in-or-next-to-body-of-water" "Q131574")

(refer-to ["properties.category_for_people_who_died_here"])
(fact claim "Prague" "category-for-people-who-died-here" "Q9913577")

(refer-to ["properties.twitter_username"])
(fact claim "Prague" "twitter-username" "PrahaEU")

(refer-to ["properties.located_in_time_zone"])
(fact claim "Prague" "located-in-time-zone" "Q6655")
(fact claim "Prague" "located-in-time-zone" "Q6723")
(fact claim "Prague" "located-in-time-zone" "Q36669")

(refer-to ["properties.topics_main_wikimedia_portal"])
(fact claim "Prague" "topic's-main-wikimedia-portal" "Q4992931")

(refer-to ["properties.highest_point"])
(fact claim "Prague" "highest-point" "Q12179822")

(refer-to ["properties.official_name"])
(fact claim "Prague" "official-name" "monolingualtext")

(refer-to ["properties.native_label"])
(fact claim "Prague" "native-label" "monolingualtext")

(refer-to ["properties.nominal_gdp"])
(fact claim "Prague" "nominal-gdp" "quantity")
(fact claim "Prague" "nominal-gdp" "quantity")
(fact claim "Prague" "nominal-gdp" "quantity")
(fact claim "Prague" "nominal-gdp" "quantity")
(fact claim "Prague" "nominal-gdp" "quantity")
(fact claim "Prague" "nominal-gdp" "quantity")

(refer-to ["properties.category_for_people_born_here"])
(fact claim "Prague" "category-for-people-born-here" "Q8068914")

(refer-to ["properties.area"])
(fact claim "Prague" "area" "quantity")

(refer-to ["properties.flag_image"])
(fact claim "Prague" "flag-image" "Flag of Prague.svg")

(refer-to ["properties.library_of_congress_authority_id"])
(fact claim "Prague" "library-of-congress-authority-id" "n79055764")

(refer-to ["properties.quora_topic_id"])
(fact claim "Prague" "quora-topic-id" "Prague-4")
