(ns clazzes.ulm
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Term "Ulm")

(name-as-in "Ulm" "" "zh-hk")
(name-as-in "Ulm" "Ulm" "pt")
(name-as-in "Ulm" "Ulm" "en")
(name-as-in "Ulm" "Ulm" "fr")
(name-as-in "Ulm" "" "zh-tw")
(name-as-in "Ulm" "Ulm" "de")
(name-as-in "Ulm" "Ульм" "ru")
(name-as-in "Ulm" "Ulm" "es")
(name-as-in "Ulm" "ウルム" "ja")
(name-as-in "Ulm" "乌尔姆" "zh-cn")
(name-as-in "Ulm" "" "zh-sg")

(descr-as-in "Ulm" "" "zh-hk")
(descr-as-in "Ulm" "" "pt")
(descr-as-in "Ulm" "city in Baden-Württemberg, Germany" "en")
(descr-as-in "Ulm" "ville d'Allemagne" "fr")
(descr-as-in "Ulm" "" "zh-tw")
(descr-as-in "Ulm" "Großstadt in Baden-Württemberg, Deutschland" "de")
(descr-as-in "Ulm" "город в земле Баден-Вюртемберг, Германия" "ru")
(descr-as-in "Ulm" "ciudad alemana" "es")
(descr-as-in "Ulm" "ドイツの都市" "ja")
(descr-as-in "Ulm" "" "zh-cn")
(descr-as-in "Ulm" "" "zh-sg")


(refer-to ["properties.country"])
(fact claim "Ulm" "country" "Q183")
(fact claim "Ulm" "country" "Q12548")
(fact claim "Ulm" "country" "Q154195")
(fact claim "Ulm" "country" "Q159631")

(refer-to ["properties.head_of_government"])
(fact claim "Ulm" "head-of-government" "Q126860")
(fact claim "Ulm" "head-of-government" "Q1359306")
(fact claim "Ulm" "head-of-government" "Q1581101")
(fact claim "Ulm" "head-of-government" "Q20770017")
(fact claim "Ulm" "head-of-government" "Q2418111")
(fact claim "Ulm" "head-of-government" "Q70898")
(fact claim "Ulm" "head-of-government" "Q24046031")
(fact claim "Ulm" "head-of-government" "Q24046033")
(fact claim "Ulm" "head-of-government" "Q972103")
(fact claim "Ulm" "head-of-government" "Q1336829")
(fact claim "Ulm" "head-of-government" "Q1599704")
(fact claim "Ulm" "head-of-government" "Q1265932")
(fact claim "Ulm" "head-of-government" "Q23879162")
(fact claim "Ulm" "head-of-government" "Q1085411")

(refer-to ["properties.locator_map_image"])
(fact claim "Ulm" "locator-map-image" "Baden-Württemberg UL (town).svg")

(refer-to ["properties.commons_gallery"])
(refer-to ["clazzes.ulm"])
(fact claim "Ulm" "commons-gallery" "Ulm")

(refer-to ["properties.commons_category"])
(refer-to ["clazzes.ulm"])
(fact claim "Ulm" "commons-category" "Ulm")

(refer-to ["properties.located_on_terrain_feature"])
(fact claim "Ulm" "located-on-terrain-feature" "Q1622371")

(refer-to ["properties.page_banner"])
(fact claim "Ulm" "page-banner" "Ulm banner.jpg")

(refer-to ["properties.shares_border_with"])
(fact claim "Ulm" "shares-border-with" "Q4120")
(fact claim "Ulm" "shares-border-with" "Q8221")
(fact claim "Ulm" "shares-border-with" "Q10410")

(refer-to ["properties.dewey_decimal_classification"])
(fact claim "Ulm" "dewey-decimal-classification" "2--4347322")

(refer-to ["properties.mountain_range"])
(fact claim "Ulm" "mountain-range" "Q159589")

(refer-to ["properties.licence_plate_code"])
(fact claim "Ulm" "licence-plate-code" "UL")

(refer-to ["properties.viaf_id"])
(fact claim "Ulm" "viaf-id" "247406865")

(refer-to ["properties.musicbrainz_area_id"])
(fact claim "Ulm" "musicbrainz-area-id" "b811f4e6-50b9-411c-bd98-9310eb0b42e3")

(refer-to ["properties.located_in_the_administrative_territorial_entity"])
(fact claim "Ulm" "located-in-the-administrative-territorial-entity" "Q8170")

(refer-to ["properties.us_national_archives_identifier"])
(fact claim "Ulm" "us-national-archives-identifier" "10044745")

(refer-to ["properties.short_name"])
(fact claim "Ulm" "short-name" "monolingualtext")
(fact claim "Ulm" "short-name" "monolingualtext")
(fact claim "Ulm" "short-name" "monolingualtext")

(refer-to ["properties.topics_main_category"])
(fact claim "Ulm" "topic's-main-category" "Q8857116")

(refer-to ["properties.postal_code"])
(fact claim "Ulm" "postal-code" "89081")
(fact claim "Ulm" "postal-code" "89073")
(fact claim "Ulm" "postal-code" "89075")
(fact claim "Ulm" "postal-code" "89077")
(fact claim "Ulm" "postal-code" "89079")

(refer-to ["properties.german_municipality_key"])
(fact claim "Ulm" "german-municipality-key" "08421000")

(refer-to ["properties.geonames_id"])
(fact claim "Ulm" "geonames-id" "2820256")

(refer-to ["properties.yso_id"])
(fact claim "Ulm" "yso-id" "108228")

(refer-to ["properties.pronunciation_audio"])
(fact claim "Ulm" "pronunciation-audio" "Ulm.ogg")

(refer-to ["properties.openstreetmap_relation_identifier"])
(fact claim "Ulm" "openstreetmap-relation-identifier" "62495")

(refer-to ["properties.time_of_earliest_written_record"])
(fact claim "Ulm" "time-of-earliest-written-record" "+0854-07-22T00:00:00Z")

(refer-to ["properties.category_of_associated_people"])
(fact claim "Ulm" "category-of-associated-people" "Q9077986")

(refer-to ["properties.nomisma_id"])
(fact claim "Ulm" "nomisma-id" "ulm")

(refer-to ["properties.german_district_key"])
(fact claim "Ulm" "german-district-key" "08421")

(refer-to ["properties.sister_city"])
(fact claim "Ulm" "sister-city" "Q1026296")
(fact claim "Ulm" "sister-city" "Q1780")
(fact claim "Ulm" "sister-city" "Q170287")
(fact claim "Ulm" "sister-city" "Q275438")

(refer-to ["properties.facebook_places_id"])
(fact claim "Ulm" "facebook-places-id" "106249829412960")

(refer-to ["properties.elevation_above_sea_level"])
(fact claim "Ulm" "elevation-above-sea-level" "quantity")

(refer-to ["properties.hds_id"])
(fact claim "Ulm" "hds-id" "6608")

(refer-to ["properties.population"])
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")
(fact claim "Ulm" "population" "quantity")

(refer-to ["properties.member_of"])
(fact claim "Ulm" "member-of" "Q1780330")

(refer-to ["properties.freebase_id"])
(fact claim "Ulm" "freebase-id" "/m/019xz9")

(refer-to ["properties.contains_administrative_territorial_entity"])
(fact claim "Ulm" "contains-administrative-territorial-entity" "Q1355936")
(fact claim "Ulm" "contains-administrative-territorial-entity" "Q1367467")
(fact claim "Ulm" "contains-administrative-territorial-entity" "Q1559217")
(fact claim "Ulm" "contains-administrative-territorial-entity" "Q1713454")
(fact claim "Ulm" "contains-administrative-territorial-entity" "Q1813353")
(fact claim "Ulm" "contains-administrative-territorial-entity" "Q972566")
(fact claim "Ulm" "contains-administrative-territorial-entity" "Q2567354")

(refer-to ["properties.coat_of_arms_image"])
(fact claim "Ulm" "coat-of-arms-image" "Coat of arms of Ulm.svg")

(refer-to ["properties.coordinate_location"])
(fact claim "Ulm" "coordinate-location" "lng 9.9833333333333 lat 48.4 alt ")

(refer-to ["properties.nuts_code"])
(fact claim "Ulm" "nuts-code" "DE144")

(refer-to ["properties.official_website"])
(fact claim "Ulm" "official-website" "http://www.ulm.de")

(refer-to ["properties.gnd_id"])
(fact claim "Ulm" "gnd-id" "4061529-7")

(refer-to ["properties.described_by_source"])
(fact claim "Ulm" "described-by-source" "Q4173137")
(fact claim "Ulm" "described-by-source" "Q19180675")
(fact claim "Ulm" "described-by-source" "Q602358")

(refer-to ["properties.instance_of"])
(fact claim "Ulm" "instance-of" "Q1549591")
(fact claim "Ulm" "instance-of" "Q1187811")
(fact claim "Ulm" "instance-of" "Q2327515")
(fact claim "Ulm" "instance-of" "Q262166")
(fact claim "Ulm" "instance-of" "Q253030")
(fact claim "Ulm" "instance-of" "Q19816359")
(fact claim "Ulm" "instance-of" "Q515")
(fact claim "Ulm" "instance-of" "Q22865")
(fact claim "Ulm" "instance-of" "Q40131033")

(refer-to ["properties.part_of"])
(fact claim "Ulm" "part-of" "Q8170")
(fact claim "Ulm" "part-of" "Q448881")

(refer-to ["properties.located_at_street_address"])
(fact claim "Ulm" "located-at-street-address" "Marktplatz")

(refer-to ["properties.local_dialing_code"])
(fact claim "Ulm" "local-dialing-code" "0731")
(fact claim "Ulm" "local-dialing-code" "07346")
(fact claim "Ulm" "local-dialing-code" "07304")
(fact claim "Ulm" "local-dialing-code" "07305")

(refer-to ["properties.image"])
(fact claim "Ulm" "image" "Ulm vom sprollheim aus.jpg")

(refer-to ["properties.located_in_or_next_to_body_of_water"])
(fact claim "Ulm" "located-in-or-next-to-body-of-water" "Q1653")
(fact claim "Ulm" "located-in-or-next-to-body-of-water" "Q159467")
(fact claim "Ulm" "located-in-or-next-to-body-of-water" "Q562302")

(refer-to ["properties.category_for_people_who_died_here"])
(fact claim "Ulm" "category-for-people-who-died-here" "Q9220239")

(refer-to ["properties.located_in_time_zone"])
(fact claim "Ulm" "located-in-time-zone" "Q6655")
(fact claim "Ulm" "located-in-time-zone" "Q6723")

(refer-to ["properties.category_for_people_born_here"])
(fact claim "Ulm" "category-for-people-born-here" "Q8076649")

(refer-to ["properties.area"])
(fact claim "Ulm" "area" "quantity")

(refer-to ["properties.archives_at"])
(fact claim "Ulm" "archives-at" "Q28720387")

(refer-to ["properties.library_of_congress_authority_id"])
(fact claim "Ulm" "library-of-congress-authority-id" "n2005067662")
