(ns clazzes.united_states_of_america
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Term "United States of America")

(name-as-in "United States of America" "美國" "zh-hk")
(name-as-in "United States of America" "Estados Unidos" "pt")
(name-as-in "United States of America" "United States of America" "en")
(name-as-in "United States of America" "États-Unis" "fr")
(name-as-in "United States of America" "美國" "zh-tw")
(name-as-in "United States of America" "Vereinigte Staaten" "de")
(name-as-in "United States of America" "Соединённые Штаты Америки" "ru")
(name-as-in "United States of America" "Estados Unidos" "es")
(name-as-in "United States of America" "アメリカ合衆国" "ja")
(name-as-in "United States of America" "美国" "zh-cn")
(name-as-in "United States of America" "美国" "zh-sg")

(descr-as-in "United States of America" "北美洲國家" "zh-hk")
(descr-as-in "United States of America" "país da América do Norte" "pt")
(descr-as-in "United States of America" "federal republic in North America" "en")
(descr-as-in "United States of America" "pays d'Amérique du Nord" "fr")
(descr-as-in "United States of America" "北美洲國家" "zh-tw")
(descr-as-in "United States of America" "Staat in Nordamerika" "de")
(descr-as-in "United States of America" "страна в Северной Америке" "ru")
(descr-as-in "United States of America" "país de América del Norte" "es")
(descr-as-in "United States of America" "北アメリカ大陸および北太平洋に位置する連邦共和国" "ja")
(descr-as-in "United States of America" "北美洲国家" "zh-cn")
(descr-as-in "United States of America" "北美洲国家" "zh-sg")


(refer-to ["properties.global_anabaptist_mennonite_encyclopedia_online_id"])
(refer-to ["clazzes.united_states_of_america"])
(fact claim "United States of America" "global-anabaptist-mennonite-encyclopedia-online-id" "United States of America")

(refer-to ["properties.country"])
(refer-to ["clazzes.united_states_of_america"])
(fact claim "United States of America" "country" "United States of America")

(refer-to ["properties.head_of_government"])
(fact claim "United States of America" "head-of-government" "Q207")
(fact claim "United States of America" "head-of-government" "Q1124")
(fact claim "United States of America" "head-of-government" "Q23505")
(fact claim "United States of America" "head-of-government" "Q9960")
(fact claim "United States of America" "head-of-government" "Q23685")
(fact claim "United States of America" "head-of-government" "Q9582")
(fact claim "United States of America" "head-of-government" "Q9588")
(fact claim "United States of America" "head-of-government" "Q9640")
(fact claim "United States of America" "head-of-government" "Q9696")
(fact claim "United States of America" "head-of-government" "Q9916")
(fact claim "United States of America" "head-of-government" "Q11613")
(fact claim "United States of America" "head-of-government" "Q8007")
(fact claim "United States of America" "head-of-government" "Q35236")
(fact claim "United States of America" "head-of-government" "Q36023")
(fact claim "United States of America" "head-of-government" "Q35286")
(fact claim "United States of America" "head-of-government" "Q34296")
(fact claim "United States of America" "head-of-government" "Q35648")
(fact claim "United States of America" "head-of-government" "Q33866")
(fact claim "United States of America" "head-of-government" "Q35041")
(fact claim "United States of America" "head-of-government" "Q35171")
(fact claim "United States of America" "head-of-government" "Q35678")
(fact claim "United States of America" "head-of-government" "Q35171")
(fact claim "United States of America" "head-of-government" "Q34597")
(fact claim "United States of America" "head-of-government" "Q35686")
(fact claim "United States of America" "head-of-government" "Q34836")
(fact claim "United States of America" "head-of-government" "Q8612")
(fact claim "United States of America" "head-of-government" "Q91")
(fact claim "United States of America" "head-of-government" "Q12325")
(fact claim "United States of America" "head-of-government" "Q12312")
(fact claim "United States of America" "head-of-government" "Q12306")
(fact claim "United States of America" "head-of-government" "Q11896")
(fact claim "United States of America" "head-of-government" "Q11891")
(fact claim "United States of America" "head-of-government" "Q11881")
(fact claim "United States of America" "head-of-government" "Q11869")
(fact claim "United States of America" "head-of-government" "Q11820")
(fact claim "United States of America" "head-of-government" "Q11817")
(fact claim "United States of America" "head-of-government" "Q11816")
(fact claim "United States of America" "head-of-government" "Q11815")
(fact claim "United States of America" "head-of-government" "Q11813")
(fact claim "United States of America" "head-of-government" "Q11812")
(fact claim "United States of America" "head-of-government" "Q11806")
(fact claim "United States of America" "head-of-government" "Q23")
(fact claim "United States of America" "head-of-government" "Q35498")
(fact claim "United States of America" "head-of-government" "Q76")
(fact claim "United States of America" "head-of-government" "Q22686")

(refer-to ["properties.ppp_gdp_per_capita"])
(fact claim "United States of America" "ppp-gdp-per-capita" "quantity")

(refer-to ["properties.locator_map_image"])
(fact claim "United States of America" "locator-map-image" "USA orthographic.svg")
(fact claim "United States of America" "locator-map-image" "USATopographicalMap.jpg")
(fact claim "United States of America" "locator-map-image" "LocationUSA.svg")

(refer-to ["properties.commons_gallery"])
(fact claim "United States of America" "commons-gallery" "United States")

(refer-to ["properties.relief_location_map"])
(fact claim "United States of America" "relief-location-map" "Usa edcp relief location map.png")

(refer-to ["properties.inflation_rate"])
(fact claim "United States of America" "inflation-rate" "quantity")

(refer-to ["properties.gdp_ppp"])
(fact claim "United States of America" "gdp-ppp" "quantity")

(refer-to ["properties.history_of_topic"])
(fact claim "United States of America" "history-of-topic" "Q131110")

(refer-to ["properties.geography_of_topic"])
(fact claim "United States of America" "geography-of-topic" "Q272160")

(refer-to ["properties.commons_category"])
(fact claim "United States of America" "commons-category" "United States")

(refer-to ["properties.page_banner"])
(fact claim "United States of America" "page-banner" "Statue of Liberty light banner.jpg")

(refer-to ["properties.gacs_id"])
(fact claim "United States of America" "gacs-id" "322")

(refer-to ["properties.ioc_country_code"])
(fact claim "United States of America" "ioc-country-code" "USA")

(refer-to ["properties.wsj_topic_id"])
(fact claim "United States of America" "wsj-topic-id" "subject/U/united-states/5590")

(refer-to ["properties.bav_id"])
(fact claim "United States of America" "bav-id" "ADV12370362")

(refer-to ["properties.encyclopædia_britannica_online_id"])
(fact claim "United States of America" "encyclopædia-britannica-online-id" "place/United-States")

(refer-to ["properties.shares_border_with"])
(fact claim "United States of America" "shares-border-with" "Q96")
(fact claim "United States of America" "shares-border-with" "Q16")
(fact claim "United States of America" "shares-border-with" "Q159")
(fact claim "United States of America" "shares-border-with" "Q241")
(fact claim "United States of America" "shares-border-with" "Q804")
(fact claim "United States of America" "shares-border-with" "Q778")
(fact claim "United States of America" "shares-border-with" "Q717")
(fact claim "United States of America" "shares-border-with" "Q248452")
(fact claim "United States of America" "shares-border-with" "Q786")
(fact claim "United States of America" "shares-border-with" "Q702")
(fact claim "United States of America" "shares-border-with" "Q17")
(fact claim "United States of America" "shares-border-with" "Q710")
(fact claim "United States of America" "shares-border-with" "Q790")
(fact claim "United States of America" "shares-border-with" "Q683")
(fact claim "United States of America" "shares-border-with" "Q678")

(refer-to ["properties.dewey_decimal_classification"])
(fact claim "United States of America" "dewey-decimal-classification" "2--73")

(refer-to ["properties.emergency_phone_number"])
(fact claim "United States of America" "emergency-phone-number" "Q533806")

(refer-to ["properties.licence_plate_code"])
(fact claim "United States of America" "licence-plate-code" "USA")

(refer-to ["properties.coordinate_of_southernmost_point"])
(fact claim "United States of America" "coordinate-of-southernmost-point" "lng -97.3948288 lat 25.8371319 alt ")

(refer-to ["properties.cantic_id"])
(fact claim "United States of America" "cantic-id" "a11444253")

(refer-to ["properties.viaf_id"])
(fact claim "United States of America" "viaf-id" "130168302")

(refer-to ["properties.people_australia_id"])
(fact claim "United States of America" "people-australia-id" "896984")
(fact claim "United States of America" "people-australia-id" "996710")
(fact claim "United States of America" "people-australia-id" "1000031")

(refer-to ["properties.coordinate_of_westernmost_point"])
(fact claim "United States of America" "coordinate-of-westernmost-point" "lng -168.11828613 lat 65.63788906 alt ")

(refer-to ["properties.language_used"])
(refer-to ["clazzes.english"])
(fact claim "United States of America" "language-used" "English")
(refer-to ["clazzes.english"])
(fact claim "United States of America" "language-used" "English")

(refer-to ["properties.real_gross_domestic_product_growth_rate"])
(fact claim "United States of America" "real-gross-domestic-product-growth-rate" "quantity")

(refer-to ["properties.ethnic_group"])
(fact claim "United States of America" "ethnic-group" "Q49078")
(fact claim "United States of America" "ethnic-group" "Q49085")
(fact claim "United States of America" "ethnic-group" "Q727928")
(fact claim "United States of America" "ethnic-group" "Q49297")

(refer-to ["properties.currency"])
(fact claim "United States of America" "currency" "Q4917")

(refer-to ["properties.official_symbol"])
(fact claim "United States of America" "official-symbol" "Q127216")

(refer-to ["properties.musicbrainz_area_id"])
(fact claim "United States of America" "musicbrainz-area-id" "489ce91b-6658-3307-9877-795b68554c98")

(refer-to ["properties.gini_coefficient"])
(fact claim "United States of America" "gini-coefficient" "quantity")

(refer-to ["properties.coat_of_arms"])
(fact claim "United States of America" "coat-of-arms" "Q171663")

(refer-to ["properties.diplomatic_relation"])
(fact claim "United States of America" "diplomatic-relation" "Q889")
(fact claim "United States of America" "diplomatic-relation" "Q222")
(fact claim "United States of America" "diplomatic-relation" "Q148")
(fact claim "United States of America" "diplomatic-relation" "Q183")
(fact claim "United States of America" "diplomatic-relation" "Q159")
(fact claim "United States of America" "diplomatic-relation" "Q408")
(fact claim "United States of America" "diplomatic-relation" "Q801")
(fact claim "United States of America" "diplomatic-relation" "Q155")
(fact claim "United States of America" "diplomatic-relation" "Q796")
(fact claim "United States of America" "diplomatic-relation" "Q403")
(fact claim "United States of America" "diplomatic-relation" "Q16")
(fact claim "United States of America" "diplomatic-relation" "Q17")
(fact claim "United States of America" "diplomatic-relation" "Q38")
(fact claim "United States of America" "diplomatic-relation" "Q347")
(fact claim "United States of America" "diplomatic-relation" "Q414")
(fact claim "United States of America" "diplomatic-relation" "Q953")
(fact claim "United States of America" "diplomatic-relation" "Q668")
(fact claim "United States of America" "diplomatic-relation" "Q37")
(fact claim "United States of America" "diplomatic-relation" "Q1011")
(fact claim "United States of America" "diplomatic-relation" "Q805")
(fact claim "United States of America" "diplomatic-relation" "Q1050")
(fact claim "United States of America" "diplomatic-relation" "Q334")
(fact claim "United States of America" "diplomatic-relation" "Q20")
(fact claim "United States of America" "diplomatic-relation" "Q142")
(fact claim "United States of America" "diplomatic-relation" "Q212")
(fact claim "United States of America" "diplomatic-relation" "Q822")
(fact claim "United States of America" "diplomatic-relation" "Q858")
(fact claim "United States of America" "diplomatic-relation" "Q884")
(fact claim "United States of America" "diplomatic-relation" "Q902")
(fact claim "United States of America" "diplomatic-relation" "Q928")
(fact claim "United States of America" "diplomatic-relation" "Q115")
(fact claim "United States of America" "diplomatic-relation" "Q184")
(fact claim "United States of America" "diplomatic-relation" "Q215")
(fact claim "United States of America" "diplomatic-relation" "Q213")
(fact claim "United States of America" "diplomatic-relation" "Q159583")
(fact claim "United States of America" "diplomatic-relation" "Q43")
(fact claim "United States of America" "diplomatic-relation" "Q227")
(fact claim "United States of America" "diplomatic-relation" "Q96")
(fact claim "United States of America" "diplomatic-relation" "Q236")
(fact claim "United States of America" "diplomatic-relation" "Q1025")
(fact claim "United States of America" "diplomatic-relation" "Q712")
(fact claim "United States of America" "diplomatic-relation" "Q851")
(fact claim "United States of America" "diplomatic-relation" "Q41")
(fact claim "United States of America" "diplomatic-relation" "Q145")
(fact claim "United States of America" "diplomatic-relation" "Q419")
(fact claim "United States of America" "diplomatic-relation" "Q811")
(fact claim "United States of America" "diplomatic-relation" "Q865")
(fact claim "United States of America" "diplomatic-relation" "Q1005")
(fact claim "United States of America" "diplomatic-relation" "Q34266")
(fact claim "United States of America" "diplomatic-relation" "Q34")
(fact claim "United States of America" "diplomatic-relation" "Q863")
(fact claim "United States of America" "diplomatic-relation" "Q25227")
(fact claim "United States of America" "diplomatic-relation" "Q458")
(fact claim "United States of America" "diplomatic-relation" "Q881")
(fact claim "United States of America" "diplomatic-relation" "Q717")
(fact claim "United States of America" "diplomatic-relation" "Q686")
(fact claim "United States of America" "diplomatic-relation" "Q265")
(fact claim "United States of America" "diplomatic-relation" "Q77")
(fact claim "United States of America" "diplomatic-relation" "Q55")
(fact claim "United States of America" "diplomatic-relation" "Q986")
(fact claim "United States of America" "diplomatic-relation" "Q1008")
(fact claim "United States of America" "diplomatic-relation" "Q31")
(fact claim "United States of America" "diplomatic-relation" "Q948")
(fact claim "United States of America" "diplomatic-relation" "Q1045")
(fact claim "United States of America" "diplomatic-relation" "Q874")
(fact claim "United States of America" "diplomatic-relation" "Q230")
(fact claim "United States of America" "diplomatic-relation" "Q15180")
(refer-to ["clazzes.switzerland"])
(fact claim "United States of America" "diplomatic-relation" "Switzerland")
(fact claim "United States of America" "diplomatic-relation" "Q916")
(fact claim "United States of America" "diplomatic-relation" "Q398")
(fact claim "United States of America" "diplomatic-relation" "Q21203")
(fact claim "United States of America" "diplomatic-relation" "Q262")
(fact claim "United States of America" "diplomatic-relation" "Q399")
(fact claim "United States of America" "diplomatic-relation" "Q23635")
(fact claim "United States of America" "diplomatic-relation" "Q967")
(fact claim "United States of America" "diplomatic-relation" "Q5785")
(fact claim "United States of America" "diplomatic-relation" "Q657")
(fact claim "United States of America" "diplomatic-relation" "Q963")
(fact claim "United States of America" "diplomatic-relation" "Q225")
(fact claim "United States of America" "diplomatic-relation" "Q298")
(fact claim "United States of America" "diplomatic-relation" "Q836")
(fact claim "United States of America" "diplomatic-relation" "Q424")
(fact claim "United States of America" "diplomatic-relation" "Q244")
(fact claim "United States of America" "diplomatic-relation" "Q242")
(fact claim "United States of America" "diplomatic-relation" "Q750")
(fact claim "United States of America" "diplomatic-relation" "Q921")
(fact claim "United States of America" "diplomatic-relation" "Q965")
(fact claim "United States of America" "diplomatic-relation" "Q224")
(fact claim "United States of America" "diplomatic-relation" "Q786")
(fact claim "United States of America" "diplomatic-relation" "Q784")
(fact claim "United States of America" "diplomatic-relation" "Q35")
(fact claim "United States of America" "diplomatic-relation" "Q33")
(fact claim "United States of America" "diplomatic-relation" "Q800")
(fact claim "United States of America" "diplomatic-relation" "Q736")
(fact claim "United States of America" "diplomatic-relation" "Q970")
(fact claim "United States of America" "diplomatic-relation" "Q229")
(fact claim "United States of America" "diplomatic-relation" "Q977")
(fact claim "United States of America" "diplomatic-relation" "Q792")
(fact claim "United States of America" "diplomatic-relation" "Q974")
(fact claim "United States of America" "diplomatic-relation" "Q574")
(fact claim "United States of America" "diplomatic-relation" "Q983")
(fact claim "United States of America" "diplomatic-relation" "Q191")
(fact claim "United States of America" "diplomatic-relation" "Q702")
(fact claim "United States of America" "diplomatic-relation" "Q790")
(fact claim "United States of America" "diplomatic-relation" "Q774")
(fact claim "United States of America" "diplomatic-relation" "Q117")
(fact claim "United States of America" "diplomatic-relation" "Q1006")
(fact claim "United States of America" "diplomatic-relation" "Q1000")
(fact claim "United States of America" "diplomatic-relation" "Q769")
(fact claim "United States of America" "diplomatic-relation" "Q1007")
(fact claim "United States of America" "diplomatic-relation" "Q734")
(fact claim "United States of America" "diplomatic-relation" "Q783")
(fact claim "United States of America" "diplomatic-relation" "Q28")
(fact claim "United States of America" "diplomatic-relation" "Q766")
(fact claim "United States of America" "diplomatic-relation" "Q189")
(fact claim "United States of America" "diplomatic-relation" "Q252")
(fact claim "United States of America" "diplomatic-relation" "Q8646")
(fact claim "United States of America" "diplomatic-relation" "Q1013")
(fact claim "United States of America" "diplomatic-relation" "Q32")
(fact claim "United States of America" "diplomatic-relation" "Q833")
(fact claim "United States of America" "diplomatic-relation" "Q843")
(fact claim "United States of America" "diplomatic-relation" "Q733")
(fact claim "United States of America" "diplomatic-relation" "Q710")
(fact claim "United States of America" "diplomatic-relation" "Q813")
(fact claim "United States of America" "diplomatic-relation" "Q1016")
(fact claim "United States of America" "diplomatic-relation" "Q1027")
(fact claim "United States of America" "diplomatic-relation" "Q730")
(fact claim "United States of America" "diplomatic-relation" "Q819")
(fact claim "United States of America" "diplomatic-relation" "Q1014")
(fact claim "United States of America" "diplomatic-relation" "Q1019")
(fact claim "United States of America" "diplomatic-relation" "Q1020")
(fact claim "United States of America" "diplomatic-relation" "Q912")
(fact claim "United States of America" "diplomatic-relation" "Q232")
(fact claim "United States of America" "diplomatic-relation" "Q1246")
(fact claim "United States of America" "diplomatic-relation" "Q709")
(fact claim "United States of America" "diplomatic-relation" "Q235")
(fact claim "United States of America" "diplomatic-relation" "Q1028")
(fact claim "United States of America" "diplomatic-relation" "Q156418")
(fact claim "United States of America" "diplomatic-relation" "Q14773")
(fact claim "United States of America" "diplomatic-relation" "Q233")
(fact claim "United States of America" "diplomatic-relation" "Q217")
(fact claim "United States of America" "diplomatic-relation" "Q711")
(fact claim "United States of America" "diplomatic-relation" "Q221")
(fact claim "United States of America" "diplomatic-relation" "Q837")
(fact claim "United States of America" "diplomatic-relation" "Q695")
(fact claim "United States of America" "diplomatic-relation" "Q760")
(fact claim "United States of America" "diplomatic-relation" "Q683")
(fact claim "United States of America" "diplomatic-relation" "Q691")
(fact claim "United States of America" "diplomatic-relation" "Q1041")
(fact claim "United States of America" "diplomatic-relation" "Q664")
(fact claim "United States of America" "diplomatic-relation" "Q1033")
(fact claim "United States of America" "diplomatic-relation" "Q45")
(fact claim "United States of America" "diplomatic-relation" "Q1037")
(fact claim "United States of America" "diplomatic-relation" "Q757")
(fact claim "United States of America" "diplomatic-relation" "Q1030")
(fact claim "United States of America" "diplomatic-relation" "Q1032")
(fact claim "United States of America" "diplomatic-relation" "Q804")
(fact claim "United States of America" "diplomatic-relation" "Q36")
(fact claim "United States of America" "diplomatic-relation" "Q170588")
(fact claim "United States of America" "diplomatic-relation" "Q218")
(fact claim "United States of America" "diplomatic-relation" "Q1042")
(fact claim "United States of America" "diplomatic-relation" "Q1044")
(fact claim "United States of America" "diplomatic-relation" "Q214")
(fact claim "United States of America" "diplomatic-relation" "Q1049")
(fact claim "United States of America" "diplomatic-relation" "Q945")
(fact claim "United States of America" "diplomatic-relation" "Q754")
(fact claim "United States of America" "diplomatic-relation" "Q826")
(fact claim "United States of America" "diplomatic-relation" "Q958")
(fact claim "United States of America" "diplomatic-relation" "Q1039")
(fact claim "United States of America" "diplomatic-relation" "Q924")
(fact claim "United States of America" "diplomatic-relation" "Q672")
(fact claim "United States of America" "diplomatic-relation" "Q22890")
(fact claim "United States of America" "diplomatic-relation" "Q854")
(fact claim "United States of America" "diplomatic-relation" "Q1036")
(fact claim "United States of America" "diplomatic-relation" "Q211")
(fact claim "United States of America" "diplomatic-relation" "Q962")
(fact claim "United States of America" "diplomatic-relation" "Q817")
(fact claim "United States of America" "diplomatic-relation" "Q971")
(fact claim "United States of America" "diplomatic-relation" "Q1029")
(fact claim "United States of America" "diplomatic-relation" "Q219060")
(fact claim "United States of America" "diplomatic-relation" "Q228")

(refer-to ["properties.unesco_thesaurus_id"])
(fact claim "United States of America" "unesco-thesaurus-id" "concept806")

(refer-to ["properties.us_national_archives_identifier"])
(fact claim "United States of America" "us-national-archives-identifier" "10045728")

(refer-to ["properties.babelnet_id"])
(fact claim "United States of America" "babelnet-id" "00003341n")

(refer-to ["properties.short_name"])
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")
(fact claim "United States of America" "short-name" "monolingualtext")

(refer-to ["properties.topics_main_category"])
(fact claim "United States of America" "topic's-main-category" "Q1410960")

(refer-to ["properties.iso_3166_1_alpha_3_code"])
(fact claim "United States of America" "iso-3166-1-alpha-3-code" "USA")

(refer-to ["properties.location_map"])
(fact claim "United States of America" "location-map" "Usa edcp location map.svg")

(refer-to ["properties.retirement_age"])
(fact claim "United States of America" "retirement-age" "quantity")

(refer-to ["properties.geonames_id"])
(fact claim "United States of America" "geonames-id" "6252001")

(refer-to ["properties.yso_id"])
(fact claim "United States of America" "yso-id" "105078")

(refer-to ["properties.openstreetmap_relation_identifier"])
(fact claim "United States of America" "openstreetmap-relation-identifier" "148838")

(refer-to ["properties.permanent_duplicated_item"])
(fact claim "United States of America" "permanent-duplicated-item" "Q20571325")
(fact claim "United States of America" "permanent-duplicated-item" "Q29045433")
(fact claim "United States of America" "permanent-duplicated-item" "Q29045456")
(fact claim "United States of America" "permanent-duplicated-item" "Q29045456")

(refer-to ["properties.tgn_id"])
(fact claim "United States of America" "tgn-id" "7012149")

(refer-to ["properties.stw_thesaurus_for_economics_id"])
(fact claim "United States of America" "stw-thesaurus-for-economics-id" "17829-1")

(refer-to ["properties.category_of_associated_people"])
(fact claim "United States of America" "category-of-associated-people" "Q3919762")

(refer-to ["properties.omni_topic_id"])
(fact claim "United States of America" "omni-topic-id" "9050eaf972828656c88d8704360f0b8e65bee3f0")

(refer-to ["properties.seal_image"])
(fact claim "United States of America" "seal-image" "Great Seal of the United States (obverse).svg")
(fact claim "United States of America" "seal-image" "Great Seal of the United States (reverse).svg")

(refer-to ["properties.official_language"])
(refer-to ["clazzes.english"])
(fact claim "United States of America" "official-language" "English")
(fact claim "United States of America" "official-language" "Q7976")

(refer-to ["properties.commons_maps_category"])
(fact claim "United States of America" "commons-maps-category" "Maps of the United States")

(refer-to ["properties.woeid"])
(fact claim "United States of America" "woeid" "23424977")

(refer-to ["properties.coordinate_of_easternmost_point"])
(fact claim "United States of America" "coordinate-of-easternmost-point" "lng -66.94995403 lat 44.81539337 alt ")

(refer-to ["properties.mains_voltage"])
(fact claim "United States of America" "mains-voltage" "quantity")

(refer-to ["properties.capital"])
(fact claim "United States of America" "capital" "Q61")
(fact claim "United States of America" "capital" "Q60")
(fact claim "United States of America" "capital" "Q1345")

(refer-to ["properties.sudoc_authorities"])
(fact claim "United States of America" "sudoc-authorities" "026376598")

(refer-to ["properties.hds_id"])
(fact claim "United States of America" "hds-id" "3380")

(refer-to ["properties.fips_10_4_countries_and_regions"])
(fact claim "United States of America" "fips-10-4-countries-and-regions" "US")

(refer-to ["properties.population"])
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")
(fact claim "United States of America" "population" "quantity")

(refer-to ["properties.bnf_id"])
(fact claim "United States of America" "bnf-id" "118636082")

(refer-to ["properties.top_level_internet_domain"])
(fact claim "United States of America" "top-level-internet-domain" "Q37861")
(fact claim "United States of America" "top-level-internet-domain" "Q31643")
(fact claim "United States of America" "top-level-internet-domain" "Q31635")
(fact claim "United States of America" "top-level-internet-domain" "Q216625")

(refer-to ["properties.public_holiday"])
(fact claim "United States of America" "public-holiday" "Q86591")
(fact claim "United States of America" "public-holiday" "Q196627")
(fact claim "United States of America" "public-holiday" "Q751738")
(fact claim "United States of America" "public-holiday" "Q744159")
(fact claim "United States of America" "public-holiday" "Q371781")
(fact claim "United States of America" "public-holiday" "Q848352")
(fact claim "United States of America" "public-holiday" "Q367523")
(fact claim "United States of America" "public-holiday" "Q755999")
(fact claim "United States of America" "public-holiday" "Q2913791")

(refer-to ["properties.member_of"])
(fact claim "United States of America" "member-of" "Q37470")
(fact claim "United States of America" "member-of" "Q1065")
(fact claim "United States of America" "member-of" "Q7184")
(fact claim "United States of America" "member-of" "Q37143")
(fact claim "United States of America" "member-of" "Q41550")
(fact claim "United States of America" "member-of" "Q7825")
(fact claim "United States of America" "member-of" "Q674182")
(fact claim "United States of America" "member-of" "Q842490")
(fact claim "United States of America" "member-of" "Q19771")
(fact claim "United States of America" "member-of" "Q170481")
(fact claim "United States of America" "member-of" "Q181574")
(fact claim "United States of America" "member-of" "Q81299")
(fact claim "United States of America" "member-of" "Q191384")
(fact claim "United States of America" "member-of" "Q827525")
(fact claim "United States of America" "member-of" "Q656801")
(fact claim "United States of America" "member-of" "Q1043527")
(fact claim "United States of America" "member-of" "Q899770")
(fact claim "United States of America" "member-of" "Q340195")
(fact claim "United States of America" "member-of" "Q7886981")
(fact claim "United States of America" "member-of" "Q188822")
(fact claim "United States of America" "member-of" "Q782942")
(fact claim "United States of America" "member-of" "Q295875")
(fact claim "United States of America" "member-of" "Q7164")
(fact claim "United States of America" "member-of" "Q7804")
(fact claim "United States of America" "member-of" "Q1928989")
(fact claim "United States of America" "member-of" "Q1072120")
(fact claim "United States of America" "member-of" "Q277252")
(fact claim "United States of America" "member-of" "Q8475")
(fact claim "United States of America" "member-of" "Q1480793")
(fact claim "United States of America" "member-of" "Q4033111")
(fact claim "United States of America" "member-of" "Q2863003")
(fact claim "United States of America" "member-of" "Q7768229")
(fact claim "United States of America" "member-of" "Q5150848")
(fact claim "United States of America" "member-of" "Q4426267")
(fact claim "United States of America" "member-of" "Q3866537")
(fact claim "United States of America" "member-of" "Q1579424")
(fact claim "United States of America" "member-of" "Q233611")
(fact claim "United States of America" "member-of" "Q826700")

(refer-to ["properties.catalog"])
(refer-to ["clazzes.wikipedia_list_of_1000_articles_each_wikipedia_should_have"])
(fact claim "United States of America" "catalog" "Wikipedia:List of 1000 articles each Wikipedia should have")

(refer-to ["properties.national_library_of_israel_id"])
(fact claim "United States of America" "national-library-of-israel-id" "000134032")

(refer-to ["properties.median_income"])
(fact claim "United States of America" "median-income" "quantity")

(refer-to ["properties.pactols_thesaurus_id"])
(fact claim "United States of America" "pactols-thesaurus-id" "pcrtiOMGsqH92p")

(refer-to ["properties.topics_main_template"])
(fact claim "United States of America" "topic's-main-template" "Q8171085")

(refer-to ["properties.freebase_id"])
(fact claim "United States of America" "freebase-id" "/m/09c7w0")

(refer-to ["properties.seal_description"])
(fact claim "United States of America" "seal-description" "Q171663")

(refer-to ["properties.contains_administrative_territorial_entity"])
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q173")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1612")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q99")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1261")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q779")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q812")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1428")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q782")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1221")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1204")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1415")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1546")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1558")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1603")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1588")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q724")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1391")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q771")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1166")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1527")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1494")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1581")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1212")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1553")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1227")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q759")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1408")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1522")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1384")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1454")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1207")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1397")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1649")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q824")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1400")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1387")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1456")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1211")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1509")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1439")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q829")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q16551")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1370")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1223")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1371")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1537")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1214")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q16641")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q61")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q16635")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q16644")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1183")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q11703")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q16645")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q797")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q816")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q547795")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1811372")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1393")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q669315")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1548588")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q660384")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q777763")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1518439")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1360064")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q1500063")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q6042084")
(fact claim "United States of America" "contains-administrative-territorial-entity" "Q146328")

(refer-to ["properties.fast_id"])
(fact claim "United States of America" "fast-id" "1204155")

(refer-to ["properties.iso_3166_1_numeric_code"])
(fact claim "United States of America" "iso-3166-1-numeric-code" "840")

(refer-to ["properties.coat_of_arms_image"])
(fact claim "United States of America" "coat-of-arms-image" "Greater coat of arms of the United States.svg")
(fact claim "United States of America" "coat-of-arms-image" "Coat of arms of the United States.svg")

(refer-to ["properties.coordinate_of_northernmost_point"])
(fact claim "United States of America" "coordinate-of-northernmost-point" "lng -156.48 lat 71.38 alt ")

(refer-to ["properties.coordinate_location"])
(fact claim "United States of America" "coordinate-location" "lng -100 lat 40 alt ")

(refer-to ["properties.electrical_plug_type"])
(fact claim "United States of America" "electrical-plug-type" "Q24288454")
(fact claim "United States of America" "electrical-plug-type" "Q24288456")

(refer-to ["properties.nla_australia_id"])
(fact claim "United States of America" "nla-australia-id" "35562417")

(refer-to ["properties.tripadvisor_id"])
(fact claim "United States of America" "tripadvisor-id" "Tourism-g191")

(refer-to ["properties.mobile_country_code"])
(fact claim "United States of America" "mobile-country-code" "310")
(fact claim "United States of America" "mobile-country-code" "311")
(fact claim "United States of America" "mobile-country-code" "312")
(fact claim "United States of America" "mobile-country-code" "313")
(fact claim "United States of America" "mobile-country-code" "316")

(refer-to ["properties.inception"])
(fact claim "United States of America" "inception" "+1776-07-04T00:00:00Z")

(refer-to ["properties.flag"])
(fact claim "United States of America" "flag" "Q42537")

(refer-to ["properties.highest_judicial_authority"])
(fact claim "United States of America" "highest-judicial-authority" "Q11201")

(refer-to ["properties.gran_enciclopèdia_catalana_id"])
(fact claim "United States of America" "gran-enciclopèdia-catalana-id" "0025184")

(refer-to ["properties.mesh_id"])
(fact claim "United States of America" "mesh-id" "D014481")

(refer-to ["properties.category_for_films_shot_at_this_location"])
(fact claim "United States of America" "category-for-films-shot-at-this-location" "Q6839466")

(refer-to ["properties.isni"])
(fact claim "United States of America" "isni" "0000 0001 2331 5230")

(refer-to ["properties.driving_side"])
(fact claim "United States of America" "driving-side" "Q14565199")

(refer-to ["properties.official_website"])
(fact claim "United States of America" "official-website" "https://www.usa.gov/")

(refer-to ["properties.guardian_topic_id"])
(fact claim "United States of America" "guardian-topic-id" "us-news")

(refer-to ["properties.ndl_auth_id"])
(fact claim "United States of America" "ndl-auth-id" "00871907")

(refer-to ["properties.insee_countries_and_foreign_territories_code"])
(fact claim "United States of America" "insee-countries-and-foreign-territories-code" "99404")

(refer-to ["properties.gnd_id"])
(fact claim "United States of America" "gnd-id" "4078704-7")

(refer-to ["properties.online_books_page_author_id"])
(fact claim "United States of America" "online-books-page-author-id" "United States")

(refer-to ["properties.described_by_source"])
(fact claim "United States of America" "described-by-source" "Q4173137")
(fact claim "United States of America" "described-by-source" "Q19180675")
(fact claim "United States of America" "described-by-source" "Q602358")

(refer-to ["properties.nominal_gdp_per_capita"])
(fact claim "United States of America" "nominal-gdp-per-capita" "quantity")

(refer-to ["properties.open_library_id"])
(fact claim "United States of America" "open-library-id" "OL18485A")

(refer-to ["properties.continent"])
(fact claim "United States of America" "continent" "Q49")
(fact claim "United States of America" "continent" "Q538")

(refer-to ["properties.le_monde_diplomatique_subject_id"])
(fact claim "United States of America" "le-monde-diplomatique-subject-id" "pays/etatsunis")

(refer-to ["properties.iso_3166_1_alpha_2_code"])
(fact claim "United States of America" "iso-3166-1-alpha-2-code" "US")

(refer-to ["properties.instance_of"])
(fact claim "United States of America" "instance-of" "Q3624078")
(fact claim "United States of America" "instance-of" "Q6256")
(fact claim "United States of America" "instance-of" "Q1520223")
(fact claim "United States of America" "instance-of" "Q160016")
(fact claim "United States of America" "instance-of" "Q6688521")
(fact claim "United States of America" "instance-of" "Q5255892")
(fact claim "United States of America" "instance-of" "Q43702")

(refer-to ["properties.legislative_body"])
(fact claim "United States of America" "legislative-body" "Q11268")

(refer-to ["properties.part_of"])
(fact claim "United States of America" "part-of" "Q49")

(refer-to ["properties.demonym"])
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")
(fact claim "United States of America" "demonym" "monolingualtext")

(refer-to ["properties.dmoz_id"])
(fact claim "United States of America" "dmoz-id" "Regional/North_America/United_States/")
(fact claim "United States of America" "dmoz-id" "World/Español/Regional/América/Estados_Unidos/")
(fact claim "United States of America" "dmoz-id" "World/Bosanski/Regionalno/Sjeverna_Amerika/Sjedinjene_Američke_Države/")
(fact claim "United States of America" "dmoz-id" "World/Català/Regional/Amèrica/Estats_Units/")
(fact claim "United States of America" "dmoz-id" "World/Česky/Státy_a_regiony/Severní_Amerika/Spojené_státy_americké/")
(fact claim "United States of America" "dmoz-id" "World/Cymraeg/Rhanbarthol/Unol_Daleithiau_America/")
(fact claim "United States of America" "dmoz-id" "World/Dansk/Regional/Nordamerika/USA/")
(fact claim "United States of America" "dmoz-id" "World/Deutsch/Regional/Amerika/Vereinigte_Staaten/")
(fact claim "United States of America" "dmoz-id" "World/Eesti/Regioonid/Põhja_Ameerika/Ameerika_Ühendriigid/")
(fact claim "United States of America" "dmoz-id" "World/Esperanto/Regionoj/Ameriko/Usono/")
(fact claim "United States of America" "dmoz-id" "World/Français/Régional/Amérique/Etats-Unis/")
(fact claim "United States of America" "dmoz-id" "World/Gaeilge/Réigiúnach/Stáit_Aontaithe_Mheirceá/")
(fact claim "United States of America" "dmoz-id" "World/Italiano/Regionale/America_del_Nord/Stati_Uniti/")
(fact claim "United States of America" "dmoz-id" "World/Latviski/Valstis_un_reģioni/Ziemeļamerika/Amerikas_Savienotās_Valstis/")
(fact claim "United States of America" "dmoz-id" "World/Lietuvių/Regionai/Šiaurės_Amerika/Jungtinės_Amerikos_Valstijos/")
(fact claim "United States of America" "dmoz-id" "World/Nederlands/Regionaal/Noord-Amerika/Verenigde_Staten/")
(fact claim "United States of America" "dmoz-id" "World/Polski/Regionalne/Ameryka_Północna/Stany_Zjednoczone/")
(fact claim "United States of America" "dmoz-id" "World/Português/Regional/América_do_Norte/Estados_Unidos/")
(fact claim "United States of America" "dmoz-id" "World/Română/Regional/America_de_Nord/Statele_Unite_ale_Americii/")
(fact claim "United States of America" "dmoz-id" "World/Slovensky/Regionálne/Severná_Amerika/Spojené_štáty_americké/")
(fact claim "United States of America" "dmoz-id" "World/Svenska/Regionalt/Nordamerika/USA/")
(fact claim "United States of America" "dmoz-id" "World/Tiếng_Việt/Địa_phương/Bắc_Mỹ/Hoa_Kỳ/")
(fact claim "United States of America" "dmoz-id" "World/Türkçe/Bölgesel/Amerika/Amerika_Birleşik_Devletleri/")
(fact claim "United States of America" "dmoz-id" "World/Greek/Κατά_Περιοχή/Βόρεια_Αμερική/Ηνωμένες_Πολιτείες_Αμερικής/")
(fact claim "United States of America" "dmoz-id" "World/Bulgarian/Региони/Северна_Америка/Съединени_Американски_Щати/")
(fact claim "United States of America" "dmoz-id" "World/Russian/Страны_и_регионы/Северная_Америка/Соединенные_Штаты_Америки/")
(fact claim "United States of America" "dmoz-id" "World/Ukrainian/Країни_та_реґіони/Північна_Америка/Сполучені_Штати_Америки/")
(fact claim "United States of America" "dmoz-id" "World/Kazakh/Региондық/Солтүстік_Америка/Америка_Құрама_Штаттары/")
(fact claim "United States of America" "dmoz-id" "World/Hebrew/אזורי/צפון_אמריקה/ארצות_הברית/")
(fact claim "United States of America" "dmoz-id" "World/Arabic/إقليمـي/أمريكا/الولايات_المتحدة/")
(fact claim "United States of America" "dmoz-id" "World/Hindi/क्षेत्रीय/उत्तर_अम्रीका/संयुक्त_राज्य/")
(fact claim "United States of America" "dmoz-id" "World/Japanese/地域/北アメリカ/アメリカ合衆国/")
(fact claim "United States of America" "dmoz-id" "World/Korean/지역,국가/북아메리카/미국/")

(refer-to ["properties.office_held_by_head_of_state"])
(fact claim "United States of America" "office-held-by-head-of-state" "Q11696")

(refer-to ["properties.office_held_by_head_of_government"])
(fact claim "United States of America" "office-held-by-head-of-government" "Q11696")

(refer-to ["properties.bne_id"])
(fact claim "United States of America" "bne-id" "XX4575366")

(refer-to ["properties.age_of_majority"])
(fact claim "United States of America" "age-of-majority" "")

(refer-to ["properties.country_calling_code"])
(fact claim "United States of America" "country-calling-code" "+1")

(refer-to ["properties.replaces"])
(fact claim "United States of America" "replaces" "Q179997")

(refer-to ["properties.selibr"])
(fact claim "United States of America" "selibr" "146174")

(refer-to ["properties.ne_se_id"])
(fact claim "United States of America" "ne_se-id" "united-states")

(refer-to ["properties.ipa_transcription"])
(fact claim "United States of America" "ipa-transcription" "ʉːɛˈsɑː")

(refer-to ["properties.image"])
(fact claim "United States of America" "image" "Flag of the United States.svg")

(refer-to ["properties.nyt_topic_id"])
(fact claim "United States of America" "nyt-topic-id" "destination/united-states")

(refer-to ["properties.category_for_people_who_died_here"])
(fact claim "United States of America" "category-for-people-who-died-here" "Q6334989")

(refer-to ["properties.ted_topic_id"])
(fact claim "United States of America" "ted-topic-id" "United+States")

(refer-to ["properties.located_in_time_zone"])
(fact claim "United States of America" "located-in-time-zone" "Q5385")
(fact claim "United States of America" "located-in-time-zone" "Q2212")
(fact claim "United States of America" "located-in-time-zone" "Q2204")
(fact claim "United States of America" "located-in-time-zone" "Q2183")
(fact claim "United States of America" "located-in-time-zone" "Q2146")
(fact claim "United States of America" "located-in-time-zone" "Q2154")
(fact claim "United States of America" "located-in-time-zone" "Q5762")
(fact claim "United States of America" "located-in-time-zone" "Q7056")
(fact claim "United States of America" "located-in-time-zone" "Q7105")
(fact claim "United States of America" "located-in-time-zone" "Q5390")
(fact claim "United States of America" "located-in-time-zone" "Q4816926")
(fact claim "United States of America" "located-in-time-zone" "Q2085376")
(fact claim "United States of America" "located-in-time-zone" "Q2086913")
(fact claim "United States of America" "located-in-time-zone" "Q3238805")
(fact claim "United States of America" "located-in-time-zone" "Q3134980")
(fact claim "United States of America" "located-in-time-zone" "Q3446496")

(refer-to ["properties.topics_main_wikimedia_portal"])
(fact claim "United States of America" "topic's-main-wikimedia-portal" "Q5365167")

(refer-to ["properties.highest_point"])
(fact claim "United States of America" "highest-point" "Q130018")

(refer-to ["properties.executive_body"])
(fact claim "United States of America" "executive-body" "Q48525")

(refer-to ["properties.ptbnp_id"])
(fact claim "United States of America" "ptbnp-id" "102017")

(refer-to ["properties.native_label"])
(fact claim "United States of America" "native-label" "monolingualtext")

(refer-to ["properties.anthem"])
(fact claim "United States of America" "anthem" "Q44696")

(refer-to ["properties.external_data_available_at"])
(fact claim "United States of America" "external-data-available-at" "https://www.data.gov/")

(refer-to ["properties.nominal_gdp"])
(fact claim "United States of America" "nominal-gdp" "quantity")

(refer-to ["properties.category_for_people_born_here"])
(fact claim "United States of America" "category-for-people-born-here" "Q7463286")

(refer-to ["properties.basic_form_of_government"])
(fact claim "United States of America" "basic-form-of-government" "Q49892")
(fact claim "United States of America" "basic-form-of-government" "Q512187")

(refer-to ["properties.total_reserves"])
(fact claim "United States of America" "total-reserves" "quantity")

(refer-to ["properties.motto_text"])
(fact claim "United States of America" "motto-text" "monolingualtext")
(fact claim "United States of America" "motto-text" "monolingualtext")
(fact claim "United States of America" "motto-text" "monolingualtext")
(fact claim "United States of America" "motto-text" "monolingualtext")

(refer-to ["properties.area"])
(fact claim "United States of America" "area" "quantity")

(refer-to ["properties.flag_image"])
(fact claim "United States of America" "flag-image" "Flag of the United States.svg")
(fact claim "United States of America" "flag-image" "US flag 49 stars.svg")
(fact claim "United States of America" "flag-image" "Flag of the United States (1912-1959).svg")
(fact claim "United States of America" "flag-image" "46 Star US Flag.svg")
(fact claim "United States of America" "flag-image" "45 Star US Flag.svg")
(fact claim "United States of America" "flag-image" "44 Star US Flag.svg")
(fact claim "United States of America" "flag-image" "Flag of the United States (1890-1891).svg")
(fact claim "United States of America" "flag-image" "US flag 38 stars.svg")
(fact claim "United States of America" "flag-image" "US flag 37 stars.svg")
(fact claim "United States of America" "flag-image" "Flag of the United States (1865-1867).svg")
(fact claim "United States of America" "flag-image" "Flag of the United States (1863-1865).svg")
(fact claim "United States of America" "flag-image" "Flag of the United States (1861-1863).svg")
(fact claim "United States of America" "flag-image" "Flag of the United States (1859-1861).svg")

(refer-to ["properties.unemployment_rate"])
(fact claim "United States of America" "unemployment-rate" "quantity")

(refer-to ["properties.library_of_congress_authority_id"])
(fact claim "United States of America" "library-of-congress-authority-id" "n78095330")

(refer-to ["properties.human_development_index"])
(fact claim "United States of America" "human-development-index" "quantity")
(fact claim "United States of America" "human-development-index" "quantity")
(fact claim "United States of America" "human-development-index" "quantity")
(fact claim "United States of America" "human-development-index" "quantity")
(fact claim "United States of America" "human-development-index" "quantity")
(fact claim "United States of America" "human-development-index" "quantity")
(fact claim "United States of America" "human-development-index" "quantity")
(fact claim "United States of America" "human-development-index" "quantity")
(fact claim "United States of America" "human-development-index" "quantity")
(fact claim "United States of America" "human-development-index" "quantity")
(fact claim "United States of America" "human-development-index" "quantity")
(fact claim "United States of America" "human-development-index" "quantity")

(refer-to ["properties.quora_topic_id"])
(fact claim "United States of America" "quora-topic-id" "The-United-States-of-America")

(refer-to ["properties.openmlol_author_id"])
(fact claim "United States of America" "openmlol-author-id" "36199")

(refer-to ["properties.dharma_drum_buddhist_college_place_id"])
(fact claim "United States of America" "dharma-drum-buddhist-college-place-id" "PL000000056125")

(refer-to ["properties.named_after"])
(fact claim "United States of America" "named-after" "Q47674")
