(ns clazzes.university_teacher
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Term "university teacher")

(name-as-in "university teacher" "大學教員" "zh-hk")
(name-as-in "university teacher" "professor catedrático" "pt")
(name-as-in "university teacher" "university teacher" "en")
(name-as-in "university teacher" "professeur d'université" "fr")
(name-as-in "university teacher" "大學教員" "zh-tw")
(name-as-in "university teacher" "Hochschullehrer" "de")
(name-as-in "university teacher" "преподаватель университета" "ru")
(name-as-in "university teacher" "profesor universitario" "es")
(name-as-in "university teacher" "大学教授" "ja")
(name-as-in "university teacher" "大学教员" "zh-cn")
(name-as-in "university teacher" "大学教员" "zh-sg")

(descr-as-in "university teacher" "" "zh-hk")
(descr-as-in "university teacher" "pessoa que leciona em uma universidade" "pt")
(descr-as-in "university teacher" "person teaching at a university" "en")
(descr-as-in "university teacher" "enseignant en poste dans une université. Voir Q121594 pour le titre de Professeur et Q28004591 pour le grade de professeur des universités en France" "fr")
(descr-as-in "university teacher" "" "zh-tw")
(descr-as-in "university teacher" "Person, die an einer Hochschule lehrt und forscht" "de")
(descr-as-in "university teacher" "часть преподавательского состава университета" "ru")
(descr-as-in "university teacher" "persona que enseña en la universidad" "es")
(descr-as-in "university teacher" "大学で教育を行う者" "ja")
(descr-as-in "university teacher" "" "zh-cn")
(descr-as-in "university teacher" "" "zh-sg")


(refer-to ["properties.subclass_of"])
(fact claim "university teacher" "subclass-of" "Q16631371")
(fact claim "university teacher" "subclass-of" "Q37226")
(fact claim "university teacher" "subclass-of" "Q41835716")

(refer-to ["properties.isco_occupation_code"])
(fact claim "university teacher" "isco-occupation-code" "2310")

(refer-to ["properties.male_form_of_label"])
(fact claim "university teacher" "male-form-of-label" "monolingualtext")
(fact claim "university teacher" "male-form-of-label" "monolingualtext")
(fact claim "university teacher" "male-form-of-label" "monolingualtext")

(refer-to ["properties.topics_main_category"])
(fact claim "university teacher" "topic's-main-category" "Q7997556")

(refer-to ["properties.field_of_this_occupation"])
(fact claim "university teacher" "field-of-this-occupation" "Q352842")

(refer-to ["properties.instance_of"])
(fact claim "university teacher" "instance-of" "Q28640")

(refer-to ["properties.different_from"])
(fact claim "university teacher" "different-from" "Q28004591")
(fact claim "university teacher" "different-from" "Q121594")
(fact claim "university teacher" "different-from" "Q37226")
(fact claim "university teacher" "different-from" "Q5669847")
(fact claim "university teacher" "different-from" "Q1706722")
(fact claim "university teacher" "different-from" "Q3054728")
(fact claim "university teacher" "different-from" "Q1914832")

(refer-to ["properties.female_form_of_label"])
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")
(fact claim "university teacher" "female-form-of-label" "monolingualtext")

(refer-to ["properties.quora_topic_id"])
(fact claim "university teacher" "quora-topic-id" "University-Professor")
