(ns clazzes.zurich
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Term "Zurich")

(name-as-in "Zurich" "蘇黎世" "zh-hk")
(name-as-in "Zurich" "Zurique" "pt")
(name-as-in "Zurich" "Zurich" "en")
(name-as-in "Zurich" "Zurich" "fr")
(name-as-in "Zurich" "蘇黎世" "zh-tw")
(name-as-in "Zurich" "Zürich" "de")
(name-as-in "Zurich" "Цюрих" "ru")
(name-as-in "Zurich" "Zúrich" "es")
(name-as-in "Zurich" "チューリッヒ" "ja")
(name-as-in "Zurich" "苏黎世" "zh-cn")
(name-as-in "Zurich" "苏黎世" "zh-sg")

(descr-as-in "Zurich" "瑞士蘇黎世州首府" "zh-hk")
(descr-as-in "Zurich" "cidade no cantão de Zurique, Suíça" "pt")
(descr-as-in "Zurich" "capital of the canton of Zürich, Switzerland" "en")
(descr-as-in "Zurich" "ville de la Suisse et chef-lieu du canton de Zurich" "fr")
(descr-as-in "Zurich" "瑞士蘇黎世州首府" "zh-tw")
(descr-as-in "Zurich" "Hauptstadt des Kantons Zürich, Schweiz" "de")
(descr-as-in "Zurich" "город в Швейцарии" "ru")
(descr-as-in "Zurich" "ciudad en el cantón de Zúrich, Suiza" "es")
(descr-as-in "Zurich" "スイスの都市" "ja")
(descr-as-in "Zurich" "瑞士苏黎世州首府" "zh-cn")
(descr-as-in "Zurich" "瑞士苏黎世州首府" "zh-sg")


(refer-to ["properties.global_anabaptist_mennonite_encyclopedia_online_id"])
(fact claim "Zurich" "global-anabaptist-mennonite-encyclopedia-online-id" "Zürich (Switzerland)")

(refer-to ["properties.country"])
(refer-to ["clazzes.switzerland"])
(fact claim "Zurich" "country" "Switzerland")

(refer-to ["properties.head_of_government"])
(fact claim "Zurich" "head-of-government" "Q123363")
(fact claim "Zurich" "head-of-government" "Q115886")
(fact claim "Zurich" "head-of-government" "Q125273")
(fact claim "Zurich" "head-of-government" "Q2427995")
(fact claim "Zurich" "head-of-government" "Q120794")
(fact claim "Zurich" "head-of-government" "Q1336378")
(fact claim "Zurich" "head-of-government" "Q1493750")
(fact claim "Zurich" "head-of-government" "Q117727")
(fact claim "Zurich" "head-of-government" "Q946822")
(fact claim "Zurich" "head-of-government" "Q120767")
(fact claim "Zurich" "head-of-government" "Q2099681")
(fact claim "Zurich" "head-of-government" "Q2048091")
(fact claim "Zurich" "head-of-government" "Q125319")
(fact claim "Zurich" "head-of-government" "Q2163606")
(fact claim "Zurich" "head-of-government" "Q2178711")
(fact claim "Zurich" "head-of-government" "Q1909507")
(fact claim "Zurich" "head-of-government" "Q2479288")
(fact claim "Zurich" "head-of-government" "Q1336429")
(fact claim "Zurich" "head-of-government" "Q2021232")
(fact claim "Zurich" "head-of-government" "Q115561")
(fact claim "Zurich" "head-of-government" "Q13635789")
(fact claim "Zurich" "head-of-government" "Q13635791")
(fact claim "Zurich" "head-of-government" "Q13635797")
(fact claim "Zurich" "head-of-government" "Q13635921")
(fact claim "Zurich" "head-of-government" "Q13636324")
(fact claim "Zurich" "head-of-government" "Q13636361")
(fact claim "Zurich" "head-of-government" "Q13636787")
(fact claim "Zurich" "head-of-government" "Q13636826")
(fact claim "Zurich" "head-of-government" "Q13636847")
(fact claim "Zurich" "head-of-government" "Q13636899")
(fact claim "Zurich" "head-of-government" "Q13636939")
(fact claim "Zurich" "head-of-government" "Q13637020")
(fact claim "Zurich" "head-of-government" "Q117092")
(fact claim "Zurich" "head-of-government" "Q13635763")
(fact claim "Zurich" "head-of-government" "Q13635769")
(fact claim "Zurich" "head-of-government" "Q13635779")
(fact claim "Zurich" "head-of-government" "Q13635977")
(fact claim "Zurich" "head-of-government" "Q13830382")
(fact claim "Zurich" "head-of-government" "Q13832030")
(fact claim "Zurich" "head-of-government" "Q13832336")
(fact claim "Zurich" "head-of-government" "Q1581533")
(fact claim "Zurich" "head-of-government" "Q124248")
(fact claim "Zurich" "head-of-government" "Q13857403")
(fact claim "Zurich" "head-of-government" "Q13858599")
(fact claim "Zurich" "head-of-government" "Q13858784")
(fact claim "Zurich" "head-of-government" "Q13858987")
(fact claim "Zurich" "head-of-government" "Q13859084")
(fact claim "Zurich" "head-of-government" "Q13882666")
(fact claim "Zurich" "head-of-government" "Q13883308")
(fact claim "Zurich" "head-of-government" "Q13883269")
(fact claim "Zurich" "head-of-government" "Q13882842")
(fact claim "Zurich" "head-of-government" "Q2214992")
(fact claim "Zurich" "head-of-government" "Q13883377")
(fact claim "Zurich" "head-of-government" "Q13882754")
(fact claim "Zurich" "head-of-government" "Q13882709")
(fact claim "Zurich" "head-of-government" "Q13882638")
(fact claim "Zurich" "head-of-government" "Q13882564")
(fact claim "Zurich" "head-of-government" "Q13882493")
(fact claim "Zurich" "head-of-government" "Q13882447")
(fact claim "Zurich" "head-of-government" "Q13859853")
(fact claim "Zurich" "head-of-government" "Q13859511")
(fact claim "Zurich" "head-of-government" "Q13857562")
(fact claim "Zurich" "head-of-government" "Q1694384")
(fact claim "Zurich" "head-of-government" "Q124408")
(fact claim "Zurich" "head-of-government" "Q13884316")
(fact claim "Zurich" "head-of-government" "Q13635950")
(fact claim "Zurich" "head-of-government" "Q1389974")
(fact claim "Zurich" "head-of-government" "Q13932987")
(fact claim "Zurich" "head-of-government" "Q14030389")
(fact claim "Zurich" "head-of-government" "Q14030627")
(fact claim "Zurich" "head-of-government" "Q14030773")
(fact claim "Zurich" "head-of-government" "Q116940")
(fact claim "Zurich" "head-of-government" "Q14032587")
(fact claim "Zurich" "head-of-government" "Q14032968")
(fact claim "Zurich" "head-of-government" "Q14034146")
(fact claim "Zurich" "head-of-government" "Q14034383")
(fact claim "Zurich" "head-of-government" "Q14034723")
(fact claim "Zurich" "head-of-government" "Q14240888")
(fact claim "Zurich" "head-of-government" "Q14241051")
(fact claim "Zurich" "head-of-government" "Q14241364")
(fact claim "Zurich" "head-of-government" "Q14242497")
(fact claim "Zurich" "head-of-government" "Q14242691")
(fact claim "Zurich" "head-of-government" "Q125071")
(fact claim "Zurich" "head-of-government" "Q14243179")
(fact claim "Zurich" "head-of-government" "Q14243466")
(fact claim "Zurich" "head-of-government" "Q14244130")
(fact claim "Zurich" "head-of-government" "Q2048091")
(fact claim "Zurich" "head-of-government" "Q14244500")
(fact claim "Zurich" "head-of-government" "Q14244684")
(fact claim "Zurich" "head-of-government" "Q14244863")
(fact claim "Zurich" "head-of-government" "Q14245221")
(fact claim "Zurich" "head-of-government" "Q13637052")
(fact claim "Zurich" "head-of-government" "Q13637052")
(fact claim "Zurich" "head-of-government" "Q13637052")
(fact claim "Zurich" "head-of-government" "Q13637111")
(fact claim "Zurich" "head-of-government" "Q13637111")
(fact claim "Zurich" "head-of-government" "Q13637111")
(fact claim "Zurich" "head-of-government" "Q124390")
(fact claim "Zurich" "head-of-government" "Q124390")

(refer-to ["properties.locator_map_image"])
(fact claim "Zurich" "locator-map-image" "Karte Gemeinde Zürich.png")
(fact claim "Zurich" "locator-map-image" "Karte Gemeinde Zürich 2007.png")

(refer-to ["properties.commons_gallery"])
(fact claim "Zurich" "commons-gallery" "Zürich")

(refer-to ["properties.award_received"])
(fact claim "Zurich" "award-received" "Q20828891")

(refer-to ["properties.catholic_encyclopedia_id"])
(fact claim "Zurich" "catholic-encyclopedia-id" "15770b")

(refer-to ["properties.history_of_topic"])
(fact claim "Zurich" "history-of-topic" "Q684180")

(refer-to ["properties.commons_category"])
(fact claim "Zurich" "commons-category" "Zürich")

(refer-to ["properties.page_banner"])
(fact claim "Zurich" "page-banner" "Zurich banner.jpg")

(refer-to ["properties.encyclopædia_britannica_online_id"])
(fact claim "Zurich" "encyclopædia-britannica-online-id" "place/Zurich")

(refer-to ["properties.shares_border_with"])
(fact claim "Zurich" "shares-border-with" "Q68210")
(fact claim "Zurich" "shares-border-with" "Q64082")
(fact claim "Zurich" "shares-border-with" "Q64857")
(fact claim "Zurich" "shares-border-with" "Q64224")
(fact claim "Zurich" "shares-border-with" "Q64205")
(fact claim "Zurich" "shares-border-with" "Q69148")
(fact claim "Zurich" "shares-border-with" "Q66062")
(fact claim "Zurich" "shares-border-with" "Q69109")
(fact claim "Zurich" "shares-border-with" "Q69374")
(fact claim "Zurich" "shares-border-with" "Q218691")
(fact claim "Zurich" "shares-border-with" "Q64869")
(fact claim "Zurich" "shares-border-with" "Q66633")
(fact claim "Zurich" "shares-border-with" "Q69963")
(fact claim "Zurich" "shares-border-with" "Q66678")
(fact claim "Zurich" "shares-border-with" "Q67894")

(refer-to ["properties.dewey_decimal_classification"])
(fact claim "Zurich" "dewey-decimal-classification" "2--4945726")

(refer-to ["properties.subreddit"])
(fact claim "Zurich" "subreddit" "zurich")

(refer-to ["properties.viaf_id"])
(fact claim "Zurich" "viaf-id" "185144783004419863241")

(refer-to ["properties.emlo_location_id"])
(fact claim "Zurich" "emlo-location-id" "2df24ec5-47e7-449b-8e08-cbc6258c6cb0")

(refer-to ["properties.list_of_monuments"])
(fact claim "Zurich" "list-of-monuments" "Q15827868")

(refer-to ["properties.musicbrainz_area_id"])
(fact claim "Zurich" "musicbrainz-area-id" "e2bd38a1-c5ad-4dd4-b9a4-0632ff3be7ae")

(refer-to ["properties.located_in_the_administrative_territorial_entity"])
(fact claim "Zurich" "located-in-the-administrative-territorial-entity" "Q11943")

(refer-to ["properties.us_national_archives_identifier"])
(fact claim "Zurich" "us-national-archives-identifier" "10045180")

(refer-to ["properties.swiss_municipality_code"])
(fact claim "Zurich" "swiss-municipality-code" "0261")

(refer-to ["properties.babelnet_id"])
(fact claim "Zurich" "babelnet-id" "00082104n")

(refer-to ["properties.topics_main_category"])
(fact claim "Zurich" "topic's-main-category" "Q7960691")

(refer-to ["properties.postal_code"])
(fact claim "Zurich" "postal-code" "8000")
(fact claim "Zurich" "postal-code" "8001")
(fact claim "Zurich" "postal-code" "8002")
(fact claim "Zurich" "postal-code" "8003")
(fact claim "Zurich" "postal-code" "8004")
(fact claim "Zurich" "postal-code" "8005")
(fact claim "Zurich" "postal-code" "8006")
(fact claim "Zurich" "postal-code" "8008")
(fact claim "Zurich" "postal-code" "8032")
(fact claim "Zurich" "postal-code" "8037")
(fact claim "Zurich" "postal-code" "8038")
(fact claim "Zurich" "postal-code" "8041")
(fact claim "Zurich" "postal-code" "8044")
(fact claim "Zurich" "postal-code" "8045")
(fact claim "Zurich" "postal-code" "8046")
(fact claim "Zurich" "postal-code" "8049")
(fact claim "Zurich" "postal-code" "8050")
(fact claim "Zurich" "postal-code" "8051")
(fact claim "Zurich" "postal-code" "8052")
(fact claim "Zurich" "postal-code" "8053")
(fact claim "Zurich" "postal-code" "8055")
(fact claim "Zurich" "postal-code" "8057")
(fact claim "Zurich" "postal-code" "8063")
(fact claim "Zurich" "postal-code" "8064")

(refer-to ["properties.geonames_id"])
(fact claim "Zurich" "geonames-id" "2657896")

(refer-to ["properties.yso_id"])
(fact claim "Zurich" "yso-id" "113076")

(refer-to ["properties.openstreetmap_relation_identifier"])
(fact claim "Zurich" "openstreetmap-relation-identifier" "1682248")

(refer-to ["properties.permanent_duplicated_item"])
(fact claim "Zurich" "permanent-duplicated-item" "Q20516593")

(refer-to ["properties.category_of_associated_people"])
(fact claim "Zurich" "category-of-associated-people" "Q6013675")

(refer-to ["properties.official_language"])
(refer-to ["clazzes.german"])
(fact claim "Zurich" "official-language" "German")

(refer-to ["properties.woeid"])
(fact claim "Zurich" "woeid" "784794")

(refer-to ["properties.sister_city"])
(fact claim "Zurich" "sister-city" "Q182852")
(fact claim "Zurich" "sister-city" "Q62")
(fact claim "Zurich" "sister-city" "Q157144")

(refer-to ["properties.facebook_places_id"])
(fact claim "Zurich" "facebook-places-id" "102160693158562")

(refer-to ["properties.sudoc_authorities"])
(fact claim "Zurich" "sudoc-authorities" "030205484")

(refer-to ["properties.elevation_above_sea_level"])
(fact claim "Zurich" "elevation-above-sea-level" "quantity")

(refer-to ["properties.hds_id"])
(fact claim "Zurich" "hds-id" "171")

(refer-to ["properties.population"])
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")
(fact claim "Zurich" "population" "quantity")

(refer-to ["properties.bnf_id"])
(fact claim "Zurich" "bnf-id" "12167046v")

(refer-to ["properties.national_library_of_israel_id"])
(fact claim "Zurich" "national-library-of-israel-id" "000978219")

(refer-to ["properties.freebase_id"])
(fact claim "Zurich" "freebase-id" "/m/08966")

(refer-to ["properties.contains_administrative_territorial_entity"])
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q445559")
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q456153")
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q675017")
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q677133")
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q460885")
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q456170")
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q456149")
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q677710")
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q456159")
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q456175")
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q870098")
(fact claim "Zurich" "contains-administrative-territorial-entity" "Q657525")

(refer-to ["properties.coat_of_arms_image"])
(fact claim "Zurich" "coat-of-arms-image" "Zurich-coat of arms.svg")

(refer-to ["properties.coordinate_location"])
(fact claim "Zurich" "coordinate-location" "lng 8.54 lat 47.378611111111 alt ")

(refer-to ["properties.capital_of"])
(fact claim "Zurich" "capital-of" "Q11943")

(refer-to ["properties.gran_enciclopèdia_catalana_id"])
(fact claim "Zurich" "gran-enciclopèdia-catalana-id" "0073462")

(refer-to ["properties.category_for_films_shot_at_this_location"])
(fact claim "Zurich" "category-for-films-shot-at-this-location" "Q10220651")

(refer-to ["properties.isni"])
(fact claim "Zurich" "isni" "0000 0001 2293 7775")

(refer-to ["properties.official_website"])
(fact claim "Zurich" "official-website" "http://www.stadt-zuerich.ch/")

(refer-to ["properties.gnd_id"])
(fact claim "Zurich" "gnd-id" "4068038-1")

(refer-to ["properties.continent"])
(fact claim "Zurich" "continent" "Q46")

(refer-to ["properties.instance_of"])
(fact claim "Zurich" "instance-of" "Q515")
(fact claim "Zurich" "instance-of" "Q5119")
(fact claim "Zurich" "instance-of" "Q14770218")
(fact claim "Zurich" "instance-of" "Q1187811")
(fact claim "Zurich" "instance-of" "Q70208")
(fact claim "Zurich" "instance-of" "Q1549591")

(refer-to ["properties.legislative_body"])
(fact claim "Zurich" "legislative-body" "Q21516057")

(refer-to ["properties.dmoz_id"])
(fact claim "Zurich" "dmoz-id" "Regional/Europe/Switzerland/Cantons/Zurich/Localities/Zurich/")

(refer-to ["properties.ne_se_id"])
(fact claim "Zurich" "ne_se-id" "zurich")

(refer-to ["properties.local_dialing_code"])
(fact claim "Zurich" "local-dialing-code" "043")
(fact claim "Zurich" "local-dialing-code" "044")

(refer-to ["properties.image"])
(fact claim "Zurich" "image" "Zuerich Fraumuenster St Peter.jpg")

(refer-to ["properties.category_of_people_buried_here"])
(fact claim "Zurich" "category-of-people-buried-here" "Q7978696")

(refer-to ["properties.located_in_or_next_to_body_of_water"])
(fact claim "Zurich" "located-in-or-next-to-body-of-water" "Q14407")
(fact claim "Zurich" "located-in-or-next-to-body-of-water" "Q14338")
(fact claim "Zurich" "located-in-or-next-to-body-of-water" "Q660909")
(fact claim "Zurich" "located-in-or-next-to-body-of-water" "Q672290")

(refer-to ["properties.category_for_people_who_died_here"])
(fact claim "Zurich" "category-for-people-who-died-here" "Q9220446")

(refer-to ["properties.located_in_time_zone"])
(fact claim "Zurich" "located-in-time-zone" "Q6655")
(fact claim "Zurich" "located-in-time-zone" "Q6723")

(refer-to ["properties.topics_main_wikimedia_portal"])
(fact claim "Zurich" "topic's-main-wikimedia-portal" "Q11384514")

(refer-to ["properties.official_name"])
(fact claim "Zurich" "official-name" "monolingualtext")

(refer-to ["properties.external_data_available_at"])
(fact claim "Zurich" "external-data-available-at" "https://ld.geo.admin.ch/boundaries/municipality/261")

(refer-to ["properties.category_for_people_born_here"])
(fact claim "Zurich" "category-for-people-born-here" "Q11221116")

(refer-to ["properties.area"])
(fact claim "Zurich" "area" "quantity")

(refer-to ["properties.flag_image"])
(fact claim "Zurich" "flag-image" "Flag of Canton of Zürich.svg")

(refer-to ["properties.library_of_congress_authority_id"])
(fact claim "Zurich" "library-of-congress-authority-id" "n80013637")

(refer-to ["properties.quora_topic_id"])
(fact claim "Zurich" "quora-topic-id" "Zürich")
