(ns properties.aat_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "aat-id")

(name-as-in "aat-id" "" "zh-hk")
(name-as-in "aat-id" "identificador Art & Architecture Thesaurus" "pt")
(name-as-in "aat-id" "AAT ID" "en")
(name-as-in "aat-id" "identifiant Art & Architecture Thesaurus" "fr")
(name-as-in "aat-id" "" "zh-tw")
(name-as-in "aat-id" "Art-and-Architecture-Thesaurus-Kennung" "de")
(name-as-in "aat-id" "код ТИА" "ru")
(name-as-in "aat-id" "identificador Tesauro de arte y arquitectura" "es")
(name-as-in "aat-id" "AAT識別子" "ja")
(name-as-in "aat-id" "" "zh-cn")
(name-as-in "aat-id" "" "zh-sg")

(descr-as-in "aat-id" "" "zh-hk")
(descr-as-in "aat-id" "" "pt")
(descr-as-in "aat-id" "identifier in the Art & Architecture Thesaurus by the Getty Research Institute" "en")
(descr-as-in "aat-id" "numéro d'identification dans l'Art & Architecture Thesaurus du Getty Research Institute" "fr")
(descr-as-in "aat-id" "" "zh-tw")
(descr-as-in "aat-id" "Identifikator im Art-and-Architecture-Thesaurus des Getty Research Institute" "de")
(descr-as-in "aat-id" "код в Тезаурусе по искусству и архитектуре Института Гетти" "ru")
(descr-as-in "aat-id" "identificador en el Tesauro de Arte & Arquitectura del Getty Research Institute" "es")
(descr-as-in "aat-id" "" "ja")
(descr-as-in "aat-id" "" "zh-cn")
(descr-as-in "aat-id" "" "zh-sg")

