(ns properties.abs_ascl_code
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "abs-ascl-code")

(name-as-in "abs-ascl-code" "ABS ASCL代碼" "zh-hk")
(name-as-in "abs-ascl-code" "" "pt")
(name-as-in "abs-ascl-code" "ABS ASCL code" "en")
(name-as-in "abs-ascl-code" "identifiant ABS ASCL" "fr")
(name-as-in "abs-ascl-code" "ABS ASCL代碼" "zh-tw")
(name-as-in "abs-ascl-code" "ABS ASCL-ID" "de")
(name-as-in "abs-ascl-code" "код ABS ASCL" "ru")
(name-as-in "abs-ascl-code" "" "es")
(name-as-in "abs-ascl-code" "" "ja")
(name-as-in "abs-ascl-code" "ABS ASCL代码" "zh-cn")
(name-as-in "abs-ascl-code" "ABS ASCL代码" "zh-sg")

(descr-as-in "abs-ascl-code" "" "zh-hk")
(descr-as-in "abs-ascl-code" "" "pt")
(descr-as-in "abs-ascl-code" "Australian Standard Classification of Languages ID for languages" "en")
(descr-as-in "abs-ascl-code" "identifiant pour les langues de Australian Standard Classification of Languages" "fr")
(descr-as-in "abs-ascl-code" "" "zh-tw")
(descr-as-in "abs-ascl-code" "Australian Standard Classification of Languages ID für Sprachen" "de")
(descr-as-in "abs-ascl-code" "идентификатор языка в Australian Standard Classification of Languages" "ru")
(descr-as-in "abs-ascl-code" "" "es")
(descr-as-in "abs-ascl-code" "" "ja")
(descr-as-in "abs-ascl-code" "" "zh-cn")
(descr-as-in "abs-ascl-code" "" "zh-sg")

