(ns properties.academia_edu_institutional_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "academia_edu-institutional-id")

(name-as-in "academia_edu-institutional-id" "" "zh-hk")
(name-as-in "academia_edu-institutional-id" "" "pt")
(name-as-in "academia_edu-institutional-id" "Academia.edu institutional ID" "en")
(name-as-in "academia_edu-institutional-id" "identifiant Academia.edu d'une institution" "fr")
(name-as-in "academia_edu-institutional-id" "" "zh-tw")
(name-as-in "academia_edu-institutional-id" "" "de")
(name-as-in "academia_edu-institutional-id" "" "ru")
(name-as-in "academia_edu-institutional-id" "identificador Academia.edu de institución" "es")
(name-as-in "academia_edu-institutional-id" "" "ja")
(name-as-in "academia_edu-institutional-id" "" "zh-cn")
(name-as-in "academia_edu-institutional-id" "" "zh-sg")

(descr-as-in "academia_edu-institutional-id" "" "zh-hk")
(descr-as-in "academia_edu-institutional-id" "" "pt")
(descr-as-in "academia_edu-institutional-id" "academic institution page on academia.edu" "en")
(descr-as-in "academia_edu-institutional-id" "identifiant d'une institution scientifique sur le site Academia.edu" "fr")
(descr-as-in "academia_edu-institutional-id" "" "zh-tw")
(descr-as-in "academia_edu-institutional-id" "" "de")
(descr-as-in "academia_edu-institutional-id" "" "ru")
(descr-as-in "academia_edu-institutional-id" "" "es")
(descr-as-in "academia_edu-institutional-id" "" "ja")
(descr-as-in "academia_edu-institutional-id" "" "zh-cn")
(descr-as-in "academia_edu-institutional-id" "" "zh-sg")

