(ns properties.anthem
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "anthem")

(name-as-in "anthem" "頌歌" "zh-hk")
(name-as-in "anthem" "hino" "pt")
(name-as-in "anthem" "anthem" "en")
(name-as-in "anthem" "hymne" "fr")
(name-as-in "anthem" "國歌" "zh-tw")
(name-as-in "anthem" "Hymne" "de")
(name-as-in "anthem" "гимн" "ru")
(name-as-in "anthem" "himno" "es")
(name-as-in "anthem" "国歌" "ja")
(name-as-in "anthem" "国歌" "zh-cn")
(name-as-in "anthem" "" "zh-sg")

(descr-as-in "anthem" "" "zh-hk")
(descr-as-in "anthem" "" "pt")
(descr-as-in "anthem" "subject's official anthem" "en")
(descr-as-in "anthem" "hymne officiel de l'entité" "fr")
(descr-as-in "anthem" "官方象徵性歌曲" "zh-tw")
(descr-as-in "anthem" "Name der Hymne" "de")
(descr-as-in "anthem" "название гимна предмета" "ru")
(descr-as-in "anthem" "himno oficial del elemento" "es")
(descr-as-in "anthem" "主題を象徴する楽曲（アンセム）。国家に対しては国歌。" "ja")
(descr-as-in "anthem" "" "zh-cn")
(descr-as-in "anthem" "" "zh-sg")

