(ns properties.archives_at
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "archives-at")

(name-as-in "archives-at" "archiviert in" "de")
(name-as-in "archives-at" "" "zh-hk")
(name-as-in "archives-at" "" "zh-tw")
(name-as-in "archives-at" "архивы хранятся в" "ru")
(name-as-in "archives-at" "local dos arquivos" "pt")
(name-as-in "archives-at" "archives at" "en")
(name-as-in "archives-at" "" "zh-cn")
(name-as-in "archives-at" "localisation des archives" "fr")
(name-as-in "archives-at" "archivado en" "es")
(name-as-in "archives-at" "" "zh-sg")
(name-as-in "archives-at" "" "ja")
(name-as-in "archives-at" "" "zh-hans")
(name-as-in "archives-at" "" "zh-hant")

(descr-as-in "archives-at" "Institution mit den Archiven des Datenobjekts" "de")
(descr-as-in "archives-at" "" "zh-hk")
(descr-as-in "archives-at" "" "zh-tw")
(descr-as-in "archives-at" "организация, в которой хранятся архивы персоны" "ru")
(descr-as-in "archives-at" "instituição que coleciona os arquivos relacionados à entidade" "pt")
(descr-as-in "archives-at" "the institution holding the subject's archives" "en")
(descr-as-in "archives-at" "" "zh-cn")
(descr-as-in "archives-at" "institution qui collecte les archives concernant le sujet" "fr")
(descr-as-in "archives-at" "institución que recoge los archivos sobre el tema" "es")
(descr-as-in "archives-at" "" "zh-sg")
(descr-as-in "archives-at" "" "ja")
(descr-as-in "archives-at" "" "zh-hans")
(descr-as-in "archives-at" "" "zh-hant")

