(ns properties.archives_at
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "archives-at")

(name-as-in "archives-at" "存檔位置" "zh-hk")
(name-as-in "archives-at" "arquivado em" "pt")
(name-as-in "archives-at" "archives at" "en")
(name-as-in "archives-at" "archives" "fr")
(name-as-in "archives-at" "" "zh-tw")
(name-as-in "archives-at" "archiviert in" "de")
(name-as-in "archives-at" "архивы хранятся в" "ru")
(name-as-in "archives-at" "archivado en" "es")
(name-as-in "archives-at" "アーカイブ" "ja")
(name-as-in "archives-at" "" "zh-cn")
(name-as-in "archives-at" "" "zh-sg")

(descr-as-in "archives-at" "" "zh-hk")
(descr-as-in "archives-at" "instituição que coleciona os arquivos relacionados à entidade" "pt")
(descr-as-in "archives-at" "the institution holding the subject's archives" "en")
(descr-as-in "archives-at" "institution qui collecte les archives concernant le sujet" "fr")
(descr-as-in "archives-at" "" "zh-tw")
(descr-as-in "archives-at" "Institution mit den Archiven oder Nachlass des Datenobjekts" "de")
(descr-as-in "archives-at" "организация, в которой хранятся архивы персоны" "ru")
(descr-as-in "archives-at" "institución que recoge los archivos sobre el tema" "es")
(descr-as-in "archives-at" "主題のアーカイブを有する機関・組織（文書館、記念図書館、資料館など）" "ja")
(descr-as-in "archives-at" "" "zh-cn")
(descr-as-in "archives-at" "" "zh-sg")

