(ns properties.art_uk_venue_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "art-uk-venue-id")

(name-as-in "art-uk-venue-id" "" "zh-hk")
(name-as-in "art-uk-venue-id" "" "pt")
(name-as-in "art-uk-venue-id" "Art UK venue ID" "en")
(name-as-in "art-uk-venue-id" "identifiant Art UK d'un lieu d'art" "fr")
(name-as-in "art-uk-venue-id" "" "zh-tw")
(name-as-in "art-uk-venue-id" "BBC Your Paintings venue-ID" "de")
(name-as-in "art-uk-venue-id" "код BBC Your Paintings venue" "ru")
(name-as-in "art-uk-venue-id" "identificador BBC Your Paintings de un lugar de arte" "es")
(name-as-in "art-uk-venue-id" "" "ja")
(name-as-in "art-uk-venue-id" "" "zh-cn")
(name-as-in "art-uk-venue-id" "" "zh-sg")

(descr-as-in "art-uk-venue-id" "" "zh-hk")
(descr-as-in "art-uk-venue-id" "" "pt")
(descr-as-in "art-uk-venue-id" "authority control identifier for venues housing art, in the UK" "en")
(descr-as-in "art-uk-venue-id" "" "fr")
(descr-as-in "art-uk-venue-id" "" "zh-tw")
(descr-as-in "art-uk-venue-id" "Identifikator in Normdatei für Kunstsammlungen in Großbritannien" "de")
(descr-as-in "art-uk-venue-id" "" "ru")
(descr-as-in "art-uk-venue-id" "" "es")
(descr-as-in "art-uk-venue-id" "" "ja")
(descr-as-in "art-uk-venue-id" "" "zh-cn")
(descr-as-in "art-uk-venue-id" "" "zh-sg")

