(ns properties.award_received
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "award-received")

(name-as-in "award-received" "獎項" "zh-hk")
(name-as-in "award-received" "distinção" "pt")
(name-as-in "award-received" "award received" "en")
(name-as-in "award-received" "distinction reçue" "fr")
(name-as-in "award-received" "獎項" "zh-tw")
(name-as-in "award-received" "Auszeichnung" "de")
(name-as-in "award-received" "полученные награды" "ru")
(name-as-in "award-received" "premio recibido" "es")
(name-as-in "award-received" "受賞" "ja")
(name-as-in "award-received" "奖项" "zh-cn")
(name-as-in "award-received" "奖项" "zh-sg")

(descr-as-in "award-received" "人物、機構或作品所獲的獎項" "zh-hk")
(descr-as-in "award-received" "prémios ou outro tipo de reconhecimento com que a pessoa, organização ou obra foi agraciada" "pt")
(descr-as-in "award-received" "award or recognition received by a person, organisation or creative work" "en")
(descr-as-in "award-received" "récompense reçue par une personne, une organisation ou une œuvre" "fr")
(descr-as-in "award-received" "人物、機構或作品所獲的獎項" "zh-tw")
(descr-as-in "award-received" "Auszeichnung einer Person, Organisation oder eines schöpferischen Werks" "de")
(descr-as-in "award-received" "награды, полученные персоной, организацией или произведением" "ru")
(descr-as-in "award-received" "premio o reconocimiento recibido por una persona, organización u obra creativa" "es")
(descr-as-in "award-received" "主題の人物・組織・作品が受けた賞・表彰" "ja")
(descr-as-in "award-received" "人物、机构或作品所获的奖项" "zh-cn")
(descr-as-in "award-received" "人物、机构或作品所获的奖项" "zh-sg")

