(ns properties.babelnet_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "babelnet-id")

(name-as-in "babelnet-id" "" "zh-hk")
(name-as-in "babelnet-id" "" "pt")
(name-as-in "babelnet-id" "BabelNet id" "en")
(name-as-in "babelnet-id" "identifiant BabelNet" "fr")
(name-as-in "babelnet-id" "" "zh-tw")
(name-as-in "babelnet-id" "" "de")
(name-as-in "babelnet-id" "код BabelNet" "ru")
(name-as-in "babelnet-id" "identificador BabelNet" "es")
(name-as-in "babelnet-id" "" "ja")
(name-as-in "babelnet-id" "" "zh-cn")
(name-as-in "babelnet-id" "" "zh-sg")

(descr-as-in "babelnet-id" "" "zh-hk")
(descr-as-in "babelnet-id" "" "pt")
(descr-as-in "babelnet-id" "ID in BabelNet encyclopedic dictionary" "en")
(descr-as-in "babelnet-id" "identifiant dans le dictionnaire encyclopédique BabelNet" "fr")
(descr-as-in "babelnet-id" "" "zh-tw")
(descr-as-in "babelnet-id" "" "de")
(descr-as-in "babelnet-id" "" "ru")
(descr-as-in "babelnet-id" "" "es")
(descr-as-in "babelnet-id" "" "ja")
(descr-as-in "babelnet-id" "" "zh-cn")
(descr-as-in "babelnet-id" "" "zh-sg")

