(ns properties.babelio_author_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "babelio-author-id")

(name-as-in "babelio-author-id" "" "zh-hk")
(name-as-in "babelio-author-id" "" "pt")
(name-as-in "babelio-author-id" "Babelio author ID" "en")
(name-as-in "babelio-author-id" "identifiant Babelio d'un auteur" "fr")
(name-as-in "babelio-author-id" "" "zh-tw")
(name-as-in "babelio-author-id" "" "de")
(name-as-in "babelio-author-id" "" "ru")
(name-as-in "babelio-author-id" "identificador Babelio de autor" "es")
(name-as-in "babelio-author-id" "" "ja")
(name-as-in "babelio-author-id" "" "zh-cn")
(name-as-in "babelio-author-id" "" "zh-sg")

(descr-as-in "babelio-author-id" "" "zh-hk")
(descr-as-in "babelio-author-id" "" "pt")
(descr-as-in "babelio-author-id" "identifier for an author on the literature website Babelio" "en")
(descr-as-in "babelio-author-id" "identifiant d'un auteur sur le site littéraire Babelio" "fr")
(descr-as-in "babelio-author-id" "" "zh-tw")
(descr-as-in "babelio-author-id" "" "de")
(descr-as-in "babelio-author-id" "" "ru")
(descr-as-in "babelio-author-id" "" "es")
(descr-as-in "babelio-author-id" "" "ja")
(descr-as-in "babelio-author-id" "" "zh-cn")
(descr-as-in "babelio-author-id" "" "zh-sg")

