(ns properties.basic_form_of_government
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "basic-form-of-government")

(name-as-in "basic-form-of-government" "政治體系" "zh-hk")
(name-as-in "basic-form-of-government" "forma de governo" "pt")
(name-as-in "basic-form-of-government" "basic form of government" "en")
(name-as-in "basic-form-of-government" "régime politique" "fr")
(name-as-in "basic-form-of-government" "政治體系" "zh-tw")
(name-as-in "basic-form-of-government" "Regierungsform" "de")
(name-as-in "basic-form-of-government" "форма правления" "ru")
(name-as-in "basic-form-of-government" "forma de gobierno" "es")
(name-as-in "basic-form-of-government" "政治体制" "ja")
(name-as-in "basic-form-of-government" "政治体系" "zh-cn")
(name-as-in "basic-form-of-government" "政治体系" "zh-sg")

(descr-as-in "basic-form-of-government" "" "zh-hk")
(descr-as-in "basic-form-of-government" "" "pt")
(descr-as-in "basic-form-of-government" "subject's government" "en")
(descr-as-in "basic-form-of-government" "régime politique du sujet" "fr")
(descr-as-in "basic-form-of-government" "" "zh-tw")
(descr-as-in "basic-form-of-government" "Art und Weise der Herrschaftsausübung" "de")
(descr-as-in "basic-form-of-government" "" "ru")
(descr-as-in "basic-form-of-government" "por ejemplo: monarquía, república, etc." "es")
(descr-as-in "basic-form-of-government" "主題の統治形態" "ja")
(descr-as-in "basic-form-of-government" "" "zh-cn")
(descr-as-in "basic-form-of-government" "" "zh-sg")

