(ns properties.bldam_object_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "bldam-object-id")

(name-as-in "bldam-object-id" "" "zh-hk")
(name-as-in "bldam-object-id" "" "pt")
(name-as-in "bldam-object-id" "BLDAM object ID" "en")
(name-as-in "bldam-object-id" "identifiant BLDAM d'un objet" "fr")
(name-as-in "bldam-object-id" "" "zh-tw")
(name-as-in "bldam-object-id" "BLDAM-Objekt-ID" "de")
(name-as-in "bldam-object-id" "код BLDAM" "ru")
(name-as-in "bldam-object-id" "identificador BLDAM de un objeto" "es")
(name-as-in "bldam-object-id" "" "ja")
(name-as-in "bldam-object-id" "" "zh-cn")
(name-as-in "bldam-object-id" "" "zh-sg")

(descr-as-in "bldam-object-id" "" "zh-hk")
(descr-as-in "bldam-object-id" "" "pt")
(descr-as-in "bldam-object-id" "Object ID to identify cultural heritage monuments in Brandenburg, Germany" "en")
(descr-as-in "bldam-object-id" "identifiant d'un bien inscrit au patrimoine culturel du Brandebourg" "fr")
(descr-as-in "bldam-object-id" "" "zh-tw")
(descr-as-in "bldam-object-id" "Objektdokumentennummer der Brandenburger Denkmaldatenbank" "de")
(descr-as-in "bldam-object-id" "код памятника культуры в Бранденбурге" "ru")
(descr-as-in "bldam-object-id" "" "es")
(descr-as-in "bldam-object-id" "" "ja")
(descr-as-in "bldam-object-id" "" "zh-cn")
(descr-as-in "bldam-object-id" "" "zh-sg")

