(ns properties.bncf_thesaurus
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "bncf-thesaurus")

(name-as-in "bncf-thesaurus" "BNCF詞庫" "zh-hk")
(name-as-in "bncf-thesaurus" "BNCF" "pt")
(name-as-in "bncf-thesaurus" "BNCF Thesaurus" "en")
(name-as-in "bncf-thesaurus" "identifiant du thésaurus de la BNCF" "fr")
(name-as-in "bncf-thesaurus" "BNCF" "zh-tw")
(name-as-in "bncf-thesaurus" "BNCF-Thesaurus" "de")
(name-as-in "bncf-thesaurus" "код BNCF" "ru")
(name-as-in "bncf-thesaurus" "identificador BNCF" "es")
(name-as-in "bncf-thesaurus" "BNCFシソーラス" "ja")
(name-as-in "bncf-thesaurus" "BNCF词库" "zh-cn")
(name-as-in "bncf-thesaurus" "" "zh-sg")

(descr-as-in "bncf-thesaurus" "" "zh-hk")
(descr-as-in "bncf-thesaurus" "" "pt")
(descr-as-in "bncf-thesaurus" "identifier in the subject indexing tool of the National Central Library of Florence" "en")
(descr-as-in "bncf-thesaurus" "identifiant du thésaurus italien de la Bibliothèque nationale centrale de Florence" "fr")
(descr-as-in "bncf-thesaurus" "" "zh-tw")
(descr-as-in "bncf-thesaurus" "bibliographischer Eintrag der italienischen Nationalbibliothek" "de")
(descr-as-in "bncf-thesaurus" "идентификатор в итальянском национальном тезаурусе" "ru")
(descr-as-in "bncf-thesaurus" "identificador del tesauro de la Biblioteca Nacional Central de Florencia" "es")
(descr-as-in "bncf-thesaurus" "イタリアのフィレンツェ国立中央図書館のシソーラス" "ja")
(descr-as-in "bncf-thesaurus" "" "zh-cn")
(descr-as-in "bncf-thesaurus" "" "zh-sg")

