(ns properties.bnf_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "bnf-id")

(name-as-in "bnf-id" "BnF編號" "zh-hk")
(name-as-in "bnf-id" "identificador BnF" "pt")
(name-as-in "bnf-id" "BnF ID" "en")
(name-as-in "bnf-id" "identifiant Bibliothèque nationale de France" "fr")
(name-as-in "bnf-id" "" "zh-tw")
(name-as-in "bnf-id" "BnF-ID" "de")
(name-as-in "bnf-id" "код BNF" "ru")
(name-as-in "bnf-id" "identificador BnF" "es")
(name-as-in "bnf-id" "BNF" "ja")
(name-as-in "bnf-id" "BnF编号" "zh-cn")
(name-as-in "bnf-id" "" "zh-sg")

(descr-as-in "bnf-id" "法國國家圖書館編號" "zh-hk")
(descr-as-in "bnf-id" "número de controlo de autoridade pela BnF (Bibliothèque nationale de France)" "pt")
(descr-as-in "bnf-id" "identifier for the subject issued by BNF (Bibliothèque nationale de France). Format: 8 digits followed by a check-digit or letter" "en")
(descr-as-in "bnf-id" "identifiant d'autorité dans le catalogue de la Bibliothèque nationale de France" "fr")
(descr-as-in "bnf-id" "" "zh-tw")
(descr-as-in "bnf-id" "Normdateneintrag in der französischen Nationalbibliothek" "de")
(descr-as-in "bnf-id" "номер в каталоге Национальной библиотеки Франции" "ru")
(descr-as-in "bnf-id" "identificador en el catálogo de la Biblioteca Nacional de Francia" "es")
(descr-as-in "bnf-id" "フランス国立図書館の管理番号" "ja")
(descr-as-in "bnf-id" "" "zh-cn")
(descr-as-in "bnf-id" "" "zh-sg")

