(ns properties.calis_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "calis-id")

(name-as-in "calis-id" "CALIS編碼" "zh-hk")
(name-as-in "calis-id" "identificador CALIS" "pt")
(name-as-in "calis-id" "CALIS ID" "en")
(name-as-in "calis-id" "identifiant CALIS" "fr")
(name-as-in "calis-id" "" "zh-tw")
(name-as-in "calis-id" "CALIS" "de")
(name-as-in "calis-id" "код CALIS" "ru")
(name-as-in "calis-id" "identificador CALIS" "es")
(name-as-in "calis-id" "CALIS" "ja")
(name-as-in "calis-id" "CALIS" "zh-cn")
(name-as-in "calis-id" "" "zh-sg")

(descr-as-in "calis-id" "中國高等教育文獻保障系統編碼" "zh-hk")
(descr-as-in "calis-id" "" "pt")
(descr-as-in "calis-id" "identifier for authority control per CALIS (China Academic Library & Information System)" "en")
(descr-as-in "calis-id" "" "fr")
(descr-as-in "calis-id" "" "zh-tw")
(descr-as-in "calis-id" "Normdateneintrag im gleichnamigen chinesischen Bibliotheksverbund" "de")
(descr-as-in "calis-id" "идентификатор в библиотечно-информационной системе АН КНР" "ru")
(descr-as-in "calis-id" "número de control de autoridad del China Academic Library & Information System" "es")
(descr-as-in "calis-id" "CALIS（中国学術図書館・情報システム）の典拠管理番号" "ja")
(descr-as-in "calis-id" "" "zh-cn")
(descr-as-in "calis-id" "" "zh-sg")

