(ns properties.cantic_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "cantic-id")

(name-as-in "cantic-id" "CANTIC" "zh-hk")
(name-as-in "cantic-id" "identificador CANTIC" "pt")
(name-as-in "cantic-id" "CANTIC-ID" "en")
(name-as-in "cantic-id" "identifiant Bibliothèque nationale de Catalogne" "fr")
(name-as-in "cantic-id" "" "zh-tw")
(name-as-in "cantic-id" "CANTIC-ID" "de")
(name-as-in "cantic-id" "код CANTIC" "ru")
(name-as-in "cantic-id" "identificador CANTIC" "es")
(name-as-in "cantic-id" "CANTIC" "ja")
(name-as-in "cantic-id" "" "zh-cn")
(name-as-in "cantic-id" "" "zh-sg")

(descr-as-in "cantic-id" "由加泰隆尼亞國立圖書館(BNC)所創的加泰隆尼亞權威控制碼" "zh-hk")
(descr-as-in "cantic-id" "controlo de autoria gerido pela Biblioteca Nacional da Catalunha" "pt")
(descr-as-in "cantic-id" "identifier for authority control managed by the National Library of Catalonia (BNC). Format: a, 7 digits, x or digit" "en")
(descr-as-in "cantic-id" "identifiant d'autorité dans le catalogue de la Bibliothèque nationale de Catalogne" "fr")
(descr-as-in "cantic-id" "" "zh-tw")
(descr-as-in "cantic-id" "Normdateneintrag der Katalanischen Nationalbibliothek" "de")
(descr-as-in "cantic-id" "номер в каталоге Национальной библиотеки Каталонии" "ru")
(descr-as-in "cantic-id" "Catálogo de autoridades de nombres y títulos de Cataluña, gestionado por la Biblioteca Nacional de Cataluña" "es")
(descr-as-in "cantic-id" "カタルーニャ図書館が管理する典拠管理 ID" "ja")
(descr-as-in "cantic-id" "" "zh-cn")
(descr-as-in "cantic-id" "" "zh-sg")

