(ns properties.capital
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "capital")

(name-as-in "capital" "首都" "zh-hk")
(name-as-in "capital" "capital" "pt")
(name-as-in "capital" "capital" "en")
(name-as-in "capital" "capitale" "fr")
(name-as-in "capital" "行政中心" "zh-tw")
(name-as-in "capital" "Hauptstadt" "de")
(name-as-in "capital" "столица" "ru")
(name-as-in "capital" "capital" "es")
(name-as-in "capital" "行政中心地" "ja")
(name-as-in "capital" "行政中心" "zh-cn")
(name-as-in "capital" "" "zh-sg")

(descr-as-in "capital" "" "zh-hk")
(descr-as-in "capital" "" "pt")
(descr-as-in "capital" "primary city of a country, state or other type of administrative territorial entity" "en")
(descr-as-in "capital" "siège du pouvoir" "fr")
(descr-as-in "capital" "" "zh-tw")
(descr-as-in "capital" "Repräsentativste Stadt innerhalb einer administrierten geografischen Region, häufig auch Regierungs- oder Verwaltungssitz der Administration.  Hauptstadt und Stadt des Regierungssitzes sind aber nicht in jedem Fall identisch." "de")
(descr-as-in "capital" "центральный населённый пункт в административной единице" "ru")
(descr-as-in "capital" "ciudad donde se ubica el gobierno del país, región o subdivisión." "es")
(descr-as-in "capital" "国、州、または行政区画の行政中枢である自治体" "ja")
(descr-as-in "capital" "" "zh-cn")
(descr-as-in "capital" "" "zh-sg")

