(ns properties.category_for_alumni_of_educational_institution
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "category-for-alumni-of-educational-institution")

(name-as-in "category-for-alumni-of-educational-institution" "" "zh-hk")
(name-as-in "category-for-alumni-of-educational-institution" "categoria para egressos da instituição educacional" "pt")
(name-as-in "category-for-alumni-of-educational-institution" "category for alumni of educational institution" "en")
(name-as-in "category-for-alumni-of-educational-institution" "catégorie pour les personnes ayant étudié dans cet établissement" "fr")
(name-as-in "category-for-alumni-of-educational-institution" "" "zh-tw")
(name-as-in "category-for-alumni-of-educational-institution" "Kategorie für Absolventen einer Bildungseinrichtung" "de")
(name-as-in "category-for-alumni-of-educational-institution" "категория для выпускников образовательного учреждения" "ru")
(name-as-in "category-for-alumni-of-educational-institution" "categoría para las personas que estudiaron en esta institución" "es")
(name-as-in "category-for-alumni-of-educational-institution" "" "ja")
(name-as-in "category-for-alumni-of-educational-institution" "" "zh-cn")
(name-as-in "category-for-alumni-of-educational-institution" "" "zh-sg")

(descr-as-in "category-for-alumni-of-educational-institution" "" "zh-hk")
(descr-as-in "category-for-alumni-of-educational-institution" "" "pt")
(descr-as-in "category-for-alumni-of-educational-institution" "category containing people who studied at this institution" "en")
(descr-as-in "category-for-alumni-of-educational-institution" "" "fr")
(descr-as-in "category-for-alumni-of-educational-institution" "" "zh-tw")
(descr-as-in "category-for-alumni-of-educational-institution" "" "de")
(descr-as-in "category-for-alumni-of-educational-institution" "элемент категории, которая включает людей, окончивших это образовательное учреждение" "ru")
(descr-as-in "category-for-alumni-of-educational-institution" "" "es")
(descr-as-in "category-for-alumni-of-educational-institution" "" "ja")
(descr-as-in "category-for-alumni-of-educational-institution" "" "zh-cn")
(descr-as-in "category-for-alumni-of-educational-institution" "" "zh-sg")

