(ns properties.category_for_people_born_here
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "category-for-people-born-here")

(name-as-in "category-for-people-born-here" "出生地分類" "zh-hk")
(name-as-in "category-for-people-born-here" "categoria para pessoas nascidas aqui" "pt")
(name-as-in "category-for-people-born-here" "category for people born here" "en")
(name-as-in "category-for-people-born-here" "catégorie pour les personnes nées à cet endroit" "fr")
(name-as-in "category-for-people-born-here" "出生地分類" "zh-tw")
(name-as-in "category-for-people-born-here" "Kategorie für hier geborene Personen" "de")
(name-as-in "category-for-people-born-here" "категория для людей, родившихся здесь" "ru")
(name-as-in "category-for-people-born-here" "categoría para las personas que nacieron aquí" "es")
(name-as-in "category-for-people-born-here" "当地生まれの人のカテゴリ" "ja")
(name-as-in "category-for-people-born-here" "出生地分类" "zh-cn")
(name-as-in "category-for-people-born-here" "出生地分类" "zh-sg")

(descr-as-in "category-for-people-born-here" "" "zh-hk")
(descr-as-in "category-for-people-born-here" "" "pt")
(descr-as-in "category-for-people-born-here" "category item that groups people born in this place" "en")
(descr-as-in "category-for-people-born-here" "catégorie des personnes qui sont nées dans cette localité" "fr")
(descr-as-in "category-for-people-born-here" "" "zh-tw")
(descr-as-in "category-for-people-born-here" "Kategorie für Personen, die an diesem Ort geboren sind" "de")
(descr-as-in "category-for-people-born-here" "элемент категории, которая включает людей, родившихся в этом месте" "ru")
(descr-as-in "category-for-people-born-here" "categoría para las personas que nacieron en este lugar" "es")
(descr-as-in "category-for-people-born-here" "" "ja")
(descr-as-in "category-for-people-born-here" "" "zh-cn")
(descr-as-in "category-for-people-born-here" "" "zh-sg")

