(ns properties.category_of_associated_people
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "category-of-associated-people")

(name-as-in "category-of-associated-people" "相關人物分類" "zh-hk")
(name-as-in "category-of-associated-people" "categoria de pessoas associadas" "pt")
(name-as-in "category-of-associated-people" "category of associated people" "en")
(name-as-in "category-of-associated-people" "catégorie de personnalité" "fr")
(name-as-in "category-of-associated-people" "相關人物分類" "zh-tw")
(name-as-in "category-of-associated-people" "Kategorie für Personen mit Bezug zum Ort" "de")
(name-as-in "category-of-associated-people" "категория для людей, связанных с местностью" "ru")
(name-as-in "category-of-associated-people" "categoría de personas relacionadas" "es")
(name-as-in "category-of-associated-people" "当地の人々のカテゴリ" "ja")
(name-as-in "category-of-associated-people" "相关人物分类" "zh-cn")
(name-as-in "category-of-associated-people" "相关人物分类" "zh-sg")

(descr-as-in "category-of-associated-people" "" "zh-hk")
(descr-as-in "category-of-associated-people" "categoria de pessoas associadas com este lugar" "pt")
(descr-as-in "category-of-associated-people" "Wikimedia category for people associated with this place" "en")
(descr-as-in "category-of-associated-people" "catégorie Wikimédia des personnalités associées à un lieu" "fr")
(descr-as-in "category-of-associated-people" "" "zh-tw")
(descr-as-in "category-of-associated-people" "Kategorie für Personen, die einen Bezug zu diesem Ort haben (Kategorie für hier geborene Personen P1464, gestorben P1465)" "de")
(descr-as-in "category-of-associated-people" "ссылка на элемент категории, содержащей людей, связанных с этой местностью" "ru")
(descr-as-in "category-of-associated-people" "categorías para personas relacionadas con este lugar" "es")
(descr-as-in "category-of-associated-people" "この場所と結びつけられる人々のウィキメディアのカテゴリ" "ja")
(descr-as-in "category-of-associated-people" "" "zh-cn")
(descr-as-in "category-of-associated-people" "" "zh-sg")

