(ns properties.category_for_employees_of_the_organization
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "category-for-employees-of-the-organization")

(name-as-in "category-for-employees-of-the-organization" "" "zh-hk")
(name-as-in "category-for-employees-of-the-organization" "categoria para empregados da organização" "pt")
(name-as-in "category-for-employees-of-the-organization" "category for employees of the organization" "en")
(name-as-in "category-for-employees-of-the-organization" "catégorie pour les employés de l'organisation" "fr")
(name-as-in "category-for-employees-of-the-organization" "" "zh-tw")
(name-as-in "category-for-employees-of-the-organization" "" "de")
(name-as-in "category-for-employees-of-the-organization" "категория для сотрудников организации" "ru")
(name-as-in "category-for-employees-of-the-organization" "categoría para empleados de la organización" "es")
(name-as-in "category-for-employees-of-the-organization" "" "ja")
(name-as-in "category-for-employees-of-the-organization" "" "zh-cn")
(name-as-in "category-for-employees-of-the-organization" "" "zh-sg")

(descr-as-in "category-for-employees-of-the-organization" "" "zh-hk")
(descr-as-in "category-for-employees-of-the-organization" "" "pt")
(descr-as-in "category-for-employees-of-the-organization" "Wikimedia category for people who work or worked at this organization" "en")
(descr-as-in "category-for-employees-of-the-organization" "catégorie Wikimedia pour les personnes qui travaillent ou ont travaillées dans cette organisation" "fr")
(descr-as-in "category-for-employees-of-the-organization" "" "zh-tw")
(descr-as-in "category-for-employees-of-the-organization" "" "de")
(descr-as-in "category-for-employees-of-the-organization" "ссылка на элемент категории, содержащей людей, работавших в данной организации" "ru")
(descr-as-in "category-for-employees-of-the-organization" "categoría de Wikimedia para las personas que trabajan o han trabajado en esta organización" "es")
(descr-as-in "category-for-employees-of-the-organization" "" "ja")
(descr-as-in "category-for-employees-of-the-organization" "" "zh-cn")
(descr-as-in "category-for-employees-of-the-organization" "" "zh-sg")

