(ns properties.category_of_people_buried_here
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "category-of-people-buried-here")

(name-as-in "category-of-people-buried-here" "" "zh-hk")
(name-as-in "category-of-people-buried-here" "" "pt")
(name-as-in "category-of-people-buried-here" "category of people buried here" "en")
(name-as-in "category-of-people-buried-here" "catégorie pour les personnes enterrées à cet endroit" "fr")
(name-as-in "category-of-people-buried-here" "" "zh-tw")
(name-as-in "category-of-people-buried-here" "Kategorie für Personen, die an diesem Ort begraben sind" "de")
(name-as-in "category-of-people-buried-here" "категория для людей, похороненных здесь" "ru")
(name-as-in "category-of-people-buried-here" "categoría para las personas enterradas aquí" "es")
(name-as-in "category-of-people-buried-here" "当地で埋葬された人々のカテゴリ" "ja")
(name-as-in "category-of-people-buried-here" "" "zh-cn")
(name-as-in "category-of-people-buried-here" "" "zh-sg")

(descr-as-in "category-of-people-buried-here" "" "zh-hk")
(descr-as-in "category-of-people-buried-here" "" "pt")
(descr-as-in "category-of-people-buried-here" "Wikimedia category for people with a burial site within this area" "en")
(descr-as-in "category-of-people-buried-here" "catégorie des personnes qui sont enterrées dans cette localité" "fr")
(descr-as-in "category-of-people-buried-here" "" "zh-tw")
(descr-as-in "category-of-people-buried-here" "Wikimedia-Kategorie für Personen mit einem Begräbnisort innerhalb dieses Gebietes" "de")
(descr-as-in "category-of-people-buried-here" "ссылка на элемент категории, содержащей людей, похоронненых в этой местности" "ru")
(descr-as-in "category-of-people-buried-here" "" "es")
(descr-as-in "category-of-people-buried-here" "埋葬場所がこの地域に含まれる人々のための、ウィキメディアのカテゴリ" "ja")
(descr-as-in "category-of-people-buried-here" "" "zh-cn")
(descr-as-in "category-of-people-buried-here" "" "zh-sg")

