(ns properties.categorys_main_topic
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "category's-main-topic")

(name-as-in "category's-main-topic" "分類主條目" "zh-hk")
(name-as-in "category's-main-topic" "artigo principal da categoria" "pt")
(name-as-in "category's-main-topic" "category's main topic" "en")
(name-as-in "category's-main-topic" "sujet de la catégorie" "fr")
(name-as-in "category's-main-topic" "分類主條目" "zh-tw")
(name-as-in "category's-main-topic" "Thema der Kategorie" "de")
(name-as-in "category's-main-topic" "общая тема категории" "ru")
(name-as-in "category's-main-topic" "tema principal de la categoría" "es")
(name-as-in "category's-main-topic" "カテゴリの中心記事" "ja")
(name-as-in "category's-main-topic" "分类主条目" "zh-cn")
(name-as-in "category's-main-topic" "分类主条目" "zh-sg")

(descr-as-in "category's-main-topic" "" "zh-hk")
(descr-as-in "category's-main-topic" "tema principal de uma categoria da Wikipédia" "pt")
(descr-as-in "category's-main-topic" "primary topic of the subject Wikimedia category" "en")
(descr-as-in "category's-main-topic" "sujet principal de la catégorie" "fr")
(descr-as-in "category's-main-topic" "" "zh-tw")
(descr-as-in "category's-main-topic" "das Hauptthema dieser Wikimedia-Kategorie" "de")
(descr-as-in "category's-main-topic" "главная тема этой категории Викимедиа" "ru")
(descr-as-in "category's-main-topic" "tema principal de una categoría de Wikipedia" "es")
(descr-as-in "category's-main-topic" "このカテゴリの中心となる主題" "ja")
(descr-as-in "category's-main-topic" "" "zh-cn")
(descr-as-in "category's-main-topic" "" "zh-sg")

