(ns properties.cause_of_death
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "cause-of-death")

(name-as-in "cause-of-death" "死因" "zh-hk")
(name-as-in "cause-of-death" "causa da morte" "pt")
(name-as-in "cause-of-death" "cause of death" "en")
(name-as-in "cause-of-death" "cause de décès" "fr")
(name-as-in "cause-of-death" "死因" "zh-tw")
(name-as-in "cause-of-death" "Todesursache" "de")
(name-as-in "cause-of-death" "причина смерти" "ru")
(name-as-in "cause-of-death" "causa de muerte" "es")
(name-as-in "cause-of-death" "死因" "ja")
(name-as-in "cause-of-death" "死因" "zh-cn")
(name-as-in "cause-of-death" "死因" "zh-sg")

(descr-as-in "cause-of-death" "" "zh-hk")
(descr-as-in "cause-of-death" "" "pt")
(descr-as-in "cause-of-death" "underlying or immediate cause of death.  Underlying cause (e.g. car accident, stomach cancer) preferred.  Use 'manner of death' (P1196) for broadest category, e.g. natural causes, accident, homicide, suicide" "en")
(descr-as-in "cause-of-death" "cause de la mort (ne doit pas être confondu avec P1196)" "fr")
(descr-as-in "cause-of-death" "" "zh-tw")
(descr-as-in "cause-of-death" "Grund für den Eintritt des Sterbevorgangs und des Todes einer Person oder eines anderen Organismus" "de")
(descr-as-in "cause-of-death" "элемент с описанием причины смерти персоны или организма. Например: лейкемия, автокатастрофа" "ru")
(descr-as-in "cause-of-death" "causa médica de la muerte" "es")
(descr-as-in "cause-of-death" "主題人物が死亡した原因（例：白血病、交通事故）。おおまかな状況（自然死、事故死、自殺、他殺など）はP1196を使用" "ja")
(descr-as-in "cause-of-death" "" "zh-cn")
(descr-as-in "cause-of-death" "" "zh-sg")

