(ns properties.caverphone
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "caverphone")

(name-as-in "caverphone" "" "zh-hk")
(name-as-in "caverphone" "" "pt")
(name-as-in "caverphone" "Caverphone" "en")
(name-as-in "caverphone" "Caverphone" "fr")
(name-as-in "caverphone" "" "zh-tw")
(name-as-in "caverphone" "Caverphone" "de")
(name-as-in "caverphone" "Caverphone" "ru")
(name-as-in "caverphone" "Caverphone" "es")
(name-as-in "caverphone" "" "ja")
(name-as-in "caverphone" "" "zh-cn")
(name-as-in "caverphone" "" "zh-sg")

(descr-as-in "caverphone" "" "zh-hk")
(descr-as-in "caverphone" "" "pt")
(descr-as-in "caverphone" "phonetic algorithm" "en")
(descr-as-in "caverphone" "algorithme phonétique" "fr")
(descr-as-in "caverphone" "" "zh-tw")
(descr-as-in "caverphone" "phonetischer Algorithmus" "de")
(descr-as-in "caverphone" "" "ru")
(descr-as-in "caverphone" "algoritmo fonético" "es")
(descr-as-in "caverphone" "" "ja")
(descr-as-in "caverphone" "" "zh-cn")
(descr-as-in "caverphone" "" "zh-sg")

