(ns properties.child
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "child")

(name-as-in "child" "子女" "zh-hk")
(name-as-in "child" "descendência" "pt")
(name-as-in "child" "child" "en")
(name-as-in "child" "enfant" "fr")
(name-as-in "child" "子女" "zh-tw")
(name-as-in "child" "Kinder" "de")
(name-as-in "child" "дети" "ru")
(name-as-in "child" "hijo o hija" "es")
(name-as-in "child" "子" "ja")
(name-as-in "child" "孩子" "zh-cn")
(name-as-in "child" "子女" "zh-sg")

(descr-as-in "child" "" "zh-hk")
(descr-as-in "child" "um ou mais filhos do sujeito" "pt")
(descr-as-in "child" "subject has the object in their family as their offspring son or daughter (independently of their age)" "en")
(descr-as-in "child" "lien familial direct indiquant que l'objet du lien est un fils ou une fille du sujet (indépendamment de son âge)" "fr")
(descr-as-in "child" "" "zh-tw")
(descr-as-in "child" "Kinder der Person" "de")
(descr-as-in "child" "дети этого человека" "ru")
(descr-as-in "child" "el objeto es el vástago biológico del sujeto" "es")
(descr-as-in "child" "その項目は主題に対し子" "ja")
(descr-as-in "child" "" "zh-cn")
(descr-as-in "child" "" "zh-sg")

