(ns properties.christies_creator_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "christie's-creator-id")

(name-as-in "christie's-creator-id" "" "zh-hk")
(name-as-in "christie's-creator-id" "" "pt")
(name-as-in "christie's-creator-id" "Christie's creator id" "en")
(name-as-in "christie's-creator-id" "identifiant Christie's d'un artiste" "fr")
(name-as-in "christie's-creator-id" "" "zh-tw")
(name-as-in "christie's-creator-id" "Christie's Künstler id" "de")
(name-as-in "christie's-creator-id" "" "ru")
(name-as-in "christie's-creator-id" "identificador Christie's de artista" "es")
(name-as-in "christie's-creator-id" "" "ja")
(name-as-in "christie's-creator-id" "" "zh-cn")
(name-as-in "christie's-creator-id" "" "zh-sg")

(descr-as-in "christie's-creator-id" "" "zh-hk")
(descr-as-in "christie's-creator-id" "" "pt")
(descr-as-in "christie's-creator-id" "identifier for an artist in the Christie's online database" "en")
(descr-as-in "christie's-creator-id" "identifiant pour un artiste dans la base de données en ligne Christie's" "fr")
(descr-as-in "christie's-creator-id" "" "zh-tw")
(descr-as-in "christie's-creator-id" "Identifikator eines Künstlers in der Christie's online database" "de")
(descr-as-in "christie's-creator-id" "" "ru")
(descr-as-in "christie's-creator-id" "" "es")
(descr-as-in "christie's-creator-id" "" "ja")
(descr-as-in "christie's-creator-id" "" "zh-cn")
(descr-as-in "christie's-creator-id" "" "zh-sg")

