(ns properties.coat_of_arms_image
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "coat-of-arms-image")

(name-as-in "coat-of-arms-image" "紋章圖片" "zh-hk")
(name-as-in "coat-of-arms-image" "imagem do brasão" "pt")
(name-as-in "coat-of-arms-image" "coat of arms image" "en")
(name-as-in "coat-of-arms-image" "image du blason" "fr")
(name-as-in "coat-of-arms-image" "紋章圖像" "zh-tw")
(name-as-in "coat-of-arms-image" "Wappen" "de")
(name-as-in "coat-of-arms-image" "изображение герба" "ru")
(name-as-in "coat-of-arms-image" "imagen del escudo de armas" "es")
(name-as-in "coat-of-arms-image" "紋章の画像" "ja")
(name-as-in "coat-of-arms-image" "纹章图像" "zh-cn")
(name-as-in "coat-of-arms-image" "纹章图像" "zh-sg")

(descr-as-in "coat-of-arms-image" "" "zh-hk")
(descr-as-in "coat-of-arms-image" "imagem do brasão do item em questão" "pt")
(descr-as-in "coat-of-arms-image" "image of the item's coat of arms" "en")
(descr-as-in "coat-of-arms-image" "image du blason" "fr")
(descr-as-in "coat-of-arms-image" "" "zh-tw")
(descr-as-in "coat-of-arms-image" "Abbildung des Wappenschilds" "de")
(descr-as-in "coat-of-arms-image" "изображение герба данного элемента" "ru")
(descr-as-in "coat-of-arms-image" "imagen del escudo de armas del elemento" "es")
(descr-as-in "coat-of-arms-image" "その項目の紋章の画像" "ja")
(descr-as-in "coat-of-arms-image" "" "zh-cn")
(descr-as-in "coat-of-arms-image" "" "zh-sg")

