(ns properties.cologne_phonetics
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "cologne-phonetics")

(name-as-in "cologne-phonetics" "" "zh-hk")
(name-as-in "cologne-phonetics" "" "pt")
(name-as-in "cologne-phonetics" "Cologne phonetics" "en")
(name-as-in "cologne-phonetics" "algorithme phonétique de Cologne" "fr")
(name-as-in "cologne-phonetics" "" "zh-tw")
(name-as-in "cologne-phonetics" "Kölner Phonetik" "de")
(name-as-in "cologne-phonetics" "кёльнская фонетика" "ru")
(name-as-in "cologne-phonetics" "fonética de Colonia" "es")
(name-as-in "cologne-phonetics" "" "ja")
(name-as-in "cologne-phonetics" "" "zh-cn")
(name-as-in "cologne-phonetics" "" "zh-sg")

(descr-as-in "cologne-phonetics" "" "zh-hk")
(descr-as-in "cologne-phonetics" "" "pt")
(descr-as-in "cologne-phonetics" "phonetic algorithm which assigns to words a sequence of digits, the phonetic code" "en")
(descr-as-in "cologne-phonetics" "algorithme phonétique qui assigne aux mots une séquence de chiffres, le code phonétique" "fr")
(descr-as-in "cologne-phonetics" "" "zh-tw")
(descr-as-in "cologne-phonetics" "phonetischer Algorithmus, der Wörter nach ihrem Klang eine Ziffernfolge zuordnet" "de")
(descr-as-in "cologne-phonetics" "" "ru")
(descr-as-in "cologne-phonetics" "algoritmo fonético que asigna una secuencia de dígitos (el código fonético) a las palabras" "es")
(descr-as-in "cologne-phonetics" "" "ja")
(descr-as-in "cologne-phonetics" "" "zh-cn")
(descr-as-in "cologne-phonetics" "" "zh-sg")

