(ns properties.commons_institution_page
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "commons-institution-page")

(name-as-in "commons-institution-page" "" "zh-hk")
(name-as-in "commons-institution-page" "página da instituição no Commons" "pt")
(name-as-in "commons-institution-page" "Commons Institution page" "en")
(name-as-in "commons-institution-page" "modèle Institution sur Commons" "fr")
(name-as-in "commons-institution-page" "" "zh-tw")
(name-as-in "commons-institution-page" "Commons-Institution-Vorlage" "de")
(name-as-in "commons-institution-page" "страница учреждения на Викискладе" "ru")
(name-as-in "commons-institution-page" "página de institución en Commons" "es")
(name-as-in "commons-institution-page" "" "ja")
(name-as-in "commons-institution-page" "" "zh-cn")
(name-as-in "commons-institution-page" "" "zh-sg")

(descr-as-in "commons-institution-page" "" "zh-hk")
(descr-as-in "commons-institution-page" "" "pt")
(descr-as-in "commons-institution-page" "name of the institutions's page on Wikimedia Commons (without the prefix Institution)" "en")
(descr-as-in "commons-institution-page" "" "fr")
(descr-as-in "commons-institution-page" "" "zh-tw")
(descr-as-in "commons-institution-page" "" "de")
(descr-as-in "commons-institution-page" "" "ru")
(descr-as-in "commons-institution-page" "nombre de la página de la institución en Wikimedia Commons" "es")
(descr-as-in "commons-institution-page" "" "ja")
(descr-as-in "commons-institution-page" "" "zh-cn")
(descr-as-in "commons-institution-page" "" "zh-sg")

