(ns properties.commons_maps_category
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "commons-maps-category")

(name-as-in "commons-maps-category" "" "zh-hk")
(name-as-in "commons-maps-category" "categoria de mapas no Commons" "pt")
(name-as-in "commons-maps-category" "Commons maps category" "en")
(name-as-in "commons-maps-category" "Catégorie Commons des cartes géographiques" "fr")
(name-as-in "commons-maps-category" "" "zh-tw")
(name-as-in "commons-maps-category" "Commons-Kategorie für Karten" "de")
(name-as-in "commons-maps-category" "категория с картами на Викискладе" "ru")
(name-as-in "commons-maps-category" "" "es")
(name-as-in "commons-maps-category" "" "ja")
(name-as-in "commons-maps-category" "" "zh-cn")
(name-as-in "commons-maps-category" "" "zh-sg")

(descr-as-in "commons-maps-category" "" "zh-hk")
(descr-as-in "commons-maps-category" "" "pt")
(descr-as-in "commons-maps-category" "name of the Wikimedia Commons category specifically for maps or plans of this item (without the prefix Category:)" "en")
(descr-as-in "commons-maps-category" "" "fr")
(descr-as-in "commons-maps-category" "" "zh-tw")
(descr-as-in "commons-maps-category" "Name der Commons-Kategorie für Karten des Objekts" "de")
(descr-as-in "commons-maps-category" "название категории Викисклада, содержащей карты для данного элемента" "ru")
(descr-as-in "commons-maps-category" "" "es")
(descr-as-in "commons-maps-category" "" "ja")
(descr-as-in "commons-maps-category" "" "zh-cn")
(descr-as-in "commons-maps-category" "" "zh-sg")

