(ns properties.commemorative_plaque_image
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "commemorative-plaque-image")

(name-as-in "commemorative-plaque-image" "" "zh-hk")
(name-as-in "commemorative-plaque-image" "imagem de placa comemorativa" "pt")
(name-as-in "commemorative-plaque-image" "commemorative plaque image" "en")
(name-as-in "commemorative-plaque-image" "image de la plaque commémorative" "fr")
(name-as-in "commemorative-plaque-image" "" "zh-tw")
(name-as-in "commemorative-plaque-image" "Bild einer Gedenktafel" "de")
(name-as-in "commemorative-plaque-image" "изображение памятной доски" "ru")
(name-as-in "commemorative-plaque-image" "imagen de una placa conmemorativa" "es")
(name-as-in "commemorative-plaque-image" "銘板画像" "ja")
(name-as-in "commemorative-plaque-image" "" "zh-cn")
(name-as-in "commemorative-plaque-image" "" "zh-sg")

(descr-as-in "commemorative-plaque-image" "" "zh-hk")
(descr-as-in "commemorative-plaque-image" "" "pt")
(descr-as-in "commemorative-plaque-image" "image of plaque or inscription commemorating or mentioning the subject. For graves, use grave picture (P1442)" "en")
(descr-as-in "commemorative-plaque-image" "" "fr")
(descr-as-in "commemorative-plaque-image" "" "zh-tw")
(descr-as-in "commemorative-plaque-image" "Bild einer Gedenktafel oder Inschrift, die an diese Entität erinnert oder sie erwähnt. Für Grabsteine P1442 benutzen" "de")
(descr-as-in "commemorative-plaque-image" "изображение таблички или надписи, отмечающей или вспоминающей тему. Для могил используйте изображения могилы (P1442)" "ru")
(descr-as-in "commemorative-plaque-image" "imagen de una placa o inscripción conmemorativa o que mencione al sujeto. Para tumbas, usar imagen de la tumba (P1442)" "es")
(descr-as-in "commemorative-plaque-image" "" "ja")
(descr-as-in "commemorative-plaque-image" "" "zh-cn")
(descr-as-in "commemorative-plaque-image" "" "zh-sg")

