(ns properties.commissioned_by
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "commissioned-by")

(name-as-in "commissioned-by" "委託人" "zh-hk")
(name-as-in "commissioned-by" "encomendador" "pt")
(name-as-in "commissioned-by" "commissioned by" "en")
(name-as-in "commissioned-by" "commanditaire" "fr")
(name-as-in "commissioned-by" "委託人" "zh-tw")
(name-as-in "commissioned-by" "Auftraggeber" "de")
(name-as-in "commissioned-by" "заказчик произведения" "ru")
(name-as-in "commissioned-by" "comisionador" "es")
(name-as-in "commissioned-by" "依頼者" "ja")
(name-as-in "commissioned-by" "委托人" "zh-cn")
(name-as-in "commissioned-by" "委托人" "zh-sg")

(descr-as-in "commissioned-by" "委託藝術家進行創作的人" "zh-hk")
(descr-as-in "commissioned-by" "pessoa ou entidade que encomendou a obra de arte" "pt")
(descr-as-in "commissioned-by" "person or organization that commissioned this work" "en")
(descr-as-in "commissioned-by" "personne ayant commandé l'œuvre d'art" "fr")
(descr-as-in "commissioned-by" "委託藝術家進行創作的人" "zh-tw")
(descr-as-in "commissioned-by" "Auftraggeber eines Kunstwerks oder Bauwerks" "de")
(descr-as-in "commissioned-by" "" "ru")
(descr-as-in "commissioned-by" "persona u organización que comisionó la obra creativa" "es")
(descr-as-in "commissioned-by" "この著作物を依頼した人または組織" "ja")
(descr-as-in "commissioned-by" "委托艺术家进行创作的人" "zh-cn")
(descr-as-in "commissioned-by" "委托艺术家进行创作的人" "zh-sg")

