(ns properties.contains_administrative_territorial_entity
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "contains-administrative-territorial-entity")

(name-as-in "contains-administrative-territorial-entity" "下級行政區劃" "zh-hk")
(name-as-in "contains-administrative-territorial-entity" "subdivide-se em" "pt")
(name-as-in "contains-administrative-territorial-entity" "contains administrative territorial entity" "en")
(name-as-in "contains-administrative-territorial-entity" "contient les subdivisions territoriales administratives" "fr")
(name-as-in "contains-administrative-territorial-entity" "下轄" "zh-tw")
(name-as-in "contains-administrative-territorial-entity" "Untereinheit (administrative Einheit)" "de")
(name-as-in "contains-administrative-territorial-entity" "административно делится на" "ru")
(name-as-in "contains-administrative-territorial-entity" "subdividido en (división administrativa)" "es")
(name-as-in "contains-administrative-territorial-entity" "直下の行政区画" "ja")
(name-as-in "contains-administrative-territorial-entity" "下辖行政区" "zh-cn")
(name-as-in "contains-administrative-territorial-entity" "" "zh-sg")

(descr-as-in "contains-administrative-territorial-entity" "" "zh-hk")
(descr-as-in "contains-administrative-territorial-entity" "subdivisão direta de um divisão administrativa" "pt")
(descr-as-in "contains-administrative-territorial-entity" "(list of) direct subdivisions of an administrative territorial entity" "en")
(descr-as-in "contains-administrative-territorial-entity" "(liste des) subdivisions directes d'une entité territorial administrative" "fr")
(descr-as-in "contains-administrative-territorial-entity" "" "zh-tw")
(descr-as-in "contains-administrative-territorial-entity" "(Liste von) direkten Untereinheiten einer administrativen Einheit" "de")
(descr-as-in "contains-administrative-territorial-entity" "единицы, на которые непосредственно подразделяется данная административная единица" "ru")
(descr-as-in "contains-administrative-territorial-entity" "subdivisiones que componen una división administrativa" "es")
(descr-as-in "contains-administrative-territorial-entity" "この項目の直下に位置付けられる行政区画。行政区画でない集落はP1383を使用。" "ja")
(descr-as-in "contains-administrative-territorial-entity" "" "zh-cn")
(descr-as-in "contains-administrative-territorial-entity" "" "zh-sg")

