(ns properties.continent
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "continent")

(name-as-in "continent" "大洲" "zh-hk")
(name-as-in "continent" "continente" "pt")
(name-as-in "continent" "continent" "en")
(name-as-in "continent" "continent" "fr")
(name-as-in "continent" "大洲" "zh-tw")
(name-as-in "continent" "Kontinent" "de")
(name-as-in "continent" "часть света" "ru")
(name-as-in "continent" "continente" "es")
(name-as-in "continent" "大陸" "ja")
(name-as-in "continent" "大洲" "zh-cn")
(name-as-in "continent" "大洲" "zh-sg")

(descr-as-in "continent" "項所在的大洲" "zh-hk")
(descr-as-in "continent" "continente onde o item está localizado" "pt")
(descr-as-in "continent" "continent of which the subject is a part" "en")
(descr-as-in "continent" "continent terrestre sur lequel se situe l'objet" "fr")
(descr-as-in "continent" "項所在的大洲" "zh-tw")
(descr-as-in "continent" "Erdteil, auf dem sich das Objekt befindet (bei Ländern und wo es sich nicht aus dem Land ergibt)" "de")
(descr-as-in "continent" "часть света, в которой находится элемент. Используется для стран" "ru")
(descr-as-in "continent" "continente donde se ubica el elemento" "es")
(descr-as-in "continent" "" "ja")
(descr-as-in "continent" "项所在的大洲" "zh-cn")
(descr-as-in "continent" "项所在的大洲" "zh-sg")

