(ns properties.coordinate_of_southernmost_point
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "coordinate-of-southernmost-point")

(name-as-in "coordinate-of-southernmost-point" "最南點" "zh-hk")
(name-as-in "coordinate-of-southernmost-point" "ponto meridional" "pt")
(name-as-in "coordinate-of-southernmost-point" "coordinate of southernmost point" "en")
(name-as-in "coordinate-of-southernmost-point" "coordonnées du point le plus au sud" "fr")
(name-as-in "coordinate-of-southernmost-point" "最南點" "zh-tw")
(name-as-in "coordinate-of-southernmost-point" "südlichster Punkt" "de")
(name-as-in "coordinate-of-southernmost-point" "самая южная точка" "ru")
(name-as-in "coordinate-of-southernmost-point" "punto más meridional" "es")
(name-as-in "coordinate-of-southernmost-point" "最南端" "ja")
(name-as-in "coordinate-of-southernmost-point" "最南点" "zh-cn")
(name-as-in "coordinate-of-southernmost-point" "" "zh-sg")

(descr-as-in "coordinate-of-southernmost-point" "" "zh-hk")
(descr-as-in "coordinate-of-southernmost-point" "" "pt")
(descr-as-in "coordinate-of-southernmost-point" "southernmost point of a place. For administrative entities this includes offshore islands" "en")
(descr-as-in "coordinate-of-southernmost-point" "point le plus au sud d'un lieu" "fr")
(descr-as-in "coordinate-of-southernmost-point" "" "zh-tw")
(descr-as-in "coordinate-of-southernmost-point" "südlichster Punkt eines Orts" "de")
(descr-as-in "coordinate-of-southernmost-point" "" "ru")
(descr-as-in "coordinate-of-southernmost-point" "" "es")
(descr-as-in "coordinate-of-southernmost-point" "場所の最南端。行政単位に関しては離島を含む" "ja")
(descr-as-in "coordinate-of-southernmost-point" "" "zh-cn")
(descr-as-in "coordinate-of-southernmost-point" "" "zh-sg")

