(ns properties.coordinate_location
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "coordinate-location")

(name-as-in "coordinate-location" "geographische Koordinate" "de")
(name-as-in "coordinate-location" "" "zh-hk")
(name-as-in "coordinate-location" "" "zh-tw")
(name-as-in "coordinate-location" "географические координаты" "ru")
(name-as-in "coordinate-location" "coordenadas" "pt")
(name-as-in "coordinate-location" "coordinate location" "en")
(name-as-in "coordinate-location" "坐标位置" "zh-cn")
(name-as-in "coordinate-location" "coordonnées géographiques" "fr")
(name-as-in "coordinate-location" "coordenadas" "es")
(name-as-in "coordinate-location" "" "zh-sg")
(name-as-in "coordinate-location" "位置座標" "ja")
(name-as-in "coordinate-location" "地理坐标" "zh-hans")
(name-as-in "coordinate-location" "地理坐標" "zh-hant")

(descr-as-in "coordinate-location" "Koordinate des Objekts" "de")
(descr-as-in "coordinate-location" "" "zh-hk")
(descr-as-in "coordinate-location" "" "zh-tw")
(descr-as-in "coordinate-location" "географические координаты данного предмета" "ru")
(descr-as-in "coordinate-location" "coordenadas geográficas da entidade" "pt")
(descr-as-in "coordinate-location" "coordinates of the subject" "en")
(descr-as-in "coordinate-location" "" "zh-cn")
(descr-as-in "coordinate-location" "coordonnées géographiques d'un objet" "fr")
(descr-as-in "coordinate-location" "coordenadas geográficas de la entidad" "es")
(descr-as-in "coordinate-location" "" "zh-sg")
(descr-as-in "coordinate-location" "主語の座標" "ja")
(descr-as-in "coordinate-location" "" "zh-hans")
(descr-as-in "coordinate-location" "" "zh-hant")

