(ns properties.coordinate_location
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "coordinate-location")

(name-as-in "coordinate-location" "地理座標" "zh-hk")
(name-as-in "coordinate-location" "coordenadas geográficas" "pt")
(name-as-in "coordinate-location" "coordinate location" "en")
(name-as-in "coordinate-location" "coordonnées géographiques" "fr")
(name-as-in "coordinate-location" "地理座標" "zh-tw")
(name-as-in "coordinate-location" "geographische Koordinaten" "de")
(name-as-in "coordinate-location" "географические координаты" "ru")
(name-as-in "coordinate-location" "coordenadas" "es")
(name-as-in "coordinate-location" "位置座標" "ja")
(name-as-in "coordinate-location" "地理坐标" "zh-cn")
(name-as-in "coordinate-location" "地理坐标" "zh-sg")

(descr-as-in "coordinate-location" "主題的座標方位，請注意目前僅支持WGS84座標系" "zh-hk")
(descr-as-in "coordinate-location" "coordenadas geográficas da entidade" "pt")
(descr-as-in "coordinate-location" "geocoordinates of the subject, please note that only WGS84 coordinating system is supported at the moment" "en")
(descr-as-in "coordinate-location" "coordonnées géographiques de l'objet" "fr")
(descr-as-in "coordinate-location" "主題的座標方位，請注意目前僅支持WGS84座標系" "zh-tw")
(descr-as-in "coordinate-location" "Koordinaten eines sich auf der Erde befindlichen Objekts, momentan werden nur WGS84 basierte Koordinaten akzeptiert." "de")
(descr-as-in "coordinate-location" "географические координаты данного предмета" "ru")
(descr-as-in "coordinate-location" "coordenadas geográficas de la entidad" "es")
(descr-as-in "coordinate-location" "主語の座標" "ja")
(descr-as-in "coordinate-location" "主题的坐标方位，请注意目前仅支持WGS84坐标系" "zh-cn")
(descr-as-in "coordinate-location" "主题的坐标方位，请注意目前仅支持WGS84坐标系" "zh-sg")

