(ns properties.country_of_citizenship
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "country-of-citizenship")

(name-as-in "country-of-citizenship" "國籍" "zh-hk")
(name-as-in "country-of-citizenship" "país de nacionalidade" "pt")
(name-as-in "country-of-citizenship" "country of citizenship" "en")
(name-as-in "country-of-citizenship" "pays de nationalité" "fr")
(name-as-in "country-of-citizenship" "國籍" "zh-tw")
(name-as-in "country-of-citizenship" "Land der Staatsangehörigkeit" "de")
(name-as-in "country-of-citizenship" "гражданство" "ru")
(name-as-in "country-of-citizenship" "país de nacionalidad" "es")
(name-as-in "country-of-citizenship" "国籍" "ja")
(name-as-in "country-of-citizenship" "国籍" "zh-cn")
(name-as-in "country-of-citizenship" "国籍" "zh-sg")

(descr-as-in "country-of-citizenship" "" "zh-hk")
(descr-as-in "country-of-citizenship" "o objeto é um país que reconhece o sujeito como seu cidadão" "pt")
(descr-as-in "country-of-citizenship" "the object is a country that recognizes the subject as its citizen" "en")
(descr-as-in "country-of-citizenship" "État dont la personne possède la nationalité" "fr")
(descr-as-in "country-of-citizenship" "" "zh-tw")
(descr-as-in "country-of-citizenship" "Staat, der die Person als Staatsangehöriger anerkennt oder anerkannte" "de")
(descr-as-in "country-of-citizenship" "государство, признающее человека своим гражданином" "ru")
(descr-as-in "country-of-citizenship" "estado soberano del cual la persona es ciudadana" "es")
(descr-as-in "country-of-citizenship" "その人物を自国の市民として認めている国" "ja")
(descr-as-in "country-of-citizenship" "" "zh-cn")
(descr-as-in "country-of-citizenship" "" "zh-sg")

