(ns properties.cths_person_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "cths-person-id")

(name-as-in "cths-person-id" "" "zh-hk")
(name-as-in "cths-person-id" "" "pt")
(name-as-in "cths-person-id" "CTHS person ID" "en")
(name-as-in "cths-person-id" "identifiant Annuaire de la France savante" "fr")
(name-as-in "cths-person-id" "" "zh-tw")
(name-as-in "cths-person-id" "CTHS-Personen-ID" "de")
(name-as-in "cths-person-id" "код персоналии CTHS" "ru")
(name-as-in "cths-person-id" "identificador CTHS de persona" "es")
(name-as-in "cths-person-id" "" "ja")
(name-as-in "cths-person-id" "" "zh-cn")
(name-as-in "cths-person-id" "" "zh-sg")

(descr-as-in "cths-person-id" "" "zh-hk")
(descr-as-in "cths-person-id" "" "pt")
(descr-as-in "cths-person-id" "identifier for a person in the directory of French learned societies" "en")
(descr-as-in "cths-person-id" "identifiant de la personne dans l'Annuaire de la France savante XVIIe-XXe du CTHS" "fr")
(descr-as-in "cths-person-id" "" "zh-tw")
(descr-as-in "cths-person-id" "" "de")
(descr-as-in "cths-person-id" "l'Annuaire de la France savante XVIIe-XXe" "ru")
(descr-as-in "cths-person-id" "" "es")
(descr-as-in "cths-person-id" "" "ja")
(descr-as-in "cths-person-id" "" "zh-cn")
(descr-as-in "cths-person-id" "" "zh-sg")

