(ns properties.cultureel_woordenboek_identifier
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "cultureel-woordenboek-identifier")

(name-as-in "cultureel-woordenboek-identifier" "" "zh-hk")
(name-as-in "cultureel-woordenboek-identifier" "" "pt")
(name-as-in "cultureel-woordenboek-identifier" "Cultureel Woordenboek identifier" "en")
(name-as-in "cultureel-woordenboek-identifier" "identifiant Cultureel Woordenboek" "fr")
(name-as-in "cultureel-woordenboek-identifier" "" "zh-tw")
(name-as-in "cultureel-woordenboek-identifier" "Cultureel-Woordenboek-ID" "de")
(name-as-in "cultureel-woordenboek-identifier" "" "ru")
(name-as-in "cultureel-woordenboek-identifier" "identificador Cultureel Woordenboek" "es")
(name-as-in "cultureel-woordenboek-identifier" "" "ja")
(name-as-in "cultureel-woordenboek-identifier" "" "zh-cn")
(name-as-in "cultureel-woordenboek-identifier" "" "zh-sg")

(descr-as-in "cultureel-woordenboek-identifier" "" "zh-hk")
(descr-as-in "cultureel-woordenboek-identifier" "" "pt")
(descr-as-in "cultureel-woordenboek-identifier" "identifier for a concept in the Dutch Cultureel Woordenboek ('Cultural Dictionary')" "en")
(descr-as-in "cultureel-woordenboek-identifier" "identifiant d'un concept dans le dictionnaire culturel néerlandais (Cultureel Woordenboek)" "fr")
(descr-as-in "cultureel-woordenboek-identifier" "" "zh-tw")
(descr-as-in "cultureel-woordenboek-identifier" "" "de")
(descr-as-in "cultureel-woordenboek-identifier" "" "ru")
(descr-as-in "cultureel-woordenboek-identifier" "" "es")
(descr-as-in "cultureel-woordenboek-identifier" "" "ja")
(descr-as-in "cultureel-woordenboek-identifier" "" "zh-cn")
(descr-as-in "cultureel-woordenboek-identifier" "" "zh-sg")

