(ns properties.czech_neighbourhood_id_code
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "czech-neighbourhood-id-code")

(name-as-in "czech-neighbourhood-id-code" "" "zh-hk")
(name-as-in "czech-neighbourhood-id-code" "código de bairro da República Checa" "pt")
(name-as-in "czech-neighbourhood-id-code" "Czech neighbourhood ID code" "en")
(name-as-in "czech-neighbourhood-id-code" "identifiant de quartier tchèque" "fr")
(name-as-in "czech-neighbourhood-id-code" "" "zh-tw")
(name-as-in "czech-neighbourhood-id-code" "tschechische Ortsteil-ID" "de")
(name-as-in "czech-neighbourhood-id-code" "код чешского района" "ru")
(name-as-in "czech-neighbourhood-id-code" "identificador de vecindario checo" "es")
(name-as-in "czech-neighbourhood-id-code" "" "ja")
(name-as-in "czech-neighbourhood-id-code" "" "zh-cn")
(name-as-in "czech-neighbourhood-id-code" "" "zh-sg")

(descr-as-in "czech-neighbourhood-id-code" "" "zh-hk")
(descr-as-in "czech-neighbourhood-id-code" "código identificador de bairro situado na República Checa" "pt")
(descr-as-in "czech-neighbourhood-id-code" "identifier for a neighbourhood in the Czech Republic" "en")
(descr-as-in "czech-neighbourhood-id-code" "identifiant pour un quartier en République tchèque" "fr")
(descr-as-in "czech-neighbourhood-id-code" "" "zh-tw")
(descr-as-in "czech-neighbourhood-id-code" "Identifikator für einen Ortsteil in der Tschechischen Republik" "de")
(descr-as-in "czech-neighbourhood-id-code" "" "ru")
(descr-as-in "czech-neighbourhood-id-code" "" "es")
(descr-as-in "czech-neighbourhood-id-code" "" "ja")
(descr-as-in "czech-neighbourhood-id-code" "" "zh-cn")
(descr-as-in "czech-neighbourhood-id-code" "" "zh-sg")

