(ns properties.date_of_death
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "date-of-death")

(name-as-in "date-of-death" "死亡日期" "zh-hk")
(name-as-in "date-of-death" "data de morte" "pt")
(name-as-in "date-of-death" "date of death" "en")
(name-as-in "date-of-death" "date de décès" "fr")
(name-as-in "date-of-death" "死亡日期" "zh-tw")
(name-as-in "date-of-death" "Sterbedatum" "de")
(name-as-in "date-of-death" "дата смерти" "ru")
(name-as-in "date-of-death" "fecha de fallecimiento" "es")
(name-as-in "date-of-death" "没年月日" "ja")
(name-as-in "date-of-death" "死亡日期" "zh-cn")
(name-as-in "date-of-death" "死亡日期" "zh-sg")

(descr-as-in "date-of-death" "" "zh-hk")
(descr-as-in "date-of-death" "" "pt")
(descr-as-in "date-of-death" "date on which the subject died" "en")
(descr-as-in "date-of-death" "date à laquelle la personne est décédée" "fr")
(descr-as-in "date-of-death" "去世的時間" "zh-tw")
(descr-as-in "date-of-death" "Datum, an dem eine Person verstarb" "de")
(descr-as-in "date-of-death" "день, месяц, год, в который субъект умер" "ru")
(descr-as-in "date-of-death" "fecha en la cual falleció el sujeto" "es")
(descr-as-in "date-of-death" "その生物が死亡した日付" "ja")
(descr-as-in "date-of-death" "" "zh-cn")
(descr-as-in "date-of-death" "" "zh-sg")

