(ns properties.date_of_official_opening
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "date-of-official-opening")

(name-as-in "date-of-official-opening" "正式開放日期" "zh-hk")
(name-as-in "date-of-official-opening" "data de abertura oficial" "pt")
(name-as-in "date-of-official-opening" "date of official opening" "en")
(name-as-in "date-of-official-opening" "date d'ouverture officielle" "fr")
(name-as-in "date-of-official-opening" "正式開放日期" "zh-tw")
(name-as-in "date-of-official-opening" "Eröffnungsdatum" "de")
(name-as-in "date-of-official-opening" "дата официального открытия" "ru")
(name-as-in "date-of-official-opening" "fecha de inauguración oficial" "es")
(name-as-in "date-of-official-opening" "開設年月日" "ja")
(name-as-in "date-of-official-opening" "正式开放日期" "zh-cn")
(name-as-in "date-of-official-opening" "正式开放日期" "zh-sg")

(descr-as-in "date-of-official-opening" "" "zh-hk")
(descr-as-in "date-of-official-opening" "" "pt")
(descr-as-in "date-of-official-opening" "date or point in time an event, museum, theater etc. officially opened" "en")
(descr-as-in "date-of-official-opening" "date d'un évènement, d'un musée, d'un théatre, etc. officiellement ouvert" "fr")
(descr-as-in "date-of-official-opening" "" "zh-tw")
(descr-as-in "date-of-official-opening" "Datum der offiziellen Eröffnung" "de")
(descr-as-in "date-of-official-opening" "" "ru")
(descr-as-in "date-of-official-opening" "fecha o punto temporal en la que un evento, museo, teatro, etc. es oficialmente abierto" "es")
(descr-as-in "date-of-official-opening" "イベント、博物館、映画館などが公式にオープンした日付や時点" "ja")
(descr-as-in "date-of-official-opening" "" "zh-cn")
(descr-as-in "date-of-official-opening" "" "zh-sg")

