(ns properties.dbnl_author_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "dbnl-author-id")

(name-as-in "dbnl-author-id" "" "zh-hk")
(name-as-in "dbnl-author-id" "identificador DBNL" "pt")
(name-as-in "dbnl-author-id" "DBNL author ID" "en")
(name-as-in "dbnl-author-id" "identifiant DBNL" "fr")
(name-as-in "dbnl-author-id" "" "zh-tw")
(name-as-in "dbnl-author-id" "DBNL-ID" "de")
(name-as-in "dbnl-author-id" "код DBNL" "ru")
(name-as-in "dbnl-author-id" "identificador DBNL" "es")
(name-as-in "dbnl-author-id" "DBNL識別子" "ja")
(name-as-in "dbnl-author-id" "" "zh-cn")
(name-as-in "dbnl-author-id" "" "zh-sg")

(descr-as-in "dbnl-author-id" "" "zh-hk")
(descr-as-in "dbnl-author-id" "" "pt")
(descr-as-in "dbnl-author-id" "identifier for an author on the DBNL-website for Dutch language authors" "en")
(descr-as-in "dbnl-author-id" "" "fr")
(descr-as-in "dbnl-author-id" "" "zh-tw")
(descr-as-in "dbnl-author-id" "" "de")
(descr-as-in "dbnl-author-id" "" "ru")
(descr-as-in "dbnl-author-id" "www.dbnl.org" "es")
(descr-as-in "dbnl-author-id" "" "ja")
(descr-as-in "dbnl-author-id" "" "zh-cn")
(descr-as-in "dbnl-author-id" "" "zh-sg")

