(ns properties.deepest_point
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "deepest-point")

(name-as-in "deepest-point" "最深點" "zh-hk")
(name-as-in "deepest-point" "ponto mais baixo" "pt")
(name-as-in "deepest-point" "deepest point" "en")
(name-as-in "deepest-point" "point le plus bas" "fr")
(name-as-in "deepest-point" "最深點" "zh-tw")
(name-as-in "deepest-point" "tiefster Punkt" "de")
(name-as-in "deepest-point" "глубочайшая точка" "ru")
(name-as-in "deepest-point" "punto más bajo" "es")
(name-as-in "deepest-point" "最も低い地点" "ja")
(name-as-in "deepest-point" "最深点" "zh-cn")
(name-as-in "deepest-point" "最深点" "zh-sg")

(descr-as-in "deepest-point" "" "zh-hk")
(descr-as-in "deepest-point" "" "pt")
(descr-as-in "deepest-point" "point with lowest elevation in the country, region, city or area" "en")
(descr-as-in "deepest-point" "point le plus bas d'une unité géographique (pays, région, ville, …)" "fr")
(descr-as-in "deepest-point" "" "zh-tw")
(descr-as-in "deepest-point" "tiefster Punkt einer geographischen Einheit" "de")
(descr-as-in "deepest-point" "место с наименьшей вертикальной координатой (удалением от центра Земли)" "ru")
(descr-as-in "deepest-point" "punto con la elevación más baja" "es")
(descr-as-in "deepest-point" "国、地域、都市、地区で最も低い標高（海抜）である地点" "ja")
(descr-as-in "deepest-point" "" "zh-cn")
(descr-as-in "deepest-point" "" "zh-sg")

