(ns properties.described_at_url
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "described-at-url")

(name-as-in "described-at-url" "" "zh-hk")
(name-as-in "described-at-url" "descrito na URL" "pt")
(name-as-in "described-at-url" "described at URL" "en")
(name-as-in "described-at-url" "décrit à l'URL" "fr")
(name-as-in "described-at-url" "" "zh-tw")
(name-as-in "described-at-url" "wird beschrieben in URL" "de")
(name-as-in "described-at-url" "описан на сайте" "ru")
(name-as-in "described-at-url" "descrito en la URL" "es")
(name-as-in "described-at-url" "詳細情報URL" "ja")
(name-as-in "described-at-url" "" "zh-cn")
(name-as-in "described-at-url" "" "zh-sg")

(descr-as-in "described-at-url" "" "zh-hk")
(descr-as-in "described-at-url" "" "pt")
(descr-as-in "described-at-url" "item is described at the following URL" "en")
(descr-as-in "described-at-url" "l'élément est décrit à l'URL suivante" "fr")
(descr-as-in "described-at-url" "" "zh-tw")
(descr-as-in "described-at-url" "das Element wird in der angegebenen URL beschrieben" "de")
(descr-as-in "described-at-url" "описание этого элемента расположено по адресу" "ru")
(descr-as-in "described-at-url" "el elemento se describe en la siguiente dirección URL" "es")
(descr-as-in "described-at-url" "項目は次のURLで詳述されている" "ja")
(descr-as-in "described-at-url" "" "zh-cn")
(descr-as-in "described-at-url" "" "zh-sg")

