(ns properties.destroyed
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "destroyed")

(name-as-in "destroyed" "" "zh-hk")
(name-as-in "destroyed" "destruído" "pt")
(name-as-in "destroyed" "destroyed" "en")
(name-as-in "destroyed" "a détruit" "fr")
(name-as-in "destroyed" "" "zh-tw")
(name-as-in "destroyed" "zerstört" "de")
(name-as-in "destroyed" "уничтожено" "ru")
(name-as-in "destroyed" "ha destruido" "es")
(name-as-in "destroyed" "" "ja")
(name-as-in "destroyed" "" "zh-cn")
(name-as-in "destroyed" "" "zh-sg")

(descr-as-in "destroyed" "" "zh-hk")
(descr-as-in "destroyed" "" "pt")
(descr-as-in "destroyed" "physical items destroyed by this event" "en")
(descr-as-in "destroyed" "ce que l'événement a détruit" "fr")
(descr-as-in "destroyed" "" "zh-tw")
(descr-as-in "destroyed" "" "de")
(descr-as-in "destroyed" "физический объект, уничтоженный во время некоторого события" "ru")
(descr-as-in "destroyed" "objeto físico destruido por este evento" "es")
(descr-as-in "destroyed" "" "ja")
(descr-as-in "destroyed" "" "zh-cn")
(descr-as-in "destroyed" "" "zh-sg")

