(ns properties.different_from
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "different-from")

(name-as-in "different-from" "相異物" "zh-hk")
(name-as-in "different-from" "diferente de" "pt")
(name-as-in "different-from" "different from" "en")
(name-as-in "different-from" "à ne pas confondre avec" "fr")
(name-as-in "different-from" "相異物" "zh-tw")
(name-as-in "different-from" "verschieden von" "de")
(name-as-in "different-from" "не путать с" "ru")
(name-as-in "different-from" "diferente de" "es")
(name-as-in "different-from" "以下と異なる" "ja")
(name-as-in "different-from" "相异物" "zh-cn")
(name-as-in "different-from" "相异物" "zh-sg")

(descr-as-in "different-from" "容易混淆但不相同的事物" "zh-hk")
(descr-as-in "different-from" "elemento similar frequentemente confundido com outro" "pt")
(descr-as-in "different-from" "item that is different from another item, but they are often confused" "en")
(descr-as-in "different-from" "élément différent d'un autre élément mais qui sont souvent confondus" "fr")
(descr-as-in "different-from" "容易混淆但不相同的事物" "zh-tw")
(descr-as-in "different-from" "Objekt das sich von einem anderen Objekt unterscheidet, die aber oft verwechselt werden" "de")
(descr-as-in "different-from" "ссылка на элемент с другим смыслом, но который часто путается с этим" "ru")
(descr-as-in "different-from" "elemento que es diferente de otro elemento, pero que son confundidos a menudo" "es")
(descr-as-in "different-from" "この項目とは異なるが、混同されることが多い項目" "ja")
(descr-as-in "different-from" "容易混淆但不相同的事物" "zh-cn")
(descr-as-in "different-from" "容易混淆但不相同的事物" "zh-sg")

