(ns properties.discoverer_or_inventor
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "discoverer-or-inventor")

(name-as-in "discoverer-or-inventor" "發現者或發明者" "zh-hk")
(name-as-in "discoverer-or-inventor" "descoberto/inventado por" "pt")
(name-as-in "discoverer-or-inventor" "discoverer or inventor" "en")
(name-as-in "discoverer-or-inventor" "découvreur ou inventeur" "fr")
(name-as-in "discoverer-or-inventor" "發現者或發明者" "zh-tw")
(name-as-in "discoverer-or-inventor" "Entdecker oder Erfinder" "de")
(name-as-in "discoverer-or-inventor" "первооткрыватель или изобретатель" "ru")
(name-as-in "discoverer-or-inventor" "descubridor o inventor" "es")
(name-as-in "discoverer-or-inventor" "発見者または発明者" "ja")
(name-as-in "discoverer-or-inventor" "发现者或发明者" "zh-cn")
(name-as-in "discoverer-or-inventor" "发现者或发明者" "zh-sg")

(descr-as-in "discoverer-or-inventor" "首次發現或發明此項的人" "zh-hk")
(descr-as-in "discoverer-or-inventor" "o objeto foi descoberto/inventado por" "pt")
(descr-as-in "discoverer-or-inventor" "discovered, first described, or invented by" "en")
(descr-as-in "discoverer-or-inventor" "découvert ou inventé par" "fr")
(descr-as-in "discoverer-or-inventor" "首次發現或發明此項的人" "zh-tw")
(descr-as-in "discoverer-or-inventor" "Name des Entdeckers oder Erfinders" "de")
(descr-as-in "discoverer-or-inventor" "кем открыт или изобретён этот элемент" "ru")
(descr-as-in "discoverer-or-inventor" "descubierto o inventado por" "es")
(descr-as-in "discoverer-or-inventor" "その項目を発見または発明した人物や団体" "ja")
(descr-as-in "discoverer-or-inventor" "首次发现或发明此项的人" "zh-cn")
(descr-as-in "discoverer-or-inventor" "首次发现或发明此项的人" "zh-sg")

