(ns properties.discogs_artist_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "discogs-artist-id")

(name-as-in "discogs-artist-id" "" "zh-hk")
(name-as-in "discogs-artist-id" "identificador de artista Discogs" "pt")
(name-as-in "discogs-artist-id" "Discogs artist ID" "en")
(name-as-in "discogs-artist-id" "identifiant Discogs d’un artiste" "fr")
(name-as-in "discogs-artist-id" "" "zh-tw")
(name-as-in "discogs-artist-id" "Discogs-Künstler-ID" "de")
(name-as-in "discogs-artist-id" "код исполнителя Discogs" "ru")
(name-as-in "discogs-artist-id" "identificador Discogs de artista" "es")
(name-as-in "discogs-artist-id" "Discogs artist ID" "ja")
(name-as-in "discogs-artist-id" "" "zh-cn")
(name-as-in "discogs-artist-id" "" "zh-sg")

(descr-as-in "discogs-artist-id" "" "zh-hk")
(descr-as-in "discogs-artist-id" "identificador para uma banda ou pessoa na base de dados do Discogs" "pt")
(descr-as-in "discogs-artist-id" "identifier for a band or person in the Discogs database" "en")
(descr-as-in "discogs-artist-id" "identifiant d’un artiste ou groupe dans la base de données Discogs" "fr")
(descr-as-in "discogs-artist-id" "" "zh-tw")
(descr-as-in "discogs-artist-id" "Identifikationsnummer eines Künstlers in der Discogs-Datenbank" "de")
(descr-as-in "discogs-artist-id" "код исполнителя в базе Discogs" "ru")
(descr-as-in "discogs-artist-id" "identificador de una banda musical o cantante en la base de datos Discogs" "es")
(descr-as-in "discogs-artist-id" "" "ja")
(descr-as-in "discogs-artist-id" "" "zh-cn")
(descr-as-in "discogs-artist-id" "" "zh-sg")

