(ns properties.disease_ontology_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "disease-ontology-id")

(name-as-in "disease-ontology-id" "" "zh-hk")
(name-as-in "disease-ontology-id" "identificador Disease Ontology" "pt")
(name-as-in "disease-ontology-id" "Disease Ontology ID" "en")
(name-as-in "disease-ontology-id" "identifiant de Disease Ontology" "fr")
(name-as-in "disease-ontology-id" "" "zh-tw")
(name-as-in "disease-ontology-id" "Disease-Ontology-ID" "de")
(name-as-in "disease-ontology-id" "код Disease Ontology" "ru")
(name-as-in "disease-ontology-id" "identificador Ontología de enfermedades" "es")
(name-as-in "disease-ontology-id" "Disease Ontology ID" "ja")
(name-as-in "disease-ontology-id" "" "zh-cn")
(name-as-in "disease-ontology-id" "" "zh-sg")

(descr-as-in "disease-ontology-id" "" "zh-hk")
(descr-as-in "disease-ontology-id" "" "pt")
(descr-as-in "disease-ontology-id" "identifier in the Disease Ontology database" "en")
(descr-as-in "disease-ontology-id" "ID dans la base de données de DiseaseOntology.org" "fr")
(descr-as-in "disease-ontology-id" "" "zh-tw")
(descr-as-in "disease-ontology-id" "Kennung in der Disease-Ontology-Datenbank" "de")
(descr-as-in "disease-ontology-id" "" "ru")
(descr-as-in "disease-ontology-id" "identificador en la base de datos Disease Ontology" "es")
(descr-as-in "disease-ontology-id" "Disease OntologyデータベースのID" "ja")
(descr-as-in "disease-ontology-id" "" "zh-cn")
(descr-as-in "disease-ontology-id" "" "zh-sg")

