(ns properties.diseasesdb
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "diseasesdb")

(name-as-in "diseasesdb" "" "zh-hk")
(name-as-in "diseasesdb" "DiseasesDB" "pt")
(name-as-in "diseasesdb" "DiseasesDB" "en")
(name-as-in "diseasesdb" "DiseasesDB" "fr")
(name-as-in "diseasesdb" "" "zh-tw")
(name-as-in "diseasesdb" "DiseasesDB-ID" "de")
(name-as-in "diseasesdb" "DiseasesDB" "ru")
(name-as-in "diseasesdb" "DiseasesDB" "es")
(name-as-in "diseasesdb" "DiseasesDB" "ja")
(name-as-in "diseasesdb" "" "zh-cn")
(name-as-in "diseasesdb" "" "zh-sg")

(descr-as-in "diseasesdb" "" "zh-hk")
(descr-as-in "diseasesdb" "" "pt")
(descr-as-in "diseasesdb" "identifier sourced on the Diseases Database" "en")
(descr-as-in "diseasesdb" "identifiant Diseases Database" "fr")
(descr-as-in "diseasesdb" "" "zh-tw")
(descr-as-in "diseasesdb" "Kennung in der Diseases Database (diseasesdatabase.com)" "de")
(descr-as-in "diseasesdb" "" "ru")
(descr-as-in "diseasesdb" "identificador en la base de datos DiseasesDB" "es")
(descr-as-in "diseasesdb" "Diseases Database 上の識別子" "ja")
(descr-as-in "diseasesdb" "" "zh-cn")
(descr-as-in "diseasesdb" "" "zh-sg")

