(ns properties.dissolved_abolished_or_demolished
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "dissolved-abolished-or-demolished")

(name-as-in "dissolved-abolished-or-demolished" "解散或廢除時間" "zh-hk")
(name-as-in "dissolved-abolished-or-demolished" "data de dissolução ou encerramento" "pt")
(name-as-in "dissolved-abolished-or-demolished" "dissolved, abolished or demolished" "en")
(name-as-in "dissolved-abolished-or-demolished" "date de dissolution" "fr")
(name-as-in "dissolved-abolished-or-demolished" "解散或廢除時間" "zh-tw")
(name-as-in "dissolved-abolished-or-demolished" "Auflösungsdatum" "de")
(name-as-in "dissolved-abolished-or-demolished" "дата прекращения существования" "ru")
(name-as-in "dissolved-abolished-or-demolished" "fecha de disolución" "es")
(name-as-in "dissolved-abolished-or-demolished" "解散日" "ja")
(name-as-in "dissolved-abolished-or-demolished" "解散或废除时间" "zh-cn")
(name-as-in "dissolved-abolished-or-demolished" "解散或废除时间" "zh-sg")

(descr-as-in "dissolved-abolished-or-demolished" "" "zh-hk")
(descr-as-in "dissolved-abolished-or-demolished" "data em que o item foi dissolvido/encerrou" "pt")
(descr-as-in "dissolved-abolished-or-demolished" "date or point in time on which an organisation was dissolved/disappeared or a building demolished; see also discontinued date (P2669)" "en")
(descr-as-in "dissolved-abolished-or-demolished" "date à laquelle l'organisation a été dissoute/a disparu ou le bâtiment démoli" "fr")
(descr-as-in "dissolved-abolished-or-demolished" "" "zh-tw")
(descr-as-in "dissolved-abolished-or-demolished" "Datum, an dem eine Organisation aufgelöst bzw. ein Bauwerk zerstört wurde" "de")
(descr-as-in "dissolved-abolished-or-demolished" "дата, когда сущность перестала существовать" "ru")
(descr-as-in "dissolved-abolished-or-demolished" "fecha en la cual fue disuelta la organización" "es")
(descr-as-in "dissolved-abolished-or-demolished" "組織が解散した日時" "ja")
(descr-as-in "dissolved-abolished-or-demolished" "" "zh-cn")
(descr-as-in "dissolved-abolished-or-demolished" "" "zh-sg")

