(ns properties.dmoz_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "dmoz-id")

(name-as-in "dmoz-id" "dmoz" "zh-hk")
(name-as-in "dmoz-id" "dmoz" "pt")
(name-as-in "dmoz-id" "DMOZ ID" "en")
(name-as-in "dmoz-id" "dmoz" "fr")
(name-as-in "dmoz-id" "dmoz" "zh-tw")
(name-as-in "dmoz-id" "dmoz" "de")
(name-as-in "dmoz-id" "dmoz" "ru")
(name-as-in "dmoz-id" "identificador dmoz" "es")
(name-as-in "dmoz-id" "dmoz" "ja")
(name-as-in "dmoz-id" "" "zh-cn")
(name-as-in "dmoz-id" "" "zh-sg")

(descr-as-in "dmoz-id" "" "zh-hk")
(descr-as-in "dmoz-id" "" "pt")
(descr-as-in "dmoz-id" "category path at Open Directory Project" "en")
(descr-as-in "dmoz-id" "localisation dans le répertoire dmoz (projet  de recensement sites internet libres)" "fr")
(descr-as-in "dmoz-id" "" "zh-tw")
(descr-as-in "dmoz-id" "Open Directory Project" "de")
(descr-as-in "dmoz-id" "Open Directory Project" "ru")
(descr-as-in "dmoz-id" "localización en el Open Directory Project (índice de sitios web gratuitos)" "es")
(descr-as-in "dmoz-id" "Open Directory Project" "ja")
(descr-as-in "dmoz-id" "" "zh-cn")
(descr-as-in "dmoz-id" "" "zh-sg")

