(ns properties.doctoral_advisor
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "doctoral-advisor")

(name-as-in "doctoral-advisor" "博士生導師" "zh-hk")
(name-as-in "doctoral-advisor" "orientador de doutorado" "pt")
(name-as-in "doctoral-advisor" "doctoral advisor" "en")
(name-as-in "doctoral-advisor" "directeur de thèse" "fr")
(name-as-in "doctoral-advisor" "博士生導師" "zh-tw")
(name-as-in "doctoral-advisor" "Promotionsbetreuer" "de")
(name-as-in "doctoral-advisor" "научный руководитель" "ru")
(name-as-in "doctoral-advisor" "supervisor doctoral" "es")
(name-as-in "doctoral-advisor" "博士論文指導教授" "ja")
(name-as-in "doctoral-advisor" "博士生导师" "zh-cn")
(name-as-in "doctoral-advisor" "博士生导师" "zh-sg")

(descr-as-in "doctoral-advisor" "指導本項博士論文的人" "zh-hk")
(descr-as-in "doctoral-advisor" "" "pt")
(descr-as-in "doctoral-advisor" "person who supervised the doctorate or PhD thesis of the subject" "en")
(descr-as-in "doctoral-advisor" "personne ayant dirigé les études doctorales du sujet" "fr")
(descr-as-in "doctoral-advisor" "指導本項博士論文的人" "zh-tw")
(descr-as-in "doctoral-advisor" "Betreuer der Doktorarbeit bzw. Gutachter der Habilitation" "de")
(descr-as-in "doctoral-advisor" "человек, курировавший подготовку диссертации персоны" "ru")
(descr-as-in "doctoral-advisor" "persona que supervisó la tesis del sujeto" "es")
(descr-as-in "doctoral-advisor" "主題人物の博士論文の指導をした人物。それ以外の師弟関係についてはP1066を使用" "ja")
(descr-as-in "doctoral-advisor" "指导本项博士论文的人" "zh-cn")
(descr-as-in "doctoral-advisor" "指导本项博士论文的人" "zh-sg")

