(ns properties.doctoral_student
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "doctoral-student")

(name-as-in "doctoral-student" "" "zh-hk")
(name-as-in "doctoral-student" "doutorando" "pt")
(name-as-in "doctoral-student" "doctoral student" "en")
(name-as-in "doctoral-student" "étudiant de thèse" "fr")
(name-as-in "doctoral-student" "博士班學生" "zh-tw")
(name-as-in "doctoral-student" "Doktorand" "de")
(name-as-in "doctoral-student" "аспиранты" "ru")
(name-as-in "doctoral-student" "doctorando" "es")
(name-as-in "doctoral-student" "博士課程指導学生" "ja")
(name-as-in "doctoral-student" "" "zh-cn")
(name-as-in "doctoral-student" "" "zh-sg")

(descr-as-in "doctoral-student" "" "zh-hk")
(descr-as-in "doctoral-student" "" "pt")
(descr-as-in "doctoral-student" "doctoral student(s) of a professor" "en")
(descr-as-in "doctoral-student" "doctorant(s) supervisé(s) par le sujet" "fr")
(descr-as-in "doctoral-student" "" "zh-tw")
(descr-as-in "doctoral-student" "Person, die unter dem Doktorvater eine Promotion anstrebt(e)" "de")
(descr-as-in "doctoral-student" "список учёных, писавших диссертацию под руководством данной персоны" "ru")
(descr-as-in "doctoral-student" "estudiante doctoral" "es")
(descr-as-in "doctoral-student" "主題人物が博士課程を指導した人物。それ以外の師弟関係についてはP802を使用" "ja")
(descr-as-in "doctoral-student" "" "zh-cn")
(descr-as-in "doctoral-student" "" "zh-sg")

