(ns properties.doi
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "doi")

(name-as-in "doi" "" "zh-hk")
(name-as-in "doi" "DOI" "pt")
(name-as-in "doi" "DOI" "en")
(name-as-in "doi" "DOI" "fr")
(name-as-in "doi" "數位物件識別碼" "zh-tw")
(name-as-in "doi" "DOI" "de")
(name-as-in "doi" "DOI" "ru")
(name-as-in "doi" "DOI" "es")
(name-as-in "doi" "DOI" "ja")
(name-as-in "doi" "" "zh-cn")
(name-as-in "doi" "" "zh-sg")

(descr-as-in "doi" "" "zh-hk")
(descr-as-in "doi" "Digital Object Identifier" "pt")
(descr-as-in "doi" "serial code used to uniquely identify digital objects like academic papers" "en")
(descr-as-in "doi" "identifiant numérique pour objets physiques, numériques ou abstraits (notamment les articles scientifiques)" "fr")
(descr-as-in "doi" "" "zh-tw")
(descr-as-in "doi" "digitaler Identifikator für physische, digitale oder abstrakte Objekte" "de")
(descr-as-in "doi" "цифровой идентификатор физического, цифрового или абстрактного объекта" "ru")
(descr-as-in "doi" "Digital Object Identifier del elemento" "es")
(descr-as-in "doi" "デジタル・オブジェクト識別子" "ja")
(descr-as-in "doi" "" "zh-cn")
(descr-as-in "doi" "" "zh-sg")

