(ns properties.doi_prefix
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "doi-prefix")

(name-as-in "doi-prefix" "" "zh-hk")
(name-as-in "doi-prefix" "prefixo DOI" "pt")
(name-as-in "doi-prefix" "DOI prefix" "en")
(name-as-in "doi-prefix" "Préfixe DOI" "fr")
(name-as-in "doi-prefix" "" "zh-tw")
(name-as-in "doi-prefix" "DOI-Präfix" "de")
(name-as-in "doi-prefix" "префикс DOI" "ru")
(name-as-in "doi-prefix" "prefijo DOI" "es")
(name-as-in "doi-prefix" "" "ja")
(name-as-in "doi-prefix" "" "zh-cn")
(name-as-in "doi-prefix" "" "zh-sg")

(descr-as-in "doi-prefix" "" "zh-hk")
(descr-as-in "doi-prefix" "" "pt")
(descr-as-in "doi-prefix" "identifier specific to a DOI registrant" "en")
(descr-as-in "doi-prefix" "identifiant d'une entité émettant des DOIs" "fr")
(descr-as-in "doi-prefix" "" "zh-tw")
(descr-as-in "doi-prefix" "" "de")
(descr-as-in "doi-prefix" "уникальный идентификатор для регистратора идентификаторов цифровых объектов" "ru")
(descr-as-in "doi-prefix" "identificador específico a un registro DOI" "es")
(descr-as-in "doi-prefix" "" "ja")
(descr-as-in "doi-prefix" "" "zh-cn")
(descr-as-in "doi-prefix" "" "zh-sg")

