(ns properties.dpla_subject_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "dpla-subject-id")

(name-as-in "dpla-subject-id" "" "zh-hk")
(name-as-in "dpla-subject-id" "" "pt")
(name-as-in "dpla-subject-id" "DPLA subject ID" "en")
(name-as-in "dpla-subject-id" "identifiant Digital Public Library of America d'un sujet" "fr")
(name-as-in "dpla-subject-id" "" "zh-tw")
(name-as-in "dpla-subject-id" "" "de")
(name-as-in "dpla-subject-id" "" "ru")
(name-as-in "dpla-subject-id" "identificador Biblioteca Digital Pública de Estados Unidos de tema" "es")
(name-as-in "dpla-subject-id" "" "ja")
(name-as-in "dpla-subject-id" "" "zh-cn")
(name-as-in "dpla-subject-id" "" "zh-sg")

(descr-as-in "dpla-subject-id" "" "zh-hk")
(descr-as-in "dpla-subject-id" "" "pt")
(descr-as-in "dpla-subject-id" "identifier  for a subject area in the Digital Public Library of America" "en")
(descr-as-in "dpla-subject-id" "identifiant pour un domaine dans le Digital Public Library of America" "fr")
(descr-as-in "dpla-subject-id" "" "zh-tw")
(descr-as-in "dpla-subject-id" "" "de")
(descr-as-in "dpla-subject-id" "" "ru")
(descr-as-in "dpla-subject-id" "" "es")
(descr-as-in "dpla-subject-id" "" "ja")
(descr-as-in "dpla-subject-id" "" "zh-cn")
(descr-as-in "dpla-subject-id" "" "zh-sg")

