(ns properties.driving_side
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "driving-side")

(name-as-in "driving-side" "道路通行方向" "zh-hk")
(name-as-in "driving-side" "direção da condução" "pt")
(name-as-in "driving-side" "driving side" "en")
(name-as-in "driving-side" "conduite à" "fr")
(name-as-in "driving-side" "道路通行方向" "zh-tw")
(name-as-in "driving-side" "Fahrseite" "de")
(name-as-in "driving-side" "сторона автомобильного движения" "ru")
(name-as-in "driving-side" "se conduce en la" "es")
(name-as-in "driving-side" "交通方法" "ja")
(name-as-in "driving-side" "道路通行方向" "zh-cn")
(name-as-in "driving-side" "道路通行方向" "zh-sg")

(descr-as-in "driving-side" "" "zh-hk")
(descr-as-in "driving-side" "em que lado os veículos dirigem em determinado país" "pt")
(descr-as-in "driving-side" "side of the road that vehicles drive on in a given jurisdiction" "en")
(descr-as-in "driving-side" "côté de conduite automobile dans un pays donné" "fr")
(descr-as-in "driving-side" "" "zh-tw")
(descr-as-in "driving-side" "links (Q14565198) oder rechts (Q14565199)" "de")
(descr-as-in "driving-side" "" "ru")
(descr-as-in "driving-side" "dirección en que los vehículos se conducen en determinado país" "es")
(descr-as-in "driving-side" "左側通行は「左」、右側通行は「右」" "ja")
(descr-as-in "driving-side" "" "zh-cn")
(descr-as-in "driving-side" "" "zh-sg")

