(ns properties.edition_number
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "edition-number")

(name-as-in "edition-number" "版次" "zh-hk")
(name-as-in "edition-number" "número de edição" "pt")
(name-as-in "edition-number" "edition number" "en")
(name-as-in "edition-number" "numéro d'édition" "fr")
(name-as-in "edition-number" "版次" "zh-tw")
(name-as-in "edition-number" "Auflage" "de")
(name-as-in "edition-number" "номер издания" "ru")
(name-as-in "edition-number" "número de edición" "es")
(name-as-in "edition-number" "版数" "ja")
(name-as-in "edition-number" "版次" "zh-cn")
(name-as-in "edition-number" "版次" "zh-sg")

(descr-as-in "edition-number" "" "zh-hk")
(descr-as-in "edition-number" "número da edição" "pt")
(descr-as-in "edition-number" "number of edition (first, second,... as 1, 2 ...) for a book or event" "en")
(descr-as-in "edition-number" "numéro d'édition pour un livre ou un événement" "fr")
(descr-as-in "edition-number" "" "zh-tw")
(descr-as-in "edition-number" "Nummer oder Bezeichnung der Auflage einer Publikation; auch Auflage einer Veranstaltung" "de")
(descr-as-in "edition-number" "число, определяющее порядок издания" "ru")
(descr-as-in "edition-number" "número de edición" "es")
(descr-as-in "edition-number" "書籍などの初版、第2版…といった版数、イベントの第1回、第2回といった回数" "ja")
(descr-as-in "edition-number" "" "zh-cn")
(descr-as-in "edition-number" "" "zh-sg")

