(ns properties.educated_at
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "educated-at")

(name-as-in "educated-at" "就讀學校" "zh-hk")
(name-as-in "educated-at" "alma mater" "pt")
(name-as-in "educated-at" "educated at" "en")
(name-as-in "educated-at" "scolarité" "fr")
(name-as-in "educated-at" "就讀學校" "zh-tw")
(name-as-in "educated-at" "besuchte Bildungseinrichtung" "de")
(name-as-in "educated-at" "учебное заведение" "ru")
(name-as-in "educated-at" "educado en" "es")
(name-as-in "educated-at" "出身校" "ja")
(name-as-in "educated-at" "就读学校" "zh-cn")
(name-as-in "educated-at" "就读学校" "zh-sg")

(descr-as-in "educated-at" "" "zh-hk")
(descr-as-in "educated-at" "estabelecimento educacional frequentado" "pt")
(descr-as-in "educated-at" "educational institution attended by the subject" "en")
(descr-as-in "educated-at" "établissement éducatif fréquenté" "fr")
(descr-as-in "educated-at" "" "zh-tw")
(descr-as-in "educated-at" "von der Person besuchte Bildungseinrichtung" "de")
(descr-as-in "educated-at" "учебное заведение, в котором учился человек" "ru")
(descr-as-in "educated-at" "instituciones educativas en las que estudió" "es")
(descr-as-in "educated-at" "主題人物が学んだ教育機関" "ja")
(descr-as-in "educated-at" "" "zh-cn")
(descr-as-in "educated-at" "" "zh-sg")

