(ns properties.egaxa_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "egaxa-id")

(name-as-in "egaxa-id" "" "zh-hk")
(name-as-in "egaxa-id" "identificador EGAXA" "pt")
(name-as-in "egaxa-id" "EGAXA ID" "en")
(name-as-in "egaxa-id" "identifiant EGAXA" "fr")
(name-as-in "egaxa-id" "" "zh-tw")
(name-as-in "egaxa-id" "EGAXA" "de")
(name-as-in "egaxa-id" "код EGAXA" "ru")
(name-as-in "egaxa-id" "identificador EGAXA" "es")
(name-as-in "egaxa-id" "EGAXA識別子" "ja")
(name-as-in "egaxa-id" "" "zh-cn")
(name-as-in "egaxa-id" "" "zh-sg")

(descr-as-in "egaxa-id" "" "zh-hk")
(descr-as-in "egaxa-id" "" "pt")
(descr-as-in "egaxa-id" "identifier in Bibliotheca Alexandrina" "en")
(descr-as-in "egaxa-id" "identifiant de la Bibliotheca Alexandrina" "fr")
(descr-as-in "egaxa-id" "" "zh-tw")
(descr-as-in "egaxa-id" "Normdateneintrag der Bibliotheca Alexandrina" "de")
(descr-as-in "egaxa-id" "" "ru")
(descr-as-in "egaxa-id" "identificador de la Bibliotheca Alexandrina" "es")
(descr-as-in "egaxa-id" "" "ja")
(descr-as-in "egaxa-id" "" "zh-cn")
(descr-as-in "egaxa-id" "" "zh-sg")

