(ns properties.electrical_plug_type
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "electrical-plug-type")

(name-as-in "electrical-plug-type" "電源插頭型式" "zh-hk")
(name-as-in "electrical-plug-type" "tipo de tomada elétrica" "pt")
(name-as-in "electrical-plug-type" "electrical plug type" "en")
(name-as-in "electrical-plug-type" "prise électrique" "fr")
(name-as-in "electrical-plug-type" "電源插頭型式" "zh-tw")
(name-as-in "electrical-plug-type" "Stecker-Typ" "de")
(name-as-in "electrical-plug-type" "тип электрического разъёма" "ru")
(name-as-in "electrical-plug-type" "tipo de tomacorriente" "es")
(name-as-in "electrical-plug-type" "" "ja")
(name-as-in "electrical-plug-type" "电源插头形式" "zh-cn")
(name-as-in "electrical-plug-type" "电源插头形式" "zh-sg")

(descr-as-in "electrical-plug-type" "" "zh-hk")
(descr-as-in "electrical-plug-type" "" "pt")
(descr-as-in "electrical-plug-type" "standard plug type for mains electricity in a country" "en")
(descr-as-in "electrical-plug-type" "" "fr")
(descr-as-in "electrical-plug-type" "" "zh-tw")
(descr-as-in "electrical-plug-type" "Typ des Steckers, der für elektrische Anschlüsse in einem Land verwendet wird" "de")
(descr-as-in "electrical-plug-type" "" "ru")
(descr-as-in "electrical-plug-type" "" "es")
(descr-as-in "electrical-plug-type" "" "ja")
(descr-as-in "electrical-plug-type" "" "zh-cn")
(descr-as-in "electrical-plug-type" "" "zh-sg")

