(ns properties.elevation_above_sea_level
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "elevation-above-sea-level")

(name-as-in "elevation-above-sea-level" "海拔" "zh-hk")
(name-as-in "elevation-above-sea-level" "altitude" "pt")
(name-as-in "elevation-above-sea-level" "elevation above sea level" "en")
(name-as-in "elevation-above-sea-level" "altitude" "fr")
(name-as-in "elevation-above-sea-level" "海拔" "zh-tw")
(name-as-in "elevation-above-sea-level" "Höhe über dem Meeresspiegel" "de")
(name-as-in "elevation-above-sea-level" "высота над уровнем моря" "ru")
(name-as-in "elevation-above-sea-level" "elevación sobre el nivel del mar" "es")
(name-as-in "elevation-above-sea-level" "標高" "ja")
(name-as-in "elevation-above-sea-level" "海拔" "zh-cn")
(name-as-in "elevation-above-sea-level" "海拔" "zh-sg")

(descr-as-in "elevation-above-sea-level" "" "zh-hk")
(descr-as-in "elevation-above-sea-level" "elevação em relação ao nível do mar" "pt")
(descr-as-in "elevation-above-sea-level" "height of the item (geographical object) as measured relative to sea level" "en")
(descr-as-in "elevation-above-sea-level" "élévation au-dessus du niveau des mers" "fr")
(descr-as-in "elevation-above-sea-level" "" "zh-tw")
(descr-as-in "elevation-above-sea-level" "Höhe eines geografischen oder technischen Objektes über dem mittleren Meeresspiegel" "de")
(descr-as-in "elevation-above-sea-level" "высота объекта, измеряемая от уровня воды" "ru")
(descr-as-in "elevation-above-sea-level" "altura del elemento en relación al nivel del mar" "es")
(descr-as-in "elevation-above-sea-level" "海水面を基準に測られる項目の高さ" "ja")
(descr-as-in "elevation-above-sea-level" "" "zh-cn")
(descr-as-in "elevation-above-sea-level" "" "zh-sg")

