(ns properties.emedicine
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "emedicine")

(name-as-in "emedicine" "" "zh-hk")
(name-as-in "emedicine" "eMedicine" "pt")
(name-as-in "emedicine" "eMedicine" "en")
(name-as-in "emedicine" "eMedicine" "fr")
(name-as-in "emedicine" "" "zh-tw")
(name-as-in "emedicine" "eMedicine" "de")
(name-as-in "emedicine" "eMedicine" "ru")
(name-as-in "emedicine" "eMedicine" "es")
(name-as-in "emedicine" "eMedicine" "ja")
(name-as-in "emedicine" "" "zh-cn")
(name-as-in "emedicine" "" "zh-sg")

(descr-as-in "emedicine" "" "zh-hk")
(descr-as-in "emedicine" "" "pt")
(descr-as-in "emedicine" "online clinical medical knowledge base" "en")
(descr-as-in "emedicine" "" "fr")
(descr-as-in "emedicine" "" "zh-tw")
(descr-as-in "emedicine" "" "de")
(descr-as-in "emedicine" "идентификатор в онлайн-базе данных клинической медицины" "ru")
(descr-as-in "emedicine" "identificador en la base de datos eMedicine" "es")
(descr-as-in "emedicine" "オンライン臨床医学知識ベース" "ja")
(descr-as-in "emedicine" "" "zh-cn")
(descr-as-in "emedicine" "" "zh-sg")

