(ns properties.employer
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "employer")

(name-as-in "employer" "僱主" "zh-hk")
(name-as-in "employer" "empregador" "pt")
(name-as-in "employer" "employer" "en")
(name-as-in "employer" "employeur" "fr")
(name-as-in "employer" "僱主" "zh-tw")
(name-as-in "employer" "Arbeitgeber" "de")
(name-as-in "employer" "работодатель" "ru")
(name-as-in "employer" "empleador" "es")
(name-as-in "employer" "勤務先" "ja")
(name-as-in "employer" "雇主" "zh-cn")
(name-as-in "employer" "雇主" "zh-sg")

(descr-as-in "employer" "" "zh-hk")
(descr-as-in "employer" "organização para qual o sujeito trabalha ou trabalhou" "pt")
(descr-as-in "employer" "person or organization for which the subject works or worked" "en")
(descr-as-in "employer" "organisation pour laquelle le sujet travaille ou a travaillé" "fr")
(descr-as-in "employer" "" "zh-tw")
(descr-as-in "employer" "früherer oder aktueller Arbeitgeber einer Person" "de")
(descr-as-in "employer" "организация, в которой субъект работает или работал" "ru")
(descr-as-in "employer" "persona o organización para la cual trabaja o trabajó" "es")
(descr-as-in "employer" "主題人物が働いている／いた組織・団体" "ja")
(descr-as-in "employer" "" "zh-cn")
(descr-as-in "employer" "" "zh-sg")

