(ns properties.encyclopædia_universalis_online_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "encyclopædia-universalis-online-id")

(name-as-in "encyclopædia-universalis-online-id" "" "zh-hk")
(name-as-in "encyclopædia-universalis-online-id" "" "pt")
(name-as-in "encyclopædia-universalis-online-id" "Encyclopædia Universalis Online ID" "en")
(name-as-in "encyclopædia-universalis-online-id" "identifiant Encyclopædia Universalis en ligne" "fr")
(name-as-in "encyclopædia-universalis-online-id" "" "zh-tw")
(name-as-in "encyclopædia-universalis-online-id" "" "de")
(name-as-in "encyclopædia-universalis-online-id" "" "ru")
(name-as-in "encyclopædia-universalis-online-id" "" "es")
(name-as-in "encyclopædia-universalis-online-id" "" "ja")
(name-as-in "encyclopædia-universalis-online-id" "" "zh-cn")
(name-as-in "encyclopædia-universalis-online-id" "" "zh-sg")

(descr-as-in "encyclopædia-universalis-online-id" "" "zh-hk")
(descr-as-in "encyclopædia-universalis-online-id" "" "pt")
(descr-as-in "encyclopædia-universalis-online-id" "identifer for an article in the online version of Encyclopædia Universalis" "en")
(descr-as-in "encyclopædia-universalis-online-id" "identifiant d'un article de la version en ligne de l'Encyclopædia Universalis" "fr")
(descr-as-in "encyclopædia-universalis-online-id" "" "zh-tw")
(descr-as-in "encyclopædia-universalis-online-id" "" "de")
(descr-as-in "encyclopædia-universalis-online-id" "" "ru")
(descr-as-in "encyclopædia-universalis-online-id" "" "es")
(descr-as-in "encyclopædia-universalis-online-id" "" "ja")
(descr-as-in "encyclopædia-universalis-online-id" "" "zh-cn")
(descr-as-in "encyclopædia-universalis-online-id" "" "zh-sg")

