(ns properties.end_time
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "end-time")

(name-as-in "end-time" "終於" "zh-hk")
(name-as-in "end-time" "data final" "pt")
(name-as-in "end-time" "end time" "en")
(name-as-in "end-time" "date de fin" "fr")
(name-as-in "end-time" "終於" "zh-tw")
(name-as-in "end-time" "Endzeitpunkt" "de")
(name-as-in "end-time" "дата окончания" "ru")
(name-as-in "end-time" "fecha de fin" "es")
(name-as-in "end-time" "終了日" "ja")
(name-as-in "end-time" "终于" "zh-cn")
(name-as-in "end-time" "终于" "zh-sg")

(descr-as-in "end-time" "某項停止存在的時間或聲明不再有效的時間" "zh-hk")
(descr-as-in "end-time" "qualificador que indica o final do período de validade de uma declaração" "pt")
(descr-as-in "end-time" "indicates the time an item ceases to exist or a statement stops being valid" "en")
(descr-as-in "end-time" "indique la date de fin de validité" "fr")
(descr-as-in "end-time" "某項停止存在的時間或聲明不再有效的時間" "zh-tw")
(descr-as-in "end-time" "Zeitpunkt, zu dem ein Objekt aufhört zu existieren oder eine Aussage aufhört gültig zu sein" "de")
(descr-as-in "end-time" "указывает время прекращения существования элемента или время, с которого утверждение утрачивает силу" "ru")
(descr-as-in "end-time" "indica la fecha en que un elemento deja de existir o en que una afirmación deja de ser válida" "es")
(descr-as-in "end-time" "存在を終了したり、無効であると宣言された日付。おもに修飾子として使用される。組織等の廃止はP576、機器設備の運用終了はP730を使用" "ja")
(descr-as-in "end-time" "某项停止存在的时间或声明不再有效的时间" "zh-cn")
(descr-as-in "end-time" "某项停止存在的时间或声明不再有效的时间" "zh-sg")

