(ns properties.equivalent_class
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "equivalent-class")

(name-as-in "equivalent-class" "" "zh-hk")
(name-as-in "equivalent-class" "classe equivalente" "pt")
(name-as-in "equivalent-class" "equivalent class" "en")
(name-as-in "equivalent-class" "classe équivalente" "fr")
(name-as-in "equivalent-class" "等價類" "zh-tw")
(name-as-in "equivalent-class" "äquivalente Klasse" "de")
(name-as-in "equivalent-class" "соответствует классу" "ru")
(name-as-in "equivalent-class" "clase equivalente" "es")
(name-as-in "equivalent-class" "同等のクラス" "ja")
(name-as-in "equivalent-class" "" "zh-cn")
(name-as-in "equivalent-class" "" "zh-sg")

(descr-as-in "equivalent-class" "" "zh-hk")
(descr-as-in "equivalent-class" "" "pt")
(descr-as-in "equivalent-class" "equivalent class in other ontologies (use property URI)" "en")
(descr-as-in "equivalent-class" "classe équivalente dans d'autres ontologies (utiliser l'URI de la propriété)" "fr")
(descr-as-in "equivalent-class" "" "zh-tw")
(descr-as-in "equivalent-class" "verweist auf eine gleichwertige Klasse in einer anderen Ontologie" "de")
(descr-as-in "equivalent-class" "эквивалентный класс в другой онтологии (URI)" "ru")
(descr-as-in "equivalent-class" "" "es")
(descr-as-in "equivalent-class" "" "ja")
(descr-as-in "equivalent-class" "" "zh-cn")
(descr-as-in "equivalent-class" "" "zh-sg")

