(ns properties.ethnologue_com_code
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "ethnologue_com-code")

(name-as-in "ethnologue_com-code" "" "zh-hk")
(name-as-in "ethnologue_com-code" "" "pt")
(name-as-in "ethnologue_com-code" "Ethnologue.com code" "en")
(name-as-in "ethnologue_com-code" "code Ethnologue.com" "fr")
(name-as-in "ethnologue_com-code" "" "zh-tw")
(name-as-in "ethnologue_com-code" "Ethnologue.com-Code" "de")
(name-as-in "ethnologue_com-code" "код Ethnologue.com" "ru")
(name-as-in "ethnologue_com-code" "código Ethnologue.com" "es")
(name-as-in "ethnologue_com-code" "Ethnologue.com識別子" "ja")
(name-as-in "ethnologue_com-code" "" "zh-cn")
(name-as-in "ethnologue_com-code" "" "zh-sg")

(descr-as-in "ethnologue_com-code" "" "zh-hk")
(descr-as-in "ethnologue_com-code" "" "pt")
(descr-as-in "ethnologue_com-code" "identifier for a language in ethnologue.com" "en")
(descr-as-in "ethnologue_com-code" "code langue utilisé dans Ethnologue.com" "fr")
(descr-as-in "ethnologue_com-code" "" "zh-tw")
(descr-as-in "ethnologue_com-code" "" "de")
(descr-as-in "ethnologue_com-code" "" "ru")
(descr-as-in "ethnologue_com-code" "" "es")
(descr-as-in "ethnologue_com-code" "" "ja")
(descr-as-in "ethnologue_com-code" "" "zh-cn")
(descr-as-in "ethnologue_com-code" "" "zh-sg")

