(ns properties.eu_transparency_register_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "eu-transparency-register-id")

(name-as-in "eu-transparency-register-id" "" "zh-hk")
(name-as-in "eu-transparency-register-id" "" "pt")
(name-as-in "eu-transparency-register-id" "EU transparency register ID" "en")
(name-as-in "eu-transparency-register-id" "identifiant du registre de transparence de l'UE" "fr")
(name-as-in "eu-transparency-register-id" "" "zh-tw")
(name-as-in "eu-transparency-register-id" "EU-Transparenzregister-ID" "de")
(name-as-in "eu-transparency-register-id" "код организации в реестре Евросоюза" "ru")
(name-as-in "eu-transparency-register-id" "" "es")
(name-as-in "eu-transparency-register-id" "" "ja")
(name-as-in "eu-transparency-register-id" "" "zh-cn")
(name-as-in "eu-transparency-register-id" "" "zh-sg")

(descr-as-in "eu-transparency-register-id" "" "zh-hk")
(descr-as-in "eu-transparency-register-id" "" "pt")
(descr-as-in "eu-transparency-register-id" "identity code for an organisation, in the transparency register of the European Union" "en")
(descr-as-in "eu-transparency-register-id" "code d'identification pour une organisation dans le registre de transparence de l'Union européenne" "fr")
(descr-as-in "eu-transparency-register-id" "" "zh-tw")
(descr-as-in "eu-transparency-register-id" "Code für eine Organisation im Transparenzregister der Europäischen Union" "de")
(descr-as-in "eu-transparency-register-id" "" "ru")
(descr-as-in "eu-transparency-register-id" "" "es")
(descr-as-in "eu-transparency-register-id" "" "ja")
(descr-as-in "eu-transparency-register-id" "" "zh-cn")
(descr-as-in "eu-transparency-register-id" "" "zh-sg")

