(ns properties.eu_vat_number
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "eu-vat-number")

(name-as-in "eu-vat-number" "" "zh-hk")
(name-as-in "eu-vat-number" "" "pt")
(name-as-in "eu-vat-number" "EU VAT number" "en")
(name-as-in "eu-vat-number" "numéro européen de TVA" "fr")
(name-as-in "eu-vat-number" "" "zh-tw")
(name-as-in "eu-vat-number" "" "de")
(name-as-in "eu-vat-number" "" "ru")
(name-as-in "eu-vat-number" "número de identificación fiscal europeo" "es")
(name-as-in "eu-vat-number" "" "ja")
(name-as-in "eu-vat-number" "" "zh-cn")
(name-as-in "eu-vat-number" "" "zh-sg")

(descr-as-in "eu-vat-number" "" "zh-hk")
(descr-as-in "eu-vat-number" "" "pt")
(descr-as-in "eu-vat-number" "EU VAT number" "en")
(descr-as-in "eu-vat-number" "numéro de taxe sur la valeur ajoutée par VIES" "fr")
(descr-as-in "eu-vat-number" "" "zh-tw")
(descr-as-in "eu-vat-number" "" "de")
(descr-as-in "eu-vat-number" "" "ru")
(descr-as-in "eu-vat-number" "" "es")
(descr-as-in "eu-vat-number" "" "ja")
(descr-as-in "eu-vat-number" "" "zh-cn")
(descr-as-in "eu-vat-number" "" "zh-sg")

