(ns properties.facebook_places_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "facebook-places-id")

(name-as-in "facebook-places-id" "" "zh-hk")
(name-as-in "facebook-places-id" "identificador de lugar do Facebook" "pt")
(name-as-in "facebook-places-id" "Facebook Places ID" "en")
(name-as-in "facebook-places-id" "identifiant Facebook de lieu" "fr")
(name-as-in "facebook-places-id" "" "zh-tw")
(name-as-in "facebook-places-id" "Facebook-Places-ID" "de")
(name-as-in "facebook-places-id" "код места в Facebook" "ru")
(name-as-in "facebook-places-id" "Identificador de lugar de Facebook" "es")
(name-as-in "facebook-places-id" "" "ja")
(name-as-in "facebook-places-id" "" "zh-cn")
(name-as-in "facebook-places-id" "" "zh-sg")

(descr-as-in "facebook-places-id" "" "zh-hk")
(descr-as-in "facebook-places-id" "código identificador do Facebook para lugares" "pt")
(descr-as-in "facebook-places-id" "identifier for a place in Facebook" "en")
(descr-as-in "facebook-places-id" "identifiant pour un lieu dans Facebook" "fr")
(descr-as-in "facebook-places-id" "" "zh-tw")
(descr-as-in "facebook-places-id" "Identifikator für einen Ort auf Facebook" "de")
(descr-as-in "facebook-places-id" "" "ru")
(descr-as-in "facebook-places-id" "" "es")
(descr-as-in "facebook-places-id" "" "ja")
(descr-as-in "facebook-places-id" "" "zh-cn")
(descr-as-in "facebook-places-id" "" "zh-sg")

