(ns properties.family_name_identical_to_this_given_name
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "family-name-identical-to-this-given-name")

(name-as-in "family-name-identical-to-this-given-name" "" "zh-hk")
(name-as-in "family-name-identical-to-this-given-name" "nome de família idêntico a este prenome" "pt")
(name-as-in "family-name-identical-to-this-given-name" "family name identical to this given name" "en")
(name-as-in "family-name-identical-to-this-given-name" "nom de famille identique à ce prénom" "fr")
(name-as-in "family-name-identical-to-this-given-name" "" "zh-tw")
(name-as-in "family-name-identical-to-this-given-name" "Familienname identisch zu diesem Vornamen" "de")
(name-as-in "family-name-identical-to-this-given-name" "фамилия с идентичным написанием" "ru")
(name-as-in "family-name-identical-to-this-given-name" "apellido idéntico a este nombre" "es")
(name-as-in "family-name-identical-to-this-given-name" "この人名と同形の姓" "ja")
(name-as-in "family-name-identical-to-this-given-name" "相关姓氏" "zh-cn")
(name-as-in "family-name-identical-to-this-given-name" "相关姓氏" "zh-sg")

(descr-as-in "family-name-identical-to-this-given-name" "" "zh-hk")
(descr-as-in "family-name-identical-to-this-given-name" "sobrenome que é igual a um nome próprio. Use em itens de prenomes" "pt")
(descr-as-in "family-name-identical-to-this-given-name" "last name that is the same as a given first name. Use on items for given names" "en")
(descr-as-in "family-name-identical-to-this-given-name" "à utiliser sur la page d'un prénom pour lier un nom de famille" "fr")
(descr-as-in "family-name-identical-to-this-given-name" "" "zh-tw")
(descr-as-in "family-name-identical-to-this-given-name" "Nur auf Datensätze von Vornamen verwenden und mit dem gleichlautenden Familiennamen verlinken" "de")
(descr-as-in "family-name-identical-to-this-given-name" "фамилия, написание которой совпадает с написанием этого имени" "ru")
(descr-as-in "family-name-identical-to-this-given-name" "apellido que es igual a un nombre dado. Úsese en nombres propios" "es")
(descr-as-in "family-name-identical-to-this-given-name" "主題の個人名 (given name) と同形の姓 (family name)。個人名のアイテムに使用" "ja")
(descr-as-in "family-name-identical-to-this-given-name" "" "zh-cn")
(descr-as-in "family-name-identical-to-this-given-name" "" "zh-sg")

