(ns properties.familypedia_person_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "familypedia-person-id")

(name-as-in "familypedia-person-id" "" "zh-hk")
(name-as-in "familypedia-person-id" "" "pt")
(name-as-in "familypedia-person-id" "Familypedia person ID" "en")
(name-as-in "familypedia-person-id" "identifiant Familypedia de personne" "fr")
(name-as-in "familypedia-person-id" "" "zh-tw")
(name-as-in "familypedia-person-id" "" "de")
(name-as-in "familypedia-person-id" "" "ru")
(name-as-in "familypedia-person-id" "" "es")
(name-as-in "familypedia-person-id" "" "ja")
(name-as-in "familypedia-person-id" "" "zh-cn")
(name-as-in "familypedia-person-id" "" "zh-sg")

(descr-as-in "familypedia-person-id" "" "zh-hk")
(descr-as-in "familypedia-person-id" "" "pt")
(descr-as-in "familypedia-person-id" "identifier for a person on Familypedia, the genealogical database by Wikia" "en")
(descr-as-in "familypedia-person-id" "identifiant pour une personne sur Familypedia, la base de données généalogiques de Wikia" "fr")
(descr-as-in "familypedia-person-id" "" "zh-tw")
(descr-as-in "familypedia-person-id" "" "de")
(descr-as-in "familypedia-person-id" "" "ru")
(descr-as-in "familypedia-person-id" "" "es")
(descr-as-in "familypedia-person-id" "" "ja")
(descr-as-in "familypedia-person-id" "" "zh-cn")
(descr-as-in "familypedia-person-id" "" "zh-sg")

