(ns properties.fast_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "fast-id")

(name-as-in "fast-id" "" "zh-hk")
(name-as-in "fast-id" "FAST ID" "pt")
(name-as-in "fast-id" "FAST ID" "en")
(name-as-in "fast-id" "identifiant FAST" "fr")
(name-as-in "fast-id" "" "zh-tw")
(name-as-in "fast-id" "FAST ID" "de")
(name-as-in "fast-id" "FAST ID" "ru")
(name-as-in "fast-id" "identificador FAST" "es")
(name-as-in "fast-id" "FAST ID" "ja")
(name-as-in "fast-id" "" "zh-cn")
(name-as-in "fast-id" "" "zh-sg")

(descr-as-in "fast-id" "" "zh-hk")
(descr-as-in "fast-id" "" "pt")
(descr-as-in "fast-id" "authority control identifier in WorldCat's “FAST Linked Data” authority file. Format: up to 8 digits, without zero-padding." "en")
(descr-as-in "fast-id" "identificateur de notice d'autorité de données FAST disponible sur WorldCat" "fr")
(descr-as-in "fast-id" "" "zh-tw")
(descr-as-in "fast-id" "ID in der FAST-Normdatei, die zu WorldCat gehört (ohne führende Nullen)" "de")
(descr-as-in "fast-id" "FAST Linked Data" "ru")
(descr-as-in "fast-id" "control de autoría de Worldcat" "es")
(descr-as-in "fast-id" "" "ja")
(descr-as-in "fast-id" "" "zh-cn")
(descr-as-in "fast-id" "" "zh-sg")

