(ns properties.father
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "father")

(name-as-in "father" "父親" "zh-hk")
(name-as-in "father" "pai" "pt")
(name-as-in "father" "father" "en")
(name-as-in "father" "père" "fr")
(name-as-in "father" "父親" "zh-tw")
(name-as-in "father" "Vater" "de")
(name-as-in "father" "отец" "ru")
(name-as-in "father" "padre" "es")
(name-as-in "father" "父親" "ja")
(name-as-in "father" "父亲" "zh-cn")
(name-as-in "father" "父亲" "zh-sg")

(descr-as-in "father" "男性家長" "zh-hk")
(descr-as-in "father" "progenitor masculino" "pt")
(descr-as-in "father" "male parent of the subject. For stepfather, use stepparent (P3448)" "en")
(descr-as-in "father" "lien familial, parent direct de sexe masculin" "fr")
(descr-as-in "father" "男性家長" "zh-tw")
(descr-as-in "father" "männlicher Elternteil" "de")
(descr-as-in "father" "отец персоны" "ru")
(descr-as-in "father" "progenitor masculino" "es")
(descr-as-in "father" "その項目は主題に対し男性の親" "ja")
(descr-as-in "father" "男性家长" "zh-cn")
(descr-as-in "father" "男性家长" "zh-sg")

