(ns properties.female_form_of_label
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "female-form-of-label")

(name-as-in "female-form-of-label" "" "zh-hk")
(name-as-in "female-form-of-label" "forma feminina da etiqueta" "pt")
(name-as-in "female-form-of-label" "female form of label" "en")
(name-as-in "female-form-of-label" "forme féminine du libellé" "fr")
(name-as-in "female-form-of-label" "" "zh-tw")
(name-as-in "female-form-of-label" "weibliche Form des Bezeichners" "de")
(name-as-in "female-form-of-label" "женская форма наименования" "ru")
(name-as-in "female-form-of-label" "forma femenina de la etiqueta" "es")
(name-as-in "female-form-of-label" "女性形" "ja")
(name-as-in "female-form-of-label" "" "zh-cn")
(name-as-in "female-form-of-label" "" "zh-sg")

(descr-as-in "female-form-of-label" "" "zh-hk")
(descr-as-in "female-form-of-label" "" "pt")
(descr-as-in "female-form-of-label" "female form of name or title" "en")
(descr-as-in "female-form-of-label" "forme féminine du nom d'un élément" "fr")
(descr-as-in "female-form-of-label" "" "zh-tw")
(descr-as-in "female-form-of-label" "" "de")
(descr-as-in "female-form-of-label" "" "ru")
(descr-as-in "female-form-of-label" "forma femenina del nombre del elemento" "es")
(descr-as-in "female-form-of-label" "" "ja")
(descr-as-in "female-form-of-label" "" "zh-cn")
(descr-as-in "female-form-of-label" "" "zh-sg")

