(ns properties.field_of_this_occupation
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "field-of-this-occupation")

(name-as-in "field-of-this-occupation" "專業領域" "zh-hk")
(name-as-in "field-of-this-occupation" "campo desta ocupação" "pt")
(name-as-in "field-of-this-occupation" "field of this occupation" "en")
(name-as-in "field-of-this-occupation" "domaine d'occupation" "fr")
(name-as-in "field-of-this-occupation" "專業領域" "zh-tw")
(name-as-in "field-of-this-occupation" "Betätigungsfeld des Berufes" "de")
(name-as-in "field-of-this-occupation" "сфера деятельности" "ru")
(name-as-in "field-of-this-occupation" "ámbito de la ocupación" "es")
(name-as-in "field-of-this-occupation" "専門的職業の分野" "ja")
(name-as-in "field-of-this-occupation" "专业领域" "zh-cn")
(name-as-in "field-of-this-occupation" "" "zh-sg")

(descr-as-in "field-of-this-occupation" "此職業的專業領域" "zh-hk")
(descr-as-in "field-of-this-occupation" "" "pt")
(descr-as-in "field-of-this-occupation" "activity corresponding to this occupation (use only for occupations - for people use Property:P101)" "en")
(descr-as-in "field-of-this-occupation" "domaine correspondant au métier (utilisé uniquement pour les occupations, pour les personnes, voir Property:P101)" "fr")
(descr-as-in "field-of-this-occupation" "" "zh-tw")
(descr-as-in "field-of-this-occupation" "Feld korrespondiert mit Beruf" "de")
(descr-as-in "field-of-this-occupation" "у занятостей: сфера деятельности работника данной профессии" "ru")
(descr-as-in "field-of-this-occupation" "campo correspondiente a esta ocupación" "es")
(descr-as-in "field-of-this-occupation" "この専門的職業に対応する分野" "ja")
(descr-as-in "field-of-this-occupation" "某职业的专业领域（参见P101）" "zh-cn")
(descr-as-in "field-of-this-occupation" "" "zh-sg")

