(ns properties.find_a_grave_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "find-a-grave-id")

(name-as-in "find-a-grave-id" "Find a Grave" "de")
(name-as-in "find-a-grave-id" "" "zh-hk")
(name-as-in "find-a-grave-id" "" "zh-tw")
(name-as-in "find-a-grave-id" "id Find a Grave" "ru")
(name-as-in "find-a-grave-id" "" "pt")
(name-as-in "find-a-grave-id" "Find a Grave ID" "en")
(name-as-in "find-a-grave-id" "" "zh-cn")
(name-as-in "find-a-grave-id" "identifiant Find a Grave" "fr")
(name-as-in "find-a-grave-id" "Find a Grave" "es")
(name-as-in "find-a-grave-id" "" "zh-sg")
(name-as-in "find-a-grave-id" "Find a Grave" "ja")
(name-as-in "find-a-grave-id" "Find a Grave" "zh-hans")
(name-as-in "find-a-grave-id" "" "zh-hant")

(descr-as-in "find-a-grave-id" "Identifikationsnummer in der Begräbnisstätten-Datenbank Find a Grave" "de")
(descr-as-in "find-a-grave-id" "" "zh-hk")
(descr-as-in "find-a-grave-id" "" "zh-tw")
(descr-as-in "find-a-grave-id" "идентификатор на сайте" "ru")
(descr-as-in "find-a-grave-id" "" "pt")
(descr-as-in "find-a-grave-id" "the subject's ID in the Find a Grave database" "en")
(descr-as-in "find-a-grave-id" "" "zh-cn")
(descr-as-in "find-a-grave-id" "" "fr")
(descr-as-in "find-a-grave-id" "" "es")
(descr-as-in "find-a-grave-id" "" "zh-sg")
(descr-as-in "find-a-grave-id" "墓地データベース「Find a Grave」の人物ID (grid)" "ja")
(descr-as-in "find-a-grave-id" "" "zh-hans")
(descr-as-in "find-a-grave-id" "" "zh-hant")

