(ns properties.find_a_grave_memorial_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "find-a-grave-memorial-id")

(name-as-in "find-a-grave-memorial-id" "Find a Grave編號" "zh-hk")
(name-as-in "find-a-grave-memorial-id" "identificador Find a Grave" "pt")
(name-as-in "find-a-grave-memorial-id" "Find a Grave memorial ID" "en")
(name-as-in "find-a-grave-memorial-id" "identifiant Find a Grave d'une tombe" "fr")
(name-as-in "find-a-grave-memorial-id" "Find a Grave編號" "zh-tw")
(name-as-in "find-a-grave-memorial-id" "Find-A-Grave-Personen-ID" "de")
(name-as-in "find-a-grave-memorial-id" "код Find a Grave" "ru")
(name-as-in "find-a-grave-memorial-id" "identificador Find a Grave de una tumba" "es")
(name-as-in "find-a-grave-memorial-id" "Find a Grave" "ja")
(name-as-in "find-a-grave-memorial-id" "Find a Grave编号" "zh-cn")
(name-as-in "find-a-grave-memorial-id" "Find a Grave编号" "zh-sg")

(descr-as-in "find-a-grave-memorial-id" "" "zh-hk")
(descr-as-in "find-a-grave-memorial-id" "" "pt")
(descr-as-in "find-a-grave-memorial-id" "identifier of an individual's burial place in the Find a Grave database" "en")
(descr-as-in "find-a-grave-memorial-id" "identifiant dans la base de données Find a Grave" "fr")
(descr-as-in "find-a-grave-memorial-id" "" "zh-tw")
(descr-as-in "find-a-grave-memorial-id" "Identifikationsnummer in der Begräbnisstätten-Datenbank Find a Grave für Personen" "de")
(descr-as-in "find-a-grave-memorial-id" "идентификатор на сайте Find a Grave" "ru")
(descr-as-in "find-a-grave-memorial-id" "identificador del lugar de enterramiento de una persona en la base de datos de Find a Grave" "es")
(descr-as-in "find-a-grave-memorial-id" "墓地データベース「Find a Grave」の人物ID (grid)" "ja")
(descr-as-in "find-a-grave-memorial-id" "" "zh-cn")
(descr-as-in "find-a-grave-memorial-id" "" "zh-sg")

