(ns properties.fips_55_3_locations_in_the_us
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "fips-55-3-locations-in-the-us")

(name-as-in "fips-55-3-locations-in-the-us" "" "zh-hk")
(name-as-in "fips-55-3-locations-in-the-us" "código FIPS 55-3 (EUA)" "pt")
(name-as-in "fips-55-3-locations-in-the-us" "FIPS 55-3 (locations in the US)" "en")
(name-as-in "fips-55-3-locations-in-the-us" "code FIPS" "fr")
(name-as-in "fips-55-3-locations-in-the-us" "" "zh-tw")
(name-as-in "fips-55-3-locations-in-the-us" "FIPS 55-3 (Orte in USA)" "de")
(name-as-in "fips-55-3-locations-in-the-us" "FIPS 55-3" "ru")
(name-as-in "fips-55-3-locations-in-the-us" "FIPS 55-3" "es")
(name-as-in "fips-55-3-locations-in-the-us" "" "ja")
(name-as-in "fips-55-3-locations-in-the-us" "" "zh-cn")
(name-as-in "fips-55-3-locations-in-the-us" "" "zh-sg")

(descr-as-in "fips-55-3-locations-in-the-us" "" "zh-hk")
(descr-as-in "fips-55-3-locations-in-the-us" "" "pt")
(descr-as-in "fips-55-3-locations-in-the-us" "identifier for places in the United States per former Federal Information Processing Standard FIPS 55-3" "en")
(descr-as-in "fips-55-3-locations-in-the-us" "code américain d'identification d'objets géographiques" "fr")
(descr-as-in "fips-55-3-locations-in-the-us" "" "zh-tw")
(descr-as-in "fips-55-3-locations-in-the-us" "Identifikationsnummer des U.S. Federal Information Processing Standard FIPS 55-3 für Orte in den USA" "de")
(descr-as-in "fips-55-3-locations-in-the-us" "бывшие коды США для географических объектов" "ru")
(descr-as-in "fips-55-3-locations-in-the-us" "código de identificación para objetos geográficos en los EUA" "es")
(descr-as-in "fips-55-3-locations-in-the-us" "" "ja")
(descr-as-in "fips-55-3-locations-in-the-us" "" "zh-cn")
(descr-as-in "fips-55-3-locations-in-the-us" "" "zh-sg")

