(ns properties.fips_10_4_countries_and_regions
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "fips-10-4-countries-and-regions")

(name-as-in "fips-10-4-countries-and-regions" "FIPS 10-4 (國家和地區)" "zh-hk")
(name-as-in "fips-10-4-countries-and-regions" "FIPS 10-4 (países e regiões fora dos EUA)" "pt")
(name-as-in "fips-10-4-countries-and-regions" "FIPS 10-4 (countries and regions)" "en")
(name-as-in "fips-10-4-countries-and-regions" "code FIPS 10-4 (pays et régions)" "fr")
(name-as-in "fips-10-4-countries-and-regions" "FIPS 10-4 (國家和地區)" "zh-tw")
(name-as-in "fips-10-4-countries-and-regions" "FIPS 10-4 (Länder und Unterteilungen weltweit)" "de")
(name-as-in "fips-10-4-countries-and-regions" "FIPS 10-4" "ru")
(name-as-in "fips-10-4-countries-and-regions" "FIPS 10-4 (países y regiones)" "es")
(name-as-in "fips-10-4-countries-and-regions" "FIPS 10-4" "ja")
(name-as-in "fips-10-4-countries-and-regions" "" "zh-cn")
(name-as-in "fips-10-4-countries-and-regions" "" "zh-sg")

(descr-as-in "fips-10-4-countries-and-regions" "" "zh-hk")
(descr-as-in "fips-10-4-countries-and-regions" "" "pt")
(descr-as-in "fips-10-4-countries-and-regions" "identifier for countries and regions per former Federal Information Processing Standard FIPS 10-4" "en")
(descr-as-in "fips-10-4-countries-and-regions" "code de pays normalisé du Federal Information Processing Standards des États-Unis" "fr")
(descr-as-in "fips-10-4-countries-and-regions" "" "zh-tw")
(descr-as-in "fips-10-4-countries-and-regions" "Identifikationsnummer für Länder und Regionen des U.S. Federal Information Processing Standard No. 10" "de")
(descr-as-in "fips-10-4-countries-and-regions" "код для стран и регионов по старому стандарту FIPS" "ru")
(descr-as-in "fips-10-4-countries-and-regions" "código de países y regiones fuera de la Unión Europea" "es")
(descr-as-in "fips-10-4-countries-and-regions" "" "ja")
(descr-as-in "fips-10-4-countries-and-regions" "" "zh-cn")
(descr-as-in "fips-10-4-countries-and-regions" "" "zh-sg")

