(ns properties.foundational_text
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "foundational-text")

(name-as-in "foundational-text" "成立文獻" "zh-hk")
(name-as-in "foundational-text" "documento fundador" "pt")
(name-as-in "foundational-text" "foundational text" "en")
(name-as-in "foundational-text" "texte fondateur" "fr")
(name-as-in "foundational-text" "" "zh-tw")
(name-as-in "foundational-text" "Gründungsvertrag" "de")
(name-as-in "foundational-text" "основополагающий текст" "ru")
(name-as-in "foundational-text" "texto fundacional" "es")
(name-as-in "foundational-text" "設立文" "ja")
(name-as-in "foundational-text" "" "zh-cn")
(name-as-in "foundational-text" "" "zh-sg")

(descr-as-in "foundational-text" "成立一個機構的文獻" "zh-hk")
(descr-as-in "foundational-text" "documento pelo qual uma instituição foi criada" "pt")
(descr-as-in "foundational-text" "text through which an institution or object has been created or established" "en")
(descr-as-in "foundational-text" "texte créant une institution" "fr")
(descr-as-in "foundational-text" "" "zh-tw")
(descr-as-in "foundational-text" "Text, durch den eine Institution gegründet wurde" "de")
(descr-as-in "foundational-text" "текст, согласно которому было создано учреждение/институт" "ru")
(descr-as-in "foundational-text" "texto por el cual una institución fue creada" "es")
(descr-as-in "foundational-text" "この機関の設立に関与した文章" "ja")
(descr-as-in "foundational-text" "" "zh-cn")
(descr-as-in "foundational-text" "" "zh-sg")

