(ns properties.founded_by
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "founded-by")

(name-as-in "founded-by" "創辦者" "zh-hk")
(name-as-in "founded-by" "fundador" "pt")
(name-as-in "founded-by" "founded by" "en")
(name-as-in "founded-by" "fondateur" "fr")
(name-as-in "founded-by" "創辦者" "zh-tw")
(name-as-in "founded-by" "Gründer" "de")
(name-as-in "founded-by" "основатель" "ru")
(name-as-in "founded-by" "fundador" "es")
(name-as-in "founded-by" "創設者" "ja")
(name-as-in "founded-by" "创办者" "zh-cn")
(name-as-in "founded-by" "创办者" "zh-sg")

(descr-as-in "founded-by" "創辦機構的人物或組織" "zh-hk")
(descr-as-in "founded-by" "pessoa ou organização que fundou uma outra organização" "pt")
(descr-as-in "founded-by" "founder or co-founder of this organization, religion or place" "en")
(descr-as-in "founded-by" "fondateur ou co-fondateur de l'organisation" "fr")
(descr-as-in "founded-by" "創辦機構的人物或組織" "zh-tw")
(descr-as-in "founded-by" "Person oder Organisation, die das Objekt gegründet hat" "de")
(descr-as-in "founded-by" "основатель или сооснователь организации, учения или населённого пункта" "ru")
(descr-as-in "founded-by" "persona que ha fundado una organización; organización que a su vez ha fundado otra" "es")
(descr-as-in "founded-by" "組織を創設した人あるいは組織" "ja")
(descr-as-in "founded-by" "创办机构的人物或组织" "zh-cn")
(descr-as-in "founded-by" "创办机构的人物或组织" "zh-sg")

