(ns properties.freebase_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "freebase-id")

(name-as-in "freebase-id" "Freebase編號" "zh-hk")
(name-as-in "freebase-id" "identificador em Freebase" "pt")
(name-as-in "freebase-id" "Freebase ID" "en")
(name-as-in "freebase-id" "identifiant Freebase" "fr")
(name-as-in "freebase-id" "Freebase" "zh-tw")
(name-as-in "freebase-id" "Freebase-Kennung" "de")
(name-as-in "freebase-id" "код Freebase" "ru")
(name-as-in "freebase-id" "identificador Freebase" "es")
(name-as-in "freebase-id" "Freebase識別子" "ja")
(name-as-in "freebase-id" "Freebase ID" "zh-cn")
(name-as-in "freebase-id" "" "zh-sg")

(descr-as-in "freebase-id" "" "zh-hk")
(descr-as-in "freebase-id" "código identificativo na base de dados de Freebase" "pt")
(descr-as-in "freebase-id" "identifier for a page in the Freebase database. Format: /m/0 followed by 2 to 7 characters. For those starting with /g/, use Google Knowledge Graph identifier (P2671)" "en")
(descr-as-in "freebase-id" "identifiant de l'entité dans la base de données Freebase" "fr")
(descr-as-in "freebase-id" "" "zh-tw")
(descr-as-in "freebase-id" "Kennung des gleichbedeutenden Eintrags in der Freebase-Datenbank" "de")
(descr-as-in "freebase-id" "идентификатор в свободной базе данных" "ru")
(descr-as-in "freebase-id" "identificador de una página equivalente en la base de datos semántica Freebase" "es")
(descr-as-in "freebase-id" "オープンな知識ベースである Freebase の同一ページを指す識別子" "ja")
(descr-as-in "freebase-id" "" "zh-cn")
(descr-as-in "freebase-id" "" "zh-sg")

