(ns properties.gacs_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "gacs-id")

(name-as-in "gacs-id" "" "zh-hk")
(name-as-in "gacs-id" "" "pt")
(name-as-in "gacs-id" "GACS ID" "en")
(name-as-in "gacs-id" "identifiant Global Agricultural Concept Scheme" "fr")
(name-as-in "gacs-id" "" "zh-tw")
(name-as-in "gacs-id" "" "de")
(name-as-in "gacs-id" "" "ru")
(name-as-in "gacs-id" "" "es")
(name-as-in "gacs-id" "" "ja")
(name-as-in "gacs-id" "" "zh-cn")
(name-as-in "gacs-id" "" "zh-sg")

(descr-as-in "gacs-id" "" "zh-hk")
(descr-as-in "gacs-id" "" "pt")
(descr-as-in "gacs-id" "identifier of a concept in the Global Agricultural Concept Scheme" "en")
(descr-as-in "gacs-id" "identifiant d'un concept dans le Global Agricultural Concept Scheme" "fr")
(descr-as-in "gacs-id" "" "zh-tw")
(descr-as-in "gacs-id" "" "de")
(descr-as-in "gacs-id" "" "ru")
(descr-as-in "gacs-id" "" "es")
(descr-as-in "gacs-id" "" "ja")
(descr-as-in "gacs-id" "" "zh-cn")
(descr-as-in "gacs-id" "" "zh-sg")

