(ns properties.gedbas_genealogy_person_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "gedbas-genealogy-person-id")

(name-as-in "gedbas-genealogy-person-id" "" "zh-hk")
(name-as-in "gedbas-genealogy-person-id" "" "pt")
(name-as-in "gedbas-genealogy-person-id" "Gedbas genealogy person ID" "en")
(name-as-in "gedbas-genealogy-person-id" "identifiant Gedbas" "fr")
(name-as-in "gedbas-genealogy-person-id" "" "zh-tw")
(name-as-in "gedbas-genealogy-person-id" "" "de")
(name-as-in "gedbas-genealogy-person-id" "" "ru")
(name-as-in "gedbas-genealogy-person-id" "" "es")
(name-as-in "gedbas-genealogy-person-id" "" "ja")
(name-as-in "gedbas-genealogy-person-id" "" "zh-cn")
(name-as-in "gedbas-genealogy-person-id" "" "zh-sg")

(descr-as-in "gedbas-genealogy-person-id" "" "zh-hk")
(descr-as-in "gedbas-genealogy-person-id" "" "pt")
(descr-as-in "gedbas-genealogy-person-id" "identifier for a person in the genealogical database of the Verein für Computergenealogie e.V. on gedbas.genealogy.net" "en")
(descr-as-in "gedbas-genealogy-person-id" "identifiant d'une personne dans la base de données généalogique de Verein für Computergenealogie e.V. sur gedbas.genealogy.net" "fr")
(descr-as-in "gedbas-genealogy-person-id" "" "zh-tw")
(descr-as-in "gedbas-genealogy-person-id" "" "de")
(descr-as-in "gedbas-genealogy-person-id" "" "ru")
(descr-as-in "gedbas-genealogy-person-id" "" "es")
(descr-as-in "gedbas-genealogy-person-id" "" "ja")
(descr-as-in "gedbas-genealogy-person-id" "" "zh-cn")
(descr-as-in "gedbas-genealogy-person-id" "" "zh-sg")

