(ns properties.genealogics_org_person_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "genealogics_org-person-id")

(name-as-in "genealogics_org-person-id" "" "zh-hk")
(name-as-in "genealogics_org-person-id" "" "pt")
(name-as-in "genealogics_org-person-id" "genealogics.org person ID" "en")
(name-as-in "genealogics_org-person-id" "identifiant de personnes sur genealogics.org" "fr")
(name-as-in "genealogics_org-person-id" "" "zh-tw")
(name-as-in "genealogics_org-person-id" "Personennunmer bei genealogics.org" "de")
(name-as-in "genealogics_org-person-id" "код человека на genealogics.org" "ru")
(name-as-in "genealogics_org-person-id" "identificador genealogics.org de persona" "es")
(name-as-in "genealogics_org-person-id" "" "ja")
(name-as-in "genealogics_org-person-id" "" "zh-cn")
(name-as-in "genealogics_org-person-id" "" "zh-sg")

(descr-as-in "genealogics_org-person-id" "" "zh-hk")
(descr-as-in "genealogics_org-person-id" "" "pt")
(descr-as-in "genealogics_org-person-id" "identifier for a person at genealogics.org" "en")
(descr-as-in "genealogics_org-person-id" "identifiant d'une personne sur genealogics.org" "fr")
(descr-as-in "genealogics_org-person-id" "" "zh-tw")
(descr-as-in "genealogics_org-person-id" "Identifikationsnummer einer Person bei genealogics.org" "de")
(descr-as-in "genealogics_org-person-id" "" "ru")
(descr-as-in "genealogics_org-person-id" "identificador de una persona en genealogics.org" "es")
(descr-as-in "genealogics_org-person-id" "" "ja")
(descr-as-in "genealogics_org-person-id" "" "zh-cn")
(descr-as-in "genealogics_org-person-id" "" "zh-sg")

