(ns properties.genetic_association
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "genetic-association")

(name-as-in "genetic-association" "" "zh-hk")
(name-as-in "genetic-association" "associação genética" "pt")
(name-as-in "genetic-association" "genetic association" "en")
(name-as-in "genetic-association" "association génétique" "fr")
(name-as-in "genetic-association" "" "zh-tw")
(name-as-in "genetic-association" "genetische Assoziation mit" "de")
(name-as-in "genetic-association" "генетическая связь" "ru")
(name-as-in "genetic-association" "asociación genética" "es")
(name-as-in "genetic-association" "遺伝的関連" "ja")
(name-as-in "genetic-association" "" "zh-cn")
(name-as-in "genetic-association" "" "zh-sg")

(descr-as-in "genetic-association" "" "zh-hk")
(descr-as-in "genetic-association" "" "pt")
(descr-as-in "genetic-association" "general link between a disease and the causal genetic entity, if the detailed mechanism is unknown/unavailable" "en")
(descr-as-in "genetic-association" "lien général entre une maladie et l'entité génétique ordinaire, si le mécanisme détaillé est inconnu/indisponible" "fr")
(descr-as-in "genetic-association" "" "zh-tw")
(descr-as-in "genetic-association" "Stellt eine generelle Verbindung zwischen einer Krankheit/Erkrankung und der ursächlichen genetischen Einheit her, vorausgesetzt die genaue genetische Ursache ist unbekannt oder Daten darüber nicht verfügbar." "de")
(descr-as-in "genetic-association" "" "ru")
(descr-as-in "genetic-association" "" "es")
(descr-as-in "genetic-association" "詳細なメカニズムが不明な場合に使う、病気とその原因遺伝子間のリンク" "ja")
(descr-as-in "genetic-association" "" "zh-cn")
(descr-as-in "genetic-association" "" "zh-sg")

