(ns properties.geoshape
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "geoshape")

(name-as-in "geoshape" "" "zh-hk")
(name-as-in "geoshape" "formato geográfico" "pt")
(name-as-in "geoshape" "geoshape" "en")
(name-as-in "geoshape" "forme géographique" "fr")
(name-as-in "geoshape" "" "zh-tw")
(name-as-in "geoshape" "geografische Form" "de")
(name-as-in "geoshape" "геоданные" "ru")
(name-as-in "geoshape" "forma geográfica" "es")
(name-as-in "geoshape" "コモンズの地理データ" "ja")
(name-as-in "geoshape" "" "zh-cn")
(name-as-in "geoshape" "" "zh-sg")

(descr-as-in "geoshape" "" "zh-hk")
(descr-as-in "geoshape" "" "pt")
(descr-as-in "geoshape" "geographic data from Wikimedia Commons" "en")
(descr-as-in "geoshape" "données géographique de Wikimedia Commons" "fr")
(descr-as-in "geoshape" "" "zh-tw")
(descr-as-in "geoshape" "geografische Daten aus Wikimedia Commons" "de")
(descr-as-in "geoshape" "файл геоданных с Викисклада" "ru")
(descr-as-in "geoshape" "datos geográficos de Wikimedia Commons" "es")
(descr-as-in "geoshape" "ウィキメディアコモンズにある地理データ" "ja")
(descr-as-in "geoshape" "" "zh-cn")
(descr-as-in "geoshape" "" "zh-sg")

