(ns properties.german_district_key
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "german-district-key")

(name-as-in "german-district-key" "" "zh-hk")
(name-as-in "german-district-key" "número de distrito alemão" "pt")
(name-as-in "german-district-key" "German district key" "en")
(name-as-in "german-district-key" "numéro de district allemand" "fr")
(name-as-in "german-district-key" "" "zh-tw")
(name-as-in "german-district-key" "Kreisschlüssel" "de")
(name-as-in "german-district-key" "код района Германии" "ru")
(name-as-in "german-district-key" "número de distrito en Alemania" "es")
(name-as-in "german-district-key" "ドイツ郡キー" "ja")
(name-as-in "german-district-key" "" "zh-cn")
(name-as-in "german-district-key" "" "zh-sg")

(descr-as-in "german-district-key" "" "zh-hk")
(descr-as-in "german-district-key" "" "pt")
(descr-as-in "german-district-key" "identifier for districts (Landkreise) and independent towns in Germany" "en")
(descr-as-in "german-district-key" "numéro d'identification de districts (Landkreis) et villes indépendantes en Allemagne" "fr")
(descr-as-in "german-district-key" "" "zh-tw")
(descr-as-in "german-district-key" "Nummernfolge für die Identifikation von Landkreisen und kreisfreien Städten in Deutschland" "de")
(descr-as-in "german-district-key" "идентификатор районов (крейсов) и независимых городов Германии" "ru")
(descr-as-in "german-district-key" "número de identificación para los distritos (Landkreise) y ciudades independientes en Alemania" "es")
(descr-as-in "german-district-key" "ドイツの郡（ラントクライス）や独立した町を識別するための数字列" "ja")
(descr-as-in "german-district-key" "" "zh-cn")
(descr-as-in "german-district-key" "" "zh-sg")

