(ns properties.global_anabaptist_mennonite_encyclopedia_online_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "global-anabaptist-mennonite-encyclopedia-online-id")

(name-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "zh-hk")
(name-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "pt")
(name-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "Global Anabaptist Mennonite Encyclopedia Online ID" "en")
(name-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "GAMEO id" "fr")
(name-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "zh-tw")
(name-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "GAMEO-ID" "de")
(name-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "код GAMEO" "ru")
(name-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "es")
(name-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "ja")
(name-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "zh-cn")
(name-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "zh-sg")

(descr-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "zh-hk")
(descr-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "pt")
(descr-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "identifier for Global Anabaptist Mennonite Encyclopedia Online" "en")
(descr-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "fr")
(descr-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "zh-tw")
(descr-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "Identifikator in Normdatei der  Global Anabaptist Mennonite Encyclopedia Online" "de")
(descr-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "код Global Anabaptist Mennonite Encyclopedia Online" "ru")
(descr-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "es")
(descr-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "ja")
(descr-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "zh-cn")
(descr-as-in "global-anabaptist-mennonite-encyclopedia-online-id" "" "zh-sg")

