(ns properties.glottolog_code
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "glottolog-code")

(name-as-in "glottolog-code" "" "zh-hk")
(name-as-in "glottolog-code" "código Glottolog" "pt")
(name-as-in "glottolog-code" "Glottolog code" "en")
(name-as-in "glottolog-code" "code Glottolog" "fr")
(name-as-in "glottolog-code" "Glottolog 編碼" "zh-tw")
(name-as-in "glottolog-code" "Glottolog code" "de")
(name-as-in "glottolog-code" "код Glottolog" "ru")
(name-as-in "glottolog-code" "Glottolog" "es")
(name-as-in "glottolog-code" "" "ja")
(name-as-in "glottolog-code" "" "zh-cn")
(name-as-in "glottolog-code" "" "zh-sg")

(descr-as-in "glottolog-code" "" "zh-hk")
(descr-as-in "glottolog-code" "" "pt")
(descr-as-in "glottolog-code" "identifier for a languoid in the Glottolog database" "en")
(descr-as-in "glottolog-code" "code de langues et dialectes utilisé dans la base de données Glottolog" "fr")
(descr-as-in "glottolog-code" "" "zh-tw")
(descr-as-in "glottolog-code" "" "de")
(descr-as-in "glottolog-code" "идентификатор языка или диалекта в базе данных Glottolog" "ru")
(descr-as-in "glottolog-code" "código de idioma en Glottolog" "es")
(descr-as-in "glottolog-code" "" "ja")
(descr-as-in "glottolog-code" "" "zh-cn")
(descr-as-in "glottolog-code" "" "zh-sg")

