(ns properties.google_doodle
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "google-doodle")

(name-as-in "google-doodle" "" "zh-hk")
(name-as-in "google-doodle" "Google Doodle" "pt")
(name-as-in "google-doodle" "Google Doodle" "en")
(name-as-in "google-doodle" "Google Doodle" "fr")
(name-as-in "google-doodle" "" "zh-tw")
(name-as-in "google-doodle" "Google Doodle" "de")
(name-as-in "google-doodle" "" "ru")
(name-as-in "google-doodle" "Google Doodle" "es")
(name-as-in "google-doodle" "" "ja")
(name-as-in "google-doodle" "" "zh-cn")
(name-as-in "google-doodle" "" "zh-sg")

(descr-as-in "google-doodle" "" "zh-hk")
(descr-as-in "google-doodle" "Google Doodle que celebra esta entidade ou evento" "pt")
(descr-as-in "google-doodle" "Google Doodle celebrating this entity or event" "en")
(descr-as-in "google-doodle" "Google Doodle célébrant cet élément ou événement" "fr")
(descr-as-in "google-doodle" "" "zh-tw")
(descr-as-in "google-doodle" "" "de")
(descr-as-in "google-doodle" "" "ru")
(descr-as-in "google-doodle" "Google Doodle que celebra esta entidad o evento" "es")
(descr-as-in "google-doodle" "" "ja")
(descr-as-in "google-doodle" "" "zh-cn")
(descr-as-in "google-doodle" "" "zh-sg")

