(ns properties.gran_enciclopèdia_catalana_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "gran-enciclopèdia-catalana-id")

(name-as-in "gran-enciclopèdia-catalana-id" "" "zh-hk")
(name-as-in "gran-enciclopèdia-catalana-id" "identificador Gran Enciclopèdia Catalana" "pt")
(name-as-in "gran-enciclopèdia-catalana-id" "Gran Enciclopèdia Catalana ID" "en")
(name-as-in "gran-enciclopèdia-catalana-id" "identifiant Gran Enciclopèdia Catalana" "fr")
(name-as-in "gran-enciclopèdia-catalana-id" "" "zh-tw")
(name-as-in "gran-enciclopèdia-catalana-id" "Große katalanische Enzyklopädie ID" "de")
(name-as-in "gran-enciclopèdia-catalana-id" "код в Большой каталанской энциклопедии" "ru")
(name-as-in "gran-enciclopèdia-catalana-id" "identificador de la Gran Enciclopedia Catalana" "es")
(name-as-in "gran-enciclopèdia-catalana-id" "カタルーニャ大百科事典識別子" "ja")
(name-as-in "gran-enciclopèdia-catalana-id" "" "zh-cn")
(name-as-in "gran-enciclopèdia-catalana-id" "" "zh-sg")

(descr-as-in "gran-enciclopèdia-catalana-id" "" "zh-hk")
(descr-as-in "gran-enciclopèdia-catalana-id" "" "pt")
(descr-as-in "gran-enciclopèdia-catalana-id" "identifier for an item in the Gran Enciclopèdia Catalana" "en")
(descr-as-in "gran-enciclopèdia-catalana-id" "identifiant de la Gran Enciclopèdia Catalana (GEC)" "fr")
(descr-as-in "gran-enciclopèdia-catalana-id" "" "zh-tw")
(descr-as-in "gran-enciclopèdia-catalana-id" "Identifikator für einen Eintrag in der Großen katalanischen Enzyklopädie" "de")
(descr-as-in "gran-enciclopèdia-catalana-id" "" "ru")
(descr-as-in "gran-enciclopèdia-catalana-id" "identificador de la Gran Enciclopedia Catalana" "es")
(descr-as-in "gran-enciclopèdia-catalana-id" "" "ja")
(descr-as-in "gran-enciclopèdia-catalana-id" "" "zh-cn")
(descr-as-in "gran-enciclopèdia-catalana-id" "" "zh-sg")

