(ns properties.great_russian_encyclopedia_online_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "great-russian-encyclopedia-online-id")

(name-as-in "great-russian-encyclopedia-online-id" "" "zh-hk")
(name-as-in "great-russian-encyclopedia-online-id" "" "pt")
(name-as-in "great-russian-encyclopedia-online-id" "Great Russian Encyclopedia Online ID" "en")
(name-as-in "great-russian-encyclopedia-online-id" "identifiant de la Grande Encyclopédie russe en ligne" "fr")
(name-as-in "great-russian-encyclopedia-online-id" "" "zh-tw")
(name-as-in "great-russian-encyclopedia-online-id" "ID der Großen Russischen Enzyklopädie" "de")
(name-as-in "great-russian-encyclopedia-online-id" "код в Большой российской энциклопедии онлайн" "ru")
(name-as-in "great-russian-encyclopedia-online-id" "identificador Gran Enciclopedia Rusa Online" "es")
(name-as-in "great-russian-encyclopedia-online-id" "ロシア大百科事典オンラインID" "ja")
(name-as-in "great-russian-encyclopedia-online-id" "" "zh-cn")
(name-as-in "great-russian-encyclopedia-online-id" "" "zh-sg")

(descr-as-in "great-russian-encyclopedia-online-id" "" "zh-hk")
(descr-as-in "great-russian-encyclopedia-online-id" "" "pt")
(descr-as-in "great-russian-encyclopedia-online-id" "identifier for an entry on the official website of the Great Russian Encyclopedia" "en")
(descr-as-in "great-russian-encyclopedia-online-id" "identifiant pour une entrée sur le site Web officiel de la Grande Encyclopédie russe" "fr")
(descr-as-in "great-russian-encyclopedia-online-id" "" "zh-tw")
(descr-as-in "great-russian-encyclopedia-online-id" "Identifikator der offiziellen Website der Großen Russischen Enzyklopädie" "de")
(descr-as-in "great-russian-encyclopedia-online-id" "идентификатор статьи в официальной онлайн-версии Большой российской энциклопедии" "ru")
(descr-as-in "great-russian-encyclopedia-online-id" "identificador para una entrada en el sitio oficial de la Gran Enciclopedia rusa" "es")
(descr-as-in "great-russian-encyclopedia-online-id" "ロシア大百科事典公式サイトにおける識別子" "ja")
(descr-as-in "great-russian-encyclopedia-online-id" "" "zh-cn")
(descr-as-in "great-russian-encyclopedia-online-id" "" "zh-sg")

