(ns properties.great_aragonese_encyclopedia_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "great-aragonese-encyclopedia-id")

(name-as-in "great-aragonese-encyclopedia-id" "" "zh-hk")
(name-as-in "great-aragonese-encyclopedia-id" "" "pt")
(name-as-in "great-aragonese-encyclopedia-id" "Great Aragonese Encyclopedia ID" "en")
(name-as-in "great-aragonese-encyclopedia-id" "identifiant Gran Enciclopedia Aragonesa" "fr")
(name-as-in "great-aragonese-encyclopedia-id" "" "zh-tw")
(name-as-in "great-aragonese-encyclopedia-id" "Gran-Enciclopedia-Aragonesa-ID" "de")
(name-as-in "great-aragonese-encyclopedia-id" "код в Большой арагонской энциклопедии" "ru")
(name-as-in "great-aragonese-encyclopedia-id" "identificador Gran Enciclopedia Aragonesa" "es")
(name-as-in "great-aragonese-encyclopedia-id" "" "ja")
(name-as-in "great-aragonese-encyclopedia-id" "" "zh-cn")
(name-as-in "great-aragonese-encyclopedia-id" "" "zh-sg")

(descr-as-in "great-aragonese-encyclopedia-id" "" "zh-hk")
(descr-as-in "great-aragonese-encyclopedia-id" "" "pt")
(descr-as-in "great-aragonese-encyclopedia-id" "identifier in the Spanish language, Aragon-themed, Great Aragonese Encyclopedia (GEA)" "en")
(descr-as-in "great-aragonese-encyclopedia-id" "identifiant de la Gran Enciclopedia Aragonesa" "fr")
(descr-as-in "great-aragonese-encyclopedia-id" "" "zh-tw")
(descr-as-in "great-aragonese-encyclopedia-id" "" "de")
(descr-as-in "great-aragonese-encyclopedia-id" "" "ru")
(descr-as-in "great-aragonese-encyclopedia-id" "" "es")
(descr-as-in "great-aragonese-encyclopedia-id" "" "ja")
(descr-as-in "great-aragonese-encyclopedia-id" "" "zh-cn")
(descr-as-in "great-aragonese-encyclopedia-id" "" "zh-sg")

