(ns properties.grid_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "grid-id")

(name-as-in "grid-id" "" "zh-hk")
(name-as-in "grid-id" "identificador na GRID" "pt")
(name-as-in "grid-id" "GRID ID" "en")
(name-as-in "grid-id" "identifiant GRID" "fr")
(name-as-in "grid-id" "" "zh-tw")
(name-as-in "grid-id" "GRID-ID" "de")
(name-as-in "grid-id" "код grid global research" "ru")
(name-as-in "grid-id" "identificador Global Research Identifier Database" "es")
(name-as-in "grid-id" "GRID ID" "ja")
(name-as-in "grid-id" "" "zh-cn")
(name-as-in "grid-id" "" "zh-sg")

(descr-as-in "grid-id" "" "zh-hk")
(descr-as-in "grid-id" "código identificador na base de dados Global Research Identifier Database (GRID)" "pt")
(descr-as-in "grid-id" "institutional identifier from the GRID.ac global research identifier database" "en")
(descr-as-in "grid-id" "identifiant institutionnel de la Global Research Identifier Database" "fr")
(descr-as-in "grid-id" "" "zh-tw")
(descr-as-in "grid-id" "Institutions-ID aus der Global Research Identifier Database" "de")
(descr-as-in "grid-id" "идентификатор от организации в глобальной базе данных исследований" "ru")
(descr-as-in "grid-id" "identificador institucional en GRID.ac" "es")
(descr-as-in "grid-id" "" "ja")
(descr-as-in "grid-id" "" "zh-cn")
(descr-as-in "grid-id" "" "zh-sg")

