(ns properties.has_contributing_factor
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "has-contributing-factor")

(name-as-in "has-contributing-factor" "" "zh-hk")
(name-as-in "has-contributing-factor" "tem como fator contribuinte" "pt")
(name-as-in "has-contributing-factor" "has contributing factor" "en")
(name-as-in "has-contributing-factor" "facteur contributif" "fr")
(name-as-in "has-contributing-factor" "影響因素" "zh-tw")
(name-as-in "has-contributing-factor" "entscheidender Faktor" "de")
(name-as-in "has-contributing-factor" "способствовавшим фактором является" "ru")
(name-as-in "has-contributing-factor" "factor contribuyente" "es")
(name-as-in "has-contributing-factor" "寄与因子" "ja")
(name-as-in "has-contributing-factor" "" "zh-cn")
(name-as-in "has-contributing-factor" "" "zh-sg")

(descr-as-in "has-contributing-factor" "" "zh-hk")
(descr-as-in "has-contributing-factor" "coisa que influienciou significativamente, mas não causou diretamente, este resultado ou efeito. Utilizado em conjunto com causado por e  tem como causa imediata. Ver Help:Modeling causes." "pt")
(descr-as-in "has-contributing-factor" "thing that significantly influenced, but did not directly cause, this outcome or effect.  Used in conjunction with 'has cause' and 'has immediate cause'.  See '[[Help:Modeling causes]]'." "en")
(descr-as-in "has-contributing-factor" "" "fr")
(descr-as-in "has-contributing-factor" "" "zh-tw")
(descr-as-in "has-contributing-factor" "" "de")
(descr-as-in "has-contributing-factor" "фактор, оказавший заметное влияние, но не ставший прямой причиной данного являения. Используется совместно с P828 и P1478, см. Help:Modeling causes" "ru")
(descr-as-in "has-contributing-factor" "" "es")
(descr-as-in "has-contributing-factor" "" "ja")
(descr-as-in "has-contributing-factor" "" "zh-cn")
(descr-as-in "has-contributing-factor" "" "zh-sg")

