(ns properties.has_grammatical_mood
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "has-grammatical-mood")

(name-as-in "has-grammatical-mood" "" "zh-hk")
(name-as-in "has-grammatical-mood" "tem modos gramaticais" "pt")
(name-as-in "has-grammatical-mood" "has grammatical mood" "en")
(name-as-in "has-grammatical-mood" "a comme mode grammatical" "fr")
(name-as-in "has-grammatical-mood" "具有語氣" "zh-tw")
(name-as-in "has-grammatical-mood" "hat grammatische Stimmung" "de")
(name-as-in "has-grammatical-mood" "имеет наклонения" "ru")
(name-as-in "has-grammatical-mood" "tiene como modo gramatical" "es")
(name-as-in "has-grammatical-mood" "" "ja")
(name-as-in "has-grammatical-mood" "" "zh-cn")
(name-as-in "has-grammatical-mood" "" "zh-sg")

(descr-as-in "has-grammatical-mood" "" "zh-hk")
(descr-as-in "has-grammatical-mood" "" "pt")
(descr-as-in "has-grammatical-mood" "language has this grammatical mood/mode for signaling modality" "en")
(descr-as-in "has-grammatical-mood" "" "fr")
(descr-as-in "has-grammatical-mood" "" "zh-tw")
(descr-as-in "has-grammatical-mood" "Stimmung, die in einer bestimmten Sprache verwendet wird" "de")
(descr-as-in "has-grammatical-mood" "какие наклонения есть в языке" "ru")
(descr-as-in "has-grammatical-mood" "modo gramatical usado en este idioma" "es")
(descr-as-in "has-grammatical-mood" "" "ja")
(descr-as-in "has-grammatical-mood" "" "zh-cn")
(descr-as-in "has-grammatical-mood" "" "zh-sg")

