(ns properties.has_effect
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "has-effect")

(name-as-in "has-effect" "" "zh-hk")
(name-as-in "has-effect" "causa de" "pt")
(name-as-in "has-effect" "has effect" "en")
(name-as-in "has-effect" "cause de" "fr")
(name-as-in "has-effect" "" "zh-tw")
(name-as-in "has-effect" "Ursache von" "de")
(name-as-in "has-effect" "вызывает" "ru")
(name-as-in "has-effect" "causa de" "es")
(name-as-in "has-effect" "以下の原因" "ja")
(name-as-in "has-effect" "可导致" "zh-cn")
(name-as-in "has-effect" "" "zh-sg")

(descr-as-in "has-effect" "" "zh-hk")
(descr-as-in "has-effect" "" "pt")
(descr-as-in "has-effect" "effect of this cause" "en")
(descr-as-in "has-effect" "effet engendré par le sujet" "fr")
(descr-as-in "has-effect" "" "zh-tw")
(descr-as-in "has-effect" "Auswirkung dieser Ursache" "de")
(descr-as-in "has-effect" "следствие данной причины" "ru")
(descr-as-in "has-effect" "efecto de esta causa" "es")
(descr-as-in "has-effect" "これを原因とする現象。原因 (P828) の逆。例と議論については「Help:Modeling causes」を参照" "ja")
(descr-as-in "has-effect" "" "zh-cn")
(descr-as-in "has-effect" "" "zh-sg")

