(ns properties.hds_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "hds-id")

(name-as-in "hds-id" "" "zh-hk")
(name-as-in "hds-id" "HDS" "pt")
(name-as-in "hds-id" "HDS ID" "en")
(name-as-in "hds-id" "identifiant DHS" "fr")
(name-as-in "hds-id" "" "zh-tw")
(name-as-in "hds-id" "Artikelnummer im HLS" "de")
(name-as-in "hds-id" "идентификатор HDS" "ru")
(name-as-in "hds-id" "identificador DHS" "es")
(name-as-in "hds-id" "スイス歴史事典識別子" "ja")
(name-as-in "hds-id" "" "zh-cn")
(name-as-in "hds-id" "" "zh-sg")

(descr-as-in "hds-id" "" "zh-hk")
(descr-as-in "hds-id" "" "pt")
(descr-as-in "hds-id" "identifier in HDS/HLS/DHS/DSS: Historical Dictionary of Switzerland (Q642074), a national encyclopedia" "en")
(descr-as-in "hds-id" "ID du Dictionnaire historique de la Suisse" "fr")
(descr-as-in "hds-id" "" "zh-tw")
(descr-as-in "hds-id" "Identifikationsnummer im Historischen Lexikon der Schweiz" "de")
(descr-as-in "hds-id" "идентификатор статьи в Историческом словаре Швейцарии" "ru")
(descr-as-in "hds-id" "identificador en el Diccionario Histórico de Suiza" "es")
(descr-as-in "hds-id" "スイス歴史事典 (Q642074) の識別子" "ja")
(descr-as-in "hds-id" "" "zh-cn")
(descr-as-in "hds-id" "" "zh-sg")

