(ns properties.headquarters_location
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "headquarters-location")

(name-as-in "headquarters-location" "總部位置" "zh-hk")
(name-as-in "headquarters-location" "sede" "pt")
(name-as-in "headquarters-location" "headquarters location" "en")
(name-as-in "headquarters-location" "siège social" "fr")
(name-as-in "headquarters-location" "總部位置" "zh-tw")
(name-as-in "headquarters-location" "Hauptverwaltung" "de")
(name-as-in "headquarters-location" "расположение штаб-квартиры" "ru")
(name-as-in "headquarters-location" "ubicación de la sede" "es")
(name-as-in "headquarters-location" "本部所在地" "ja")
(name-as-in "headquarters-location" "总部位置" "zh-cn")
(name-as-in "headquarters-location" "总部位置" "zh-sg")

(descr-as-in "headquarters-location" "組織總部的所在地" "zh-hk")
(descr-as-in "headquarters-location" "local da sede de uma organização" "pt")
(descr-as-in "headquarters-location" "specific location where an organization's HQ is or has been situated" "en")
(descr-as-in "headquarters-location" "lieu où se trouve (ou où s'est trouvé) le siège principal d'une organisation" "fr")
(descr-as-in "headquarters-location" "組織總部的所在地" "zh-tw")
(descr-as-in "headquarters-location" "Ort oder Gebäude, in dem die Hauptverwaltung einer Organisation ihren Sitz hat" "de")
(descr-as-in "headquarters-location" "определенное место, где располагается штаб-квартира организации" "ru")
(descr-as-in "headquarters-location" "ubicación específica donde se sitúa la sede de una organización" "es")
(descr-as-in "headquarters-location" "組織の本部が置かれている具体的な場所" "ja")
(descr-as-in "headquarters-location" "组织总部的所在地" "zh-cn")
(descr-as-in "headquarters-location" "组织总部的所在地" "zh-sg")

