(ns properties.heritage_designation
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "heritage-designation")

(name-as-in "heritage-designation" "文化遺產保護狀況" "zh-hk")
(name-as-in "heritage-designation" "situação patrimonial" "pt")
(name-as-in "heritage-designation" "heritage designation" "en")
(name-as-in "heritage-designation" "statut patrimonial" "fr")
(name-as-in "heritage-designation" "文化遺產保護狀況" "zh-tw")
(name-as-in "heritage-designation" "Kulturerbestatus" "de")
(name-as-in "heritage-designation" "статус наследия" "ru")
(name-as-in "heritage-designation" "estatus patrimonial" "es")
(name-as-in "heritage-designation" "文化遺産保護" "ja")
(name-as-in "heritage-designation" "文化遗产保护状况" "zh-cn")
(name-as-in "heritage-designation" "文化遗产保护状况" "zh-sg")

(descr-as-in "heritage-designation" "歷史遺迹的保護狀況" "zh-hk")
(descr-as-in "heritage-designation" "situação patrimonial de um lugar histórico" "pt")
(descr-as-in "heritage-designation" "heritage designation of a historical site" "en")
(descr-as-in "heritage-designation" "statut patrimonial de l'élément" "fr")
(descr-as-in "heritage-designation" "歷史遺迹的保護狀況" "zh-tw")
(descr-as-in "heritage-designation" "Schutzstatus einer historischen Stätte oder eines denkmalgeschützten Objekts" "de")
(descr-as-in "heritage-designation" "статус культурного наследия некоторого исторического места" "ru")
(descr-as-in "heritage-designation" "declaración patrimonial del elemento" "es")
(descr-as-in "heritage-designation" "の保護の指定状況" "ja")
(descr-as-in "heritage-designation" "历史遗迹的保护状况" "zh-cn")
(descr-as-in "heritage-designation" "历史遗迹的保护状况" "zh-sg")

