(ns properties.highest_judicial_authority
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "highest-judicial-authority")

(name-as-in "highest-judicial-authority" "最高司法機關" "zh-hk")
(name-as-in "highest-judicial-authority" "suprema autoridade judiciária" "pt")
(name-as-in "highest-judicial-authority" "highest judicial authority" "en")
(name-as-in "highest-judicial-authority" "plus haute juridiction" "fr")
(name-as-in "highest-judicial-authority" "最高司法機關" "zh-tw")
(name-as-in "highest-judicial-authority" "höchstes Gericht" "de")
(name-as-in "highest-judicial-authority" "высший судебный орган" "ru")
(name-as-in "highest-judicial-authority" "máxima autoridad judicial" "es")
(name-as-in "highest-judicial-authority" "最高司法府" "ja")
(name-as-in "highest-judicial-authority" "最高司法机关" "zh-cn")
(name-as-in "highest-judicial-authority" "最高司法机关" "zh-sg")

(descr-as-in "highest-judicial-authority" "" "zh-hk")
(descr-as-in "highest-judicial-authority" "" "pt")
(descr-as-in "highest-judicial-authority" "supreme judicial body within a country, administrative division, or other organization" "en")
(descr-as-in "highest-judicial-authority" "corps judiciaire suprême dans un pays, une division administrative, ou une autre organisation" "fr")
(descr-as-in "highest-judicial-authority" "" "zh-tw")
(descr-as-in "highest-judicial-authority" "oberstes Gerichtsorgan eines Landes, einer Verwaltungseinheit oder einer Organisation" "de")
(descr-as-in "highest-judicial-authority" "высший судебный орган страны, региона или какой-либо организации" "ru")
(descr-as-in "highest-judicial-authority" "máximo órgano judicial de un Estado, división administrativa o otro tipo de organización" "es")
(descr-as-in "highest-judicial-authority" "主題の国や地域・地方行政区画やその他の組織において、最上位の司法機関" "ja")
(descr-as-in "highest-judicial-authority" "" "zh-cn")
(descr-as-in "highest-judicial-authority" "" "zh-sg")

