(ns properties.human_development_index
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "human-development-index")

(name-as-in "human-development-index" "人類發展指數" "zh-hk")
(name-as-in "human-development-index" "Índice de Desenvolvimento Humano" "pt")
(name-as-in "human-development-index" "Human Development Index" "en")
(name-as-in "human-development-index" "indice de développement humain" "fr")
(name-as-in "human-development-index" "人類發展指數" "zh-tw")
(name-as-in "human-development-index" "Index der menschlichen Entwicklung" "de")
(name-as-in "human-development-index" "индекс человеческого развития" "ru")
(name-as-in "human-development-index" "índice de desarrollo humano" "es")
(name-as-in "human-development-index" "人間開発指数" "ja")
(name-as-in "human-development-index" "人类发展指数" "zh-cn")
(name-as-in "human-development-index" "人类发展指数" "zh-sg")

(descr-as-in "human-development-index" "" "zh-hk")
(descr-as-in "human-development-index" "IDH de um país" "pt")
(descr-as-in "human-development-index" "HDI value of a country" "en")
(descr-as-in "human-development-index" "" "fr")
(descr-as-in "human-development-index" "" "zh-tw")
(descr-as-in "human-development-index" "Wohlstandsindikator der Vereinten Nationen" "de")
(descr-as-in "human-development-index" "" "ru")
(descr-as-in "human-development-index" "" "es")
(descr-as-in "human-development-index" "" "ja")
(descr-as-in "human-development-index" "" "zh-cn")
(descr-as-in "human-development-index" "" "zh-sg")

