(ns properties.image_of_grave
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "image-of-grave")

(name-as-in "image-of-grave" "" "zh-hk")
(name-as-in "image-of-grave" "imagem do túmulo" "pt")
(name-as-in "image-of-grave" "image of grave" "en")
(name-as-in "image-of-grave" "image de la tombe" "fr")
(name-as-in "image-of-grave" "" "zh-tw")
(name-as-in "image-of-grave" "Bild des Grabes" "de")
(name-as-in "image-of-grave" "изображение могилы" "ru")
(name-as-in "image-of-grave" "imagen de la tumba" "es")
(name-as-in "image-of-grave" "墓の画像" "ja")
(name-as-in "image-of-grave" "" "zh-cn")
(name-as-in "image-of-grave" "" "zh-sg")

(descr-as-in "image-of-grave" "" "zh-hk")
(descr-as-in "image-of-grave" "" "pt")
(descr-as-in "image-of-grave" "picture of a person or animal's grave, gravestone or tomb" "en")
(descr-as-in "image-of-grave" "sert à identifier l'image de la tombe d'une personne" "fr")
(descr-as-in "image-of-grave" "" "zh-tw")
(descr-as-in "image-of-grave" "Bild des Grabes, Grabsteines etc. einer Person oder eines Tieres" "de")
(descr-as-in "image-of-grave" "изображение места, где персона похоронена" "ru")
(descr-as-in "image-of-grave" "" "es")
(descr-as-in "image-of-grave" "人・動物の墓・墓石の写真" "ja")
(descr-as-in "image-of-grave" "" "zh-cn")
(descr-as-in "image-of-grave" "" "zh-sg")

