(ns properties.image
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "image")

(name-as-in "image" "圖片" "zh-hk")
(name-as-in "image" "imagem" "pt")
(name-as-in "image" "image" "en")
(name-as-in "image" "image" "fr")
(name-as-in "image" "圖像" "zh-tw")
(name-as-in "image" "Bild" "de")
(name-as-in "image" "изображение" "ru")
(name-as-in "image" "imagen" "es")
(name-as-in "image" "画像" "ja")
(name-as-in "image" "图像" "zh-cn")
(name-as-in "image" "图像" "zh-sg")

(descr-as-in "image" "" "zh-hk")
(descr-as-in "image" "uma ilustração relevante" "pt")
(descr-as-in "image" "image of relevant illustration of the subject; if available, use more specific properties (sample: coat of arms image, locator map, flag image, signature image, logo image, collage image); only images which exist on Wikimedia Commons are acceptable" "en")
(descr-as-in "image" "image illustrant l'élément ; voir page de discussion pour d'autres propriétés" "fr")
(descr-as-in "image" "" "zh-tw")
(descr-as-in "image" "Foto, Grafik etc. des Objekts" "de")
(descr-as-in "image" "соответствующая иллюстрация" "ru")
(descr-as-in "image" "imagen ilustrativa del elemento" "es")
(descr-as-in "image" "関連する画像、挿絵" "ja")
(descr-as-in "image" "" "zh-cn")
(descr-as-in "image" "" "zh-sg")

