(ns properties.imdb_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "imdb-id")

(name-as-in "imdb-id" "IMDb編號" "zh-hk")
(name-as-in "imdb-id" "identificador IMDb" "pt")
(name-as-in "imdb-id" "IMDb ID" "en")
(name-as-in "imdb-id" "identifiant IMDb" "fr")
(name-as-in "imdb-id" "IMDb編號" "zh-tw")
(name-as-in "imdb-id" "IMDb-ID" "de")
(name-as-in "imdb-id" "код IMDb" "ru")
(name-as-in "imdb-id" "identificador IMDb" "es")
(name-as-in "imdb-id" "IMDb識別子" "ja")
(name-as-in "imdb-id" "IMDb编号" "zh-cn")
(name-as-in "imdb-id" "IMDb编号" "zh-sg")

(descr-as-in "imdb-id" "互聯網電影數據庫（IMDb）編號，前綴為 (tt-, nm-, ch-, co-)" "zh-hk")
(descr-as-in "imdb-id" "identificador do Internet Movie Database (IMDb) com o prefixo (tt- nm- ch- co-)" "pt")
(descr-as-in "imdb-id" "identifier from the Internet Movie Database (IMDb) with prefix ('tt', 'nm', 'ch', 'co', 'ev' or 'ni')" "en")
(descr-as-in "imdb-id" "identifiant Internet Movie Database (IMDb) avec un préfixe (tt-, nm-, ch-, co-, ni-)" "fr")
(descr-as-in "imdb-id" "網路電影資料庫（IMDB）編號，前綴為（tt-, nm-, ch-, co-）" "zh-tw")
(descr-as-in "imdb-id" "Identifikationsnummer in der Internet Movie Database (IMDb) inklusive Präfix (tt-, nm-, ch-, ev-, co-, ni-)" "de")
(descr-as-in "imdb-id" "код в Internet Movie Database (IMDb) с префиксом (tt-, nm-, ch-, co-, ev-)" "ru")
(descr-as-in "imdb-id" "identificador para la Internet Movie Database (IMDb) con prefijo (tt- nm- ch- co-)" "es")
(descr-as-in "imdb-id" "インターネット・ムービー・データベース（IMDb）のtt、nm、ch、coで始まる識別子" "ja")
(descr-as-in "imdb-id" "互联网电影数据库（IMDB）编号，前缀为（tt-, nm-, ch-, co-）" "zh-cn")
(descr-as-in "imdb-id" "互联网电影数据库（IMDB）编号，前缀为（tt-, nm-, ch-, co-）" "zh-sg")

