(ns properties.indigenous_to
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "indigenous-to")

(name-as-in "indigenous-to" "" "zh-hk")
(name-as-in "indigenous-to" "nativo de" "pt")
(name-as-in "indigenous-to" "indigenous to" "en")
(name-as-in "indigenous-to" "autochtone de" "fr")
(name-as-in "indigenous-to" "" "zh-tw")
(name-as-in "indigenous-to" "heimisch" "de")
(name-as-in "indigenous-to" "происходит из" "ru")
(name-as-in "indigenous-to" "nativo de" "es")
(name-as-in "indigenous-to" "" "ja")
(name-as-in "indigenous-to" "" "zh-cn")
(name-as-in "indigenous-to" "" "zh-sg")

(descr-as-in "indigenous-to" "" "zh-hk")
(descr-as-in "indigenous-to" "" "pt")
(descr-as-in "indigenous-to" "area or ethnic group that a language, folk dance, cooking style or other cultural expression is found (or was originally found)" "en")
(descr-as-in "indigenous-to" "région ou groupe ethnique où une langue, une danse traditionnelle, une cuisine ou toute autre expression culturelle se trouve (ou a été trouvée à l'origine)" "fr")
(descr-as-in "indigenous-to" "" "zh-tw")
(descr-as-in "indigenous-to" "" "de")
(descr-as-in "indigenous-to" "регион или этническая группа, откуда происходит язык, танец, стиль готовки или другое средство культурной выразительности" "ru")
(descr-as-in "indigenous-to" "área o grupo étnico en donde se encuentra originalmente un idioma o expresión cultural" "es")
(descr-as-in "indigenous-to" "" "ja")
(descr-as-in "indigenous-to" "" "zh-cn")
(descr-as-in "indigenous-to" "" "zh-sg")

