(ns properties.instagram_username
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "instagram-username")

(name-as-in "instagram-username" "Instagram用戶名" "zh-hk")
(name-as-in "instagram-username" "nome de utilizador no Instagram" "pt")
(name-as-in "instagram-username" "Instagram username" "en")
(name-as-in "instagram-username" "nom d'usager Instagram" "fr")
(name-as-in "instagram-username" "Instagram使用者名稱" "zh-tw")
(name-as-in "instagram-username" "Instagram-Benutzername" "de")
(name-as-in "instagram-username" "учётная запись в Instagram" "ru")
(name-as-in "instagram-username" "nombre de usuario de Instagram" "es")
(name-as-in "instagram-username" "インスタグラムのユーザー名" "ja")
(name-as-in "instagram-username" "Instagram用户名" "zh-cn")
(name-as-in "instagram-username" "Instagram用户名" "zh-sg")

(descr-as-in "instagram-username" "此項在Instagram上的用戶名" "zh-hk")
(descr-as-in "instagram-username" "nome de utilizador do item no Instagram" "pt")
(descr-as-in "instagram-username" "item's username on Instagram" "en")
(descr-as-in "instagram-username" "nom d'usager du site web Instagram" "fr")
(descr-as-in "instagram-username" "此項在Instagram上的使用者名稱" "zh-tw")
(descr-as-in "instagram-username" "Name des Instagramkontos eines Projekts / einer Person" "de")
(descr-as-in "instagram-username" "имя аккаунта персоны в Instagram" "ru")
(descr-as-in "instagram-username" "nombre de usuario en Instagram" "es")
(descr-as-in "instagram-username" "インスタグラムのユーザー名を記すための項目" "ja")
(descr-as-in "instagram-username" "此项在Instagram上的用户名" "zh-cn")
(descr-as-in "instagram-username" "此项在Instagram上的用户名" "zh-sg")

