(ns properties.instance_of
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "instance-of")

(name-as-in "instance-of" "性質" "zh-hk")
(name-as-in "instance-of" "instância de" "pt")
(name-as-in "instance-of" "instance of" "en")
(name-as-in "instance-of" "nature de l'élément" "fr")
(name-as-in "instance-of" "性質" "zh-tw")
(name-as-in "instance-of" "ist ein(e)" "de")
(name-as-in "instance-of" "это частный случай понятия" "ru")
(name-as-in "instance-of" "instancia de" "es")
(name-as-in "instance-of" "分類" "ja")
(name-as-in "instance-of" "性质" "zh-cn")
(name-as-in "instance-of" "性质" "zh-sg")

(descr-as-in "instance-of" "本項目所屬的性質，本以項目為實例的類別" "zh-hk")
(descr-as-in "instance-of" "este item é uma instância deste outro item" "pt")
(descr-as-in "instance-of" "that class of which this subject is a particular example and member. (Subject typically an individual member with Proper Name label.) Different from P279 (subclass of)" "en")
(descr-as-in "instance-of" "Cet élément est un exemple spécifique de cette classe qui en précise la nature. Ne pas confondre avec la propriété P279 (sous-classe de)." "fr")
(descr-as-in "instance-of" "本項目所屬的性質，本以項目為實例的類別" "zh-tw")
(descr-as-in "instance-of" "Ausprägung oder Exemplar einer Sache, Mitglied einer Klasse. Unterscheide von P279 (Unterklasse von)." "de")
(descr-as-in "instance-of" "данный элемент представляет собой конкретный объект (экземпляр / частный случай) класса, категории. Не путать с Property:P279 (подкласс от)." "ru")
(descr-as-in "instance-of" "este elemento es un ejemplar del otro elemento" "es")
(descr-as-in "instance-of" "この項目をインスタンスとする種類・概念" "ja")
(descr-as-in "instance-of" "本项目所属的性质，本以项目为实例的类别" "zh-cn")
(descr-as-in "instance-of" "本项目所属的性质，本以项目为实例的类别" "zh-sg")

