(ns properties.internetmedicin_se_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "internetmedicin_se-id")

(name-as-in "internetmedicin_se-id" "" "zh-hk")
(name-as-in "internetmedicin_se-id" "" "pt")
(name-as-in "internetmedicin_se-id" "internetmedicin.se ID" "en")
(name-as-in "internetmedicin_se-id" "identifiant internetmedicin.se" "fr")
(name-as-in "internetmedicin_se-id" "" "zh-tw")
(name-as-in "internetmedicin_se-id" "internetmedicin.se-ID" "de")
(name-as-in "internetmedicin_se-id" "код internetmedicin.se" "ru")
(name-as-in "internetmedicin_se-id" "internetmedicin.se" "es")
(name-as-in "internetmedicin_se-id" "" "ja")
(name-as-in "internetmedicin_se-id" "" "zh-cn")
(name-as-in "internetmedicin_se-id" "" "zh-sg")

(descr-as-in "internetmedicin_se-id" "" "zh-hk")
(descr-as-in "internetmedicin_se-id" "" "pt")
(descr-as-in "internetmedicin_se-id" "ID in the Swedish database about medical topics" "en")
(descr-as-in "internetmedicin_se-id" "identifiant dans la base de données suédoise pour les éléments en lien avec le médical" "fr")
(descr-as-in "internetmedicin_se-id" "" "zh-tw")
(descr-as-in "internetmedicin_se-id" "" "de")
(descr-as-in "internetmedicin_se-id" "шведская база данных по медицинским темам" "ru")
(descr-as-in "internetmedicin_se-id" "" "es")
(descr-as-in "internetmedicin_se-id" "" "ja")
(descr-as-in "internetmedicin_se-id" "" "zh-cn")
(descr-as-in "internetmedicin_se-id" "" "zh-sg")

