(ns properties.integrated_postsecondary_education_data_system_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "integrated-postsecondary-education-data-system-id")

(name-as-in "integrated-postsecondary-education-data-system-id" "" "zh-hk")
(name-as-in "integrated-postsecondary-education-data-system-id" "" "pt")
(name-as-in "integrated-postsecondary-education-data-system-id" "Integrated Postsecondary Education Data System ID" "en")
(name-as-in "integrated-postsecondary-education-data-system-id" "identifiant IPEDS" "fr")
(name-as-in "integrated-postsecondary-education-data-system-id" "" "zh-tw")
(name-as-in "integrated-postsecondary-education-data-system-id" "IPEDS-ID" "de")
(name-as-in "integrated-postsecondary-education-data-system-id" "код IPEDS" "ru")
(name-as-in "integrated-postsecondary-education-data-system-id" "" "es")
(name-as-in "integrated-postsecondary-education-data-system-id" "" "ja")
(name-as-in "integrated-postsecondary-education-data-system-id" "" "zh-cn")
(name-as-in "integrated-postsecondary-education-data-system-id" "" "zh-sg")

(descr-as-in "integrated-postsecondary-education-data-system-id" "" "zh-hk")
(descr-as-in "integrated-postsecondary-education-data-system-id" "" "pt")
(descr-as-in "integrated-postsecondary-education-data-system-id" "identifier for colleges and universities in the United States" "en")
(descr-as-in "integrated-postsecondary-education-data-system-id" "identifiant de l'Integrated Postsecondary Education Data System (IPEDS) pour les universités des États-Unis" "fr")
(descr-as-in "integrated-postsecondary-education-data-system-id" "" "zh-tw")
(descr-as-in "integrated-postsecondary-education-data-system-id" "" "de")
(descr-as-in "integrated-postsecondary-education-data-system-id" "код Integrated Postsecondary Education Data System" "ru")
(descr-as-in "integrated-postsecondary-education-data-system-id" "" "es")
(descr-as-in "integrated-postsecondary-education-data-system-id" "" "ja")
(descr-as-in "integrated-postsecondary-education-data-system-id" "" "zh-cn")
(descr-as-in "integrated-postsecondary-education-data-system-id" "" "zh-sg")

