(ns properties.ipv4_routing_prefix
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "ipv4-routing-prefix")

(name-as-in "ipv4-routing-prefix" "" "zh-hk")
(name-as-in "ipv4-routing-prefix" "intervalo de endereços IPv4" "pt")
(name-as-in "ipv4-routing-prefix" "IPv4 routing prefix" "en")
(name-as-in "ipv4-routing-prefix" "plage IPv4" "fr")
(name-as-in "ipv4-routing-prefix" "" "zh-tw")
(name-as-in "ipv4-routing-prefix" "IPv4-Bereich" "de")
(name-as-in "ipv4-routing-prefix" "диапазон IPv4" "ru")
(name-as-in "ipv4-routing-prefix" "rango IPv4" "es")
(name-as-in "ipv4-routing-prefix" "" "ja")
(name-as-in "ipv4-routing-prefix" "" "zh-cn")
(name-as-in "ipv4-routing-prefix" "" "zh-sg")

(descr-as-in "ipv4-routing-prefix" "" "zh-hk")
(descr-as-in "ipv4-routing-prefix" "" "pt")
(descr-as-in "ipv4-routing-prefix" "range of IPv4 addresses" "en")
(descr-as-in "ipv4-routing-prefix" "plage d'adresses IPv4 possédées" "fr")
(descr-as-in "ipv4-routing-prefix" "" "zh-tw")
(descr-as-in "ipv4-routing-prefix" "Bereich der IPv4 Adressen, die einer Organisation gehören" "de")
(descr-as-in "ipv4-routing-prefix" "" "ru")
(descr-as-in "ipv4-routing-prefix" "rango de direcciones IPv4 poseídas" "es")
(descr-as-in "ipv4-routing-prefix" "" "ja")
(descr-as-in "ipv4-routing-prefix" "" "zh-cn")
(descr-as-in "ipv4-routing-prefix" "" "zh-sg")

