(ns properties.ipv6_routing_prefix
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "ipv6-routing-prefix")

(name-as-in "ipv6-routing-prefix" "" "zh-hk")
(name-as-in "ipv6-routing-prefix" "" "pt")
(name-as-in "ipv6-routing-prefix" "IPv6 routing prefix" "en")
(name-as-in "ipv6-routing-prefix" "plage IPv6" "fr")
(name-as-in "ipv6-routing-prefix" "" "zh-tw")
(name-as-in "ipv6-routing-prefix" "IPv6-Präfix" "de")
(name-as-in "ipv6-routing-prefix" "" "ru")
(name-as-in "ipv6-routing-prefix" "rango IPv6" "es")
(name-as-in "ipv6-routing-prefix" "" "ja")
(name-as-in "ipv6-routing-prefix" "" "zh-cn")
(name-as-in "ipv6-routing-prefix" "" "zh-sg")

(descr-as-in "ipv6-routing-prefix" "" "zh-hk")
(descr-as-in "ipv6-routing-prefix" "" "pt")
(descr-as-in "ipv6-routing-prefix" "range of IPv6 addresses" "en")
(descr-as-in "ipv6-routing-prefix" "plage d'adresses IPv6 possédées" "fr")
(descr-as-in "ipv6-routing-prefix" "" "zh-tw")
(descr-as-in "ipv6-routing-prefix" "" "de")
(descr-as-in "ipv6-routing-prefix" "" "ru")
(descr-as-in "ipv6-routing-prefix" "" "es")
(descr-as-in "ipv6-routing-prefix" "" "ja")
(descr-as-in "ipv6-routing-prefix" "" "zh-cn")
(descr-as-in "ipv6-routing-prefix" "" "zh-sg")

