(ns properties.isni
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "isni")

(name-as-in "isni" "ISNI編號" "zh-hk")
(name-as-in "isni" "identificador ISNI" "pt")
(name-as-in "isni" "ISNI" "en")
(name-as-in "isni" "identifiant ISNI" "fr")
(name-as-in "isni" "國際標準名稱標識符" "zh-tw")
(name-as-in "isni" "ISNI" "de")
(name-as-in "isni" "код ISNI" "ru")
(name-as-in "isni" "ISNI" "es")
(name-as-in "isni" "ISNI" "ja")
(name-as-in "isni" "国际标准名称标识符" "zh-cn")
(name-as-in "isni" "" "zh-sg")

(descr-as-in "isni" "" "zh-hk")
(descr-as-in "isni" "" "pt")
(descr-as-in "isni" "International Standard Name Identifier for an identity. Format: 4 blocks of 4 digits separated by a space, first block is 0000." "en")
(descr-as-in "isni" "code international normalisé des noms" "fr")
(descr-as-in "isni" "" "zh-tw")
(descr-as-in "isni" "International Standard Name Identifier (Eingabe mit Leerzeichen. Beispiel: 0000 0001 0886 1508.)" "de")
(descr-as-in "isni" "шестнадцатизначный Международный идентификатор стандартных наименований (по ISO 27729)" "ru")
(descr-as-in "isni" "International Standard Name Identifier" "es")
(descr-as-in "isni" "国際標準名称識別子。-を含まない16文字の識別子を使用。" "ja")
(descr-as-in "isni" "" "zh-cn")
(descr-as-in "isni" "" "zh-sg")

