(ns properties.italian_cadastre_code
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "italian-cadastre-code")

(name-as-in "italian-cadastre-code" "italienische Kataster-ID" "de")
(name-as-in "italian-cadastre-code" "" "zh-hk")
(name-as-in "italian-cadastre-code" "" "zh-tw")
(name-as-in "italian-cadastre-code" "" "ru")
(name-as-in "italian-cadastre-code" "" "pt")
(name-as-in "italian-cadastre-code" "Italian cadastre code" "en")
(name-as-in "italian-cadastre-code" "" "zh-cn")
(name-as-in "italian-cadastre-code" "" "fr")
(name-as-in "italian-cadastre-code" "" "es")
(name-as-in "italian-cadastre-code" "" "zh-sg")
(name-as-in "italian-cadastre-code" "" "ja")
(name-as-in "italian-cadastre-code" "" "zh-hans")
(name-as-in "italian-cadastre-code" "" "zh-hant")

(descr-as-in "italian-cadastre-code" "" "de")
(descr-as-in "italian-cadastre-code" "" "zh-hk")
(descr-as-in "italian-cadastre-code" "" "zh-tw")
(descr-as-in "italian-cadastre-code" "" "ru")
(descr-as-in "italian-cadastre-code" "" "pt")
(descr-as-in "italian-cadastre-code" "identifies Italian comunes in the cadastre" "en")
(descr-as-in "italian-cadastre-code" "" "zh-cn")
(descr-as-in "italian-cadastre-code" "" "fr")
(descr-as-in "italian-cadastre-code" "" "es")
(descr-as-in "italian-cadastre-code" "" "zh-sg")
(descr-as-in "italian-cadastre-code" "" "ja")
(descr-as-in "italian-cadastre-code" "" "zh-hans")
(descr-as-in "italian-cadastre-code" "" "zh-hant")

