(ns properties.item_operated
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "item-operated")

(name-as-in "item-operated" "營運" "zh-hk")
(name-as-in "item-operated" "item operado" "pt")
(name-as-in "item-operated" "item operated" "en")
(name-as-in "item-operated" "élément opéré" "fr")
(name-as-in "item-operated" "" "zh-tw")
(name-as-in "item-operated" "eingesetztes Objekt" "de")
(name-as-in "item-operated" "использует объект" "ru")
(name-as-in "item-operated" "elemento operado" "es")
(name-as-in "item-operated" "以下を運用する" "ja")
(name-as-in "item-operated" "" "zh-cn")
(name-as-in "item-operated" "" "zh-sg")

(descr-as-in "item-operated" "" "zh-hk")
(descr-as-in "item-operated" "equipamento, instalação ou serviço operado pelo sujeito" "pt")
(descr-as-in "item-operated" "equipment, installation or service operated by the subject" "en")
(descr-as-in "item-operated" "équipement, installation ou service opéré ou utilisé par le sujet" "fr")
(descr-as-in "item-operated" "" "zh-tw")
(descr-as-in "item-operated" "eingesetztes Objekt" "de")
(descr-as-in "item-operated" "используемое оборудование или услуга" "ru")
(descr-as-in "item-operated" "equipo, instalación o servicio operado por el sujeto" "es")
(descr-as-in "item-operated" "この組織は以下の施設・設備・サービスを保有・運営・運用する" "ja")
(descr-as-in "item-operated" "" "zh-cn")
(descr-as-in "item-operated" "" "zh-sg")

