(ns properties.jstor_topic_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "jstor-topic-id")

(name-as-in "jstor-topic-id" "" "zh-hk")
(name-as-in "jstor-topic-id" "" "pt")
(name-as-in "jstor-topic-id" "JSTOR topic ID" "en")
(name-as-in "jstor-topic-id" "identifiant de sujet JSTOR" "fr")
(name-as-in "jstor-topic-id" "" "zh-tw")
(name-as-in "jstor-topic-id" "JSTOR-Themen-ID" "de")
(name-as-in "jstor-topic-id" "тема JSTOR" "ru")
(name-as-in "jstor-topic-id" "identificador JSTOR de tema" "es")
(name-as-in "jstor-topic-id" "" "ja")
(name-as-in "jstor-topic-id" "" "zh-cn")
(name-as-in "jstor-topic-id" "" "zh-sg")

(descr-as-in "jstor-topic-id" "" "zh-hk")
(descr-as-in "jstor-topic-id" "" "pt")
(descr-as-in "jstor-topic-id" "identifier for a topic at JSTOR" "en")
(descr-as-in "jstor-topic-id" "identifiant pour un sujet sur JSTOR" "fr")
(descr-as-in "jstor-topic-id" "" "zh-tw")
(descr-as-in "jstor-topic-id" "" "de")
(descr-as-in "jstor-topic-id" "" "ru")
(descr-as-in "jstor-topic-id" "identificador para un tema en JSTOR" "es")
(descr-as-in "jstor-topic-id" "" "ja")
(descr-as-in "jstor-topic-id" "" "zh-cn")
(descr-as-in "jstor-topic-id" "" "zh-sg")

