(ns properties.knaw_past_member_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "knaw-past-member-id")

(name-as-in "knaw-past-member-id" "" "zh-hk")
(name-as-in "knaw-past-member-id" "" "pt")
(name-as-in "knaw-past-member-id" "KNAW past member ID" "en")
(name-as-in "knaw-past-member-id" "identifiant KNAW Past Members" "fr")
(name-as-in "knaw-past-member-id" "" "zh-tw")
(name-as-in "knaw-past-member-id" "KNAW-Nummer" "de")
(name-as-in "knaw-past-member-id" "код KNAW Past Members" "ru")
(name-as-in "knaw-past-member-id" "identificador KNAW Historisch Ledenbestand" "es")
(name-as-in "knaw-past-member-id" "" "ja")
(name-as-in "knaw-past-member-id" "" "zh-cn")
(name-as-in "knaw-past-member-id" "" "zh-sg")

(descr-as-in "knaw-past-member-id" "" "zh-hk")
(descr-as-in "knaw-past-member-id" "" "pt")
(descr-as-in "knaw-past-member-id" "identifier for people in the Royal Netherlands Academy of Arts and Sciences past member database" "en")
(descr-as-in "knaw-past-member-id" "" "fr")
(descr-as-in "knaw-past-member-id" "" "zh-tw")
(descr-as-in "knaw-past-member-id" "" "de")
(descr-as-in "knaw-past-member-id" "база данных бывших членов Нидерландской королевской академии наук" "ru")
(descr-as-in "knaw-past-member-id" "" "es")
(descr-as-in "knaw-past-member-id" "" "ja")
(descr-as-in "knaw-past-member-id" "" "zh-cn")
(descr-as-in "knaw-past-member-id" "" "zh-sg")

