(ns properties.kvk_company_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "kvk-company-id")

(name-as-in "kvk-company-id" "" "zh-hk")
(name-as-in "kvk-company-id" "" "pt")
(name-as-in "kvk-company-id" "KvK company ID" "en")
(name-as-in "kvk-company-id" "identifiant KvK" "fr")
(name-as-in "kvk-company-id" "" "zh-tw")
(name-as-in "kvk-company-id" "KvK-ID" "de")
(name-as-in "kvk-company-id" "" "ru")
(name-as-in "kvk-company-id" "" "es")
(name-as-in "kvk-company-id" "" "ja")
(name-as-in "kvk-company-id" "" "zh-cn")
(name-as-in "kvk-company-id" "" "zh-sg")

(descr-as-in "kvk-company-id" "" "zh-hk")
(descr-as-in "kvk-company-id" "" "pt")
(descr-as-in "kvk-company-id" "identifier of a company in the KvK Business Register" "en")
(descr-as-in "kvk-company-id" "identifiant d'une entreprise dans le registre KvK" "fr")
(descr-as-in "kvk-company-id" "" "zh-tw")
(descr-as-in "kvk-company-id" "niederländisches Unternehmensregister (Kamer van Koophandel)" "de")
(descr-as-in "kvk-company-id" "" "ru")
(descr-as-in "kvk-company-id" "" "es")
(descr-as-in "kvk-company-id" "" "ja")
(descr-as-in "kvk-company-id" "" "zh-cn")
(descr-as-in "kvk-company-id" "" "zh-sg")

