(ns properties.language_used
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "language-used")

(name-as-in "language-used" "" "zh-hk")
(name-as-in "language-used" "idioma usado" "pt")
(name-as-in "language-used" "language used" "en")
(name-as-in "language-used" "langue utilisée" "fr")
(name-as-in "language-used" "" "zh-tw")
(name-as-in "language-used" "genutzte Sprache" "de")
(name-as-in "language-used" "используемый язык" "ru")
(name-as-in "language-used" "idioma usado" "es")
(name-as-in "language-used" "" "ja")
(name-as-in "language-used" "" "zh-cn")
(name-as-in "language-used" "" "zh-sg")

(descr-as-in "language-used" "" "zh-hk")
(descr-as-in "language-used" "língua usada amplamente (em forma oral ou escrita) neste local ou evento" "pt")
(descr-as-in "language-used" "language widely used (spoken or written) in this place or at this event" "en")
(descr-as-in "language-used" "langue largement utilisée (parlée ou écrite) à cet endroit ou lors de cet événement" "fr")
(descr-as-in "language-used" "" "zh-tw")
(descr-as-in "language-used" "Sprache (gesprochen oder geschrieben), die an diesem Ort/dieser Veranstaltung genutzt wird" "de")
(descr-as-in "language-used" "язык широко используется (в разговорной или письменной форме) в этом месте или событии" "ru")
(descr-as-in "language-used" "lengua ampliamente usada (hablada o escrita) en este lugar o evento" "es")
(descr-as-in "language-used" "" "ja")
(descr-as-in "language-used" "" "zh-cn")
(descr-as-in "language-used" "" "zh-sg")

