(ns properties.language_regulatory_body
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "language-regulatory-body")

(name-as-in "language-regulatory-body" "" "zh-hk")
(name-as-in "language-regulatory-body" "órgão regulador do idioma" "pt")
(name-as-in "language-regulatory-body" "language regulatory body" "en")
(name-as-in "language-regulatory-body" "institution de normalisation" "fr")
(name-as-in "language-regulatory-body" "" "zh-tw")
(name-as-in "language-regulatory-body" "Kontrollorgan der Sprache" "de")
(name-as-in "language-regulatory-body" "регулятор языка" "ru")
(name-as-in "language-regulatory-body" "institución de normalización" "es")
(name-as-in "language-regulatory-body" "言語統制機関" "ja")
(name-as-in "language-regulatory-body" "" "zh-cn")
(name-as-in "language-regulatory-body" "" "zh-sg")

(descr-as-in "language-regulatory-body" "" "zh-hk")
(descr-as-in "language-regulatory-body" "" "pt")
(descr-as-in "language-regulatory-body" "regulatory body of a language" "en")
(descr-as-in "language-regulatory-body" "organisation chargée d'améliorer ou de normaliser une langue" "fr")
(descr-as-in "language-regulatory-body" "" "zh-tw")
(descr-as-in "language-regulatory-body" "Behörde, derer die Reglementierung einer Sprache obliegt" "de")
(descr-as-in "language-regulatory-body" "организация управляющая стандартизацией языка" "ru")
(descr-as-in "language-regulatory-body" "órgano regulador de una lengua" "es")
(descr-as-in "language-regulatory-body" "言語の統制を行う組織" "ja")
(descr-as-in "language-regulatory-body" "" "zh-cn")
(descr-as-in "language-regulatory-body" "" "zh-sg")

