(ns properties.leader
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "leader")

(name-as-in "leader" "主席" "zh-hk")
(name-as-in "leader" "presidente" "pt")
(name-as-in "leader" "leader" "en")
(name-as-in "leader" "président" "fr")
(name-as-in "leader" "主席" "zh-tw")
(name-as-in "leader" "Vorsitzender" "de")
(name-as-in "leader" "руководитель" "ru")
(name-as-in "leader" "presidente" "es")
(name-as-in "leader" "会長" "ja")
(name-as-in "leader" "主席" "zh-cn")
(name-as-in "leader" "主席" "zh-sg")

(descr-as-in "leader" "機構的主席" "zh-hk")
(descr-as-in "leader" "presidente de alguma organização ou grupo" "pt")
(descr-as-in "leader" "presiding member of an organization, group or body" "en")
(descr-as-in "leader" "président d'une assemblée de membres d'une organisation ou d'un groupe ; utiliser P6 pour le chef de l'exécutif d'une assemblée" "fr")
(descr-as-in "leader" "" "zh-tw")
(descr-as-in "leader" "Vorsitzendes Mitglied einer Organisation oder Körperschaft" "de")
(descr-as-in "leader" "председательствующий участник организации, группы или учреждения" "ru")
(descr-as-in "leader" "presidente de una organización o grupo" "es")
(descr-as-in "leader" "主題の組織や団体を主宰する人物" "ja")
(descr-as-in "leader" "" "zh-cn")
(descr-as-in "leader" "" "zh-sg")

