(ns properties.legislative_body
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "legislative-body")

(name-as-in "legislative-body" "立法機構" "zh-hk")
(name-as-in "legislative-body" "órgão legislativo" "pt")
(name-as-in "legislative-body" "legislative body" "en")
(name-as-in "legislative-body" "assemblée délibérante" "fr")
(name-as-in "legislative-body" "立法機構" "zh-tw")
(name-as-in "legislative-body" "gesetzgebende Körperschaft" "de")
(name-as-in "legislative-body" "законодательный орган" "ru")
(name-as-in "legislative-body" "órgano legislativo" "es")
(name-as-in "legislative-body" "立法府" "ja")
(name-as-in "legislative-body" "立法机构" "zh-cn")
(name-as-in "legislative-body" "立法机构" "zh-sg")

(descr-as-in "legislative-body" "" "zh-hk")
(descr-as-in "legislative-body" "" "pt")
(descr-as-in "legislative-body" "legislative body governing this entity; political institution with elected representatives, such as a parliament/legislature or council" "en")
(descr-as-in "legislative-body" "assemblée où siègent les représentants élus ou désignés dans la circonscription" "fr")
(descr-as-in "legislative-body" "" "zh-tw")
(descr-as-in "legislative-body" "politische Institution mit gewählten oder berufenen Vertretern wie ein Parlament oder ein Rat" "de")
(descr-as-in "legislative-body" "собрание избираемых представителей, уполномоченное принимать законы" "ru")
(descr-as-in "legislative-body" "institución política con representantes electos" "es")
(descr-as-in "legislative-body" "選挙で選ばれた代表から成る政治機関。議会や国会など。" "ja")
(descr-as-in "legislative-body" "" "zh-cn")
(descr-as-in "legislative-body" "" "zh-sg")

