(ns properties.leidse_hoogleraren_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "leidse-hoogleraren-id")

(name-as-in "leidse-hoogleraren-id" "" "zh-hk")
(name-as-in "leidse-hoogleraren-id" "" "pt")
(name-as-in "leidse-hoogleraren-id" "Leidse Hoogleraren ID" "en")
(name-as-in "leidse-hoogleraren-id" "identifiant Leidse Hoogleraren" "fr")
(name-as-in "leidse-hoogleraren-id" "" "zh-tw")
(name-as-in "leidse-hoogleraren-id" "" "de")
(name-as-in "leidse-hoogleraren-id" "" "ru")
(name-as-in "leidse-hoogleraren-id" "identificador Leidse Hoogleraren" "es")
(name-as-in "leidse-hoogleraren-id" "" "ja")
(name-as-in "leidse-hoogleraren-id" "" "zh-cn")
(name-as-in "leidse-hoogleraren-id" "" "zh-sg")

(descr-as-in "leidse-hoogleraren-id" "" "zh-hk")
(descr-as-in "leidse-hoogleraren-id" "" "pt")
(descr-as-in "leidse-hoogleraren-id" "Identifier in the Leidse Hoogleraren, a catalogue of University Professors of Leiden University since 1575." "en")
(descr-as-in "leidse-hoogleraren-id" "" "fr")
(descr-as-in "leidse-hoogleraren-id" "" "zh-tw")
(descr-as-in "leidse-hoogleraren-id" "" "de")
(descr-as-in "leidse-hoogleraren-id" "" "ru")
(descr-as-in "leidse-hoogleraren-id" "" "es")
(descr-as-in "leidse-hoogleraren-id" "" "ja")
(descr-as-in "leidse-hoogleraren-id" "" "zh-cn")
(descr-as-in "leidse-hoogleraren-id" "" "zh-sg")

