(ns properties.les_archives_du_spectacle_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "les-archives-du-spectacle-id")

(name-as-in "les-archives-du-spectacle-id" "" "zh-hk")
(name-as-in "les-archives-du-spectacle-id" "" "pt")
(name-as-in "les-archives-du-spectacle-id" "Les Archives du Spectacle ID" "en")
(name-as-in "les-archives-du-spectacle-id" "identifiant lesarchivesduspectacle" "fr")
(name-as-in "les-archives-du-spectacle-id" "" "zh-tw")
(name-as-in "les-archives-du-spectacle-id" "ID von lesarchivesduspectacle" "de")
(name-as-in "les-archives-du-spectacle-id" "код lesarchivesduspectacle" "ru")
(name-as-in "les-archives-du-spectacle-id" "identificador lesarchivesduspectacle" "es")
(name-as-in "les-archives-du-spectacle-id" "" "ja")
(name-as-in "les-archives-du-spectacle-id" "" "zh-cn")
(name-as-in "les-archives-du-spectacle-id" "" "zh-sg")

(descr-as-in "les-archives-du-spectacle-id" "" "zh-hk")
(descr-as-in "les-archives-du-spectacle-id" "" "pt")
(descr-as-in "les-archives-du-spectacle-id" "Identifier for an actor/actress/playwright/play, in the lesarchivesduspectacle database of actors/actresses" "en")
(descr-as-in "les-archives-du-spectacle-id" "identifiant pour un acteur dans la base de données lesarchivesduspectacle des acteurs" "fr")
(descr-as-in "les-archives-du-spectacle-id" "" "zh-tw")
(descr-as-in "les-archives-du-spectacle-id" "ID für Schauspieler in der Datenbank lesarchivesduspectacle" "de")
(descr-as-in "les-archives-du-spectacle-id" "" "ru")
(descr-as-in "les-archives-du-spectacle-id" "" "es")
(descr-as-in "les-archives-du-spectacle-id" "" "ja")
(descr-as-in "les-archives-du-spectacle-id" "" "zh-cn")
(descr-as-in "les-archives-du-spectacle-id" "" "zh-sg")

