(ns properties.librivox_author_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "librivox-author-id")

(name-as-in "librivox-author-id" "" "zh-hk")
(name-as-in "librivox-author-id" "identificador Librivox de autor" "pt")
(name-as-in "librivox-author-id" "LibriVox author ID" "en")
(name-as-in "librivox-author-id" "identifiant LibriVox d'auteur" "fr")
(name-as-in "librivox-author-id" "" "zh-tw")
(name-as-in "librivox-author-id" "LibriVox author ID" "de")
(name-as-in "librivox-author-id" "код автора в LibriVox" "ru")
(name-as-in "librivox-author-id" "identificador LibriVox de autor" "es")
(name-as-in "librivox-author-id" "" "ja")
(name-as-in "librivox-author-id" "" "zh-cn")
(name-as-in "librivox-author-id" "" "zh-sg")

(descr-as-in "librivox-author-id" "" "zh-hk")
(descr-as-in "librivox-author-id" "" "pt")
(descr-as-in "librivox-author-id" "author ID for an author represented at LibriVox" "en")
(descr-as-in "librivox-author-id" "identifiant pour un auteur présent sur LibriVox" "fr")
(descr-as-in "librivox-author-id" "" "zh-tw")
(descr-as-in "librivox-author-id" "" "de")
(descr-as-in "librivox-author-id" "" "ru")
(descr-as-in "librivox-author-id" "" "es")
(descr-as-in "librivox-author-id" "" "ja")
(descr-as-in "librivox-author-id" "" "zh-cn")
(descr-as-in "librivox-author-id" "" "zh-sg")

