(ns properties.linguistic_typology
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "linguistic-typology")

(name-as-in "linguistic-typology" "" "zh-hk")
(name-as-in "linguistic-typology" "tipologia linguística" "pt")
(name-as-in "linguistic-typology" "linguistic typology" "en")
(name-as-in "linguistic-typology" "typologie linguistique" "fr")
(name-as-in "linguistic-typology" "語言類型學" "zh-tw")
(name-as-in "linguistic-typology" "Sprachtypologie" "de")
(name-as-in "linguistic-typology" "языковая типология" "ru")
(name-as-in "linguistic-typology" "tipología lingüística" "es")
(name-as-in "linguistic-typology" "" "ja")
(name-as-in "linguistic-typology" "" "zh-cn")
(name-as-in "linguistic-typology" "" "zh-sg")

(descr-as-in "linguistic-typology" "" "zh-hk")
(descr-as-in "linguistic-typology" "" "pt")
(descr-as-in "linguistic-typology" "classification of languages according to their linguistic trait (as opposed to historical families like romance languages)" "en")
(descr-as-in "linguistic-typology" "classification des langues en fonction de leur traits caractéristiques" "fr")
(descr-as-in "linguistic-typology" "基於語言特徵去分類語言。" "zh-tw")
(descr-as-in "linguistic-typology" "" "de")
(descr-as-in "linguistic-typology" "" "ru")
(descr-as-in "linguistic-typology" "clasificación de las lenguas en función de sus rasgos característicos (en oposición a familias históricas, como las lenguas romances)" "es")
(descr-as-in "linguistic-typology" "" "ja")
(descr-as-in "linguistic-typology" "" "zh-cn")
(descr-as-in "linguistic-typology" "" "zh-sg")

