(ns properties.lir
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "lir")

(name-as-in "lir" "" "zh-hk")
(name-as-in "lir" "LIR" "pt")
(name-as-in "lir" "LIR" "en")
(name-as-in "lir" "LIR" "fr")
(name-as-in "lir" "" "zh-tw")
(name-as-in "lir" "LIR" "de")
(name-as-in "lir" "LIR" "ru")
(name-as-in "lir" "identificador LIR" "es")
(name-as-in "lir" "" "ja")
(name-as-in "lir" "" "zh-cn")
(name-as-in "lir" "" "zh-sg")

(descr-as-in "lir" "" "zh-hk")
(descr-as-in "lir" "" "pt")
(descr-as-in "lir" "identifier in the Lexicon istoric retic (LIR), Romansh variant of Historical Dictionary of Switzerland" "en")
(descr-as-in "lir" "identifiant du dictionnaire historique LIR de Suisse romande" "fr")
(descr-as-in "lir" "" "zh-tw")
(descr-as-in "lir" "Identifikator im Lexicon Istoric Retic, der romanischen Variante des Historisches Lexikons der Schweiz" "de")
(descr-as-in "lir" "Идентификатор Lexicon istoric retic (LIR), романшского варианта Исторического словаря Швейцарии (Q642074)" "ru")
(descr-as-in "lir" "identificador en el Lexicon Istoric Retic (LIR), una variante del Historical Dictionary of Switzerland" "es")
(descr-as-in "lir" "" "ja")
(descr-as-in "lir" "" "zh-cn")
(descr-as-in "lir" "" "zh-sg")

