(ns properties.list_of_monuments
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "list-of-monuments")

(name-as-in "list-of-monuments" "" "zh-hk")
(name-as-in "list-of-monuments" "lista de monumentos" "pt")
(name-as-in "list-of-monuments" "list of monuments" "en")
(name-as-in "list-of-monuments" "liste de biens patrimoniaux" "fr")
(name-as-in "list-of-monuments" "" "zh-tw")
(name-as-in "list-of-monuments" "Liste der Denkmale" "de")
(name-as-in "list-of-monuments" "список памятников" "ru")
(name-as-in "list-of-monuments" "lista de monumentos" "es")
(name-as-in "list-of-monuments" "" "ja")
(name-as-in "list-of-monuments" "" "zh-cn")
(name-as-in "list-of-monuments" "" "zh-sg")

(descr-as-in "list-of-monuments" "" "zh-hk")
(descr-as-in "list-of-monuments" "" "pt")
(descr-as-in "list-of-monuments" "link to the list of heritage monuments in the place/area" "en")
(descr-as-in "list-of-monuments" "lien vers la liste des biens patrimoniaux de l'élément" "fr")
(descr-as-in "list-of-monuments" "" "zh-tw")
(descr-as-in "list-of-monuments" "Verweis auf die Liste der Denkmale im Ort oder Gebiet" "de")
(descr-as-in "list-of-monuments" "ссылка на элемент со списком памятников данного географического местоположения" "ru")
(descr-as-in "list-of-monuments" "" "es")
(descr-as-in "list-of-monuments" "" "ja")
(descr-as-in "list-of-monuments" "" "zh-cn")
(descr-as-in "list-of-monuments" "" "zh-sg")

