(ns properties.located_at_street_address
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "located-at-street-address")

(name-as-in "located-at-street-address" "地址" "zh-hk")
(name-as-in "located-at-street-address" "morada" "pt")
(name-as-in "located-at-street-address" "located at street address" "en")
(name-as-in "located-at-street-address" "adresse" "fr")
(name-as-in "located-at-street-address" "地址" "zh-tw")
(name-as-in "located-at-street-address" "Adresse" "de")
(name-as-in "located-at-street-address" "адрес" "ru")
(name-as-in "located-at-street-address" "dirección postal" "es")
(name-as-in "located-at-street-address" "所在地" "ja")
(name-as-in "located-at-street-address" "地址" "zh-cn")
(name-as-in "located-at-street-address" "地址" "zh-sg")

(descr-as-in "located-at-street-address" "" "zh-hk")
(descr-as-in "located-at-street-address" "morada completa do elemento, incluindo a localidade e o código postal." "pt")
(descr-as-in "located-at-street-address" "full street address that the subject is located at. Include building number through to post code. Use also P669 if the street is known as a separate element." "en")
(descr-as-in "located-at-street-address" "adresse complète de l'élément incluant le code postal et la ville. Utilisez P669 si la rue est connue comme un élément distinct." "fr")
(descr-as-in "located-at-street-address" "" "zh-tw")
(descr-as-in "located-at-street-address" "vollständige Hausanschrift des Objektes. Verwende P669, wenn die Straße als separates Element bekannt ist." "de")
(descr-as-in "located-at-street-address" "указание улицы и дома, где физически находится объект" "ru")
(descr-as-in "located-at-street-address" "dirección física donde el elemento está ubicado" "es")
(descr-as-in "located-at-street-address" "主題の事物が存在する住所" "ja")
(descr-as-in "located-at-street-address" "" "zh-cn")
(descr-as-in "located-at-street-address" "" "zh-sg")

