(ns properties.located_on_street
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "located-on-street")

(name-as-in "located-on-street" "" "zh-hk")
(name-as-in "located-on-street" "rua" "pt")
(name-as-in "located-on-street" "located on street" "en")
(name-as-in "located-on-street" "voie" "fr")
(name-as-in "located-on-street" "" "zh-tw")
(name-as-in "located-on-street" "Straße" "de")
(name-as-in "located-on-street" "расположен на улице" "ru")
(name-as-in "located-on-street" "calle" "es")
(name-as-in "located-on-street" "所在地（街路）" "ja")
(name-as-in "located-on-street" "" "zh-cn")
(name-as-in "located-on-street" "" "zh-sg")

(descr-as-in "located-on-street" "" "zh-hk")
(descr-as-in "located-on-street" "rua ou via onde se encontra um edifício" "pt")
(descr-as-in "located-on-street" "street, road, or square, where the item is located. To add the number, use Property:P670 street number as qualifier. Use property P969 if there is no item for the street." "en")
(descr-as-in "located-on-street" "rue ou voie où se trouve le bâtiment (type de données « élément »). Pour ajouter le numéro, utiliser P670 (numéro de voirie) en qualificateur. Utilisez la propriété P969 s'il n'y a pas d'objet pour la rue." "fr")
(descr-as-in "located-on-street" "" "zh-tw")
(descr-as-in "located-on-street" "Straße oder Platz, an der sich das Objekt befindet. Benutzen Sie Eigenschaft P969, wenn es kein Einzelteil für die Straße gibt." "de")
(descr-as-in "located-on-street" "улица или дорога, на которой расположен элемент; часть адреса" "ru")
(descr-as-in "located-on-street" "calle o carretera donde se encuentra el edificio. Para añadir el número usar el calificador número de la calle (Property:P670)" "es")
(descr-as-in "located-on-street" "主題のものが所在する街路（道路方式の住所表記）。住居番号は修飾子でP670を使用して加える" "ja")
(descr-as-in "located-on-street" "" "zh-cn")
(descr-as-in "located-on-street" "" "zh-sg")

