(ns properties.locator_map_image
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "locator-map-image")

(name-as-in "locator-map-image" "地理位置圖" "zh-hk")
(name-as-in "locator-map-image" "imagem do mapa de localização" "pt")
(name-as-in "locator-map-image" "locator map image" "en")
(name-as-in "locator-map-image" "carte de localisation" "fr")
(name-as-in "locator-map-image" "地理位置圖" "zh-tw")
(name-as-in "locator-map-image" "Lagekarte" "de")
(name-as-in "locator-map-image" "карта местонахождения" "ru")
(name-as-in "locator-map-image" "mapa de localización" "es")
(name-as-in "locator-map-image" "位置地図画像" "ja")
(name-as-in "locator-map-image" "位置图图像" "zh-cn")
(name-as-in "locator-map-image" "" "zh-sg")

(descr-as-in "locator-map-image" "" "zh-hk")
(descr-as-in "locator-map-image" "mapa que salienta a localização de determinado local" "pt")
(descr-as-in "locator-map-image" "geographic map image which highlights the location of the subject" "en")
(descr-as-in "locator-map-image" "image de carte permettant de situer l'élément" "fr")
(descr-as-in "locator-map-image" "" "zh-tw")
(descr-as-in "locator-map-image" "Landkarte, die den geographischen Ort des Objekts hervorhebt" "de")
(descr-as-in "locator-map-image" "изображение географической карты, которая показывает местоположение объекта" "ru")
(descr-as-in "locator-map-image" "imagen de mapa que destaca la localización del sujeto" "es")
(descr-as-in "locator-map-image" "主題の位置を地図上に示す画像" "ja")
(descr-as-in "locator-map-image" "" "zh-cn")
(descr-as-in "locator-map-image" "" "zh-sg")

