(ns properties.located_in_time_zone
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "located-in-time-zone")

(name-as-in "located-in-time-zone" "時區" "zh-hk")
(name-as-in "located-in-time-zone" "fuso horário" "pt")
(name-as-in "located-in-time-zone" "located in time zone" "en")
(name-as-in "located-in-time-zone" "fuseau horaire" "fr")
(name-as-in "located-in-time-zone" "時區" "zh-tw")
(name-as-in "located-in-time-zone" "Zeitzone" "de")
(name-as-in "located-in-time-zone" "часовой пояс" "ru")
(name-as-in "located-in-time-zone" "huso horario" "es")
(name-as-in "located-in-time-zone" "標準時間帯" "ja")
(name-as-in "located-in-time-zone" "时区" "zh-cn")
(name-as-in "located-in-time-zone" "时区" "zh-sg")

(descr-as-in "located-in-time-zone" "" "zh-hk")
(descr-as-in "located-in-time-zone" "fuso horário para este local" "pt")
(descr-as-in "located-in-time-zone" "time zone for this item" "en")
(descr-as-in "located-in-time-zone" "fuseau horaire pour ce lieu" "fr")
(descr-as-in "located-in-time-zone" "" "zh-tw")
(descr-as-in "located-in-time-zone" "Bezeichnung der Zeitzone" "de")
(descr-as-in "located-in-time-zone" "статья Википедии про часовой пояс элемента" "ru")
(descr-as-in "located-in-time-zone" "huso horario de este lugar" "es")
(descr-as-in "located-in-time-zone" "この場所の標準時間帯" "ja")
(descr-as-in "located-in-time-zone" "" "zh-cn")
(descr-as-in "located-in-time-zone" "" "zh-sg")

