(ns properties.mactutor_id_biographies
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "mactutor-id-biographies")

(name-as-in "mactutor-id-biographies" "" "zh-hk")
(name-as-in "mactutor-id-biographies" "id no MacTutor (biografias)" "pt")
(name-as-in "mactutor-id-biographies" "MacTutor id (biographies)" "en")
(name-as-in "mactutor-id-biographies" "identifiant MacTutor (biographies)" "fr")
(name-as-in "mactutor-id-biographies" "" "zh-tw")
(name-as-in "mactutor-id-biographies" "MacTutor-ID" "de")
(name-as-in "mactutor-id-biographies" "код MacTutor" "ru")
(name-as-in "mactutor-id-biographies" "identificador MacTutor (biografías)" "es")
(name-as-in "mactutor-id-biographies" "" "ja")
(name-as-in "mactutor-id-biographies" "" "zh-cn")
(name-as-in "mactutor-id-biographies" "" "zh-sg")

(descr-as-in "mactutor-id-biographies" "" "zh-hk")
(descr-as-in "mactutor-id-biographies" "id da biografia de uma pessoa no MacTutor History of Mathematics archive" "pt")
(descr-as-in "mactutor-id-biographies" "identifier of the person's biography in the MacTutor History of Mathematics archive" "en")
(descr-as-in "mactutor-id-biographies" "identifiant d'une personne sur le site MacTutor History of Mathematics archive" "fr")
(descr-as-in "mactutor-id-biographies" "" "zh-tw")
(descr-as-in "mactutor-id-biographies" "ID der Biographie der Person im MacTutor History of Mathematics archive" "de")
(descr-as-in "mactutor-id-biographies" "идентификатор биографии в архиве истории математики Мактьютор" "ru")
(descr-as-in "mactutor-id-biographies" "identificador de una persona en el archivo de MacTutor History of Mathematics" "es")
(descr-as-in "mactutor-id-biographies" "" "ja")
(descr-as-in "mactutor-id-biographies" "" "zh-cn")
(descr-as-in "mactutor-id-biographies" "" "zh-sg")

