(ns properties.mains_voltage
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "mains-voltage")

(name-as-in "mains-voltage" "市電電壓" "zh-hk")
(name-as-in "mains-voltage" "eletricidade doméstica" "pt")
(name-as-in "mains-voltage" "mains voltage" "en")
(name-as-in "mains-voltage" "électricité domestique" "fr")
(name-as-in "mains-voltage" "市電電壓" "zh-tw")
(name-as-in "mains-voltage" "Netzspannung" "de")
(name-as-in "mains-voltage" "сетевое напряжение" "ru")
(name-as-in "mains-voltage" "electricidad doméstica" "es")
(name-as-in "mains-voltage" "" "ja")
(name-as-in "mains-voltage" "市电电压" "zh-cn")
(name-as-in "mains-voltage" "市电电压" "zh-sg")

(descr-as-in "mains-voltage" "" "zh-hk")
(descr-as-in "mains-voltage" "" "pt")
(descr-as-in "mains-voltage" "voltage of residential mains electricity in a country or region" "en")
(descr-as-in "mains-voltage" "tension d'un réseau électrique domestique dans un pays ou une région" "fr")
(descr-as-in "mains-voltage" "" "zh-tw")
(descr-as-in "mains-voltage" "" "de")
(descr-as-in "mains-voltage" "напряжение в бытовой электрической сети данной страны или региона" "ru")
(descr-as-in "mains-voltage" "" "es")
(descr-as-in "mains-voltage" "" "ja")
(descr-as-in "mains-voltage" "" "zh-cn")
(descr-as-in "mains-voltage" "" "zh-sg")

