(ns properties.manager_director
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "manager_director")

(name-as-in "manager_director" "主管" "zh-hk")
(name-as-in "manager_director" "gerente/diretor" "pt")
(name-as-in "manager_director" "manager/director" "en")
(name-as-in "manager_director" "dirigeant" "fr")
(name-as-in "manager_director" "主管" "zh-tw")
(name-as-in "manager_director" "Leiter" "de")
(name-as-in "manager_director" "менеджер/директор" "ru")
(name-as-in "manager_director" "gerente/director" "es")
(name-as-in "manager_director" "マネージャー/ディレクター" "ja")
(name-as-in "manager_director" "主管" "zh-cn")
(name-as-in "manager_director" "主管" "zh-sg")

(descr-as-in "manager_director" "管理任何組織的人" "zh-hk")
(descr-as-in "manager_director" "" "pt")
(descr-as-in "manager_director" "person who manages any kind of group" "en")
(descr-as-in "manager_director" "personne qui dirige ou gère une organisation, un groupe" "fr")
(descr-as-in "manager_director" "管理任何組織的人" "zh-tw")
(descr-as-in "manager_director" "Person, die eine Gruppe oder Organisation führt" "de")
(descr-as-in "manager_director" "человек, который руководит какой-либо группой [используется только, если не подходят генеральный директор (P169) или руководитель (P488)]" "ru")
(descr-as-in "manager_director" "persona que maneja cualquier tipo de grupo" "es")
(descr-as-in "manager_director" "集団・組織の管理・運営を行う人物。マネージャー、ディレクター。" "ja")
(descr-as-in "manager_director" "管理任何组织的人" "zh-cn")
(descr-as-in "manager_director" "管理任何组织的人" "zh-sg")

