(ns properties.manner_of_death
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "manner-of-death")

(name-as-in "manner-of-death" "死亡方式" "zh-hk")
(name-as-in "manner-of-death" "circunstâncias do falecimento" "pt")
(name-as-in "manner-of-death" "manner of death" "en")
(name-as-in "manner-of-death" "circonstances du décès" "fr")
(name-as-in "manner-of-death" "死亡方式" "zh-tw")
(name-as-in "manner-of-death" "Todesart" "de")
(name-as-in "manner-of-death" "род смерти" "ru")
(name-as-in "manner-of-death" "circunstancias de la muerte" "es")
(name-as-in "manner-of-death" "死亡状況" "ja")
(name-as-in "manner-of-death" "死亡方式" "zh-cn")
(name-as-in "manner-of-death" "死亡方式" "zh-sg")

(descr-as-in "manner-of-death" "死亡方法是描述一人死亡的環境或加工方法，與死因描述人體停止運作的原因不同。（請用P509屬性來敘述死因）" "zh-hk")
(descr-as-in "manner-of-death" "" "pt")
(descr-as-in "manner-of-death" "circumstances of a person's death; one of: natural causes, accident, suicide, homicide, pending investigation or special 'unknown value'.  Use 'cause of death' (P509) for more immediate or underlying causes and events, e.g. heart attack, car accident" "en")
(descr-as-in "manner-of-death" "circonstances de la mort d'une personne : causes naturelles, accident, suicide, homicide, enquête en cours, ... Utilisez « cause de la mort » (P509) pour des causes plus immédiates comme une attaque cardiaque ou un accident de la route." "fr")
(descr-as-in "manner-of-death" "死亡方法是描述一人死亡的環境或加工方法，與死因描述人體停止運作的原因不同。（請用P509屬性來敘述死因）" "zh-tw")
(descr-as-in "manner-of-death" "Umstände des Todes einer Person; natürliche Ursachen, Unfall, Suizid, Tötungsdelikt, laufende Ermittlungen, Todesstrafe. Für genauere Angaben zu Todesursachen und -umständen P509 verwenden." "de")
(descr-as-in "manner-of-death" "термин в судебной медицине" "ru")
(descr-as-in "manner-of-death" "circunstancias de la muerte de una persona; puede ser: causas naturales, accidente, suicidio, homicidio, investigación pendiente o 'valor desconocido'. Use 'causa de muerte' (P509) para más causas y eventos (i.e. paro cardíaco, accidente vehicular)" "es")
(descr-as-in "manner-of-death" "主題人物の死亡時の状況（自然死、事故死、自殺、他殺など）。より詳細な死因（交通事故、心臓発作など）はP509を使用" "ja")
(descr-as-in "manner-of-death" "" "zh-cn")
(descr-as-in "manner-of-death" "" "zh-sg")

