(ns properties.manufacturer
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "manufacturer")

(name-as-in "manufacturer" "生產商" "zh-hk")
(name-as-in "manufacturer" "fabricante" "pt")
(name-as-in "manufacturer" "manufacturer" "en")
(name-as-in "manufacturer" "fabricant" "fr")
(name-as-in "manufacturer" "生產商" "zh-tw")
(name-as-in "manufacturer" "Hersteller" "de")
(name-as-in "manufacturer" "производитель" "ru")
(name-as-in "manufacturer" "fabricante" "es")
(name-as-in "manufacturer" "製造元" "ja")
(name-as-in "manufacturer" "生产商" "zh-cn")
(name-as-in "manufacturer" "生产商" "zh-sg")

(descr-as-in "manufacturer" "產品的製造者" "zh-hk")
(descr-as-in "manufacturer" "" "pt")
(descr-as-in "manufacturer" "manufacturer or producer of this product" "en")
(descr-as-in "manufacturer" "entité qui a construit le produit" "fr")
(descr-as-in "manufacturer" "產品的製造者" "zh-tw")
(descr-as-in "manufacturer" "Haupthersteller eines Produkts (Subunternehmen ausgeschlossen)" "de")
(descr-as-in "manufacturer" "основной производитель (без субподрядчиков)" "ru")
(descr-as-in "manufacturer" "entidad que manufactura un producto" "es")
(descr-as-in "manufacturer" "主たる製造元（下請けを除く）" "ja")
(descr-as-in "manufacturer" "产品的制造者" "zh-cn")
(descr-as-in "manufacturer" "产品的制造者" "zh-sg")

