(ns properties.marriageable_age
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "marriageable-age")

(name-as-in "marriageable-age" "法定結婚年齡" "zh-hk")
(name-as-in "marriageable-age" "idade mínima de casamento" "pt")
(name-as-in "marriageable-age" "marriageable age" "en")
(name-as-in "marriageable-age" "âge nubile" "fr")
(name-as-in "marriageable-age" "法定結婚年齡" "zh-tw")
(name-as-in "marriageable-age" "Ehemündigkeit" "de")
(name-as-in "marriageable-age" "возраст вступления в брак" "ru")
(name-as-in "marriageable-age" "edad para contraer matrimonio" "es")
(name-as-in "marriageable-age" "婚姻適齢" "ja")
(name-as-in "marriageable-age" "法定结婚年龄" "zh-cn")
(name-as-in "marriageable-age" "法定结婚年龄" "zh-sg")

(descr-as-in "marriageable-age" "一般法律許可最小結婚年齡,性別不同，法定結婚年齡也不同。" "zh-hk")
(descr-as-in "marriageable-age" "" "pt")
(descr-as-in "marriageable-age" "minimum age at which a person is generally allowed by law to marry. Use qualifier applies to part (P518), to specify if it applies only to males (Q6581097), females (Q6581072) or both genders (Q27177113)" "en")
(descr-as-in "marriageable-age" "âge minimal auquel une personne est généralement autorisé par la loi à se marier. Utiliser un qualificateur si l'âge dépend du sexe" "fr")
(descr-as-in "marriageable-age" "一般法律許可最小結婚年齡,性別不同，法定結婚年齡也不同。" "zh-tw")
(descr-as-in "marriageable-age" "Mindestalter, das es einer Person erlaubt, zu heiraten" "de")
(descr-as-in "marriageable-age" "минимальный возраст вступления в брак" "ru")
(descr-as-in "marriageable-age" "edad mínima a la que una persona puede casarse" "es")
(descr-as-in "marriageable-age" "法的に婚姻が許可される最低年齢。性別により異なる場合は修飾子を使用します。" "ja")
(descr-as-in "marriageable-age" "一般法律许可最小结婚年龄,性别不同，法定结婚年龄也不同。" "zh-cn")
(descr-as-in "marriageable-age" "一般法律许可最小结婚年龄,性别不同，法定结婚年龄也不同。" "zh-sg")

