(ns properties.mathematics_genealogy_project_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "mathematics-genealogy-project-id")

(name-as-in "mathematics-genealogy-project-id" "" "zh-hk")
(name-as-in "mathematics-genealogy-project-id" "identificador do Mathematics Genealogy Project" "pt")
(name-as-in "mathematics-genealogy-project-id" "Mathematics Genealogy Project ID" "en")
(name-as-in "mathematics-genealogy-project-id" "identifiant MGP" "fr")
(name-as-in "mathematics-genealogy-project-id" "" "zh-tw")
(name-as-in "mathematics-genealogy-project-id" "MGP-ID" "de")
(name-as-in "mathematics-genealogy-project-id" "идентификатор MGP" "ru")
(name-as-in "mathematics-genealogy-project-id" "identificador MGP" "es")
(name-as-in "mathematics-genealogy-project-id" "" "ja")
(name-as-in "mathematics-genealogy-project-id" "" "zh-cn")
(name-as-in "mathematics-genealogy-project-id" "" "zh-sg")

(descr-as-in "mathematics-genealogy-project-id" "" "zh-hk")
(descr-as-in "mathematics-genealogy-project-id" "identificador de um indivíduo no Mathematics Genealogy Project" "pt")
(descr-as-in "mathematics-genealogy-project-id" "identifier for mathematicians and computer scientists at the Mathematics Genealogy Project" "en")
(descr-as-in "mathematics-genealogy-project-id" "identifiant d'une personne dans le Mathematics Genealogy Project" "fr")
(descr-as-in "mathematics-genealogy-project-id" "" "zh-tw")
(descr-as-in "mathematics-genealogy-project-id" "Identifikationsnummer in der Mathematiker-Datenbank des Mathematics Genealogy Project" "de")
(descr-as-in "mathematics-genealogy-project-id" "идентификатор учёного в Mathematics Genealogy Project" "ru")
(descr-as-in "mathematics-genealogy-project-id" "identificador para los matemáticos e informáticos en el Mathematics Genealogy Project" "es")
(descr-as-in "mathematics-genealogy-project-id" "" "ja")
(descr-as-in "mathematics-genealogy-project-id" "" "zh-cn")
(descr-as-in "mathematics-genealogy-project-id" "" "zh-sg")

