(ns properties.mathematics_genealogy_project_identifier
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "mathematics-genealogy-project-identifier")

(name-as-in "mathematics-genealogy-project-identifier" "MGP-ID" "de")
(name-as-in "mathematics-genealogy-project-identifier" "" "zh-hk")
(name-as-in "mathematics-genealogy-project-identifier" "" "zh-tw")
(name-as-in "mathematics-genealogy-project-identifier" "идентификатор MGP" "ru")
(name-as-in "mathematics-genealogy-project-identifier" "identificador do Mathematics Genealogy Project" "pt")
(name-as-in "mathematics-genealogy-project-identifier" "Mathematics Genealogy Project identifier" "en")
(name-as-in "mathematics-genealogy-project-identifier" "" "zh-cn")
(name-as-in "mathematics-genealogy-project-identifier" "identifiant MGP" "fr")
(name-as-in "mathematics-genealogy-project-identifier" "" "es")
(name-as-in "mathematics-genealogy-project-identifier" "" "zh-sg")
(name-as-in "mathematics-genealogy-project-identifier" "" "ja")
(name-as-in "mathematics-genealogy-project-identifier" "" "zh-hans")
(name-as-in "mathematics-genealogy-project-identifier" "" "zh-hant")

(descr-as-in "mathematics-genealogy-project-identifier" "Identifikationsnummer in der Mathematiker-Datenbank des Mathematics Genealogy Project" "de")
(descr-as-in "mathematics-genealogy-project-identifier" "" "zh-hk")
(descr-as-in "mathematics-genealogy-project-identifier" "" "zh-tw")
(descr-as-in "mathematics-genealogy-project-identifier" "" "ru")
(descr-as-in "mathematics-genealogy-project-identifier" "identificador de um indivíduo no Mathematics Genealogy Project" "pt")
(descr-as-in "mathematics-genealogy-project-identifier" "identifier for mathematicians and computer scientists at the Mathematics Genealogy Project" "en")
(descr-as-in "mathematics-genealogy-project-identifier" "" "zh-cn")
(descr-as-in "mathematics-genealogy-project-identifier" "identifiant d'une personne dans le Mathematics Genealogy Project" "fr")
(descr-as-in "mathematics-genealogy-project-identifier" "" "es")
(descr-as-in "mathematics-genealogy-project-identifier" "" "zh-sg")
(descr-as-in "mathematics-genealogy-project-identifier" "" "ja")
(descr-as-in "mathematics-genealogy-project-identifier" "" "zh-hans")
(descr-as-in "mathematics-genealogy-project-identifier" "" "zh-hant")

