(ns properties.median_income
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "median-income")

(name-as-in "median-income" "" "zh-hk")
(name-as-in "median-income" "renda média" "pt")
(name-as-in "median-income" "median income" "en")
(name-as-in "median-income" "revenu médian" "fr")
(name-as-in "median-income" "" "zh-tw")
(name-as-in "median-income" "Medianeinkommen" "de")
(name-as-in "median-income" "медианный доход" "ru")
(name-as-in "median-income" "ingreso mediano" "es")
(name-as-in "median-income" "" "ja")
(name-as-in "median-income" "" "zh-cn")
(name-as-in "median-income" "" "zh-sg")

(descr-as-in "median-income" "" "zh-hk")
(descr-as-in "median-income" "" "pt")
(descr-as-in "median-income" "median income in a place" "en")
(descr-as-in "median-income" "" "fr")
(descr-as-in "median-income" "" "zh-tw")
(descr-as-in "median-income" "Median des Einkommens in einem Ort" "de")
(descr-as-in "median-income" "" "ru")
(descr-as-in "median-income" "" "es")
(descr-as-in "median-income" "" "ja")
(descr-as-in "median-income" "" "zh-cn")
(descr-as-in "median-income" "" "zh-sg")

