(ns properties.member_count
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "member-count")

(name-as-in "member-count" "成員數目" "zh-hk")
(name-as-in "member-count" "número de membros" "pt")
(name-as-in "member-count" "member count" "en")
(name-as-in "member-count" "nombre de membres" "fr")
(name-as-in "member-count" "成員數目" "zh-tw")
(name-as-in "member-count" "Mitgliederzahl" "de")
(name-as-in "member-count" "число членов" "ru")
(name-as-in "member-count" "número de miembros" "es")
(name-as-in "member-count" "会員数" "ja")
(name-as-in "member-count" "成员数目" "zh-cn")
(name-as-in "member-count" "成员数目" "zh-sg")

(descr-as-in "member-count" "" "zh-hk")
(descr-as-in "member-count" "" "pt")
(descr-as-in "member-count" "number of people who are part of an organization at a particular time" "en")
(descr-as-in "member-count" "nombre de personnes qui ont rejoint une organisation à un moment donné" "fr")
(descr-as-in "member-count" "" "zh-tw")
(descr-as-in "member-count" "Anzahl der Personen, die Teil einer Organisation in einer spezifischen Zeitspanne sind" "de")
(descr-as-in "member-count" "число членов организации" "ru")
(descr-as-in "member-count" "número de personas que forman parte de una organización" "es")
(descr-as-in "member-count" "組織のある時期に参加している人の数" "ja")
(descr-as-in "member-count" "" "zh-cn")
(descr-as-in "member-count" "" "zh-sg")

