(ns properties.mesh_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "mesh-id")

(name-as-in "mesh-id" "" "zh-hk")
(name-as-in "mesh-id" "identificador MeSH" "pt")
(name-as-in "mesh-id" "MeSH ID" "en")
(name-as-in "mesh-id" "identifiant Medical Subject Headings" "fr")
(name-as-in "mesh-id" "" "zh-tw")
(name-as-in "mesh-id" "MeSH-ID" "de")
(name-as-in "mesh-id" "MeSH ID" "ru")
(name-as-in "mesh-id" "identificador MeSH" "es")
(name-as-in "mesh-id" "MeSH ID" "ja")
(name-as-in "mesh-id" "" "zh-cn")
(name-as-in "mesh-id" "" "zh-sg")

(descr-as-in "mesh-id" "" "zh-hk")
(descr-as-in "mesh-id" "identificador da base de dados MeSH, para doenças e conceitos relativos à medicina" "pt")
(descr-as-in "mesh-id" "identifier for diseases and other medically relevant concepts, in the MeSH descriptor database" "en")
(descr-as-in "mesh-id" "identifiant de la base de données MeSH (maladie et autres concepts biomédicaux)" "fr")
(descr-as-in "mesh-id" "" "zh-tw")
(descr-as-in "mesh-id" "Primärschlüssel der Medical-Subject-Headings-Datenbank" "de")
(descr-as-in "mesh-id" "идентификатор в базе описаний" "ru")
(descr-as-in "mesh-id" "identificador de enfermedades en la base de datos MeSH" "es")
(descr-as-in "mesh-id" "" "ja")
(descr-as-in "mesh-id" "" "zh-cn")
(descr-as-in "mesh-id" "" "zh-sg")

