(ns properties.mobile_country_code
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "mobile-country-code")

(name-as-in "mobile-country-code" "" "zh-hk")
(name-as-in "mobile-country-code" "" "pt")
(name-as-in "mobile-country-code" "mobile country code" "en")
(name-as-in "mobile-country-code" "code pays pour mobile" "fr")
(name-as-in "mobile-country-code" "" "zh-tw")
(name-as-in "mobile-country-code" "Mobile Country Code" "de")
(name-as-in "mobile-country-code" "мобильный код страны" "ru")
(name-as-in "mobile-country-code" "código de país UIT-T" "es")
(name-as-in "mobile-country-code" "MCC" "ja")
(name-as-in "mobile-country-code" "" "zh-cn")
(name-as-in "mobile-country-code" "" "zh-sg")

(descr-as-in "mobile-country-code" "" "zh-hk")
(descr-as-in "mobile-country-code" "" "pt")
(descr-as-in "mobile-country-code" "identifier for countries in ITU-T Recommendation E.212 for use in describing mobile networks" "en")
(descr-as-in "mobile-country-code" "identifiant des pays dans ITU-T Recommendation E.212 pour utilisation dans la description des réseaux mobiles" "fr")
(descr-as-in "mobile-country-code" "" "zh-tw")
(descr-as-in "mobile-country-code" "von der ITU im Standard E.212 festgelegte Länderkennung zur Identifizierung von Mobilfunknetzen" "de")
(descr-as-in "mobile-country-code" "код страны ITU-T" "ru")
(descr-as-in "mobile-country-code" "" "es")
(descr-as-in "mobile-country-code" "ITU-T 勧告 E.212で定められている国別のコード" "ja")
(descr-as-in "mobile-country-code" "" "zh-cn")
(descr-as-in "mobile-country-code" "" "zh-sg")

