(ns properties.mother
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "mother")

(name-as-in "mother" "母親" "zh-hk")
(name-as-in "mother" "mãe" "pt")
(name-as-in "mother" "mother" "en")
(name-as-in "mother" "mère" "fr")
(name-as-in "mother" "母親" "zh-tw")
(name-as-in "mother" "Mutter" "de")
(name-as-in "mother" "мать" "ru")
(name-as-in "mother" "madre" "es")
(name-as-in "mother" "母親" "ja")
(name-as-in "mother" "母亲" "zh-cn")
(name-as-in "mother" "母亲" "zh-sg")

(descr-as-in "mother" "女性家長" "zh-hk")
(descr-as-in "mother" "progenitor feminino" "pt")
(descr-as-in "mother" "female parent of the subject. For stepmother, use stepparent (P3448)" "en")
(descr-as-in "mother" "lien familial, parent direct de sexe féminin" "fr")
(descr-as-in "mother" "女性家長" "zh-tw")
(descr-as-in "mother" "weiblicher Elternteil" "de")
(descr-as-in "mother" "мать персоны" "ru")
(descr-as-in "mother" "progenitor femenino" "es")
(descr-as-in "mother" "その項目は主題に対し女性の親" "ja")
(descr-as-in "mother" "女性家长" "zh-cn")
(descr-as-in "mother" "女性家长" "zh-sg")

