(ns properties.mother
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "mother")

(name-as-in "mother" "Mutter" "de")
(name-as-in "mother" "母親" "zh-hk")
(name-as-in "mother" "母親" "zh-tw")
(name-as-in "mother" "мать" "ru")
(name-as-in "mother" "mãe" "pt")
(name-as-in "mother" "mother" "en")
(name-as-in "mother" "母亲" "zh-cn")
(name-as-in "mother" "mère" "fr")
(name-as-in "mother" "madre" "es")
(name-as-in "mother" "" "zh-sg")
(name-as-in "mother" "母親" "ja")
(name-as-in "mother" "母亲" "zh-hans")
(name-as-in "mother" "母親" "zh-hant")

(descr-as-in "mother" "weiblicher Elternteil" "de")
(descr-as-in "mother" "" "zh-hk")
(descr-as-in "mother" "" "zh-tw")
(descr-as-in "mother" "мать персоны" "ru")
(descr-as-in "mother" "" "pt")
(descr-as-in "mother" "female parent" "en")
(descr-as-in "mother" "" "zh-cn")
(descr-as-in "mother" "lien familial" "fr")
(descr-as-in "mother" "el sujeto tuvo como madre al objeto" "es")
(descr-as-in "mother" "" "zh-sg")
(descr-as-in "mother" "その項目は主題に対し女性の親" "ja")
(descr-as-in "mother" "" "zh-hans")
(descr-as-in "mother" "" "zh-hant")

