(ns properties.motto
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "motto")

(name-as-in "motto" "" "zh-hk")
(name-as-in "motto" "lema" "pt")
(name-as-in "motto" "motto" "en")
(name-as-in "motto" "devise" "fr")
(name-as-in "motto" "" "zh-tw")
(name-as-in "motto" "Wahlspruch" "de")
(name-as-in "motto" "описание девиза" "ru")
(name-as-in "motto" "lema" "es")
(name-as-in "motto" "標語" "ja")
(name-as-in "motto" "" "zh-cn")
(name-as-in "motto" "" "zh-sg")

(descr-as-in "motto" "" "zh-hk")
(descr-as-in "motto" "" "pt")
(descr-as-in "motto" "description of the motto of the subject" "en")
(descr-as-in "motto" "description de la devise du sujet" "fr")
(descr-as-in "motto" "" "zh-tw")
(descr-as-in "motto" "Beschreibung des Mottos eines Datenobjekts" "de")
(descr-as-in "motto" "указание на сущность, описывающую девиз" "ru")
(descr-as-in "motto" "descripción del lema del objeto principal" "es")
(descr-as-in "motto" "主題の標語" "ja")
(descr-as-in "motto" "" "zh-cn")
(descr-as-in "motto" "" "zh-sg")

