(ns properties.munzinger_iba
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "munzinger-iba")

(name-as-in "munzinger-iba" "" "zh-hk")
(name-as-in "munzinger-iba" "" "pt")
(name-as-in "munzinger-iba" "Munzinger IBA" "en")
(name-as-in "munzinger-iba" "identifiant Munzinger" "fr")
(name-as-in "munzinger-iba" "" "zh-tw")
(name-as-in "munzinger-iba" "Munzinger Personen" "de")
(name-as-in "munzinger-iba" "Munzinger IBA" "ru")
(name-as-in "munzinger-iba" "identificador Munzinger" "es")
(name-as-in "munzinger-iba" "" "ja")
(name-as-in "munzinger-iba" "" "zh-cn")
(name-as-in "munzinger-iba" "" "zh-sg")

(descr-as-in "munzinger-iba" "" "zh-hk")
(descr-as-in "munzinger-iba" "" "pt")
(descr-as-in "munzinger-iba" "identifier on the Munzinger Archiv" "en")
(descr-as-in "munzinger-iba" "" "fr")
(descr-as-in "munzinger-iba" "" "zh-tw")
(descr-as-in "munzinger-iba" "Internationales Biographisches Archiv im Verlag Munzinger-Archiv" "de")
(descr-as-in "munzinger-iba" "код в Мунцингер-Архиве" "ru")
(descr-as-in "munzinger-iba" "" "es")
(descr-as-in "munzinger-iba" "" "ja")
(descr-as-in "munzinger-iba" "" "zh-cn")
(descr-as-in "munzinger-iba" "" "zh-sg")

