(ns properties.musicbrainz_artist_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "musicbrainz-artist-id")

(name-as-in "musicbrainz-artist-id" "MusicBrainz音樂家編號" "zh-hk")
(name-as-in "musicbrainz-artist-id" "identificador MusicBrainz de artista" "pt")
(name-as-in "musicbrainz-artist-id" "MusicBrainz artist ID" "en")
(name-as-in "musicbrainz-artist-id" "identifiant MusicBrainz de l'artiste" "fr")
(name-as-in "musicbrainz-artist-id" "MusicBrainz音樂家編號" "zh-tw")
(name-as-in "musicbrainz-artist-id" "MusicBrainz-Künstler-ID" "de")
(name-as-in "musicbrainz-artist-id" "код MusicBrainz для исполнителя" "ru")
(name-as-in "musicbrainz-artist-id" "identificador MusicBrainz de artista" "es")
(name-as-in "musicbrainz-artist-id" "MusicBrainzアーティストID" "ja")
(name-as-in "musicbrainz-artist-id" "MusicBrainz音乐家编号" "zh-cn")
(name-as-in "musicbrainz-artist-id" "MusicBrainz音乐家编号" "zh-sg")

(descr-as-in "musicbrainz-artist-id" "" "zh-hk")
(descr-as-in "musicbrainz-artist-id" "" "pt")
(descr-as-in "musicbrainz-artist-id" "identifier for an artist per the MusicBrainz open music encyclopedia" "en")
(descr-as-in "musicbrainz-artist-id" "identifiant de l'artiste dans l'encyclopédie musicale MusicBrainz" "fr")
(descr-as-in "musicbrainz-artist-id" "" "zh-tw")
(descr-as-in "musicbrainz-artist-id" "Identifikationsnummer des Künstlers (Musiker, Schriftsteller) in MusicBrainz" "de")
(descr-as-in "musicbrainz-artist-id" "идентификатор исполнителя в свободной музыкальной энциклопедии" "ru")
(descr-as-in "musicbrainz-artist-id" "número de indentificación de artista en la enciclopedia MusicBrainz" "es")
(descr-as-in "musicbrainz-artist-id" "MusicBrainzオープン音楽百科事典のアーティストID" "ja")
(descr-as-in "musicbrainz-artist-id" "" "zh-cn")
(descr-as-in "musicbrainz-artist-id" "" "zh-sg")

