(ns properties.musicbrainz_area_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "musicbrainz-area-id")

(name-as-in "musicbrainz-area-id" "MusicBrainz地區編號" "zh-hk")
(name-as-in "musicbrainz-area-id" "identificador de área no MusicBrainz" "pt")
(name-as-in "musicbrainz-area-id" "MusicBrainz area ID" "en")
(name-as-in "musicbrainz-area-id" "identifiant MusicBrainz d'un lieu" "fr")
(name-as-in "musicbrainz-area-id" "MusicBrainz地區編號" "zh-tw")
(name-as-in "musicbrainz-area-id" "MusicBrainz-Gebiets-ID" "de")
(name-as-in "musicbrainz-area-id" "место в MusicBrainz" "ru")
(name-as-in "musicbrainz-area-id" "identificador MusicBrainz de área" "es")
(name-as-in "musicbrainz-area-id" "MusicBrainz地域ID" "ja")
(name-as-in "musicbrainz-area-id" "MusicBrainz地区编号" "zh-cn")
(name-as-in "musicbrainz-area-id" "MusicBrainz地区编号" "zh-sg")

(descr-as-in "musicbrainz-area-id" "" "zh-hk")
(descr-as-in "musicbrainz-area-id" "" "pt")
(descr-as-in "musicbrainz-area-id" "identifier for an area in the MusicBrainz open music database" "en")
(descr-as-in "musicbrainz-area-id" "" "fr")
(descr-as-in "musicbrainz-area-id" "" "zh-tw")
(descr-as-in "musicbrainz-area-id" "Identifikationsnummer des Gebiets in der Musikdatenbank MusicBrainz" "de")
(descr-as-in "musicbrainz-area-id" "идентификатор места в музыкальной энциклопедии" "ru")
(descr-as-in "musicbrainz-area-id" "" "es")
(descr-as-in "musicbrainz-area-id" "MusicBrainz オープン音楽百科事典の地域ID" "ja")
(descr-as-in "musicbrainz-area-id" "" "zh-cn")
(descr-as-in "musicbrainz-area-id" "" "zh-sg")

