(ns properties.name_assigning_authority_number
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "name-assigning-authority-number")

(name-as-in "name-assigning-authority-number" "" "zh-hk")
(name-as-in "name-assigning-authority-number" "" "pt")
(name-as-in "name-assigning-authority-number" "Name Assigning Authority Number" "en")
(name-as-in "name-assigning-authority-number" "identifiant NAAN" "fr")
(name-as-in "name-assigning-authority-number" "" "zh-tw")
(name-as-in "name-assigning-authority-number" "" "de")
(name-as-in "name-assigning-authority-number" "код NAAN" "ru")
(name-as-in "name-assigning-authority-number" "Name Assigning Authority Number" "es")
(name-as-in "name-assigning-authority-number" "" "ja")
(name-as-in "name-assigning-authority-number" "" "zh-cn")
(name-as-in "name-assigning-authority-number" "" "zh-sg")

(descr-as-in "name-assigning-authority-number" "" "zh-hk")
(descr-as-in "name-assigning-authority-number" "" "pt")
(descr-as-in "name-assigning-authority-number" "identifier in the Archival Resource Key registry" "en")
(descr-as-in "name-assigning-authority-number" "identifiant du registre de l'Archival Resource Key" "fr")
(descr-as-in "name-assigning-authority-number" "" "zh-tw")
(descr-as-in "name-assigning-authority-number" "" "de")
(descr-as-in "name-assigning-authority-number" "Name Assigning Authority Number" "ru")
(descr-as-in "name-assigning-authority-number" "" "es")
(descr-as-in "name-assigning-authority-number" "" "ja")
(descr-as-in "name-assigning-authority-number" "" "zh-cn")
(descr-as-in "name-assigning-authority-number" "" "zh-sg")

