(ns properties.named_after
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "named-after")

(name-as-in "named-after" "名稱由來" "zh-hk")
(name-as-in "named-after" "origem do nome" "pt")
(name-as-in "named-after" "named after" "en")
(name-as-in "named-after" "nommé en référence à" "fr")
(name-as-in "named-after" "名稱由來" "zh-tw")
(name-as-in "named-after" "benannt nach" "de")
(name-as-in "named-after" "названо в честь" "ru")
(name-as-in "named-after" "nombrado por" "es")
(name-as-in "named-after" "名前の由来" "ja")
(name-as-in "named-after" "得名自" "zh-cn")
(name-as-in "named-after" "名称由来" "zh-sg")

(descr-as-in "named-after" "啟發其名稱的事物、人物或事件（在至少一種語言中）" "zh-hk")
(descr-as-in "named-after" "entidade ou evento que inspirou o nome do sujeito" "pt")
(descr-as-in "named-after" "entity or event that inspired the subject's name, or namesake (in at least one language)" "en")
(descr-as-in "named-after" "quelque chose/quelqu'un qui a inspiré le nom de l'élément" "fr")
(descr-as-in "named-after" "啟發其名稱的事物、人物或事件（在至少一種語言中）" "zh-tw")
(descr-as-in "named-after" "Person oder anderes Objekt als Namensgeber dieses Objekts" "de")
(descr-as-in "named-after" "объект, персона или событие, чьё имя/название послужило основой для данного элемента" "ru")
(descr-as-in "named-after" "entidad o evento que inspiró el nombre del elemento" "es")
(descr-as-in "named-after" "この項目の名前の由来となったもの・出来事" "ja")
(descr-as-in "named-after" "启发其名称的事物、人物或事件（在至少一种语言中）" "zh-cn")
(descr-as-in "named-after" "启发其名称的事物、人物或事件（在至少一种语言中）" "zh-sg")

