(ns properties.native_language
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "native-language")

(name-as-in "native-language" "母語" "zh-hk")
(name-as-in "native-language" "língua materna" "pt")
(name-as-in "native-language" "native language" "en")
(name-as-in "native-language" "langue maternelle" "fr")
(name-as-in "native-language" "母語" "zh-tw")
(name-as-in "native-language" "Muttersprache" "de")
(name-as-in "native-language" "родной язык" "ru")
(name-as-in "native-language" "lengua materna" "es")
(name-as-in "native-language" "母語" "ja")
(name-as-in "native-language" "母语" "zh-cn")
(name-as-in "native-language" "母语" "zh-sg")

(descr-as-in "native-language" "一個人生來就會的語言" "zh-hk")
(descr-as-in "native-language" "língua materna do sujeito" "pt")
(descr-as-in "native-language" "language or languages a person has learned from birth" "en")
(descr-as-in "native-language" "première langue apprise par le sujet" "fr")
(descr-as-in "native-language" "一個人生來就會的語言" "zh-tw")
(descr-as-in "native-language" "in der frühen Kindheit ohne Unterricht erlernte Erstsprache" "de")
(descr-as-in "native-language" "язык, который персона знает с рождения" "ru")
(descr-as-in "native-language" "idioma que la persona aprendió de manera nativa" "es")
(descr-as-in "native-language" "主題人物の母語" "ja")
(descr-as-in "native-language" "一个人生来就会的语言" "zh-cn")
(descr-as-in "native-language" "一个人生来就会的语言" "zh-sg")

