(ns properties.national_library_of_israel_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "national-library-of-israel-id")

(name-as-in "national-library-of-israel-id" "NLI編號" "zh-hk")
(name-as-in "national-library-of-israel-id" "identificador NLI (Israel)" "pt")
(name-as-in "national-library-of-israel-id" "National Library of Israel ID" "en")
(name-as-in "national-library-of-israel-id" "identifiant Bibliothèque nationale d'Israël" "fr")
(name-as-in "national-library-of-israel-id" "" "zh-tw")
(name-as-in "national-library-of-israel-id" "NLI (Israel)" "de")
(name-as-in "national-library-of-israel-id" "код NLI" "ru")
(name-as-in "national-library-of-israel-id" "identificador NLI" "es")
(name-as-in "national-library-of-israel-id" "NLI（イスラエル）識別子" "ja")
(name-as-in "national-library-of-israel-id" "" "zh-cn")
(name-as-in "national-library-of-israel-id" "" "zh-sg")

(descr-as-in "national-library-of-israel-id" "" "zh-hk")
(descr-as-in "national-library-of-israel-id" "" "pt")
(descr-as-in "national-library-of-israel-id" "identifier for authority control used at the National Library of Israel" "en")
(descr-as-in "national-library-of-israel-id" "identifiant de la Bibliothèque nationale d'Israël" "fr")
(descr-as-in "national-library-of-israel-id" "" "zh-tw")
(descr-as-in "national-library-of-israel-id" "ID in der Normdatei der Israelischen Nationalbibliothek, mit führenden Nullen" "de")
(descr-as-in "national-library-of-israel-id" "библиотечный номер в Национальной библиотеке Израиля" "ru")
(descr-as-in "national-library-of-israel-id" "identificador de la National Library of Israel" "es")
(descr-as-in "national-library-of-israel-id" "イスラエル国立図書館の典拠コントロール識別子" "ja")
(descr-as-in "national-library-of-israel-id" "" "zh-cn")
(descr-as-in "national-library-of-israel-id" "" "zh-sg")

