(ns properties.nationalmuseum_sweden_artist_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nationalmuseum-sweden-artist-id")

(name-as-in "nationalmuseum-sweden-artist-id" "" "zh-hk")
(name-as-in "nationalmuseum-sweden-artist-id" "" "pt")
(name-as-in "nationalmuseum-sweden-artist-id" "Nationalmuseum Sweden artist ID" "en")
(name-as-in "nationalmuseum-sweden-artist-id" "identifiant Nationalmuseum d'un artiste" "fr")
(name-as-in "nationalmuseum-sweden-artist-id" "" "zh-tw")
(name-as-in "nationalmuseum-sweden-artist-id" "Künstler-ID beim Schwedischen Nationalmuseum" "de")
(name-as-in "nationalmuseum-sweden-artist-id" "код персоналии в Национальном музее Швеции" "ru")
(name-as-in "nationalmuseum-sweden-artist-id" "identificador Museo Nacional de Estocolmo de artista" "es")
(name-as-in "nationalmuseum-sweden-artist-id" "" "ja")
(name-as-in "nationalmuseum-sweden-artist-id" "" "zh-cn")
(name-as-in "nationalmuseum-sweden-artist-id" "" "zh-sg")

(descr-as-in "nationalmuseum-sweden-artist-id" "" "zh-hk")
(descr-as-in "nationalmuseum-sweden-artist-id" "" "pt")
(descr-as-in "nationalmuseum-sweden-artist-id" "Artist identifier for Nationalmuseum in Sweden" "en")
(descr-as-in "nationalmuseum-sweden-artist-id" "" "fr")
(descr-as-in "nationalmuseum-sweden-artist-id" "" "zh-tw")
(descr-as-in "nationalmuseum-sweden-artist-id" "Identifikationsnummer für Künstler beim Schwedischen Nationalmuseum" "de")
(descr-as-in "nationalmuseum-sweden-artist-id" "" "ru")
(descr-as-in "nationalmuseum-sweden-artist-id" "" "es")
(descr-as-in "nationalmuseum-sweden-artist-id" "" "ja")
(descr-as-in "nationalmuseum-sweden-artist-id" "" "zh-cn")
(descr-as-in "nationalmuseum-sweden-artist-id" "" "zh-sg")

