(ns properties.national_library_of_greece_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "national-library-of-greece-id")

(name-as-in "national-library-of-greece-id" "" "zh-hk")
(name-as-in "national-library-of-greece-id" "" "pt")
(name-as-in "national-library-of-greece-id" "National Library of Greece ID" "en")
(name-as-in "national-library-of-greece-id" "identifiant Bibliothèque nationale de Grèce" "fr")
(name-as-in "national-library-of-greece-id" "" "zh-tw")
(name-as-in "national-library-of-greece-id" "ID der Nationalbibliothek von Griechenland" "de")
(name-as-in "national-library-of-greece-id" "код Национальной библиотеки Греции" "ru")
(name-as-in "national-library-of-greece-id" "identificador Biblioteca Nacional de Grecia" "es")
(name-as-in "national-library-of-greece-id" "" "ja")
(name-as-in "national-library-of-greece-id" "" "zh-cn")
(name-as-in "national-library-of-greece-id" "" "zh-sg")

(descr-as-in "national-library-of-greece-id" "" "zh-hk")
(descr-as-in "national-library-of-greece-id" "" "pt")
(descr-as-in "national-library-of-greece-id" "Authority ID from the National Library of Greece Authority Records" "en")
(descr-as-in "national-library-of-greece-id" "" "fr")
(descr-as-in "national-library-of-greece-id" "" "zh-tw")
(descr-as-in "national-library-of-greece-id" "" "de")
(descr-as-in "national-library-of-greece-id" "" "ru")
(descr-as-in "national-library-of-greece-id" "" "es")
(descr-as-in "national-library-of-greece-id" "" "ja")
(descr-as-in "national-library-of-greece-id" "" "zh-cn")
(descr-as-in "national-library-of-greece-id" "" "zh-sg")

