(ns properties.nci_thesaurus_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nci-thesaurus-id")

(name-as-in "nci-thesaurus-id" "" "zh-hk")
(name-as-in "nci-thesaurus-id" "identificador NCI Thesaurus" "pt")
(name-as-in "nci-thesaurus-id" "NCI Thesaurus ID" "en")
(name-as-in "nci-thesaurus-id" "identifiant NCI Thesaurus" "fr")
(name-as-in "nci-thesaurus-id" "" "zh-tw")
(name-as-in "nci-thesaurus-id" "NCI-Thesaurus-ID" "de")
(name-as-in "nci-thesaurus-id" "код NCI Thesaurus" "ru")
(name-as-in "nci-thesaurus-id" "identificador NCI Thesaurus" "es")
(name-as-in "nci-thesaurus-id" "NCI Thesaurus ID" "ja")
(name-as-in "nci-thesaurus-id" "" "zh-cn")
(name-as-in "nci-thesaurus-id" "" "zh-sg")

(descr-as-in "nci-thesaurus-id" "" "zh-hk")
(descr-as-in "nci-thesaurus-id" "" "pt")
(descr-as-in "nci-thesaurus-id" "identifier in the United States National Cancer Institute Thesaurus, vocabulary for clinical care, translational and basic research, etc" "en")
(descr-as-in "nci-thesaurus-id" "identifiant du National Cancer Institute Thesaurus des États-Unis" "fr")
(descr-as-in "nci-thesaurus-id" "" "zh-tw")
(descr-as-in "nci-thesaurus-id" "" "de")
(descr-as-in "nci-thesaurus-id" "" "ru")
(descr-as-in "nci-thesaurus-id" "identificador del National Cancer Institute Thesaurus de Estados Unidos" "es")
(descr-as-in "nci-thesaurus-id" "" "ja")
(descr-as-in "nci-thesaurus-id" "" "zh-cn")
(descr-as-in "nci-thesaurus-id" "" "zh-sg")

