(ns properties.ndl_auth_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "ndl-auth-id")

(name-as-in "ndl-auth-id" "NDL編號" "zh-hk")
(name-as-in "ndl-auth-id" "ID da NDL" "pt")
(name-as-in "ndl-auth-id" "NDL Auth ID" "en")
(name-as-in "ndl-auth-id" "identifiant Bibliothèque nationale de la Diète" "fr")
(name-as-in "ndl-auth-id" "NDL編號" "zh-tw")
(name-as-in "ndl-auth-id" "Web NDL Authorities" "de")
(name-as-in "ndl-auth-id" "код NDL" "ru")
(name-as-in "ndl-auth-id" "identificador NDL" "es")
(name-as-in "ndl-auth-id" "国立国会図書館典拠ID" "ja")
(name-as-in "ndl-auth-id" "NDL编号" "zh-cn")
(name-as-in "ndl-auth-id" "" "zh-sg")

(descr-as-in "ndl-auth-id" "" "zh-hk")
(descr-as-in "ndl-auth-id" "" "pt")
(descr-as-in "ndl-auth-id" "identifier for authority control per the National Diet Library of Japan" "en")
(descr-as-in "ndl-auth-id" "identifiant de la Bibliothèque nationale de la Diète (parlement du Japon)" "fr")
(descr-as-in "ndl-auth-id" "" "zh-tw")
(descr-as-in "ndl-auth-id" "Normdateneintrag in der Nationalen Parlamentsbibliothek (NDL), Japan" "de")
(descr-as-in "ndl-auth-id" "библиотечный номер в Парламентской библиотеке Японии" "ru")
(descr-as-in "ndl-auth-id" "número de control de autoridad en la Biblioteca de la Dieta Nacional de Japón" "es")
(descr-as-in "ndl-auth-id" "日本の国立国会図書館の典拠 ID" "ja")
(descr-as-in "ndl-auth-id" "" "zh-cn")
(descr-as-in "ndl-auth-id" "" "zh-sg")

