(ns properties.nkcr_aut_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nkcr-aut-id")

(name-as-in "nkcr-aut-id" "NKC編號" "zh-hk")
(name-as-in "nkcr-aut-id" "AUT NKC" "pt")
(name-as-in "nkcr-aut-id" "NKCR AUT ID" "en")
(name-as-in "nkcr-aut-id" "identifiant Bibliothèque nationale tchèque" "fr")
(name-as-in "nkcr-aut-id" "" "zh-tw")
(name-as-in "nkcr-aut-id" "NK ČR ID" "de")
(name-as-in "nkcr-aut-id" "код NKC" "ru")
(name-as-in "nkcr-aut-id" "identificador NKC" "es")
(name-as-in "nkcr-aut-id" "NKC識別子" "ja")
(name-as-in "nkcr-aut-id" "NKC识别码" "zh-cn")
(name-as-in "nkcr-aut-id" "" "zh-sg")

(descr-as-in "nkcr-aut-id" "" "zh-hk")
(descr-as-in "nkcr-aut-id" "" "pt")
(descr-as-in "nkcr-aut-id" "identifier in the Czech National Authority Database (National Library of Czech Republic)" "en")
(descr-as-in "nkcr-aut-id" "identifiant de la Bibliothèque nationale tchèque" "fr")
(descr-as-in "nkcr-aut-id" "" "zh-tw")
(descr-as-in "nkcr-aut-id" "Datenbanklink zum Portal der Nationalbibliothek der Tschechischen Republik" "de")
(descr-as-in "nkcr-aut-id" "код в каталоге Национальной библиотеки Чехии" "ru")
(descr-as-in "nkcr-aut-id" "Identificador del archivo de autoridad nacional de la República Checa (Biblioteca Nacional de República Checa)" "es")
(descr-as-in "nkcr-aut-id" "チェコ共和国国立図書館の典拠ファイルのID" "ja")
(descr-as-in "nkcr-aut-id" "捷克共和国国家机关文件（捷克共和国国家图书馆）编号" "zh-cn")
(descr-as-in "nkcr-aut-id" "" "zh-sg")

