(ns properties.nla_australia_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nla-australia-id")

(name-as-in "nla-australia-id" "NLA編號" "zh-hk")
(name-as-in "nla-australia-id" "identificador NLA" "pt")
(name-as-in "nla-australia-id" "NLA (Australia) ID" "en")
(name-as-in "nla-australia-id" "identifiant Bibliothèque nationale d'Australie" "fr")
(name-as-in "nla-australia-id" "" "zh-tw")
(name-as-in "nla-australia-id" "NLA Authorities" "de")
(name-as-in "nla-australia-id" "код NLA" "ru")
(name-as-in "nla-australia-id" "identificador NLA" "es")
(name-as-in "nla-australia-id" "NLA" "ja")
(name-as-in "nla-australia-id" "" "zh-cn")
(name-as-in "nla-australia-id" "" "zh-sg")

(descr-as-in "nla-australia-id" "" "zh-hk")
(descr-as-in "nla-australia-id" "" "pt")
(descr-as-in "nla-australia-id" "identifier issued by the National Library of Australia (see also P1315 for the newer People Australia identifier). VIAF component. Format: 1-12 digits, removing leading zero-padding." "en")
(descr-as-in "nla-australia-id" "Identifiant de la Bibliothèque nationale australienne (NLA)" "fr")
(descr-as-in "nla-australia-id" "" "zh-tw")
(descr-as-in "nla-australia-id" "Normdatennummer der Australischen Nationalbibliothek (siehe auch P1315), ohne führende Nullen" "de")
(descr-as-in "nla-australia-id" "библиотечный номер в Национальной библиотеке Австралии" "ru")
(descr-as-in "nla-australia-id" "número de control de autoridad de la National Library of Australia" "es")
(descr-as-in "nla-australia-id" "オーストラリア国立図書館の典拠コントロール番号" "ja")
(descr-as-in "nla-australia-id" "" "zh-cn")
(descr-as-in "nla-australia-id" "" "zh-sg")

