(ns properties.nlc_authorities
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nlc-authorities")

(name-as-in "nlc-authorities" "中國國家圖書館系統號" "zh-hk")
(name-as-in "nlc-authorities" "" "pt")
(name-as-in "nlc-authorities" "NLC authorities" "en")
(name-as-in "nlc-authorities" "identifiant NLC" "fr")
(name-as-in "nlc-authorities" "中國國家圖書館系統號" "zh-tw")
(name-as-in "nlc-authorities" "NLC (China)" "de")
(name-as-in "nlc-authorities" "код NLC" "ru")
(name-as-in "nlc-authorities" "NLC (control de autoría)" "es")
(name-as-in "nlc-authorities" "" "ja")
(name-as-in "nlc-authorities" "中国国家图书馆系统号" "zh-cn")
(name-as-in "nlc-authorities" "中国国家图书馆系统号" "zh-sg")

(descr-as-in "nlc-authorities" "中國國家圖書館的系統號" "zh-hk")
(descr-as-in "nlc-authorities" "" "pt")
(descr-as-in "nlc-authorities" "identifier for a person per National Library of China" "en")
(descr-as-in "nlc-authorities" "identifiant de la Bibliothèque Nationale de Chine (National Library of China)" "fr")
(descr-as-in "nlc-authorities" "中國國家圖書館的系統號" "zh-tw")
(descr-as-in "nlc-authorities" "Normdateneintrag in der Chinesischen Nationalbibliothek" "de")
(descr-as-in "nlc-authorities" "код человека в национальной библиотеке Китая" "ru")
(descr-as-in "nlc-authorities" "" "es")
(descr-as-in "nlc-authorities" "" "ja")
(descr-as-in "nlc-authorities" "中国国家图书馆的系统号" "zh-cn")
(descr-as-in "nlc-authorities" "中国国家图书馆的系统号" "zh-sg")

