(ns properties.nobel_prize_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nobel-prize-id")

(name-as-in "nobel-prize-id" "" "zh-hk")
(name-as-in "nobel-prize-id" "ID de prêmio Nobel" "pt")
(name-as-in "nobel-prize-id" "Nobel prize ID" "en")
(name-as-in "nobel-prize-id" "identifiant de biographie des lauréats du prix Nobel" "fr")
(name-as-in "nobel-prize-id" "" "zh-tw")
(name-as-in "nobel-prize-id" "Nobelpreis-ID" "de")
(name-as-in "nobel-prize-id" "" "ru")
(name-as-in "nobel-prize-id" "identificador de la biografía de los laureados de un premio Nobel" "es")
(name-as-in "nobel-prize-id" "" "ja")
(name-as-in "nobel-prize-id" "" "zh-cn")
(name-as-in "nobel-prize-id" "" "zh-sg")

(descr-as-in "nobel-prize-id" "" "zh-hk")
(descr-as-in "nobel-prize-id" "" "pt")
(descr-as-in "nobel-prize-id" "ID in the Nobel prize organization homepage" "en")
(descr-as-in "nobel-prize-id" "lien vers la biographie de chaque lauréat par l'organisation du prix Nobel" "fr")
(descr-as-in "nobel-prize-id" "" "zh-tw")
(descr-as-in "nobel-prize-id" "Identifikator einer Person auf der Website des Nobelpreises" "de")
(descr-as-in "nobel-prize-id" "" "ru")
(descr-as-in "nobel-prize-id" "" "es")
(descr-as-in "nobel-prize-id" "" "ja")
(descr-as-in "nobel-prize-id" "" "zh-cn")
(descr-as-in "nobel-prize-id" "" "zh-sg")

