(ns properties.nobel_prize_people_nomination_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nobel-prize-people-nomination-id")

(name-as-in "nobel-prize-people-nomination-id" "" "zh-hk")
(name-as-in "nobel-prize-people-nomination-id" "" "pt")
(name-as-in "nobel-prize-people-nomination-id" "Nobel Prize People Nomination ID" "en")
(name-as-in "nobel-prize-people-nomination-id" "identifiant de nomination de personnes au prix Nobel" "fr")
(name-as-in "nobel-prize-people-nomination-id" "" "zh-tw")
(name-as-in "nobel-prize-people-nomination-id" "" "de")
(name-as-in "nobel-prize-people-nomination-id" "идентификатор номинации на Нобелевскую премию" "ru")
(name-as-in "nobel-prize-people-nomination-id" "identificador de nominación de persona al Premio Nobel" "es")
(name-as-in "nobel-prize-people-nomination-id" "" "ja")
(name-as-in "nobel-prize-people-nomination-id" "" "zh-cn")
(name-as-in "nobel-prize-people-nomination-id" "" "zh-sg")

(descr-as-in "nobel-prize-people-nomination-id" "" "zh-hk")
(descr-as-in "nobel-prize-people-nomination-id" "" "pt")
(descr-as-in "nobel-prize-people-nomination-id" "identifier for a person who nominated someone, or who was nominated, for a Nobel Prize" "en")
(descr-as-in "nobel-prize-people-nomination-id" "identifiant pour une personne qui a nominé quelqu'un, ou qui a été nominé, pour le prix Nobel" "fr")
(descr-as-in "nobel-prize-people-nomination-id" "" "zh-tw")
(descr-as-in "nobel-prize-people-nomination-id" "" "de")
(descr-as-in "nobel-prize-people-nomination-id" "" "ru")
(descr-as-in "nobel-prize-people-nomination-id" "" "es")
(descr-as-in "nobel-prize-people-nomination-id" "" "ja")
(descr-as-in "nobel-prize-people-nomination-id" "" "zh-cn")
(descr-as-in "nobel-prize-people-nomination-id" "" "zh-sg")

