(ns properties.nominal_gdp_per_capita
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nominal-gdp-per-capita")

(name-as-in "nominal-gdp-per-capita" "" "zh-hk")
(name-as-in "nominal-gdp-per-capita" "PIB per capita" "pt")
(name-as-in "nominal-gdp-per-capita" "nominal GDP per capita" "en")
(name-as-in "nominal-gdp-per-capita" "PIB par habitant" "fr")
(name-as-in "nominal-gdp-per-capita" "" "zh-tw")
(name-as-in "nominal-gdp-per-capita" "BIP pro Kopf" "de")
(name-as-in "nominal-gdp-per-capita" "ВВП на душу населения" "ru")
(name-as-in "nominal-gdp-per-capita" "PBI per cápita" "es")
(name-as-in "nominal-gdp-per-capita" "" "ja")
(name-as-in "nominal-gdp-per-capita" "" "zh-cn")
(name-as-in "nominal-gdp-per-capita" "" "zh-sg")

(descr-as-in "nominal-gdp-per-capita" "" "zh-hk")
(descr-as-in "nominal-gdp-per-capita" "" "pt")
(descr-as-in "nominal-gdp-per-capita" "a country's total GDP divided by the population" "en")
(descr-as-in "nominal-gdp-per-capita" "" "fr")
(descr-as-in "nominal-gdp-per-capita" "" "zh-tw")
(descr-as-in "nominal-gdp-per-capita" "" "de")
(descr-as-in "nominal-gdp-per-capita" "" "ru")
(descr-as-in "nominal-gdp-per-capita" "" "es")
(descr-as-in "nominal-gdp-per-capita" "" "ja")
(descr-as-in "nominal-gdp-per-capita" "" "zh-cn")
(descr-as-in "nominal-gdp-per-capita" "" "zh-sg")

