(ns properties.nomisma_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nomisma-id")

(name-as-in "nomisma-id" "" "zh-hk")
(name-as-in "nomisma-id" "" "pt")
(name-as-in "nomisma-id" "Nomisma ID" "en")
(name-as-in "nomisma-id" "identifiant Nomisma" "fr")
(name-as-in "nomisma-id" "" "zh-tw")
(name-as-in "nomisma-id" "Nomisma ID" "de")
(name-as-in "nomisma-id" "" "ru")
(name-as-in "nomisma-id" "identificador Nomisma" "es")
(name-as-in "nomisma-id" "" "ja")
(name-as-in "nomisma-id" "" "zh-cn")
(name-as-in "nomisma-id" "" "zh-sg")

(descr-as-in "nomisma-id" "" "zh-hk")
(descr-as-in "nomisma-id" "" "pt")
(descr-as-in "nomisma-id" "identifier in Nomisma.org, a linked open data thesaurus of numismatic concepts" "en")
(descr-as-in "nomisma-id" "identifiant dans Nomisma.org, un thésaurus de données ouvert de concepts numismatiques" "fr")
(descr-as-in "nomisma-id" "" "zh-tw")
(descr-as-in "nomisma-id" "" "de")
(descr-as-in "nomisma-id" "" "ru")
(descr-as-in "nomisma-id" "" "es")
(descr-as-in "nomisma-id" "" "ja")
(descr-as-in "nomisma-id" "" "zh-cn")
(descr-as-in "nomisma-id" "" "zh-sg")

