(ns properties.notable_work
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "notable-work")

(name-as-in "notable-work" "主要作品" "zh-hk")
(name-as-in "notable-work" "obra" "pt")
(name-as-in "notable-work" "notable work" "en")
(name-as-in "notable-work" "œuvre notable" "fr")
(name-as-in "notable-work" "主要作品" "zh-tw")
(name-as-in "notable-work" "Werke" "de")
(name-as-in "notable-work" "выдающееся произведение" "ru")
(name-as-in "notable-work" "obra destacada" "es")
(name-as-in "notable-work" "主要作品" "ja")
(name-as-in "notable-work" "主要作品" "zh-cn")
(name-as-in "notable-work" "主要作品" "zh-sg")

(descr-as-in "notable-work" "主要的科研或藝術等作品" "zh-hk")
(descr-as-in "notable-work" "obras de arte ou trabalhos científicos notáveis do sujeito" "pt")
(descr-as-in "notable-work" "subject's notable scientific, artistic or literary work, or other work of significance" "en")
(descr-as-in "notable-work" "œuvre particulièrement notable créée par la personne de l'élément" "fr")
(descr-as-in "notable-work" "主要的科研或藝術等作品" "zh-tw")
(descr-as-in "notable-work" "relevante wissenschaftliche oder künstlerische Werke der Person" "de")
(descr-as-in "notable-work" "выдающаяся научная работа или произведение искусства" "ru")
(descr-as-in "notable-work" "obra científica o de arte destacada del sujeto" "es")
(descr-as-in "notable-work" "主題による著名な作品（文学作品、芸術作品、科学論文など）" "ja")
(descr-as-in "notable-work" "主要的科研或艺术等作品" "zh-cn")
(descr-as-in "notable-work" "主要的科研或艺术等作品" "zh-sg")

