(ns properties.nukat_warsawu_authorities
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nukat-warsawu-authorities")

(name-as-in "nukat-warsawu-authorities" "NUKAT編號" "zh-hk")
(name-as-in "nukat-warsawu-authorities" "identificador NUKAT" "pt")
(name-as-in "nukat-warsawu-authorities" "NUKAT (WarsawU) authorities" "en")
(name-as-in "nukat-warsawu-authorities" "identifiant NUKAT" "fr")
(name-as-in "nukat-warsawu-authorities" "" "zh-tw")
(name-as-in "nukat-warsawu-authorities" "NUKAT-Normdaten" "de")
(name-as-in "nukat-warsawu-authorities" "код NUKAT" "ru")
(name-as-in "nukat-warsawu-authorities" "identificador NUKAT" "es")
(name-as-in "nukat-warsawu-authorities" "NUKAT" "ja")
(name-as-in "nukat-warsawu-authorities" "" "zh-cn")
(name-as-in "nukat-warsawu-authorities" "" "zh-sg")

(descr-as-in "nukat-warsawu-authorities" "" "zh-hk")
(descr-as-in "nukat-warsawu-authorities" "controlo de autoria da Polónia" "pt")
(descr-as-in "nukat-warsawu-authorities" "identifier for authority control in the Center of Warsaw University Library catalog" "en")
(descr-as-in "nukat-warsawu-authorities" "numéro de contrôle d'autorité du Catalogue de l'union polonaise" "fr")
(descr-as-in "nukat-warsawu-authorities" "" "zh-tw")
(descr-as-in "nukat-warsawu-authorities" "Normdateneintrag im polnischen Verbundkatalog NUKAT" "de")
(descr-as-in "nukat-warsawu-authorities" "идентификатор в каталогизаторе библиотечного cоюза Польши" "ru")
(descr-as-in "nukat-warsawu-authorities" "identificador para el control de autoridades del catálogo de la Biblioteca de la Universidad de Varsovia" "es")
(descr-as-in "nukat-warsawu-authorities" "ポーランドの図書館による共同目録の典拠管理番号" "ja")
(descr-as-in "nukat-warsawu-authorities" "" "zh-cn")
(descr-as-in "nukat-warsawu-authorities" "" "zh-sg")

