(ns properties.nuts_code
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nuts-code")

(name-as-in "nuts-code" "" "zh-hk")
(name-as-in "nuts-code" "código NUTS" "pt")
(name-as-in "nuts-code" "NUTS code" "en")
(name-as-in "nuts-code" "identifiant NUTS" "fr")
(name-as-in "nuts-code" "" "zh-tw")
(name-as-in "nuts-code" "NUTS" "de")
(name-as-in "nuts-code" "код NUTS" "ru")
(name-as-in "nuts-code" "NUTS" "es")
(name-as-in "nuts-code" "NUTSコード" "ja")
(name-as-in "nuts-code" "" "zh-cn")
(name-as-in "nuts-code" "" "zh-sg")

(descr-as-in "nuts-code" "" "zh-hk")
(descr-as-in "nuts-code" "" "pt")
(descr-as-in "nuts-code" "identifier for a region per NUTS" "en")
(descr-as-in "nuts-code" "code dans la nomenclature des unités territoriales statistiques" "fr")
(descr-as-in "nuts-code" "" "zh-tw")
(descr-as-in "nuts-code" "Systematik der Gebietseinheiten für die Statistik in der Europäischen Union" "de")
(descr-as-in "nuts-code" "" "ru")
(descr-as-in "nuts-code" "código de una región" "es")
(descr-as-in "nuts-code" "地域統計分類単位コード" "ja")
(descr-as-in "nuts-code" "" "zh-cn")
(descr-as-in "nuts-code" "" "zh-sg")

