(ns properties.nyt_topic_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "nyt-topic-id")

(name-as-in "nyt-topic-id" "紐約時報主題ID" "zh-hk")
(name-as-in "nyt-topic-id" "" "pt")
(name-as-in "nyt-topic-id" "NYT topic ID" "en")
(name-as-in "nyt-topic-id" "identifiant New York Times d'un sujet" "fr")
(name-as-in "nyt-topic-id" "紐約時報主題ID" "zh-tw")
(name-as-in "nyt-topic-id" "NYT-Themen-ID" "de")
(name-as-in "nyt-topic-id" "код темы NYT" "ru")
(name-as-in "nyt-topic-id" "identificador New York Times de tema" "es")
(name-as-in "nyt-topic-id" "" "ja")
(name-as-in "nyt-topic-id" "纽约时报主题ID" "zh-cn")
(name-as-in "nyt-topic-id" "纽约时报主题ID" "zh-sg")

(descr-as-in "nyt-topic-id" "" "zh-hk")
(descr-as-in "nyt-topic-id" "" "pt")
(descr-as-in "nyt-topic-id" "identifier for a topic, at the New York Times' website" "en")
(descr-as-in "nyt-topic-id" "identifiant d'un sujet sur le site Web du New York Times" "fr")
(descr-as-in "nyt-topic-id" "" "zh-tw")
(descr-as-in "nyt-topic-id" "Identifikator eines Themas auf der Webseite der New York Times" "de")
(descr-as-in "nyt-topic-id" "" "ru")
(descr-as-in "nyt-topic-id" "" "es")
(descr-as-in "nyt-topic-id" "" "ja")
(descr-as-in "nyt-topic-id" "" "zh-cn")
(descr-as-in "nyt-topic-id" "" "zh-sg")

