(ns properties.occupation
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "occupation")

(name-as-in "occupation" "職業" "zh-hk")
(name-as-in "occupation" "ocupação" "pt")
(name-as-in "occupation" "occupation" "en")
(name-as-in "occupation" "occupation" "fr")
(name-as-in "occupation" "職業" "zh-tw")
(name-as-in "occupation" "Tätigkeit" "de")
(name-as-in "occupation" "род занятий" "ru")
(name-as-in "occupation" "ocupación" "es")
(name-as-in "occupation" "職業" "ja")
(name-as-in "occupation" "职业" "zh-cn")
(name-as-in "occupation" "职业" "zh-sg")

(descr-as-in "occupation" "項所從事的行業" "zh-hk")
(descr-as-in "occupation" "ocupação de uma pessoa; ver também campo de trabalho (Property:P101)" "pt")
(descr-as-in "occupation" "occupation of a person; see also field of work (Property:P101), position held (Property:P39)" "en")
(descr-as-in "occupation" "qualité d'une personne (métier, hobby...), voir aussi domaine d'activité (Property:P101) et fonction (Property:P39)" "fr")
(descr-as-in "occupation" "項所從事的行業" "zh-tw")
(descr-as-in "occupation" "Beruf oder andere Tätigkeit einer Person (ergänzt durch Arbeitsgebiet: Property:P101)" "de")
(descr-as-in "occupation" "профессия персоны; см. также свойство «область деятельности» (Property:P101)" "ru")
(descr-as-in "occupation" "actividad laboral u otra ocupación de la persona; véase también campo de trabajo (propiedad 101)" "es")
(descr-as-in "occupation" "人物の職業。「専門分野」(Property:P101) も参照" "ja")
(descr-as-in "occupation" "项所从事的行业" "zh-cn")
(descr-as-in "occupation" "项所从事的行业" "zh-sg")

