(ns properties.occupant
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "occupant")

(name-as-in "occupant" "" "zh-hk")
(name-as-in "occupant" "ocupante" "pt")
(name-as-in "occupant" "occupant" "en")
(name-as-in "occupant" "occupant" "fr")
(name-as-in "occupant" "" "zh-tw")
(name-as-in "occupant" "Bewohner/Nutzer" "de")
(name-as-in "occupant" "обитатель" "ru")
(name-as-in "occupant" "ocupante" "es")
(name-as-in "occupant" "入居者" "ja")
(name-as-in "occupant" "" "zh-cn")
(name-as-in "occupant" "" "zh-sg")

(descr-as-in "occupant" "" "zh-hk")
(descr-as-in "occupant" "pessoa ou organização ocupando um local" "pt")
(descr-as-in "occupant" "person or organization occupying a building or facility" "en")
(descr-as-in "occupant" "personne ou organisation occupant un bâtiment" "fr")
(descr-as-in "occupant" "" "zh-tw")
(descr-as-in "occupant" "Person, Gruppe oder Organisation, die ein Gebäude bewohnt bzw. nutzt" "de")
(descr-as-in "occupant" "личность или организация, занимающая данное здание или сооружение" "ru")
(descr-as-in "occupant" "persona u organización que se encuentra en una edificación" "es")
(descr-as-in "occupant" "この建築物に入居している人または組織" "ja")
(descr-as-in "occupant" "" "zh-cn")
(descr-as-in "occupant" "" "zh-sg")

