(ns properties.oclc_control_number
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "oclc-control-number")

(name-as-in "oclc-control-number" "OCLC" "zh-hk")
(name-as-in "oclc-control-number" "número de controle da Online Computer Library Center" "pt")
(name-as-in "oclc-control-number" "OCLC control number" "en")
(name-as-in "oclc-control-number" "identifiant OCLC" "fr")
(name-as-in "oclc-control-number" "OCLC" "zh-tw")
(name-as-in "oclc-control-number" "OCLC-ID" "de")
(name-as-in "oclc-control-number" "OCLC" "ru")
(name-as-in "oclc-control-number" "identificador OCLC" "es")
(name-as-in "oclc-control-number" "OCLC" "ja")
(name-as-in "oclc-control-number" "OCLC" "zh-cn")
(name-as-in "oclc-control-number" "OCLC" "zh-sg")

(descr-as-in "oclc-control-number" "聯機計算機圖書館中心編號" "zh-hk")
(descr-as-in "oclc-control-number" "" "pt")
(descr-as-in "oclc-control-number" "identifier from the Online Computer Library Center" "en")
(descr-as-in "oclc-control-number" "numéro de contrôle de l’Online Computer Library Center" "fr")
(descr-as-in "oclc-control-number" "聯機計算機圖書館中心編號" "zh-tw")
(descr-as-in "oclc-control-number" "Identifikationsnummer im Online Computer Library Center und WorldCat" "de")
(descr-as-in "oclc-control-number" "Online Computer Library Center" "ru")
(descr-as-in "oclc-control-number" "número de control del Online Computer Library Center" "es")
(descr-as-in "oclc-control-number" "Online Computer Library Center（オンライン・コンピューター・ライブラリー・センター）の識別番号" "ja")
(descr-as-in "oclc-control-number" "线上计算机图书馆中心管理编号" "zh-cn")
(descr-as-in "oclc-control-number" "线上计算机图书馆中心管理编号" "zh-sg")

