(ns properties.official_name
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "official-name")

(name-as-in "official-name" "官方名稱" "zh-hk")
(name-as-in "official-name" "nome oficial" "pt")
(name-as-in "official-name" "official name" "en")
(name-as-in "official-name" "nom officiel" "fr")
(name-as-in "official-name" "官方名稱" "zh-tw")
(name-as-in "official-name" "offizieller Name" "de")
(name-as-in "official-name" "официальное название" "ru")
(name-as-in "official-name" "nombre oficial" "es")
(name-as-in "official-name" "正式名称" "ja")
(name-as-in "official-name" "官方名称" "zh-cn")
(name-as-in "official-name" "官方名称" "zh-sg")

(descr-as-in "official-name" "" "zh-hk")
(descr-as-in "official-name" "" "pt")
(descr-as-in "official-name" "official name of the subject in its official language(s)" "en")
(descr-as-in "official-name" "nom du sujet dans la (les) langue(s) officielle(s) de ce sujet (lieu, organisation...)" "fr")
(descr-as-in "official-name" "" "zh-tw")
(descr-as-in "official-name" "offizieller Name eines Objektes in seiner offiziellen Sprache" "de")
(descr-as-in "official-name" "строка с названием субъекта на официальном языке" "ru")
(descr-as-in "official-name" "nombre oficial del sujeto en su(s) idiomas oficial(es)" "es")
(descr-as-in "official-name" "主題の正式な名前" "ja")
(descr-as-in "official-name" "" "zh-cn")
(descr-as-in "official-name" "" "zh-sg")

