(ns properties.official_language
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "official-language")

(name-as-in "official-language" "官方語言" "zh-hk")
(name-as-in "official-language" "língua oficial" "pt")
(name-as-in "official-language" "official language" "en")
(name-as-in "official-language" "langue officielle" "fr")
(name-as-in "official-language" "官方語言" "zh-tw")
(name-as-in "official-language" "Amtssprache" "de")
(name-as-in "official-language" "официальный язык" "ru")
(name-as-in "official-language" "idioma oficial" "es")
(name-as-in "official-language" "公用語" "ja")
(name-as-in "official-language" "官方语言" "zh-cn")
(name-as-in "official-language" "官方语言" "zh-sg")

(descr-as-in "official-language" "" "zh-hk")
(descr-as-in "official-language" "" "pt")
(descr-as-in "official-language" "language designated as official by this item" "en")
(descr-as-in "official-language" "langue officiellement reconnue par l'élément" "fr")
(descr-as-in "official-language" "" "zh-tw")
(descr-as-in "official-language" "offizielle Sprache des Staates" "de")
(descr-as-in "official-language" "язык, определённый как официальный для этого элемента" "ru")
(descr-as-in "official-language" "idioma oficial del elemento" "es")
(descr-as-in "official-language" "この項目が公用語としている言語" "ja")
(descr-as-in "official-language" "" "zh-cn")
(descr-as-in "official-language" "" "zh-sg")

