(ns properties.omni_topic_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "omni-topic-id")

(name-as-in "omni-topic-id" "" "zh-hk")
(name-as-in "omni-topic-id" "" "pt")
(name-as-in "omni-topic-id" "Omni topic ID" "en")
(name-as-in "omni-topic-id" "identifiant Omni du sujet d'actualité" "fr")
(name-as-in "omni-topic-id" "" "zh-tw")
(name-as-in "omni-topic-id" "" "de")
(name-as-in "omni-topic-id" "" "ru")
(name-as-in "omni-topic-id" "identificador Omni de tema" "es")
(name-as-in "omni-topic-id" "" "ja")
(name-as-in "omni-topic-id" "" "zh-cn")
(name-as-in "omni-topic-id" "" "zh-sg")

(descr-as-in "omni-topic-id" "" "zh-hk")
(descr-as-in "omni-topic-id" "" "pt")
(descr-as-in "omni-topic-id" "identifier for a topic, used by Omni and Aftonbladet" "en")
(descr-as-in "omni-topic-id" "identifiant d'un sujet utilisé par Omni et Aftonbladet (journaux suédois)" "fr")
(descr-as-in "omni-topic-id" "" "zh-tw")
(descr-as-in "omni-topic-id" "" "de")
(descr-as-in "omni-topic-id" "" "ru")
(descr-as-in "omni-topic-id" "" "es")
(descr-as-in "omni-topic-id" "" "ja")
(descr-as-in "omni-topic-id" "" "zh-cn")
(descr-as-in "omni-topic-id" "" "zh-sg")

