(ns properties.openplaques_subject_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "openplaques-subject-id")

(name-as-in "openplaques-subject-id" "" "zh-hk")
(name-as-in "openplaques-subject-id" "identificador OpenPlaques" "pt")
(name-as-in "openplaques-subject-id" "OpenPlaques subject ID" "en")
(name-as-in "openplaques-subject-id" "identifiant OpenPlaques" "fr")
(name-as-in "openplaques-subject-id" "" "zh-tw")
(name-as-in "openplaques-subject-id" "OpenPlaques-Themen-ID" "de")
(name-as-in "openplaques-subject-id" "код OpenPlaques" "ru")
(name-as-in "openplaques-subject-id" "identificador OpenPlaques" "es")
(name-as-in "openplaques-subject-id" "OpenPlaques識別子" "ja")
(name-as-in "openplaques-subject-id" "" "zh-cn")
(name-as-in "openplaques-subject-id" "" "zh-sg")

(descr-as-in "openplaques-subject-id" "" "zh-hk")
(descr-as-in "openplaques-subject-id" "identificador de uma pessoa na base de dados OpenPlaques - http://openplaques.org" "pt")
(descr-as-in "openplaques-subject-id" "identifier for a person or other subject in the OpenPlaques database - http://openplaques.org/" "en")
(descr-as-in "openplaques-subject-id" "identifiant d'une personne dans la base de données OpenPlaques - http://openplaques.org/" "fr")
(descr-as-in "openplaques-subject-id" "" "zh-tw")
(descr-as-in "openplaques-subject-id" "ID des Objektes in der OpenPlaques-Datenbank (dort people genannt, umfasst aber allgemein Themen, die Plaketten haben können)" "de")
(descr-as-in "openplaques-subject-id" "" "ru")
(descr-as-in "openplaques-subject-id" "identificador de persona en la base de datos OpenPlaques" "es")
(descr-as-in "openplaques-subject-id" "OpenPlaquesデータベースの識別子 - http://openplaques.org/" "ja")
(descr-as-in "openplaques-subject-id" "" "zh-cn")
(descr-as-in "openplaques-subject-id" "" "zh-sg")

