(ns properties.open_library_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "open-library-id")

(name-as-in "open-library-id" "Open Library編號" "zh-hk")
(name-as-in "open-library-id" "identificador Open Library" "pt")
(name-as-in "open-library-id" "Open Library ID" "en")
(name-as-in "open-library-id" "identifiant Open Library" "fr")
(name-as-in "open-library-id" "Open Library編號" "zh-tw")
(name-as-in "open-library-id" "Open-Library-ID" "de")
(name-as-in "open-library-id" "код в Открытой библиотеке" "ru")
(name-as-in "open-library-id" "identificador Open Library" "es")
(name-as-in "open-library-id" "Open Library識別子" "ja")
(name-as-in "open-library-id" "Open Library编号" "zh-cn")
(name-as-in "open-library-id" "Open Library编号" "zh-sg")

(descr-as-in "open-library-id" "" "zh-hk")
(descr-as-in "open-library-id" "" "pt")
(descr-as-in "open-library-id" "identifier for works, editions and authors" "en")
(descr-as-in "open-library-id" "identifiant d'une oeuvre (W), d'une édition (M) ou d'un Auteur (A)" "fr")
(descr-as-in "open-library-id" "" "zh-tw")
(descr-as-in "open-library-id" "numerische Buch-Kennung für Werke (W), einzelne Ausgaben (M) und Autoren (A)" "de")
(descr-as-in "open-library-id" "числовой идентификатор для работ, изданий и авторов" "ru")
(descr-as-in "open-library-id" "" "es")
(descr-as-in "open-library-id" "" "ja")
(descr-as-in "open-library-id" "" "zh-cn")
(descr-as-in "open-library-id" "" "zh-sg")

