(ns properties.openstreetmap_relation_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "openstreetmap-relation-id")

(name-as-in "openstreetmap-relation-id" "OpenStreetMap-Relation-ID" "de")
(name-as-in "openstreetmap-relation-id" "" "zh-hk")
(name-as-in "openstreetmap-relation-id" "開放街圖關聯ID" "zh-tw")
(name-as-in "openstreetmap-relation-id" "ID отношения в OpenStreetMap" "ru")
(name-as-in "openstreetmap-relation-id" "ID de relação OpenStreetMap" "pt")
(name-as-in "openstreetmap-relation-id" "OpenStreetMap Relation ID" "en")
(name-as-in "openstreetmap-relation-id" "" "zh-cn")
(name-as-in "openstreetmap-relation-id" "relation OpenStreetMap" "fr")
(name-as-in "openstreetmap-relation-id" "identificador OpenStreetMap" "es")
(name-as-in "openstreetmap-relation-id" "" "zh-sg")
(name-as-in "openstreetmap-relation-id" "オープンストリートマップのリレーションID" "ja")
(name-as-in "openstreetmap-relation-id" "OpenStreetMap关系ID" "zh-hans")
(name-as-in "openstreetmap-relation-id" "OpenStreetMap 關聯ID" "zh-hant")

(descr-as-in "openstreetmap-relation-id" "ID des geographischen Objekts in OpenStreetMap" "de")
(descr-as-in "openstreetmap-relation-id" "" "zh-hk")
(descr-as-in "openstreetmap-relation-id" "" "zh-tw")
(descr-as-in "openstreetmap-relation-id" "" "ru")
(descr-as-in "openstreetmap-relation-id" "" "pt")
(descr-as-in "openstreetmap-relation-id" "the ID of the relation of this place/object in OpenStreetMap" "en")
(descr-as-in "openstreetmap-relation-id" "" "zh-cn")
(descr-as-in "openstreetmap-relation-id" "identifiant de la relation OpenStreetMap" "fr")
(descr-as-in "openstreetmap-relation-id" "" "es")
(descr-as-in "openstreetmap-relation-id" "" "zh-sg")
(descr-as-in "openstreetmap-relation-id" "この場所・建造物のオープンストリートマップにおけるリレーションのID" "ja")
(descr-as-in "openstreetmap-relation-id" "" "zh-hans")
(descr-as-in "openstreetmap-relation-id" "" "zh-hant")

