(ns properties.openmlol_author_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "openmlol-author-id")

(name-as-in "openmlol-author-id" "" "zh-hk")
(name-as-in "openmlol-author-id" "" "pt")
(name-as-in "openmlol-author-id" "openMLOL author ID" "en")
(name-as-in "openmlol-author-id" "identifiant openMLOL d'auteur" "fr")
(name-as-in "openmlol-author-id" "" "zh-tw")
(name-as-in "openmlol-author-id" "openMLOL-Autorennummer" "de")
(name-as-in "openmlol-author-id" "код автора openMLOL" "ru")
(name-as-in "openmlol-author-id" "identificador openMLOL de un autor" "es")
(name-as-in "openmlol-author-id" "" "ja")
(name-as-in "openmlol-author-id" "" "zh-cn")
(name-as-in "openmlol-author-id" "" "zh-sg")

(descr-as-in "openmlol-author-id" "" "zh-hk")
(descr-as-in "openmlol-author-id" "" "pt")
(descr-as-in "openmlol-author-id" "identifier of an author in the openMLOL digital library of cultural resources" "en")
(descr-as-in "openmlol-author-id" "identifiant d'un auteur dans la bibliothèque digitale de ressources culturelles openMLOL" "fr")
(descr-as-in "openmlol-author-id" "" "zh-tw")
(descr-as-in "openmlol-author-id" "Identifikator in der openMLOL-Datenbank" "de")
(descr-as-in "openmlol-author-id" "" "ru")
(descr-as-in "openmlol-author-id" "" "es")
(descr-as-in "openmlol-author-id" "" "ja")
(descr-as-in "openmlol-author-id" "" "zh-cn")
(descr-as-in "openmlol-author-id" "" "zh-sg")

