(ns properties.opposite_of
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "opposite-of")

(name-as-in "opposite-of" "相對概念" "zh-hk")
(name-as-in "opposite-of" "oposto de" "pt")
(name-as-in "opposite-of" "opposite of" "en")
(name-as-in "opposite-of" "contraire" "fr")
(name-as-in "opposite-of" "相對概念" "zh-tw")
(name-as-in "opposite-of" "Gegenteil von" "de")
(name-as-in "opposite-of" "противоположно" "ru")
(name-as-in "opposite-of" "opuesto a" "es")
(name-as-in "opposite-of" "反対の概念" "ja")
(name-as-in "opposite-of" "相对概念" "zh-cn")
(name-as-in "opposite-of" "相对概念" "zh-sg")

(descr-as-in "opposite-of" "與此項相反的概念" "zh-hk")
(descr-as-in "opposite-of" "" "pt")
(descr-as-in "opposite-of" "item that is the opposite of this item" "en")
(descr-as-in "opposite-of" "objet contraire à l'objet" "fr")
(descr-as-in "opposite-of" "與此項相反的概念" "zh-tw")
(descr-as-in "opposite-of" "Objekt, das das Gegenteil dieses Objekts ist" "de")
(descr-as-in "opposite-of" "элемент, являющийся антонимом данному элементу" "ru")
(descr-as-in "opposite-of" "elemento que es el opuesto de este elemento" "es")
(descr-as-in "opposite-of" "この項目の反対の関係にある概念の項目" "ja")
(descr-as-in "opposite-of" "与此项相反的概念" "zh-cn")
(descr-as-in "opposite-of" "与此项相反的概念" "zh-sg")

