(ns properties.pactols_thesaurus_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "pactols-thesaurus-id")

(name-as-in "pactols-thesaurus-id" "" "zh-hk")
(name-as-in "pactols-thesaurus-id" "" "pt")
(name-as-in "pactols-thesaurus-id" "PACTOLS thesaurus ID" "en")
(name-as-in "pactols-thesaurus-id" "identifiant PACTOLS" "fr")
(name-as-in "pactols-thesaurus-id" "" "zh-tw")
(name-as-in "pactols-thesaurus-id" "" "de")
(name-as-in "pactols-thesaurus-id" "" "ru")
(name-as-in "pactols-thesaurus-id" "" "es")
(name-as-in "pactols-thesaurus-id" "" "ja")
(name-as-in "pactols-thesaurus-id" "" "zh-cn")
(name-as-in "pactols-thesaurus-id" "" "zh-sg")

(descr-as-in "pactols-thesaurus-id" "" "zh-hk")
(descr-as-in "pactols-thesaurus-id" "" "pt")
(descr-as-in "pactols-thesaurus-id" "identifier in the PACTOLS archaeology thesaurus by FRANTIQ" "en")
(descr-as-in "pactols-thesaurus-id" "identifiant dans le thésaurus PACTOLS du réseau FRANTIQ (archéologie et Antiquité)" "fr")
(descr-as-in "pactols-thesaurus-id" "" "zh-tw")
(descr-as-in "pactols-thesaurus-id" "" "de")
(descr-as-in "pactols-thesaurus-id" "" "ru")
(descr-as-in "pactols-thesaurus-id" "" "es")
(descr-as-in "pactols-thesaurus-id" "" "ja")
(descr-as-in "pactols-thesaurus-id" "" "zh-cn")
(descr-as-in "pactols-thesaurus-id" "" "zh-sg")

