(ns properties.page_banner
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "page-banner")

(name-as-in "page-banner" "維基導遊橫幅" "zh-hk")
(name-as-in "page-banner" "banner de Wikivoyage" "pt")
(name-as-in "page-banner" "page banner" "en")
(name-as-in "page-banner" "bannière Wikivoyage" "fr")
(name-as-in "page-banner" "維基導遊橫幅" "zh-tw")
(name-as-in "page-banner" "Wikivoyage-Banner" "de")
(name-as-in "page-banner" "баннер Викигида" "ru")
(name-as-in "page-banner" "banner de Wikiviajes" "es")
(name-as-in "page-banner" "ページバナー" "ja")
(name-as-in "page-banner" "维基导游横幅" "zh-cn")
(name-as-in "page-banner" "" "zh-sg")

(descr-as-in "page-banner" "相關維基導遊頁面的橫幅圖片" "zh-hk")
(descr-as-in "page-banner" "" "pt")
(descr-as-in "page-banner" "a lead image about the topic, mainly used by Wikivoyages" "en")
(descr-as-in "page-banner" "bannière en haut des articles de Wikivoyage" "fr")
(descr-as-in "page-banner" "相關維基導遊頁面的橫幅圖片" "zh-tw")
(descr-as-in "page-banner" "Banner-Bild der Wikivoyage-Seite" "de")
(descr-as-in "page-banner" "протяжённое изображение, размещаемое в верхней части статьи Викигида" "ru")
(descr-as-in "page-banner" "" "es")
(descr-as-in "page-banner" "主題についての冒頭画像、主にウィキボヤージュで使用" "ja")
(descr-as-in "page-banner" "相关维基导游页面的横幅图片" "zh-cn")
(descr-as-in "page-banner" "" "zh-sg")

