(ns properties.part_of
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "part-of")

(name-as-in "part-of" "屬於" "zh-hk")
(name-as-in "part-of" "parte de" "pt")
(name-as-in "part-of" "part of" "en")
(name-as-in "part-of" "partie de" "fr")
(name-as-in "part-of" "屬於" "zh-tw")
(name-as-in "part-of" "ist Teil von" "de")
(name-as-in "part-of" "часть от" "ru")
(name-as-in "part-of" "forma parte de" "es")
(name-as-in "part-of" "以下の一部分" "ja")
(name-as-in "part-of" "属于" "zh-cn")
(name-as-in "part-of" "属于" "zh-sg")

(descr-as-in "part-of" "此項是另一個實體的一部分" "zh-hk")
(descr-as-in "part-of" "o sujeito é uma parte daquele objeto" "pt")
(descr-as-in "part-of" "object of which the subject is a part. Inverse property of has part (P527). See also has parts of the class (P2670)." "en")
(descr-as-in "part-of" "objet dont fait directement partie cet élément. Il est inutile de lier des objets qui font eux-mêmes déjà partie d'autres objets indiqués comme parties d'un élément. Propriété inverse de comprend (P527)." "fr")
(descr-as-in "part-of" "此項是另一個實體的一部分" "zh-tw")
(descr-as-in "part-of" "Subjekt ist Teil des Objekts. (Teil-Ganzes-Relation)" "de")
(descr-as-in "part-of" "меронимическое отношение" "ru")
(descr-as-in "part-of" "es parte del elemento. Propiedad inversa de compuesto de (P527). También véase tiene partes de la clase (P2670)." "es")
(descr-as-in "part-of" "この項目を一部分とする全体" "ja")
(descr-as-in "part-of" "此项是另一个实体的一部分" "zh-cn")
(descr-as-in "part-of" "此项是另一个实体的一部分" "zh-sg")

