(ns properties.people_australia_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "people-australia-id")

(name-as-in "people-australia-id" "" "zh-hk")
(name-as-in "people-australia-id" "" "pt")
(name-as-in "people-australia-id" "People Australia ID" "en")
(name-as-in "people-australia-id" "identifiant People Australia" "fr")
(name-as-in "people-australia-id" "" "zh-tw")
(name-as-in "people-australia-id" "NLA Persistent Identifier" "de")
(name-as-in "people-australia-id" "код в Национальной библиотеке Австралии" "ru")
(name-as-in "people-australia-id" "identificador People Australia" "es")
(name-as-in "people-australia-id" "" "ja")
(name-as-in "people-australia-id" "" "zh-cn")
(name-as-in "people-australia-id" "" "zh-sg")

(descr-as-in "people-australia-id" "" "zh-hk")
(descr-as-in "people-australia-id" "" "pt")
(descr-as-in "people-australia-id" "identifier for people per National Library of Australia (see also P409 for the older Libraries Australia identifier). Format: 6 to 8 digits." "en")
(descr-as-in "people-australia-id" "identifiant pour une personne par la National Library of Australia (voir aussi P409 pour les identifiants de Libraries Australia plus anciens)" "fr")
(descr-as-in "people-australia-id" "" "zh-tw")
(descr-as-in "people-australia-id" "Normdatennummer der Australischen Nationalbibliothek (siehe auch P409), ohne führende Nullen, i.d.R. für Personen" "de")
(descr-as-in "people-australia-id" "идентификатор персоналии в Национальной библиотеке Австралии" "ru")
(descr-as-in "people-australia-id" "identificador para personas en la National Library of Australia" "es")
(descr-as-in "people-australia-id" "" "ja")
(descr-as-in "people-australia-id" "" "zh-cn")
(descr-as-in "people-australia-id" "" "zh-sg")

