(ns properties.permanent_duplicated_item
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "permanent-duplicated-item")

(name-as-in "permanent-duplicated-item" "永久重複項" "zh-hk")
(name-as-in "permanent-duplicated-item" "item duplicado permanentemente" "pt")
(name-as-in "permanent-duplicated-item" "permanent duplicated item" "en")
(name-as-in "permanent-duplicated-item" "élément doublon permanent" "fr")
(name-as-in "permanent-duplicated-item" "永久重複項" "zh-tw")
(name-as-in "permanent-duplicated-item" "dauerhaftes Duplikat von" "de")
(name-as-in "permanent-duplicated-item" "постоянный дубликат" "ru")
(name-as-in "permanent-duplicated-item" "duplicado permanente" "es")
(name-as-in "permanent-duplicated-item" "永久な重複項目" "ja")
(name-as-in "permanent-duplicated-item" "永久重复项" "zh-cn")
(name-as-in "permanent-duplicated-item" "永久重复项" "zh-sg")

(descr-as-in "permanent-duplicated-item" "" "zh-hk")
(descr-as-in "permanent-duplicated-item" "" "pt")
(descr-as-in "permanent-duplicated-item" "this item duplicates another item and the two can't be merged, as one Wikimedia project includes two pages, e. g. in different scripts or languages, Wikimedia list article that has been splitted into pages" "en")
(descr-as-in "permanent-duplicated-item" "cet élément est un doublon d'un autre élément et les deux ne peuvent pas être fusionné, étant donné que l'un des projets Wikimédia inclut deux pages, par exemple dans deux alphabets ou langues différents" "fr")
(descr-as-in "permanent-duplicated-item" "" "zh-tw")
(descr-as-in "permanent-duplicated-item" "dieser Eintrag ist ein Duplikat eines anderen. Sie können nicht zusammengeführt, weil ein Wikimedia-Projekt unterschiedliche Seiten dazu hat, z. B. in unterschiedlichen Schriften oder Sprachen" "de")
(descr-as-in "permanent-duplicated-item" "обычно для связи двух статей в одном проекте Викимедиа об одном и том же (но на другом диалекте или в другом алфавите)" "ru")
(descr-as-in "permanent-duplicated-item" "" "es")
(descr-as-in "permanent-duplicated-item" "重複項目ではあるが、さまざまな理由により併合できないもの" "ja")
(descr-as-in "permanent-duplicated-item" "" "zh-cn")
(descr-as-in "permanent-duplicated-item" "" "zh-sg")

