(ns properties.place_of_publication
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "place-of-publication")

(name-as-in "place-of-publication" "出版地" "zh-hk")
(name-as-in "place-of-publication" "local de publicação" "pt")
(name-as-in "place-of-publication" "place of publication" "en")
(name-as-in "place-of-publication" "lieu de publication" "fr")
(name-as-in "place-of-publication" "出版地" "zh-tw")
(name-as-in "place-of-publication" "Erscheinungsort" "de")
(name-as-in "place-of-publication" "место публикации" "ru")
(name-as-in "place-of-publication" "lugar de publicación" "es")
(name-as-in "place-of-publication" "出版地" "ja")
(name-as-in "place-of-publication" "出版地" "zh-cn")
(name-as-in "place-of-publication" "出版地" "zh-sg")

(descr-as-in "place-of-publication" "" "zh-hk")
(descr-as-in "place-of-publication" "" "pt")
(descr-as-in "place-of-publication" "geographical place of publication of the edition (use 1st edition when referring to works)" "en")
(descr-as-in "place-of-publication" "lieu de publication de l'édition" "fr")
(descr-as-in "place-of-publication" "項目第一版的出版地" "zh-tw")
(descr-as-in "place-of-publication" "Erscheinungsort einer Publikation (bei Büchern der Ort der Erstausgabe)" "de")
(descr-as-in "place-of-publication" "географическое место публикации (для произведений - первого издания)" "ru")
(descr-as-in "place-of-publication" "ubicación geográfica de la primera edición" "es")
(descr-as-in "place-of-publication" "初版が出版された地理的位置" "ja")
(descr-as-in "place-of-publication" "" "zh-cn")
(descr-as-in "place-of-publication" "" "zh-sg")

