(ns properties.place_of_death
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "place-of-death")

(name-as-in "place-of-death" "死亡地" "zh-hk")
(name-as-in "place-of-death" "local de morte" "pt")
(name-as-in "place-of-death" "place of death" "en")
(name-as-in "place-of-death" "lieu de décès" "fr")
(name-as-in "place-of-death" "死亡地" "zh-tw")
(name-as-in "place-of-death" "Sterbeort" "de")
(name-as-in "place-of-death" "место смерти" "ru")
(name-as-in "place-of-death" "lugar de fallecimiento" "es")
(name-as-in "place-of-death" "死亡地" "ja")
(name-as-in "place-of-death" "死亡地" "zh-cn")
(name-as-in "place-of-death" "死亡地" "zh-sg")

(descr-as-in "place-of-death" "最具體地點（例如城市，而非國家）" "zh-hk")
(descr-as-in "place-of-death" "" "pt")
(descr-as-in "place-of-death" "most specific known (e.g. city instead of country, or hospital instead of city) death location of a person, animal or fictional character" "en")
(descr-as-in "place-of-death" "lieu où la personne est morte la plus précise possible (ville au lieu de pays par exemple)" "fr")
(descr-as-in "place-of-death" "最具體地點（例如城市，而非國家）" "zh-tw")
(descr-as-in "place-of-death" "Ort, an dem ein Mensch gestorben ist (so genau wie bekannt, z. B. Stadt anstatt von Land)" "de")
(descr-as-in "place-of-death" "наиболее точное место, где субъект умер (например, город, а не страна)" "ru")
(descr-as-in "place-of-death" "Sitio donde murió una persona. Usar el sitio más específico disponible." "es")
(descr-as-in "place-of-death" "最も詳細かつ知られた死亡地（例：国ではなく市）" "ja")
(descr-as-in "place-of-death" "最具体地点（例如城市，而非国家）" "zh-cn")
(descr-as-in "place-of-death" "" "zh-sg")

