(ns properties.pm20_folder_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "pm20-folder-id")

(name-as-in "pm20-folder-id" "" "zh-hk")
(name-as-in "pm20-folder-id" "" "pt")
(name-as-in "pm20-folder-id" "PM20 folder ID" "en")
(name-as-in "pm20-folder-id" "identifiant PM20 de dossier" "fr")
(name-as-in "pm20-folder-id" "" "zh-tw")
(name-as-in "pm20-folder-id" "PM20 Mappen-ID" "de")
(name-as-in "pm20-folder-id" "" "ru")
(name-as-in "pm20-folder-id" "identificador PM20 carpeta" "es")
(name-as-in "pm20-folder-id" "" "ja")
(name-as-in "pm20-folder-id" "" "zh-cn")
(name-as-in "pm20-folder-id" "" "zh-sg")

(descr-as-in "pm20-folder-id" "" "zh-hk")
(descr-as-in "pm20-folder-id" "" "pt")
(descr-as-in "pm20-folder-id" "identifier for a folder in the German  Pressemappe 20. Jahrhundert (20th century press archive)" "en")
(descr-as-in "pm20-folder-id" "identifiant pour un dossier dans le Pressemappe 20. Jahrhundert allemand (archive de presse du 20e siècle)" "fr")
(descr-as-in "pm20-folder-id" "" "zh-tw")
(descr-as-in "pm20-folder-id" "Bezeichner für eine Mappe in der Pressemappe 20. Jahrhundert des deutschen Pressearchiv 20. Jahrhundert" "de")
(descr-as-in "pm20-folder-id" "" "ru")
(descr-as-in "pm20-folder-id" "" "es")
(descr-as-in "pm20-folder-id" "" "ja")
(descr-as-in "pm20-folder-id" "" "zh-cn")
(descr-as-in "pm20-folder-id" "" "zh-sg")

