(ns properties.population
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "population")

(name-as-in "population" "人口" "zh-hk")
(name-as-in "population" "população" "pt")
(name-as-in "population" "population" "en")
(name-as-in "population" "population" "fr")
(name-as-in "population" "人口" "zh-tw")
(name-as-in "population" "Einwohnerzahl" "de")
(name-as-in "population" "численность населения" "ru")
(name-as-in "population" "población" "es")
(name-as-in "population" "人口" "ja")
(name-as-in "population" "人口" "zh-cn")
(name-as-in "population" "人口" "zh-sg")

(descr-as-in "population" "" "zh-hk")
(descr-as-in "population" "número de pessoas que habitam o local" "pt")
(descr-as-in "population" "number of people inhabiting the place; number of people of subject" "en")
(descr-as-in "population" "nombre d'habitants du lieu ou de personnes dans un groupe." "fr")
(descr-as-in "population" "" "zh-tw")
(descr-as-in "population" "Anzahl der Einwohner eines Orts oder Gebietes" "de")
(descr-as-in "population" "количество людей, населяющих место" "ru")
(descr-as-in "population" "número de habitantes de un lugar" "es")
(descr-as-in "population" "" "ja")
(descr-as-in "population" "" "zh-cn")
(descr-as-in "population" "" "zh-sg")

