(ns properties.port_person_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "port-person-id")

(name-as-in "port-person-id" "" "zh-hk")
(name-as-in "port-person-id" "" "pt")
(name-as-in "port-person-id" "PORT person ID" "en")
(name-as-in "port-person-id" "identifiant PORT de personne" "fr")
(name-as-in "port-person-id" "" "zh-tw")
(name-as-in "port-person-id" "PORT Personen-ID" "de")
(name-as-in "port-person-id" "код персоналии PORT" "ru")
(name-as-in "port-person-id" "identificador PORT de persona" "es")
(name-as-in "port-person-id" "" "ja")
(name-as-in "port-person-id" "" "zh-cn")
(name-as-in "port-person-id" "" "zh-sg")

(descr-as-in "port-person-id" "" "zh-hk")
(descr-as-in "port-person-id" "" "pt")
(descr-as-in "port-person-id" "PORT-network film database: identifier for a person" "en")
(descr-as-in "port-person-id" "identifiant d’une personne dans le réseau PORT" "fr")
(descr-as-in "port-person-id" "" "zh-tw")
(descr-as-in "port-person-id" "Identifikationsnummer für eine Person bei der Filmdatenbank PORT.hu" "de")
(descr-as-in "port-person-id" "" "ru")
(descr-as-in "port-person-id" "" "es")
(descr-as-in "port-person-id" "" "ja")
(descr-as-in "port-person-id" "" "zh-cn")
(descr-as-in "port-person-id" "" "zh-sg")

