(ns properties.product_or_material_produced
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "product-or-material-produced")

(name-as-in "product-or-material-produced" "產物" "zh-hk")
(name-as-in "product-or-material-produced" "produto" "pt")
(name-as-in "product-or-material-produced" "product or material produced" "en")
(name-as-in "product-or-material-produced" "produit" "fr")
(name-as-in "product-or-material-produced" "產品" "zh-tw")
(name-as-in "product-or-material-produced" "Produkt" "de")
(name-as-in "product-or-material-produced" "производит" "ru")
(name-as-in "product-or-material-produced" "producto" "es")
(name-as-in "product-or-material-produced" "生産品目" "ja")
(name-as-in "product-or-material-produced" "产品" "zh-cn")
(name-as-in "product-or-material-produced" "" "zh-sg")

(descr-as-in "product-or-material-produced" "一個地礦、工業設施或工業程序所生產的物質" "zh-hk")
(descr-as-in "product-or-material-produced" "material produzido por mina ou área industrial" "pt")
(descr-as-in "product-or-material-produced" "material or product produced by a business, industry, facility, or process" "en")
(descr-as-in "product-or-material-produced" "matériau ou produit fabriqué par une entreprise, de l'industrie, installation, ou le processus" "fr")
(descr-as-in "product-or-material-produced" "一個地礦、工業設施或工業程序所生產的物質" "zh-tw")
(descr-as-in "product-or-material-produced" "produziertes Material oder Produkt" "de")
(descr-as-in "product-or-material-produced" "что: сырьё, продукцию или материал" "ru")
(descr-as-in "product-or-material-produced" "material o producto producido por una empresa, industria, instalación o proceso" "es")
(descr-as-in "product-or-material-produced" "鉱山・工場・製法が生産する品目" "ja")
(descr-as-in "product-or-material-produced" "一个地矿、工业设施或工业程序所生产的物质" "zh-cn")
(descr-as-in "product-or-material-produced" "" "zh-sg")

