(ns properties.project_gutenberg_author_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "project-gutenberg-author-id")

(name-as-in "project-gutenberg-author-id" "" "zh-hk")
(name-as-in "project-gutenberg-author-id" "" "pt")
(name-as-in "project-gutenberg-author-id" "Project Gutenberg author ID" "en")
(name-as-in "project-gutenberg-author-id" "identifiant Projet Gutenberg d'auteur" "fr")
(name-as-in "project-gutenberg-author-id" "" "zh-tw")
(name-as-in "project-gutenberg-author-id" "Gutenberg-Autoren-ID" "de")
(name-as-in "project-gutenberg-author-id" "код проекта «Гутенберг»" "ru")
(name-as-in "project-gutenberg-author-id" "identificador Proyecto Gutenberg de autor" "es")
(name-as-in "project-gutenberg-author-id" "" "ja")
(name-as-in "project-gutenberg-author-id" "古腾堡作者编号" "zh-cn")
(name-as-in "project-gutenberg-author-id" "" "zh-sg")

(descr-as-in "project-gutenberg-author-id" "" "zh-hk")
(descr-as-in "project-gutenberg-author-id" "" "pt")
(descr-as-in "project-gutenberg-author-id" "author identifier at Project Gutenberg" "en")
(descr-as-in "project-gutenberg-author-id" "identifiant d'auteur sur le projet Gutenberg" "fr")
(descr-as-in "project-gutenberg-author-id" "" "zh-tw")
(descr-as-in "project-gutenberg-author-id" "Autoren-Identifikator beim Projekt Gutenberg" "de")
(descr-as-in "project-gutenberg-author-id" "" "ru")
(descr-as-in "project-gutenberg-author-id" "identificador de autor en el Proyecto Gutenberg" "es")
(descr-as-in "project-gutenberg-author-id" "" "ja")
(descr-as-in "project-gutenberg-author-id" "古腾堡计划的作者编号" "zh-cn")
(descr-as-in "project-gutenberg-author-id" "" "zh-sg")

