(ns properties.properties_for_this_type
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "properties-for-this-type")

(name-as-in "properties-for-this-type" "" "zh-hk")
(name-as-in "properties-for-this-type" "propriedades para este tipo" "pt")
(name-as-in "properties-for-this-type" "properties for this type" "en")
(name-as-in "properties-for-this-type" "propriété Wikidata pour ce type" "fr")
(name-as-in "properties-for-this-type" "用於此類型的屬性" "zh-tw")
(name-as-in "properties-for-this-type" "Eigenschaften für diesen Typ" "de")
(name-as-in "properties-for-this-type" "свойства у этого класса" "ru")
(name-as-in "properties-for-this-type" "propiedades de Wikidata para este tipo" "es")
(name-as-in "properties-for-this-type" "適用プロパティ候補" "ja")
(name-as-in "properties-for-this-type" "" "zh-cn")
(name-as-in "properties-for-this-type" "" "zh-sg")

(descr-as-in "properties-for-this-type" "" "zh-hk")
(descr-as-in "properties-for-this-type" "" "pt")
(descr-as-in "properties-for-this-type" "when this subject is used as object of instance of or occupation, the following properties normally apply" "en")
(descr-as-in "properties-for-this-type" "lorsque l'élément est utilisé comme objet de « nature de l'élément » ou « occupation », les propriétés énoncées s'appliquent" "fr")
(descr-as-in "properties-for-this-type" "" "zh-tw")
(descr-as-in "properties-for-this-type" "wenn das Subjekt als Objekt von ist ein(e) genutzt wird, finden üblicherweise die folgenden Eigenschaften Verwendung" "de")
(descr-as-in "properties-for-this-type" "на сущностях-свойствах: список свойств Викиданных, обычно используемых для такого типа элементов" "ru")
(descr-as-in "properties-for-this-type" "" "es")
(descr-as-in "properties-for-this-type" "この主題が「分類」や「職業」のオブジェクトとして使用される際には一般的に以下のプロパティが適用される" "ja")
(descr-as-in "properties-for-this-type" "" "zh-cn")
(descr-as-in "properties-for-this-type" "" "zh-sg")

