(ns properties.public_holiday
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "public-holiday")

(name-as-in "public-holiday" "公眾假期" "zh-hk")
(name-as-in "public-holiday" "feriado público" "pt")
(name-as-in "public-holiday" "public holiday" "en")
(name-as-in "public-holiday" "jour férié" "fr")
(name-as-in "public-holiday" "國家假日" "zh-tw")
(name-as-in "public-holiday" "Feiertag" "de")
(name-as-in "public-holiday" "официальный праздник" "ru")
(name-as-in "public-holiday" "feriado" "es")
(name-as-in "public-holiday" "祝日" "ja")
(name-as-in "public-holiday" "" "zh-cn")
(name-as-in "public-holiday" "" "zh-sg")

(descr-as-in "public-holiday" "" "zh-hk")
(descr-as-in "public-holiday" "" "pt")
(descr-as-in "public-holiday" "official public holiday that occurs in this place in its honor, usually a non-working day" "en")
(descr-as-in "public-holiday" "" "fr")
(descr-as-in "public-holiday" "" "zh-tw")
(descr-as-in "public-holiday" "gesetzlicher Feiertag(e) an diesem Ort" "de")
(descr-as-in "public-holiday" "" "ru")
(descr-as-in "public-holiday" "festividad oficial que ocurre en este lugar" "es")
(descr-as-in "public-holiday" "国家公式の祝日。" "ja")
(descr-as-in "public-holiday" "" "zh-cn")
(descr-as-in "public-holiday" "" "zh-sg")

