(ns properties.publisher
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "publisher")

(name-as-in "publisher" "出版社" "zh-hk")
(name-as-in "publisher" "editora" "pt")
(name-as-in "publisher" "publisher" "en")
(name-as-in "publisher" "éditeur" "fr")
(name-as-in "publisher" "出版社" "zh-tw")
(name-as-in "publisher" "Verlag" "de")
(name-as-in "publisher" "издатель" "ru")
(name-as-in "publisher" "editorial" "es")
(name-as-in "publisher" "発行者" "ja")
(name-as-in "publisher" "出版社" "zh-cn")
(name-as-in "publisher" "出版社" "zh-sg")

(descr-as-in "publisher" "負責書籍、電子遊戲或軟件出版的機構" "zh-hk")
(descr-as-in "publisher" "nome da organização responsável pela publicação do item em questão (livros apenas)" "pt")
(descr-as-in "publisher" "organization or person responsible for publishing books, periodicals, games or software" "en")
(descr-as-in "publisher" "organisation qui est responsable pour la publication du sujet" "fr")
(descr-as-in "publisher" "負責書籍、電子遊戲或軟件出版的機構" "zh-tw")
(descr-as-in "publisher" "Namen des Medienunternehmens, das die Publikation auf den Markt gebracht hat" "de")
(descr-as-in "publisher" "имя организации, ответственной за публикацию объекта" "ru")
(descr-as-in "publisher" "organización responsable de la publicación de textos o software" "es")
(descr-as-in "publisher" "本・出版物・ゲーム・ソフトウェアの発行者・出版社・発売元・販売元" "ja")
(descr-as-in "publisher" "负责书籍、电子游戏或软件出版的机构" "zh-cn")
(descr-as-in "publisher" "负责书籍、电子游戏或软件出版的机构" "zh-sg")

