(ns properties.quora_topic_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "quora-topic-id")

(name-as-in "quora-topic-id" "Quora主題代碼" "zh-hk")
(name-as-in "quora-topic-id" "identificador de tema em Quora" "pt")
(name-as-in "quora-topic-id" "Quora topic ID" "en")
(name-as-in "quora-topic-id" "identifiant Quora d'un sujet" "fr")
(name-as-in "quora-topic-id" "Quora主題代碼" "zh-tw")
(name-as-in "quora-topic-id" "Quora-Themenkennung" "de")
(name-as-in "quora-topic-id" "код темы Quora" "ru")
(name-as-in "quora-topic-id" "identificador de tema en Quora" "es")
(name-as-in "quora-topic-id" "Quoraトピック識別子" "ja")
(name-as-in "quora-topic-id" "Quora主题代码" "zh-cn")
(name-as-in "quora-topic-id" "Quora主题代码" "zh-sg")

(descr-as-in "quora-topic-id" "" "zh-hk")
(descr-as-in "quora-topic-id" "identificador em Quora de um tema (versão em inglês)" "pt")
(descr-as-in "quora-topic-id" "identifier for a topic on Quora (English language version)" "en")
(descr-as-in "quora-topic-id" "identifiant d'un sujet sur Quora (version anglaise)" "fr")
(descr-as-in "quora-topic-id" "" "zh-tw")
(descr-as-in "quora-topic-id" "Kennung zu einem Thema auf Quora (englische Sprachversion)" "de")
(descr-as-in "quora-topic-id" "идентификатор на сайте Quora (англоязычная версия)" "ru")
(descr-as-in "quora-topic-id" "identificador Quora de un tema (idioma en Inglés)" "es")
(descr-as-in "quora-topic-id" "Quora英語版のトピックID" "ja")
(descr-as-in "quora-topic-id" "互动问答型线上知识市场" "zh-cn")
(descr-as-in "quora-topic-id" "" "zh-sg")

