(ns properties.ra_collections_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "ra-collections-id")

(name-as-in "ra-collections-id" "" "zh-hk")
(name-as-in "ra-collections-id" "" "pt")
(name-as-in "ra-collections-id" "RA Collections ID" "en")
(name-as-in "ra-collections-id" "identifiant Royal Academy" "fr")
(name-as-in "ra-collections-id" "" "zh-tw")
(name-as-in "ra-collections-id" "" "de")
(name-as-in "ra-collections-id" "" "ru")
(name-as-in "ra-collections-id" "Identificador colección Royal Academy of Arts, Londres" "es")
(name-as-in "ra-collections-id" "" "ja")
(name-as-in "ra-collections-id" "" "zh-cn")
(name-as-in "ra-collections-id" "" "zh-sg")

(descr-as-in "ra-collections-id" "" "zh-hk")
(descr-as-in "ra-collections-id" "" "pt")
(descr-as-in "ra-collections-id" "identifier for an entry in the collections database of the Royal Academy of Arts, London" "en")
(descr-as-in "ra-collections-id" "" "fr")
(descr-as-in "ra-collections-id" "" "zh-tw")
(descr-as-in "ra-collections-id" "" "de")
(descr-as-in "ra-collections-id" "" "ru")
(descr-as-in "ra-collections-id" "Identificador de la base de datos de la colección de la Royal Academy of Arts, London" "es")
(descr-as-in "ra-collections-id" "" "ja")
(descr-as-in "ra-collections-id" "" "zh-cn")
(descr-as-in "ra-collections-id" "" "zh-sg")

