(ns properties.religion
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "religion")

(name-as-in "religion" "信仰" "zh-hk")
(name-as-in "religion" "religião" "pt")
(name-as-in "religion" "religion" "en")
(name-as-in "religion" "religion" "fr")
(name-as-in "religion" "信仰" "zh-tw")
(name-as-in "religion" "Religionszugehörigkeit" "de")
(name-as-in "religion" "отношение к религии" "ru")
(name-as-in "religion" "religión" "es")
(name-as-in "religion" "宗教" "ja")
(name-as-in "religion" "信仰" "zh-cn")
(name-as-in "religion" "信仰" "zh-sg")

(descr-as-in "religion" "" "zh-hk")
(descr-as-in "religion" "religião do indivíduo (deve ser corroborada pelo próprio ou documentada por fontes históricas)" "pt")
(descr-as-in "religion" "religion of a person, organization or religious building, or associated with this subject" "en")
(descr-as-in "religion" "religion de la personne, de l'organisation ou de l'édifice, ou associée avec ce sujet" "fr")
(descr-as-in "religion" "" "zh-tw")
(descr-as-in "religion" "(MUSS von der Person behauptet oder durch historische Quellen dokumentiert sein)" "de")
(descr-as-in "religion" "ДОЛЖНО быть утверждено самим субъектом или подтверждено историческими источниками" "ru")
(descr-as-in "religion" "religión de una persona u organización (debe ser declarada por el sujeto o documentada por fuentes históricas)" "es")
(descr-as-in "religion" "主題の人物や組織の宗教 (本人または史料による裏付けがあるものに限る)" "ja")
(descr-as-in "religion" "" "zh-cn")
(descr-as-in "religion" "" "zh-sg")

