(ns properties.replaces
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "replaces")

(name-as-in "replaces" "取代" "zh-hk")
(name-as-in "replaces" "substituiu" "pt")
(name-as-in "replaces" "replaces" "en")
(name-as-in "replaces" "remplace" "fr")
(name-as-in "replaces" "取代" "zh-tw")
(name-as-in "replaces" "ersetzt" "de")
(name-as-in "replaces" "заменил" "ru")
(name-as-in "replaces" "reemplaza a" "es")
(name-as-in "replaces" "先行" "ja")
(name-as-in "replaces" "取代" "zh-cn")
(name-as-in "replaces" "取代" "zh-sg")

(descr-as-in "replaces" "" "zh-hk")
(descr-as-in "replaces" "Pessoa, estado ou outro item que foi substituído num cargo, posição, etc. Use P1398 para estruturas; P155 (precedido por) se o item não foi substituído e o predecessor e sucessor são idênticos." "pt")
(descr-as-in "replaces" "Person or item replaced. Use P1398 (structure replaces) for structures. Use P155 (follows) if the previous item was not replaced or predecessor and successor are identical." "en")
(descr-as-in "replaces" "personne(s), État(s) ou autres éléments qui a (ont) été remplacé(s) à une fonction ou un office comparable.  Utiliser P1398 (structure précédente) pour les structures. Utiliser P155 (suivi par) si un prédécesseur est identique à son successeur." "fr")
(descr-as-in "replaces" "" "zh-tw")
(descr-as-in "replaces" "Durch das aktuelle Objekt ersetzte(r) Person, Organisation oder Gegenstand. Verw. P1398 (Bauwerk ersetzt) für Gebäude. Verw. P155 (Vorgänger), wenn das Nachfolgerobjekt das Vorgängerobjekt nicht ersetzt und Vorgänger und Nachfolger identisch sind" "de")
(descr-as-in "replaces" "человек, организация или объект, который был заменён в должности, позиции и т.д. Используйте P155 (предыдущее по порядку), если предыдущий объект не заменялся, а предшественник и преемник идентичны" "ru")
(descr-as-in "replaces" "persona, organización u otro elemento que fue reemplazado en el puesto, posición, etc. Usar P155 si el anterior elemento no fue reemplazado y el predecesor y sucesor son idénticos" "es")
(descr-as-in "replaces" "主題の地位・領土等を直前に占めていたもの（前任の人物、先行の国家など）。順序についてはP155を使用。" "ja")
(descr-as-in "replaces" "" "zh-cn")
(descr-as-in "replaces" "" "zh-sg")

