(ns properties.researcherid
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "researcherid")

(name-as-in "researcherid" "" "zh-hk")
(name-as-in "researcherid" "ResearcherID" "pt")
(name-as-in "researcherid" "ResearcherID" "en")
(name-as-in "researcherid" "identifiant ResearcherID" "fr")
(name-as-in "researcherid" "" "zh-tw")
(name-as-in "researcherid" "ResearcherID" "de")
(name-as-in "researcherid" "ResearcherID" "ru")
(name-as-in "researcherid" "identificador ResearcherID" "es")
(name-as-in "researcherid" "ResearcherID" "ja")
(name-as-in "researcherid" "" "zh-cn")
(name-as-in "researcherid" "" "zh-sg")

(descr-as-in "researcherid" "" "zh-hk")
(descr-as-in "researcherid" "" "pt")
(descr-as-in "researcherid" "identifier for a researcher in a system for scientific authors, primarily used in Web of Science" "en")
(descr-as-in "researcherid" "identifiant de chercheurs introduit en 2008 par Thomson Reuter" "fr")
(descr-as-in "researcherid" "" "zh-tw")
(descr-as-in "researcherid" "" "de")
(descr-as-in "researcherid" "код исследователя, предложенный в 2008 году Thomson Reuters" "ru")
(descr-as-in "researcherid" "identificador de investigadores introducido en 2008 por Thomson Reuter" "es")
(descr-as-in "researcherid" "トムソン・ロイター社が付与する研究者の識別子" "ja")
(descr-as-in "researcherid" "" "zh-cn")
(descr-as-in "researcherid" "" "zh-sg")

