(ns properties.researchgate_institute_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "researchgate-institute-id")

(name-as-in "researchgate-institute-id" "" "zh-hk")
(name-as-in "researchgate-institute-id" "" "pt")
(name-as-in "researchgate-institute-id" "ResearchGate institute ID" "en")
(name-as-in "researchgate-institute-id" "identifiant ResearchGate d'un institut" "fr")
(name-as-in "researchgate-institute-id" "" "zh-tw")
(name-as-in "researchgate-institute-id" "ResearchGate Institut ID" "de")
(name-as-in "researchgate-institute-id" "код института ResearchGate" "ru")
(name-as-in "researchgate-institute-id" "identificador de instituto ResearchGate" "es")
(name-as-in "researchgate-institute-id" "" "ja")
(name-as-in "researchgate-institute-id" "" "zh-cn")
(name-as-in "researchgate-institute-id" "" "zh-sg")

(descr-as-in "researchgate-institute-id" "" "zh-hk")
(descr-as-in "researchgate-institute-id" "" "pt")
(descr-as-in "researchgate-institute-id" "identifier of an institute in ResearchGate" "en")
(descr-as-in "researchgate-institute-id" "identifiant d'un institut dans ResearchGate" "fr")
(descr-as-in "researchgate-institute-id" "" "zh-tw")
(descr-as-in "researchgate-institute-id" "Identifikator für eine Institution auf ResearchGate" "de")
(descr-as-in "researchgate-institute-id" "" "ru")
(descr-as-in "researchgate-institute-id" "" "es")
(descr-as-in "researchgate-institute-id" "" "ja")
(descr-as-in "researchgate-institute-id" "" "zh-cn")
(descr-as-in "researchgate-institute-id" "" "zh-sg")

