(ns properties.residence
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "residence")

(name-as-in "residence" "居住地" "zh-hk")
(name-as-in "residence" "residência" "pt")
(name-as-in "residence" "residence" "en")
(name-as-in "residence" "résidence" "fr")
(name-as-in "residence" "居住地" "zh-tw")
(name-as-in "residence" "Wohnsitz" "de")
(name-as-in "residence" "место жительства" "ru")
(name-as-in "residence" "residencia" "es")
(name-as-in "residence" "居住地" "ja")
(name-as-in "residence" "居住地" "zh-cn")
(name-as-in "residence" "居住地" "zh-sg")

(descr-as-in "residence" "" "zh-hk")
(descr-as-in "residence" "" "pt")
(descr-as-in "residence" "the place where the person is, or has been, resident" "en")
(descr-as-in "residence" "lieu où la personne réside ou a résidé" "fr")
(descr-as-in "residence" "" "zh-tw")
(descr-as-in "residence" "Ort, an dem die Person einen Wohnsitz hat oder hatte (Alternative: Wirkungsstätte, P937)" "de")
(descr-as-in "residence" "место, где человек живёт или жил" "ru")
(descr-as-in "residence" "lugar donde una persona reside o ha residido" "es")
(descr-as-in "residence" "主題人物が居住している／いた場所。官公邸についてはP263を使用。" "ja")
(descr-as-in "residence" "" "zh-cn")
(descr-as-in "residence" "" "zh-sg")

