(ns properties.retirement_age
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "retirement-age")

(name-as-in "retirement-age" "" "zh-hk")
(name-as-in "retirement-age" "idade de aposentadoria" "pt")
(name-as-in "retirement-age" "retirement age" "en")
(name-as-in "retirement-age" "âge de départ à la retraite" "fr")
(name-as-in "retirement-age" "" "zh-tw")
(name-as-in "retirement-age" "Rentenalter" "de")
(name-as-in "retirement-age" "пенсионный возраст" "ru")
(name-as-in "retirement-age" "edad de jubilación" "es")
(name-as-in "retirement-age" "定年" "ja")
(name-as-in "retirement-age" "" "zh-cn")
(name-as-in "retirement-age" "" "zh-sg")

(descr-as-in "retirement-age" "" "zh-hk")
(descr-as-in "retirement-age" "" "pt")
(descr-as-in "retirement-age" "the age at which most people normally retire from work" "en")
(descr-as-in "retirement-age" "l'âge généralement admis pour qu'un individu puisse partir à la retraite" "fr")
(descr-as-in "retirement-age" "" "zh-tw")
(descr-as-in "retirement-age" "" "de")
(descr-as-in "retirement-age" "возраст выхода на пенсию" "ru")
(descr-as-in "retirement-age" "edad en la que normalmente se deja de trabajar" "es")
(descr-as-in "retirement-age" "" "ja")
(descr-as-in "retirement-age" "" "zh-cn")
(descr-as-in "retirement-age" "" "zh-sg")

