(ns properties.scopus_author_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "scopus-author-id")

(name-as-in "scopus-author-id" "" "zh-hk")
(name-as-in "scopus-author-id" "" "pt")
(name-as-in "scopus-author-id" "Scopus Author ID" "en")
(name-as-in "scopus-author-id" "code d'auteur dans Scopus" "fr")
(name-as-in "scopus-author-id" "Scopus資料庫文獻作者編碼" "zh-tw")
(name-as-in "scopus-author-id" "Scopus-Autor-ID" "de")
(name-as-in "scopus-author-id" "код автора по Scopus" "ru")
(name-as-in "scopus-author-id" "identificador Scopus de autor" "es")
(name-as-in "scopus-author-id" "" "ja")
(name-as-in "scopus-author-id" "" "zh-cn")
(name-as-in "scopus-author-id" "" "zh-sg")

(descr-as-in "scopus-author-id" "" "zh-hk")
(descr-as-in "scopus-author-id" "" "pt")
(descr-as-in "scopus-author-id" "identifier for an author assigned in Scopus bibliographic database" "en")
(descr-as-in "scopus-author-id" "identifiant unique dans la base bibliographique Scopus" "fr")
(descr-as-in "scopus-author-id" "Scopus的書目資料庫中，為所有的文獻作者都建立了的作者編碼" "zh-tw")
(descr-as-in "scopus-author-id" "Identifikator für eine/n Autor/in in der bibliographischen Datenbank Scopus" "de")
(descr-as-in "scopus-author-id" "идентификатор для автора, присвоенный в библиографической базе данных Scopus" "ru")
(descr-as-in "scopus-author-id" "" "es")
(descr-as-in "scopus-author-id" "" "ja")
(descr-as-in "scopus-author-id" "" "zh-cn")
(descr-as-in "scopus-author-id" "" "zh-sg")

