(ns properties.selibr
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "selibr")

(name-as-in "selibr" "SELIBR編號" "zh-hk")
(name-as-in "selibr" "SELIBR" "pt")
(name-as-in "selibr" "SELIBR" "en")
(name-as-in "selibr" "identifiant SELIBR" "fr")
(name-as-in "selibr" "" "zh-tw")
(name-as-in "selibr" "SELIBR" "de")
(name-as-in "selibr" "код SELIBR" "ru")
(name-as-in "selibr" "identificador SELIBR" "es")
(name-as-in "selibr" "SELIBR" "ja")
(name-as-in "selibr" "" "zh-cn")
(name-as-in "selibr" "" "zh-sg")

(descr-as-in "selibr" "" "zh-hk")
(descr-as-in "selibr" "" "pt")
(descr-as-in "selibr" "identifier per National Library of Sweden Libris library catalog" "en")
(descr-as-in "selibr" "identifiant de la base de données bibliothécaire suédoise SELIBR" "fr")
(descr-as-in "selibr" "" "zh-tw")
(descr-as-in "selibr" "Normdatei des schwedischen Verbundkatalogs LIBRIS" "de")
(descr-as-in "selibr" "номер в каталоге Национальной библиотеки Швеции" "ru")
(descr-as-in "selibr" "código de identificación en el catálogo Libris" "es")
(descr-as-in "selibr" "スウェーデン国立図書館の LIBRIS 図書目録におけるID番号" "ja")
(descr-as-in "selibr" "" "zh-cn")
(descr-as-in "selibr" "" "zh-sg")

