(ns properties.service_ribbon_image
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "service-ribbon-image")

(name-as-in "service-ribbon-image" "" "zh-hk")
(name-as-in "service-ribbon-image" "imagem da barreta" "pt")
(name-as-in "service-ribbon-image" "service ribbon image" "en")
(name-as-in "service-ribbon-image" "ruban de médaille" "fr")
(name-as-in "service-ribbon-image" "" "zh-tw")
(name-as-in "service-ribbon-image" "Bild der Bandschnalle" "de")
(name-as-in "service-ribbon-image" "изображение орденской планки" "ru")
(name-as-in "service-ribbon-image" "imagen de condecoración" "es")
(name-as-in "service-ribbon-image" "略綬画像" "ja")
(name-as-in "service-ribbon-image" "" "zh-cn")
(name-as-in "service-ribbon-image" "" "zh-sg")

(descr-as-in "service-ribbon-image" "" "zh-hk")
(descr-as-in "service-ribbon-image" "" "pt")
(descr-as-in "service-ribbon-image" "an image depicting the ribbon associated with a medal, order, etc." "en")
(descr-as-in "service-ribbon-image" "image pour représenter le ruban de la médaille" "fr")
(descr-as-in "service-ribbon-image" "" "zh-tw")
(descr-as-in "service-ribbon-image" "" "de")
(descr-as-in "service-ribbon-image" "изображение планки ордена или медали" "ru")
(descr-as-in "service-ribbon-image" "insignia distintiva de una orden, medalla, condecoración, etc" "es")
(descr-as-in "service-ribbon-image" "" "ja")
(descr-as-in "service-ribbon-image" "" "zh-cn")
(descr-as-in "service-ribbon-image" "" "zh-sg")

