(ns properties.short_name
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "short-name")

(name-as-in "short-name" "簡稱" "zh-hk")
(name-as-in "short-name" "nome curto" "pt")
(name-as-in "short-name" "short name" "en")
(name-as-in "short-name" "nom court" "fr")
(name-as-in "short-name" "簡稱" "zh-tw")
(name-as-in "short-name" "Kurzname" "de")
(name-as-in "short-name" "короткое название" "ru")
(name-as-in "short-name" "nombre corto" "es")
(name-as-in "short-name" "短縮名" "ja")
(name-as-in "short-name" "简称" "zh-cn")
(name-as-in "short-name" "简称" "zh-sg")

(descr-as-in "short-name" "" "zh-hk")
(descr-as-in "short-name" "" "pt")
(descr-as-in "short-name" "short name of a place, organisation, person etc." "en")
(descr-as-in "short-name" "le nom court d'un lieu, d'une organisation, d'une personne, etc." "fr")
(descr-as-in "short-name" "" "zh-tw")
(descr-as-in "short-name" "kurzer Name eines Ortes, einer Organisation, Person, etc." "de")
(descr-as-in "short-name" "сокращённое название места, организации, персоны и т. д." "ru")
(descr-as-in "short-name" "nombre corto de un lugar, organización, persona, etc." "es")
(descr-as-in "short-name" "地名、組織名、人名などの短縮形" "ja")
(descr-as-in "short-name" "" "zh-cn")
(descr-as-in "short-name" "" "zh-sg")

