(ns properties.signed_form
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "signed-form")

(name-as-in "signed-form" "" "zh-hk")
(name-as-in "signed-form" "forma gestual" "pt")
(name-as-in "signed-form" "signed form" "en")
(name-as-in "signed-form" "forme signée" "fr")
(name-as-in "signed-form" "" "zh-tw")
(name-as-in "signed-form" "lautsprachbegleitende Gebärden" "de")
(name-as-in "signed-form" "жестовая форма" "ru")
(name-as-in "signed-form" "forma gestual" "es")
(name-as-in "signed-form" "" "ja")
(name-as-in "signed-form" "" "zh-cn")
(name-as-in "signed-form" "" "zh-sg")

(descr-as-in "signed-form" "" "zh-hk")
(descr-as-in "signed-form" "" "pt")
(descr-as-in "signed-form" "manually coded form of this language" "en")
(descr-as-in "signed-form" "forme codée manuellement de cette langue" "fr")
(descr-as-in "signed-form" "" "zh-tw")
(descr-as-in "signed-form" "simulatan zum gesprochenen Wort ausgeführte Gebärden" "de")
(descr-as-in "signed-form" "" "ru")
(descr-as-in "signed-form" "forma manualmente codificada de esta lengua" "es")
(descr-as-in "signed-form" "" "ja")
(descr-as-in "signed-form" "" "zh-cn")
(descr-as-in "signed-form" "" "zh-sg")

