(ns properties.sister_city
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "sister-city")

(name-as-in "sister-city" "友好城市" "zh-hk")
(name-as-in "sister-city" "geminação" "pt")
(name-as-in "sister-city" "sister city" "en")
(name-as-in "sister-city" "jumelage et partenariats" "fr")
(name-as-in "sister-city" "姐妹市" "zh-tw")
(name-as-in "sister-city" "Partnerkommune" "de")
(name-as-in "sister-city" "город-побратим" "ru")
(name-as-in "sister-city" "ciudad hermana" "es")
(name-as-in "sister-city" "姉妹都市" "ja")
(name-as-in "sister-city" "" "zh-cn")
(name-as-in "sister-city" "" "zh-sg")

(descr-as-in "sister-city" "" "zh-hk")
(descr-as-in "sister-city" "cidades com que é geminada" "pt")
(descr-as-in "sister-city" "twin towns, sister cities, twinned municipalities and other localities that have a partnership or cooperative agreement, either legally or informally acknowledged by their governments" "en")
(descr-as-in "sister-city" "villes jumelées ou sœurs" "fr")
(descr-as-in "sister-city" "" "zh-tw")
(descr-as-in "sister-city" "andere Kommune, zu der eine Partnerschaft besteht (z. B. Städtepartnerschaft)" "de")
(descr-as-in "sister-city" "город, с которым у данного города установлены постоянные дружественные отношения" "ru")
(descr-as-in "sister-city" "ciudad que han firmado acuerdo de cooperación y desarrollo humano" "es")
(descr-as-in "sister-city" "" "ja")
(descr-as-in "sister-city" "" "zh-cn")
(descr-as-in "sister-city" "" "zh-sg")

