(ns properties.soundex
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "soundex")

(name-as-in "soundex" "" "zh-hk")
(name-as-in "soundex" "Soundex" "pt")
(name-as-in "soundex" "Soundex" "en")
(name-as-in "soundex" "Soundex" "fr")
(name-as-in "soundex" "" "zh-tw")
(name-as-in "soundex" "Soundex" "de")
(name-as-in "soundex" "Soundex" "ru")
(name-as-in "soundex" "Soundex" "es")
(name-as-in "soundex" "" "ja")
(name-as-in "soundex" "" "zh-cn")
(name-as-in "soundex" "" "zh-sg")

(descr-as-in "soundex" "" "zh-hk")
(descr-as-in "soundex" "" "pt")
(descr-as-in "soundex" "phonetic algorithm for indexing names by sound, as pronounced in English. Format: initial of word followed by 3 digits (0-6)" "en")
(descr-as-in "soundex" "algorithme phonétique pour indexer les noms par son tel que prononcé en anglais" "fr")
(descr-as-in "soundex" "" "zh-tw")
(descr-as-in "soundex" "phonetischer Algorithmus, der Wörter nach ihrem Klang in der englischen Sprache eine Ziffernfolge zuordnet" "de")
(descr-as-in "soundex" "" "ru")
(descr-as-in "soundex" "algoritmo fonético para indexar nombres por sonidos tal y como se pronuncian en inglés" "es")
(descr-as-in "soundex" "" "ja")
(descr-as-in "soundex" "" "zh-cn")
(descr-as-in "soundex" "" "zh-sg")

