(ns properties.spouse
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "spouse")

(name-as-in "spouse" "配偶" "zh-hk")
(name-as-in "spouse" "cônjuge" "pt")
(name-as-in "spouse" "spouse" "en")
(name-as-in "spouse" "époux" "fr")
(name-as-in "spouse" "配偶" "zh-tw")
(name-as-in "spouse" "Ehepartner" "de")
(name-as-in "spouse" "супруг(а)" "ru")
(name-as-in "spouse" "cónyuge" "es")
(name-as-in "spouse" "配偶者" "ja")
(name-as-in "spouse" "配偶" "zh-cn")
(name-as-in "spouse" "配偶" "zh-sg")

(descr-as-in "spouse" "" "zh-hk")
(descr-as-in "spouse" "o sujeito tem como objeto o seu cônjuge (homem ou mulher)" "pt")
(descr-as-in "spouse" "the subject has the object as their spouse (husband, wife, partner, etc.). Use unmarried partner (P451) for non-married companions" "en")
(descr-as-in "spouse" "personne liée par le mariage ou une union civile" "fr")
(descr-as-in "spouse" "" "zh-tw")
(descr-as-in "spouse" "weiterer Teil der gefestigten Lebensgemeinschaft" "de")
(descr-as-in "spouse" "супруг или супруга персоны" "ru")
(descr-as-in "spouse" "el sujeto tuvo como cónyuge al objeto" "es")
(descr-as-in "spouse" "その項目は主題に対し配偶者（夫、妻、同性婚など）。婚姻関係にない同棲関係の場合はP451を使用。" "ja")
(descr-as-in "spouse" "" "zh-cn")
(descr-as-in "spouse" "" "zh-sg")

