(ns properties.stw_thesaurus_for_economics_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "stw-thesaurus-for-economics-id")

(name-as-in "stw-thesaurus-for-economics-id" "" "zh-hk")
(name-as-in "stw-thesaurus-for-economics-id" "" "pt")
(name-as-in "stw-thesaurus-for-economics-id" "STW Thesaurus for Economics ID" "en")
(name-as-in "stw-thesaurus-for-economics-id" "identifiant STW thésaurus sur l'économie" "fr")
(name-as-in "stw-thesaurus-for-economics-id" "" "zh-tw")
(name-as-in "stw-thesaurus-for-economics-id" "STW-ID" "de")
(name-as-in "stw-thesaurus-for-economics-id" "" "ru")
(name-as-in "stw-thesaurus-for-economics-id" "identificador del tesauro STW de economía" "es")
(name-as-in "stw-thesaurus-for-economics-id" "" "ja")
(name-as-in "stw-thesaurus-for-economics-id" "" "zh-cn")
(name-as-in "stw-thesaurus-for-economics-id" "" "zh-sg")

(descr-as-in "stw-thesaurus-for-economics-id" "" "zh-hk")
(descr-as-in "stw-thesaurus-for-economics-id" "" "pt")
(descr-as-in "stw-thesaurus-for-economics-id" "identifier for a descriptor of the STW Thesaurus for Economics, linking to literature on economics and business administration" "en")
(descr-as-in "stw-thesaurus-for-economics-id" "identifiant pour un descripteur sur le thésaurus sur l'économie du STW, décrivant des concepts sur l'économie, l'administration des entreprises et les sujets connexes" "fr")
(descr-as-in "stw-thesaurus-for-economics-id" "" "zh-tw")
(descr-as-in "stw-thesaurus-for-economics-id" "Identifikator für einen Deskriptor des Standard-Thesaurus Wirtschaft (STW), der auf volks- und betriebswirtschaftliche Literatur verlinkt" "de")
(descr-as-in "stw-thesaurus-for-economics-id" "" "ru")
(descr-as-in "stw-thesaurus-for-economics-id" "identificador para un descriptor del tesauro STW de economía que describe conceptos de economía, negocios, administración y temas relacionados" "es")
(descr-as-in "stw-thesaurus-for-economics-id" "" "ja")
(descr-as-in "stw-thesaurus-for-economics-id" "" "zh-cn")
(descr-as-in "stw-thesaurus-for-economics-id" "" "zh-sg")

