(ns properties.subreddit
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "subreddit")

(name-as-in "subreddit" "" "zh-hk")
(name-as-in "subreddit" "subreddit" "pt")
(name-as-in "subreddit" "subreddit" "en")
(name-as-in "subreddit" "subreddit" "fr")
(name-as-in "subreddit" "" "zh-tw")
(name-as-in "subreddit" "Subreddit" "de")
(name-as-in "subreddit" "сабреддит" "ru")
(name-as-in "subreddit" "subreddit" "es")
(name-as-in "subreddit" "" "ja")
(name-as-in "subreddit" "" "zh-cn")
(name-as-in "subreddit" "" "zh-sg")

(descr-as-in "subreddit" "" "zh-hk")
(descr-as-in "subreddit" "" "pt")
(descr-as-in "subreddit" "name of the Reddit forum associated to this subject" "en")
(descr-as-in "subreddit" "nom du forum Reddit associé à ce sujet" "fr")
(descr-as-in "subreddit" "" "zh-tw")
(descr-as-in "subreddit" "" "de")
(descr-as-in "subreddit" "имя форума Reddit, связанного с этим объектом" "ru")
(descr-as-in "subreddit" "" "es")
(descr-as-in "subreddit" "" "ja")
(descr-as-in "subreddit" "" "zh-cn")
(descr-as-in "subreddit" "" "zh-sg")

