(ns properties.subtitle
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "subtitle")

(name-as-in "subtitle" "副標題" "zh-hk")
(name-as-in "subtitle" "legenda" "pt")
(name-as-in "subtitle" "subtitle" "en")
(name-as-in "subtitle" "sous-titre" "fr")
(name-as-in "subtitle" "副標題" "zh-tw")
(name-as-in "subtitle" "Untertitel" "de")
(name-as-in "subtitle" "подзаголовок" "ru")
(name-as-in "subtitle" "subtítulo" "es")
(name-as-in "subtitle" "副題" "ja")
(name-as-in "subtitle" "副标题" "zh-cn")
(name-as-in "subtitle" "" "zh-sg")

(descr-as-in "subtitle" "一個作品（如一本書或一部電影）的副標題" "zh-hk")
(descr-as-in "subtitle" "" "pt")
(descr-as-in "subtitle" "for works, when the title is followed by a subtitle" "en")
(descr-as-in "subtitle" "pour les ouvrages, quand un titre est accompagné d'un sous-titre" "fr")
(descr-as-in "subtitle" "一個作品（如一本書或一部電影）的副標題" "zh-tw")
(descr-as-in "subtitle" "zweiter Titel, der unter dem ersten steht" "de")
(descr-as-in "subtitle" "второй заголовок" "ru")
(descr-as-in "subtitle" "subtítulo de la obra que sigue al título" "es")
(descr-as-in "subtitle" "サブタイトル" "ja")
(descr-as-in "subtitle" "一个作品（如一本书或一部电影）的副标题" "zh-cn")
(descr-as-in "subtitle" "" "zh-sg")

