(ns properties.swiss_municipality_code
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "swiss-municipality-code")

(name-as-in "swiss-municipality-code" "" "zh-hk")
(name-as-in "swiss-municipality-code" "código municipal suíço" "pt")
(name-as-in "swiss-municipality-code" "Swiss municipality code" "en")
(name-as-in "swiss-municipality-code" "numéro OFS" "fr")
(name-as-in "swiss-municipality-code" "" "zh-tw")
(name-as-in "swiss-municipality-code" "Gemeindenummer in der Schweiz" "de")
(name-as-in "swiss-municipality-code" "код швейцарского муниципалитета" "ru")
(name-as-in "swiss-municipality-code" "código de municipio suizo" "es")
(name-as-in "swiss-municipality-code" "" "ja")
(name-as-in "swiss-municipality-code" "" "zh-cn")
(name-as-in "swiss-municipality-code" "" "zh-sg")

(descr-as-in "swiss-municipality-code" "" "zh-hk")
(descr-as-in "swiss-municipality-code" "" "pt")
(descr-as-in "swiss-municipality-code" "identifier for a municipality in Switzerland" "en")
(descr-as-in "swiss-municipality-code" "numérotation officielle des communes suisses par l'OFS" "fr")
(descr-as-in "swiss-municipality-code" "" "zh-tw")
(descr-as-in "swiss-municipality-code" "Nummer des Bundesamtes für Statistik (BFS) in der Schweiz" "de")
(descr-as-in "swiss-municipality-code" "" "ru")
(descr-as-in "swiss-municipality-code" "identificador para los municipios en Suiza" "es")
(descr-as-in "swiss-municipality-code" "" "ja")
(descr-as-in "swiss-municipality-code" "" "zh-cn")
(descr-as-in "swiss-municipality-code" "" "zh-sg")

