(ns properties.te_papa_person_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "te-papa-person-id")

(name-as-in "te-papa-person-id" "" "zh-hk")
(name-as-in "te-papa-person-id" "" "pt")
(name-as-in "te-papa-person-id" "Te Papa person ID" "en")
(name-as-in "te-papa-person-id" "identifiant Te Papa Tongarewa" "fr")
(name-as-in "te-papa-person-id" "" "zh-tw")
(name-as-in "te-papa-person-id" "" "de")
(name-as-in "te-papa-person-id" "" "ru")
(name-as-in "te-papa-person-id" "" "es")
(name-as-in "te-papa-person-id" "" "ja")
(name-as-in "te-papa-person-id" "" "zh-cn")
(name-as-in "te-papa-person-id" "" "zh-sg")

(descr-as-in "te-papa-person-id" "" "zh-hk")
(descr-as-in "te-papa-person-id" "" "pt")
(descr-as-in "te-papa-person-id" "identifier assigned to a person by the Museum of New Zealand Te Papa Tongarewa" "en")
(descr-as-in "te-papa-person-id" "identifiant assigné à une personne par le Musée de Nouvelle-Zélande" "fr")
(descr-as-in "te-papa-person-id" "" "zh-tw")
(descr-as-in "te-papa-person-id" "" "de")
(descr-as-in "te-papa-person-id" "" "ru")
(descr-as-in "te-papa-person-id" "identificador asignado a un artista para el Museo de Nueva Zelanda Te Papa Tongarewa" "es")
(descr-as-in "te-papa-person-id" "" "ja")
(descr-as-in "te-papa-person-id" "" "zh-cn")
(descr-as-in "te-papa-person-id" "" "zh-sg")

