(ns properties.time_of_earliest_written_record
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "time-of-earliest-written-record")

(name-as-in "time-of-earliest-written-record" "" "zh-hk")
(name-as-in "time-of-earliest-written-record" "primeira menção escrita" "pt")
(name-as-in "time-of-earliest-written-record" "time of earliest written record" "en")
(name-as-in "time-of-earliest-written-record" "date de première mention écrite" "fr")
(name-as-in "time-of-earliest-written-record" "" "zh-tw")
(name-as-in "time-of-earliest-written-record" "erste schriftliche Erwähnung" "de")
(name-as-in "time-of-earliest-written-record" "первое письменное упоминание" "ru")
(name-as-in "time-of-earliest-written-record" "primer registro escrito" "es")
(name-as-in "time-of-earliest-written-record" "文献記録の初出年" "ja")
(name-as-in "time-of-earliest-written-record" "" "zh-cn")
(name-as-in "time-of-earliest-written-record" "" "zh-sg")

(descr-as-in "time-of-earliest-written-record" "" "zh-hk")
(descr-as-in "time-of-earliest-written-record" "" "pt")
(descr-as-in "time-of-earliest-written-record" "first time a subject was mentioned in writing" "en")
(descr-as-in "time-of-earliest-written-record" "date de première référence écrite au sujet" "fr")
(descr-as-in "time-of-earliest-written-record" "" "zh-tw")
(descr-as-in "time-of-earliest-written-record" "erstmalige schriftliche Erwähnung" "de")
(descr-as-in "time-of-earliest-written-record" "дата, когда объект был впервые упомянут в письменном источнике" "ru")
(descr-as-in "time-of-earliest-written-record" "primera vez que un tema se menciona en la escritura" "es")
(descr-as-in "time-of-earliest-written-record" "主題項目に関する最古の文献記録が記された年月日" "ja")
(descr-as-in "time-of-earliest-written-record" "" "zh-cn")
(descr-as-in "time-of-earliest-written-record" "" "zh-sg")

