(ns properties.topics_main_wikimedia_portal
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "topic's-main-wikimedia-portal")

(name-as-in "topic's-main-wikimedia-portal" "主題入口頁" "zh-hk")
(name-as-in "topic's-main-wikimedia-portal" "portal principal do tópico" "pt")
(name-as-in "topic's-main-wikimedia-portal" "topic's main Wikimedia portal" "en")
(name-as-in "topic's-main-wikimedia-portal" "portail Wikimedia" "fr")
(name-as-in "topic's-main-wikimedia-portal" "主題入口頁" "zh-tw")
(name-as-in "topic's-main-wikimedia-portal" "Themenportal" "de")
(name-as-in "topic's-main-wikimedia-portal" "портал Викимедиа" "ru")
(name-as-in "topic's-main-wikimedia-portal" "portal principal del tema" "es")
(name-as-in "topic's-main-wikimedia-portal" "ウィキメディアのポータル" "ja")
(name-as-in "topic's-main-wikimedia-portal" "话题主要主题" "zh-cn")
(name-as-in "topic's-main-wikimedia-portal" "" "zh-sg")

(descr-as-in "topic's-main-wikimedia-portal" "關於此主題的維基媒體入口導覽頁" "zh-hk")
(descr-as-in "topic's-main-wikimedia-portal" "" "pt")
(descr-as-in "topic's-main-wikimedia-portal" "Wikimedia portal associated with this topic" "en")
(descr-as-in "topic's-main-wikimedia-portal" "portail Wikimedia principal de l'élément" "fr")
(descr-as-in "topic's-main-wikimedia-portal" "關於此主題的維基媒體入口導覽頁" "zh-tw")
(descr-as-in "topic's-main-wikimedia-portal" "Wikimedia-Portal, das dieses Thema behandelt" "de")
(descr-as-in "topic's-main-wikimedia-portal" "портал Викимедии, связанный с данной темой" "ru")
(descr-as-in "topic's-main-wikimedia-portal" "Portal de Wikimedia asociado a esta temática" "es")
(descr-as-in "topic's-main-wikimedia-portal" "" "ja")
(descr-as-in "topic's-main-wikimedia-portal" "" "zh-cn")
(descr-as-in "topic's-main-wikimedia-portal" "" "zh-sg")

