(ns properties.topics_main_category
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "topic's-main-category")

(name-as-in "topic's-main-category" "話題主分類" "zh-hk")
(name-as-in "topic's-main-category" "categoria principal do tópico" "pt")
(name-as-in "topic's-main-category" "topic's main category" "en")
(name-as-in "topic's-main-category" "catégorie" "fr")
(name-as-in "topic's-main-category" "話題主分類" "zh-tw")
(name-as-in "topic's-main-category" "Hauptkategorie zum Artikel" "de")
(name-as-in "topic's-main-category" "основная категория по теме" "ru")
(name-as-in "topic's-main-category" "categoría principal del tema" "es")
(name-as-in "topic's-main-category" "記事の中心カテゴリ" "ja")
(name-as-in "topic's-main-category" "话题主分类" "zh-cn")
(name-as-in "topic's-main-category" "话题主分类" "zh-sg")

(descr-as-in "topic's-main-category" "主要的維基媒體分類" "zh-hk")
(descr-as-in "topic's-main-category" "" "pt")
(descr-as-in "topic's-main-category" "main Wikimedia category" "en")
(descr-as-in "topic's-main-category" "catégorie principale de l'élément" "fr")
(descr-as-in "topic's-main-category" "主要的維基媒體分類" "zh-tw")
(descr-as-in "topic's-main-category" "Hauptkategorie des Themas" "de")
(descr-as-in "topic's-main-category" "категория Викимедиа, соответствующая данной теме" "ru")
(descr-as-in "topic's-main-category" "categoría principal del elemento" "es")
(descr-as-in "topic's-main-category" "この記事の中心カテゴリ" "ja")
(descr-as-in "topic's-main-category" "主要的维基媒体分类" "zh-cn")
(descr-as-in "topic's-main-category" "主要的维基媒体分类" "zh-sg")

