(ns properties.topics_main_template
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "topic's-main-template")

(name-as-in "topic's-main-template" "主題的主模板" "zh-hk")
(name-as-in "topic's-main-template" "predefinição principal do assunto" "pt")
(name-as-in "topic's-main-template" "topic's main template" "en")
(name-as-in "topic's-main-template" "modèle principal d'un sujet" "fr")
(name-as-in "topic's-main-template" "主題的主模板" "zh-tw")
(name-as-in "topic's-main-template" "Hauptvorlage des Themas" "de")
(name-as-in "topic's-main-template" "основной шаблон по теме" "ru")
(name-as-in "topic's-main-template" "plantilla principal del tema" "es")
(name-as-in "topic's-main-template" "記事の中心テンプレート" "ja")
(name-as-in "topic's-main-template" "主题的主模板" "zh-cn")
(name-as-in "topic's-main-template" "主题的主模板" "zh-sg")

(descr-as-in "topic's-main-template" "" "zh-hk")
(descr-as-in "topic's-main-template" "infocaixa ou navecaixa principal sobre esse assunto" "pt")
(descr-as-in "topic's-main-template" "primary infobox or navigational template of this subject" "en")
(descr-as-in "topic's-main-template" "Infobox principale ou modèle sur un sujet" "fr")
(descr-as-in "topic's-main-template" "" "zh-tw")
(descr-as-in "topic's-main-template" "Hauptinfobox oder -navigationsvorlage für dieses Thema" "de")
(descr-as-in "topic's-main-template" "карточка или навигационный" "ru")
(descr-as-in "topic's-main-template" "ficha o plantilla de navegación principalmente relacionada con este elemento" "es")
(descr-as-in "topic's-main-template" "この記事の中心テンプレート" "ja")
(descr-as-in "topic's-main-template" "" "zh-cn")
(descr-as-in "topic's-main-template" "" "zh-sg")

