(ns properties.treccani_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "treccani-id")

(name-as-in "treccani-id" "" "zh-hk")
(name-as-in "treccani-id" "Enciclopedia Treccani" "pt")
(name-as-in "treccani-id" "Treccani ID" "en")
(name-as-in "treccani-id" "Enciclopedia Treccani" "fr")
(name-as-in "treccani-id" "" "zh-tw")
(name-as-in "treccani-id" "Enciclopedia Treccani" "de")
(name-as-in "treccani-id" "код в Итальянской энциклопедии онлайн" "ru")
(name-as-in "treccani-id" "Enciclopedia Treccani" "es")
(name-as-in "treccani-id" "" "ja")
(name-as-in "treccani-id" "" "zh-cn")
(name-as-in "treccani-id" "" "zh-sg")

(descr-as-in "treccani-id" "" "zh-hk")
(descr-as-in "treccani-id" "" "pt")
(descr-as-in "treccani-id" "identifier for the Treccani website" "en")
(descr-as-in "treccani-id" "identifiant sur le site web Enciclopedia Treccani" "fr")
(descr-as-in "treccani-id" "" "zh-tw")
(descr-as-in "treccani-id" "Eintrag in Enciclopedie on line (Treccani)" "de")
(descr-as-in "treccani-id" "" "ru")
(descr-as-in "treccani-id" "" "es")
(descr-as-in "treccani-id" "" "ja")
(descr-as-in "treccani-id" "" "zh-cn")
(descr-as-in "treccani-id" "" "zh-sg")

