(ns properties.ulan_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "ulan-id")

(name-as-in "ulan-id" "" "zh-hk")
(name-as-in "ulan-id" "identificador ULAN" "pt")
(name-as-in "ulan-id" "ULAN ID" "en")
(name-as-in "ulan-id" "identifiant Union List of Artist Names" "fr")
(name-as-in "ulan-id" "藝術家名稱聯合目錄" "zh-tw")
(name-as-in "ulan-id" "ULAN-ID" "de")
(name-as-in "ulan-id" "код ULAN" "ru")
(name-as-in "ulan-id" "identificador ULAN" "es")
(name-as-in "ulan-id" "ULAN" "ja")
(name-as-in "ulan-id" "艺术家名称联合目录" "zh-cn")
(name-as-in "ulan-id" "" "zh-sg")

(descr-as-in "ulan-id" "" "zh-hk")
(descr-as-in "ulan-id" "" "pt")
(descr-as-in "ulan-id" "identifier from the Getty Union List of Artist Names" "en")
(descr-as-in "ulan-id" "liste anglophone du site internet de l'institut de recherche Getty" "fr")
(descr-as-in "ulan-id" "" "zh-tw")
(descr-as-in "ulan-id" "Identifikationsnummer in der Union List of Artist Names" "de")
(descr-as-in "ulan-id" "номер записи в базе данных Union List of Artist Names" "ru")
(descr-as-in "ulan-id" "identificador de Getty Union List of Artist Names" "es")
(descr-as-in "ulan-id" "美術人名ユニオン・リスト（美術家名鑑）" "ja")
(descr-as-in "ulan-id" "" "zh-cn")
(descr-as-in "ulan-id" "" "zh-sg")

