(ns properties.umls_cui
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "umls-cui")

(name-as-in "umls-cui" "" "zh-hk")
(name-as-in "umls-cui" "" "pt")
(name-as-in "umls-cui" "UMLS CUI" "en")
(name-as-in "umls-cui" "UMLS CUI" "fr")
(name-as-in "umls-cui" "" "zh-tw")
(name-as-in "umls-cui" "UMLS CUI" "de")
(name-as-in "umls-cui" "UMLS CUI" "ru")
(name-as-in "umls-cui" "UMLS CUI" "es")
(name-as-in "umls-cui" "UMLS CUI" "ja")
(name-as-in "umls-cui" "" "zh-cn")
(name-as-in "umls-cui" "" "zh-sg")

(descr-as-in "umls-cui" "" "zh-hk")
(descr-as-in "umls-cui" "" "pt")
(descr-as-in "umls-cui" "NLM Unified Medical Language System (UMLS) controlled biomedical vocabulary unique identifier" "en")
(descr-as-in "umls-cui" "Unified Medical Language System (UMLS) controlled biomedical vocabulary unique identifier (CUI)" "fr")
(descr-as-in "umls-cui" "" "zh-tw")
(descr-as-in "umls-cui" "" "de")
(descr-as-in "umls-cui" "NLM Unified Medical Language System (UMLS) controlled unique identifier" "ru")
(descr-as-in "umls-cui" "" "es")
(descr-as-in "umls-cui" "" "ja")
(descr-as-in "umls-cui" "" "zh-cn")
(descr-as-in "umls-cui" "" "zh-sg")

