(ns properties.unesco_language_status
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "unesco-language-status")

(name-as-in "unesco-language-status" "" "zh-hk")
(name-as-in "unesco-language-status" "estado de vulnerabilidade de idioma" "pt")
(name-as-in "unesco-language-status" "UNESCO language status" "en")
(name-as-in "unesco-language-status" "statut UNESCO d'une langue" "fr")
(name-as-in "unesco-language-status" "" "zh-tw")
(name-as-in "unesco-language-status" "UNESCO-Sprachstatus" "de")
(name-as-in "unesco-language-status" "статус языка ЮНЕСКО" "ru")
(name-as-in "unesco-language-status" "estado de vulnerabilidad de idioma" "es")
(name-as-in "unesco-language-status" "" "ja")
(name-as-in "unesco-language-status" "" "zh-cn")
(name-as-in "unesco-language-status" "" "zh-sg")

(descr-as-in "unesco-language-status" "" "zh-hk")
(descr-as-in "unesco-language-status" "grau de ameaça de uma língua conferida pelo Atlas da UNESCO sobre Línguas em Perigo no Mundo" "pt")
(descr-as-in "unesco-language-status" "degree of endangerment of a language conferred by the UNESCO Atlas of World Languages in Danger" "en")
(descr-as-in "unesco-language-status" "statut UNESCO d'une langue" "fr")
(descr-as-in "unesco-language-status" "" "zh-tw")
(descr-as-in "unesco-language-status" "" "de")
(descr-as-in "unesco-language-status" "" "ru")
(descr-as-in "unesco-language-status" "lista elaborada por la Unesco" "es")
(descr-as-in "unesco-language-status" "" "ja")
(descr-as-in "unesco-language-status" "" "zh-cn")
(descr-as-in "unesco-language-status" "" "zh-sg")

