(ns properties.unicode_character
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "unicode-character")

(name-as-in "unicode-character" "Unicode字符" "zh-hk")
(name-as-in "unicode-character" "caractere Unicode" "pt")
(name-as-in "unicode-character" "Unicode character" "en")
(name-as-in "unicode-character" "caractère Unicode" "fr")
(name-as-in "unicode-character" "Unicode字元" "zh-tw")
(name-as-in "unicode-character" "Unicodezeichen" "de")
(name-as-in "unicode-character" "символ Юникода" "ru")
(name-as-in "unicode-character" "carácter Unicode" "es")
(name-as-in "unicode-character" "Unicodeキャラクタ" "ja")
(name-as-in "unicode-character" "Unicode字符" "zh-cn")
(name-as-in "unicode-character" "Unicode字符" "zh-sg")

(descr-as-in "unicode-character" "" "zh-hk")
(descr-as-in "unicode-character" "" "pt")
(descr-as-in "unicode-character" "Unicode character representing the item" "en")
(descr-as-in "unicode-character" "caractère Unicode représentant l’objet" "fr")
(descr-as-in "unicode-character" "" "zh-tw")
(descr-as-in "unicode-character" "Zeichen des Datenobjekts" "de")
(descr-as-in "unicode-character" "символ Юникода, соответствующий данному элементу" "ru")
(descr-as-in "unicode-character" "carácter Unicode del elemento" "es")
(descr-as-in "unicode-character" "その項目のUnicodeのキャラクタ（文字）" "ja")
(descr-as-in "unicode-character" "" "zh-cn")
(descr-as-in "unicode-character" "" "zh-sg")

