(ns properties.unified_astronomy_thesaurus_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "unified-astronomy-thesaurus-id")

(name-as-in "unified-astronomy-thesaurus-id" "" "zh-hk")
(name-as-in "unified-astronomy-thesaurus-id" "" "pt")
(name-as-in "unified-astronomy-thesaurus-id" "Unified Astronomy Thesaurus ID" "en")
(name-as-in "unified-astronomy-thesaurus-id" "identifiant Unified Astronomy Thesaurus" "fr")
(name-as-in "unified-astronomy-thesaurus-id" "" "zh-tw")
(name-as-in "unified-astronomy-thesaurus-id" "" "de")
(name-as-in "unified-astronomy-thesaurus-id" "" "ru")
(name-as-in "unified-astronomy-thesaurus-id" "" "es")
(name-as-in "unified-astronomy-thesaurus-id" "" "ja")
(name-as-in "unified-astronomy-thesaurus-id" "" "zh-cn")
(name-as-in "unified-astronomy-thesaurus-id" "" "zh-sg")

(descr-as-in "unified-astronomy-thesaurus-id" "" "zh-hk")
(descr-as-in "unified-astronomy-thesaurus-id" "" "pt")
(descr-as-in "unified-astronomy-thesaurus-id" "identifier for a term in the Unified Astronomy Thesaurus (UAT)" "en")
(descr-as-in "unified-astronomy-thesaurus-id" "identifiant pour un terme dans Unified Astronomy Thesaurus (UAT)" "fr")
(descr-as-in "unified-astronomy-thesaurus-id" "" "zh-tw")
(descr-as-in "unified-astronomy-thesaurus-id" "" "de")
(descr-as-in "unified-astronomy-thesaurus-id" "" "ru")
(descr-as-in "unified-astronomy-thesaurus-id" "" "es")
(descr-as-in "unified-astronomy-thesaurus-id" "" "ja")
(descr-as-in "unified-astronomy-thesaurus-id" "" "zh-cn")
(descr-as-in "unified-astronomy-thesaurus-id" "" "zh-sg")

