(ns properties.uses
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "uses")

(name-as-in "uses" "" "zh-hk")
(name-as-in "uses" "usa" "pt")
(name-as-in "uses" "uses" "en")
(name-as-in "uses" "utilise" "fr")
(name-as-in "uses" "" "zh-tw")
(name-as-in "uses" "benutzt" "de")
(name-as-in "uses" "использует" "ru")
(name-as-in "uses" "usa" "es")
(name-as-in "uses" "使用" "ja")
(name-as-in "uses" "" "zh-cn")
(name-as-in "uses" "" "zh-sg")

(descr-as-in "uses" "" "zh-hk")
(descr-as-in "uses" "" "pt")
(descr-as-in "uses" "item or concept used by the subject or in the operation" "en")
(descr-as-in "uses" "élément ou concept utilisé par le sujet ou impliqué dans l'opération" "fr")
(descr-as-in "uses" "" "zh-tw")
(descr-as-in "uses" "verwendetes Objekt" "de")
(descr-as-in "uses" "что: используемые предметы или принципы" "ru")
(descr-as-in "uses" "objeto usado por el sujeto" "es")
(descr-as-in "uses" "" "ja")
(descr-as-in "uses" "" "zh-cn")
(descr-as-in "uses" "" "zh-sg")

