(ns properties.ushmm_holocaust_encyclopedia_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "ushmm-holocaust-encyclopedia-id")

(name-as-in "ushmm-holocaust-encyclopedia-id" "" "zh-hk")
(name-as-in "ushmm-holocaust-encyclopedia-id" "" "pt")
(name-as-in "ushmm-holocaust-encyclopedia-id" "USHMM Holocaust Encyclopedia ID" "en")
(name-as-in "ushmm-holocaust-encyclopedia-id" "identifiant USHMM Holocaust Encyclopedia" "fr")
(name-as-in "ushmm-holocaust-encyclopedia-id" "" "zh-tw")
(name-as-in "ushmm-holocaust-encyclopedia-id" "" "de")
(name-as-in "ushmm-holocaust-encyclopedia-id" "" "ru")
(name-as-in "ushmm-holocaust-encyclopedia-id" "identificador Enciclopedia del Holocausto USHMM" "es")
(name-as-in "ushmm-holocaust-encyclopedia-id" "" "ja")
(name-as-in "ushmm-holocaust-encyclopedia-id" "" "zh-cn")
(name-as-in "ushmm-holocaust-encyclopedia-id" "" "zh-sg")

(descr-as-in "ushmm-holocaust-encyclopedia-id" "" "zh-hk")
(descr-as-in "ushmm-holocaust-encyclopedia-id" "" "pt")
(descr-as-in "ushmm-holocaust-encyclopedia-id" "identifier in the Holocaust Encyclopedia of the United States Holocaust Memorial Museum" "en")
(descr-as-in "ushmm-holocaust-encyclopedia-id" "identifiant dans Holocaust Encyclopedia du mémorial de l'Holocauste des États-Unis" "fr")
(descr-as-in "ushmm-holocaust-encyclopedia-id" "" "zh-tw")
(descr-as-in "ushmm-holocaust-encyclopedia-id" "" "de")
(descr-as-in "ushmm-holocaust-encyclopedia-id" "" "ru")
(descr-as-in "ushmm-holocaust-encyclopedia-id" "identificador en la Enciclopedia del Holocausto del Museo Estadounidense Conmemorativo del Holocausto" "es")
(descr-as-in "ushmm-holocaust-encyclopedia-id" "" "ja")
(descr-as-in "ushmm-holocaust-encyclopedia-id" "" "zh-cn")
(descr-as-in "ushmm-holocaust-encyclopedia-id" "" "zh-sg")

