(ns properties.wals_lect_code
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "wals-lect-code")

(name-as-in "wals-lect-code" "" "zh-hk")
(name-as-in "wals-lect-code" "" "pt")
(name-as-in "wals-lect-code" "WALS lect code" "en")
(name-as-in "wals-lect-code" "code de lecte WALS" "fr")
(name-as-in "wals-lect-code" "" "zh-tw")
(name-as-in "wals-lect-code" "WALS Sprach-ID" "de")
(name-as-in "wals-lect-code" "код языка во Всемирном атласе языковых структур" "ru")
(name-as-in "wals-lect-code" "" "es")
(name-as-in "wals-lect-code" "WALSコード" "ja")
(name-as-in "wals-lect-code" "" "zh-cn")
(name-as-in "wals-lect-code" "" "zh-sg")

(descr-as-in "wals-lect-code" "" "zh-hk")
(descr-as-in "wals-lect-code" "" "pt")
(descr-as-in "wals-lect-code" "identifier for a language" "en")
(descr-as-in "wals-lect-code" "identifiant pour une langue" "fr")
(descr-as-in "wals-lect-code" "" "zh-tw")
(descr-as-in "wals-lect-code" "" "de")
(descr-as-in "wals-lect-code" "идентификатор на сайте" "ru")
(descr-as-in "wals-lect-code" "" "es")
(descr-as-in "wals-lect-code" "言語の識別子" "ja")
(descr-as-in "wals-lect-code" "" "zh-cn")
(descr-as-in "wals-lect-code" "" "zh-sg")

