(ns properties.werelate_person_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "werelate-person-id")

(name-as-in "werelate-person-id" "" "zh-hk")
(name-as-in "werelate-person-id" "" "pt")
(name-as-in "werelate-person-id" "WeRelate person ID" "en")
(name-as-in "werelate-person-id" "identifiant WeRelate de personne" "fr")
(name-as-in "werelate-person-id" "" "zh-tw")
(name-as-in "werelate-person-id" "" "de")
(name-as-in "werelate-person-id" "" "ru")
(name-as-in "werelate-person-id" "" "es")
(name-as-in "werelate-person-id" "" "ja")
(name-as-in "werelate-person-id" "" "zh-cn")
(name-as-in "werelate-person-id" "" "zh-sg")

(descr-as-in "werelate-person-id" "" "zh-hk")
(descr-as-in "werelate-person-id" "" "pt")
(descr-as-in "werelate-person-id" "identifier for a person in the Creative Commons licensed genealogical database WeRelate" "en")
(descr-as-in "werelate-person-id" "identifiant pour une personne dans la base de données généalogiques sous licence Creative Commons WeRelate" "fr")
(descr-as-in "werelate-person-id" "" "zh-tw")
(descr-as-in "werelate-person-id" "" "de")
(descr-as-in "werelate-person-id" "" "ru")
(descr-as-in "werelate-person-id" "" "es")
(descr-as-in "werelate-person-id" "" "ja")
(descr-as-in "werelate-person-id" "" "zh-cn")
(descr-as-in "werelate-person-id" "" "zh-sg")

