(ns properties.wikidata_property
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "wikidata-property")

(name-as-in "wikidata-property" "" "zh-hk")
(name-as-in "wikidata-property" "propriedade principal" "pt")
(name-as-in "wikidata-property" "Wikidata property" "en")
(name-as-in "wikidata-property" "propriété Wikidata associée à l'élément" "fr")
(name-as-in "wikidata-property" "主要屬性" "zh-tw")
(name-as-in "wikidata-property" "Wikidata-Eigenschaft" "de")
(name-as-in "wikidata-property" "соответствующее свойство" "ru")
(name-as-in "wikidata-property" "propiedad principal" "es")
(name-as-in "wikidata-property" "対応するプロパティ" "ja")
(name-as-in "wikidata-property" "" "zh-cn")
(name-as-in "wikidata-property" "" "zh-sg")

(descr-as-in "wikidata-property" "" "zh-hk")
(descr-as-in "wikidata-property" "principal propriedade do Wikidata para este item" "pt")
(descr-as-in "wikidata-property" "main Wikidata property for this item" "en")
(descr-as-in "wikidata-property" "propriété Wikidata associée à l'élément" "fr")
(descr-as-in "wikidata-property" "" "zh-tw")
(descr-as-in "wikidata-property" "Eigenschaft in Wikidata für dieses Datenobjekt" "de")
(descr-as-in "wikidata-property" "свойство Викиданных, соответствующее данному элементу" "ru")
(descr-as-in "wikidata-property" "principal propiedad de Wikidata para este elemento" "es")
(descr-as-in "wikidata-property" "この項目に対する主要なウィキデータのプロパティ" "ja")
(descr-as-in "wikidata-property" "" "zh-cn")
(descr-as-in "wikidata-property" "" "zh-sg")

