(ns properties.wikidata_usage_instructions
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "wikidata-usage-instructions")

(name-as-in "wikidata-usage-instructions" "" "zh-hk")
(name-as-in "wikidata-usage-instructions" "como usar no Wikidata" "pt")
(name-as-in "wikidata-usage-instructions" "Wikidata usage instructions" "en")
(name-as-in "wikidata-usage-instructions" "instructions d'usage sur Wikidata" "fr")
(name-as-in "wikidata-usage-instructions" "維基數據使用說明" "zh-tw")
(name-as-in "wikidata-usage-instructions" "Hinweis zur Benutzung" "de")
(name-as-in "wikidata-usage-instructions" "документация Викиданных" "ru")
(name-as-in "wikidata-usage-instructions" "instrucciones de uso en Wikidata" "es")
(name-as-in "wikidata-usage-instructions" "ウィキデータ利用手順" "ja")
(name-as-in "wikidata-usage-instructions" "" "zh-cn")
(name-as-in "wikidata-usage-instructions" "" "zh-sg")

(descr-as-in "wikidata-usage-instructions" "" "zh-hk")
(descr-as-in "wikidata-usage-instructions" "" "pt")
(descr-as-in "wikidata-usage-instructions" "text describing how to use a property or item. Eventually, this statement is to replace usage instructions currently found in description. Until the corresponding feature is implemented, do not remove it from description." "en")
(descr-as-in "wikidata-usage-instructions" "texte décrivant comment utiliser une propriété ou un élément" "fr")
(descr-as-in "wikidata-usage-instructions" "" "zh-tw")
(descr-as-in "wikidata-usage-instructions" "beschreibt die Verwendung einer Wikidata-Eigenschaft oder -Objekts" "de")
(descr-as-in "wikidata-usage-instructions" "на сущностях-свойствах: как пользоваться этим элементом или свойством Викиданных" "ru")
(descr-as-in "wikidata-usage-instructions" "Texto que describe cómo usar una propiedada o item. Eventualmente, esta propiedad debe reemplazar a las instrucciones de uso que se encuentran en la descripción. Hasta que la función correspondiente se implemente, no se debe remover de la descripción" "es")
(descr-as-in "wikidata-usage-instructions" "プロパティや項目の利用法を記述したテキスト。最終的にはこの文は、現在説明にある利用手順を置き換えるが、対応する機能が実装されるまでは、説明から削除しないこと" "ja")
(descr-as-in "wikidata-usage-instructions" "" "zh-cn")
(descr-as-in "wikidata-usage-instructions" "" "zh-sg")

