(ns properties.wikiskripta_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "wikiskripta-id")

(name-as-in "wikiskripta-id" "" "zh-hk")
(name-as-in "wikiskripta-id" "" "pt")
(name-as-in "wikiskripta-id" "WikiSkripta ID" "en")
(name-as-in "wikiskripta-id" "identifiant WikiSkripta" "fr")
(name-as-in "wikiskripta-id" "" "zh-tw")
(name-as-in "wikiskripta-id" "" "de")
(name-as-in "wikiskripta-id" "код wikiskripta" "ru")
(name-as-in "wikiskripta-id" "identificador WikiSkripta" "es")
(name-as-in "wikiskripta-id" "" "ja")
(name-as-in "wikiskripta-id" "" "zh-cn")
(name-as-in "wikiskripta-id" "" "zh-sg")

(descr-as-in "wikiskripta-id" "" "zh-hk")
(descr-as-in "wikiskripta-id" "" "pt")
(descr-as-in "wikiskripta-id" "identificator for articles on wikiskripta.eu" "en")
(descr-as-in "wikiskripta-id" "identifiant d'un article sur wikiskripta.eu" "fr")
(descr-as-in "wikiskripta-id" "" "zh-tw")
(descr-as-in "wikiskripta-id" "" "de")
(descr-as-in "wikiskripta-id" "" "ru")
(descr-as-in "wikiskripta-id" "" "es")
(descr-as-in "wikiskripta-id" "" "ja")
(descr-as-in "wikiskripta-id" "" "zh-cn")
(descr-as-in "wikiskripta-id" "" "zh-sg")

