(ns properties.wikitree_person_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "wikitree-person-id")

(name-as-in "wikitree-person-id" "" "zh-hk")
(name-as-in "wikitree-person-id" "identificador WikiTree" "pt")
(name-as-in "wikitree-person-id" "WikiTree person ID" "en")
(name-as-in "wikitree-person-id" "identifiant WikiTree" "fr")
(name-as-in "wikitree-person-id" "" "zh-tw")
(name-as-in "wikitree-person-id" "WikiTree ID" "de")
(name-as-in "wikitree-person-id" "идентификатор WikiTree" "ru")
(name-as-in "wikitree-person-id" "identificador WikiTree" "es")
(name-as-in "wikitree-person-id" "" "ja")
(name-as-in "wikitree-person-id" "" "zh-cn")
(name-as-in "wikitree-person-id" "" "zh-sg")

(descr-as-in "wikitree-person-id" "" "zh-hk")
(descr-as-in "wikitree-person-id" "" "pt")
(descr-as-in "wikitree-person-id" "identifier for a person in the WikiTree genealogy website" "en")
(descr-as-in "wikitree-person-id" "identifiant pour une personne dans le site Web de généalogie WikiTree" "fr")
(descr-as-in "wikitree-person-id" "" "zh-tw")
(descr-as-in "wikitree-person-id" "Identifikator einer Person auf der WikiTree Genealogie website" "de")
(descr-as-in "wikitree-person-id" "" "ru")
(descr-as-in "wikitree-person-id" "" "es")
(descr-as-in "wikitree-person-id" "" "ja")
(descr-as-in "wikitree-person-id" "" "zh-cn")
(descr-as-in "wikitree-person-id" "" "zh-sg")

