(ns properties.winner
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "winner")

(name-as-in "winner" "獲勝者" "zh-hk")
(name-as-in "winner" "vencido por" "pt")
(name-as-in "winner" "winner" "en")
(name-as-in "winner" "vainqueur" "fr")
(name-as-in "winner" "獲勝者" "zh-tw")
(name-as-in "winner" "Sieger" "de")
(name-as-in "winner" "победитель" "ru")
(name-as-in "winner" "ganador" "es")
(name-as-in "winner" "勝者" "ja")
(name-as-in "winner" "获胜者" "zh-cn")
(name-as-in "winner" "获胜者" "zh-sg")

(descr-as-in "winner" "在某項活動中取得勝利的一方" "zh-hk")
(descr-as-in "winner" "" "pt")
(descr-as-in "winner" "winner of an event - do not use for wars or battles" "en")
(descr-as-in "winner" "vainqueur d'un évènement" "fr")
(descr-as-in "winner" "在某項活動中取得勝利的一方" "zh-tw")
(descr-as-in "winner" "Sieger bei einem Ereignis (nicht für Kriege und Schlachten verwenden)" "de")
(descr-as-in "winner" "победитель соревнования" "ru")
(descr-as-in "winner" "ganador del evento" "es")
(descr-as-in "winner" "イベントの勝者" "ja")
(descr-as-in "winner" "在某项活动中取得胜利的一方" "zh-cn")
(descr-as-in "winner" "在某项活动中取得胜利的一方" "zh-sg")

