(ns properties.woeid
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "woeid")

(name-as-in "woeid" "" "zh-hk")
(name-as-in "woeid" "" "pt")
(name-as-in "woeid" "WOEID" "en")
(name-as-in "woeid" "identifiant Where On Earth" "fr")
(name-as-in "woeid" "" "zh-tw")
(name-as-in "woeid" "WOEID" "de")
(name-as-in "woeid" "WOEID" "ru")
(name-as-in "woeid" "WOEID" "es")
(name-as-in "woeid" "WOEID" "ja")
(name-as-in "woeid" "" "zh-cn")
(name-as-in "woeid" "" "zh-sg")

(descr-as-in "woeid" "" "zh-hk")
(descr-as-in "woeid" "" "pt")
(descr-as-in "woeid" "identifier for a location on Yahoo! GeoPlanet and Flickr" "en")
(descr-as-in "woeid" "Identifiant de 32 bits (Where on Earth identifier) lié à GeoPlanet et assigné par Yahoo" "fr")
(descr-as-in "woeid" "" "zh-tw")
(descr-as-in "woeid" "Ortskenner auf Yahoo! GeoPlanet and Flickr" "de")
(descr-as-in "woeid" "код географического положения, используемый Yahoo! GeoPlanet и Flickr" "ru")
(descr-as-in "woeid" "identificador de un lugar en Yahoo! GeoPlanet y Flickr" "es")
(descr-as-in "woeid" "" "ja")
(descr-as-in "woeid" "" "zh-cn")
(descr-as-in "woeid" "" "zh-sg")

