(ns properties.work_location
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "work-location")

(name-as-in "work-location" "工作地點" "zh-hk")
(name-as-in "work-location" "local de trabalho" "pt")
(name-as-in "work-location" "work location" "en")
(name-as-in "work-location" "lieu de travail" "fr")
(name-as-in "work-location" "工作地點" "zh-tw")
(name-as-in "work-location" "Wirkungsort" "de")
(name-as-in "work-location" "место активности" "ru")
(name-as-in "work-location" "lugar de trabajo" "es")
(name-as-in "work-location" "活動地" "ja")
(name-as-in "work-location" "工作地点" "zh-cn")
(name-as-in "work-location" "工作地点" "zh-sg")

(descr-as-in "work-location" "" "zh-hk")
(descr-as-in "work-location" "local ou locais onde o criador esteve a(c)tivo" "pt")
(descr-as-in "work-location" "location where persons were active" "en")
(descr-as-in "work-location" "lieu où une ou plusieurs  personnes ont travaillé" "fr")
(descr-as-in "work-location" "" "zh-tw")
(descr-as-in "work-location" "Ort, an dem Personen aktiv waren" "de")
(descr-as-in "work-location" "место деятельности субъекта" "ru")
(descr-as-in "work-location" "donde una persona trabajaba" "es")
(descr-as-in "work-location" "主題の人物（芸術家など）が活動（作品の創作など）をした場所" "ja")
(descr-as-in "work-location" "" "zh-cn")
(descr-as-in "work-location" "" "zh-sg")

