(ns properties.world_heritage_site_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "world-heritage-site-id")

(name-as-in "world-heritage-site-id" "世界遺產識別碼" "zh-hk")
(name-as-in "world-heritage-site-id" "identificador de Património Mundial" "pt")
(name-as-in "world-heritage-site-id" "World Heritage Site ID" "en")
(name-as-in "world-heritage-site-id" "identifiant Patrimoine mondial" "fr")
(name-as-in "world-heritage-site-id" "" "zh-tw")
(name-as-in "world-heritage-site-id" "Welterbe-Referenznummer" "de")
(name-as-in "world-heritage-site-id" "код Всемирного наследия ЮНЕСКО" "ru")
(name-as-in "world-heritage-site-id" "identificador del patrimonio mundial" "es")
(name-as-in "world-heritage-site-id" "世界遺産識別子" "ja")
(name-as-in "world-heritage-site-id" "" "zh-cn")
(name-as-in "world-heritage-site-id" "" "zh-sg")

(descr-as-in "world-heritage-site-id" "" "zh-hk")
(descr-as-in "world-heritage-site-id" "número de identificação da UNESCO.  Use on one item per site, link parts with property has part (P527)" "pt")
(descr-as-in "world-heritage-site-id" "identifier for a site as assigned by UNESCO. Use on one item per site, link parts with property has part (P527)" "en")
(descr-as-in "world-heritage-site-id" "numéro d'identification du patrimoine mondial de l'UNESCO.  Utiliser un élément par site, lier les autres avec  composé de (P527)" "fr")
(descr-as-in "world-heritage-site-id" "" "zh-tw")
(descr-as-in "world-heritage-site-id" "von der UNESCO vergebene Identifikationsnummer (zur Datenbank-Verlinkung).  Use on one item per site, link parts with property has part (P527)" "de")
(descr-as-in "world-heritage-site-id" "" "ru")
(descr-as-in "world-heritage-site-id" "Número de referencia del sitio asignado por la UNESCO. Utilizar en un artículo por cada sitio, enlace las partes o componentes del sitio con la propiedad tiene parte (P527)" "es")
(descr-as-in "world-heritage-site-id" "UNESCOが世界遺産に割り当てる参考番号。遺産1件につき最も範囲の広い1項目のみに付与し、遺産の各構成要素は「以下を含む」(P527)で関連付ける。" "ja")
(descr-as-in "world-heritage-site-id" "" "zh-cn")
(descr-as-in "world-heritage-site-id" "" "zh-sg")

