(ns properties.zbmath_author_id
   (:refer-clojure :exclude [==])
   (:use clojure.core.logic)
   (:use meta.meta))

(fact Property "zbmath-author-id")

(name-as-in "zbmath-author-id" "" "zh-hk")
(name-as-in "zbmath-author-id" "" "pt")
(name-as-in "zbmath-author-id" "zbMATH author ID" "en")
(name-as-in "zbmath-author-id" "identifiant d'auteur zbMATH" "fr")
(name-as-in "zbmath-author-id" "" "zh-tw")
(name-as-in "zbmath-author-id" "zbMATH Autoren-ID" "de")
(name-as-in "zbmath-author-id" "код автора в базе данных zbMATH" "ru")
(name-as-in "zbmath-author-id" "identificador de autor zbMATH" "es")
(name-as-in "zbmath-author-id" "" "ja")
(name-as-in "zbmath-author-id" "" "zh-cn")
(name-as-in "zbmath-author-id" "" "zh-sg")

(descr-as-in "zbmath-author-id" "" "zh-hk")
(descr-as-in "zbmath-author-id" "" "pt")
(descr-as-in "zbmath-author-id" "identifier of a person in the Zentralblatt MATH database" "en")
(descr-as-in "zbmath-author-id" "identifiant d'une personne sur la base de données Zentralblatt MATH" "fr")
(descr-as-in "zbmath-author-id" "" "zh-tw")
(descr-as-in "zbmath-author-id" "" "de")
(descr-as-in "zbmath-author-id" "" "ru")
(descr-as-in "zbmath-author-id" "identificador para una persona en la base de datos Zentralblatt MATH" "es")
(descr-as-in "zbmath-author-id" "" "ja")
(descr-as-in "zbmath-author-id" "" "zh-cn")
(descr-as-in "zbmath-author-id" "" "zh-sg")

